### ISSUE TITLE
`from_definition` does not actually support relay connections

### ISSUE THREAD

**Issue by staugaard** [rmosolgo/graphql-ruby#1043]
This unfortunately fails with this exception:
```
KeyError: Can't resolve field edges on #<GraphQL::Relay::ArrayConnection:0x00007fe86529cc00>
    /Users/staugaard/code/graphql-ruby/lib/graphql/schema/build_from_definition/resolve_map/default_resolve.rb:23:in `call'
    /Users/staugaard/code/graphql-ruby/lib/graphql/schema/build_from_definition/resolve_map.rb:57:in `call'
    /Users/staugaard/code/graphql-ruby/lib/graphql/schema/build_from_definition.rb:171:in `block in build_object_type'
    /Users/staugaard/code/graphql-ruby/lib/graphql/schema/build_from_definition.rb:280:in `block (2 levels) in build_fields'
    /Users/staugaard/code/graphql-ruby/lib/graphql/field.rb:230:in `resolve'
```

```ruby
  it "supports resolving relay connections" do
    schema = <<-SCHEMA
schema {
  query: Type
}

type Organization {
  email: String
}

# The connection type for Organization.
type OrganizationConnection {
  # A list of edges.
  edges: [OrganizationEdge]

  # A list of nodes.
  nodes: [Organization]

  # Information to aid in pagination.
  pageInfo: PageInfo!

  # Identifies the total count of items in the connection.
  totalCount: Int!
}

# An edge in a connection.
type OrganizationEdge {
  # A cursor for use in pagination.
  cursor: String!

  # The item at the end of the edge.
  node: Organization
}

# Information about pagination in a connection.
type PageInfo {
  # When paginating forwards, the cursor to continue.
  endCursor: String

  # When paginating forwards, are there more items?
  hasNextPage: Boolean!

  # When paginating backwards, are there more items?
  hasPreviousPage: Boolean!

  # When paginating backwards, the cursor to continue.
  startCursor: String
}

type Type {
  # A list of organizations the user belongs to.
  organizations(
    # Returns the elements in the list that come after the specified global ID.
    after: String

    # Returns the elements in the list that come before the specified global ID.
    before: String

    # Returns the first _n_ elements from the list.
    first: Int

    # Returns the last _n_ elements from the list.
    last: Int
  ): OrganizationConnection!
}
    SCHEMA

    resolver = {
      "Type" => {
        "organizations" => ->(obj, args, ctx) { [] }
      }
    }

    schema = GraphQL::Schema.from_definition(schema, default_resolve: resolver)

    result = schema.execute("query { organizations { edges { node { email } } } }")
    puts result.to_json
  end
```

**Comment by rmosolgo** [comment]
Awesome, thanks for the reproducing case! I wonder if it would be as "easy" as adding an `#edges` method to BaseConnection.

**Comment by staugaard** [comment]
For a `threads` connection, I had to add this to my resolver to make it work:

```ruby
    'ThreadConnection' => {
      'edges' => ->(obj, _args, _ctx) { obj.edge_nodes },
      'pageInfo' => ->(obj, _args, _ctx) { obj.page_info }
    },
    'ThreadEdge' => {
      'node' => ->(obj, _args, ctx) { obj }
    },

```

**Comment by rmosolgo** [comment]
Similar to #2731, the current behavior of halfway connection support is confusing and tricky. I'm going to remove it altogether. I've added some example code there for migrating old resolver behavior.
