### ISSUE TITLE
GraphQL::Function usage not clear / not working

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1257]
Hello,

Consider this simplistic approach where There are Outer (think Shelves) objects that contain Inner objects (think Books). We want to create a query where we can restrict the number of Outer / Inner object we return, like so:

```
  query {
    outers(count: 3) {
      name
      inners(count:2) { 
        name
      }
    }
  }
```

or just return a bunch of inner objects.

```
  query {
    inners(count:5) {
      name 
    }
  }
```

I'm trying to resolve using this, based on https://github.com/rmosolgo/graphql-ruby/blob/master/guides/fields/function.md:
```
  InnerObj = Struct.new(:name)
  OuterObj = Struct.new(:name, :inners)

  INNERS = (1..60).map { |i| InnerObj.new("Inner #{i}") }
  OUTERS = (1..6).map { |i| OuterObj.new("Outer #{i}", INNERS.slice(3*i..3*(i+1))) }


  Inner = GraphQL::ObjectType.define do
    name 'Inner'

    field 'name', types.String
  end

  class LimitedInners < GraphQL::Function
    type types[Inner]
    argument :count, types.Int

    def initialize(&block)
      @fetcher = block
    end


    def call(obj, args, ctx)
      binding.pry
      data = @fetcher.call(obj)
      data[0..args[:count] - 1]
    end
  end


  Outer = GraphQL::ObjectType.define do
    name 'Outer'

    field 'name', types.String
    field 'inners', function: LimitedInners.new { |obj| obj.inners }
  end


  GetOuters = GraphQL::Field.define do
    type types[Outer]

    argument :count, types.Int

    resolve ->(obj, args, ctx) do
      OUTERS[0..args[:count] - 1]
    end
  end

  GetInners = GraphQL::Field.define do
    function LimitedInners.new { |obj| INNERS }
  end

  QueryType = GraphQL::ObjectType.define do
    name 'Query'
    description 'The query root for this schema'

    field :inners, GetInners
    field :outers, GetOuters
  end

 Schema = GraphQL::Schema.define do
    query DataHub::QueryType
  end
```

But when running the introspection query, I get:

```
{"query":"
  query IntrospectionQuery {
    __schema {
      queryType { name }
      mutationType { name }
      subscriptionType { name }
      types {
        ...FullType
      }
      directives {
        name
        description
        locations
        args {
          ...InputValue
        }
      }
    }
  }

  fragment FullType on __Type {
    kind
    name
    description
    fields(includeDeprecated: true) {
      name
      description
      args {
        ...InputValue
      }
      type {
        ...TypeRef
      }
      isDeprecated
      deprecationReason
    }
    inputFields {
      ...InputValue
    }
    interfaces {
      ...TypeRef
    }
    enumValues(includeDeprecated: true) {
      name
      description
      isDeprecated
      deprecationReason
    }
    possibleTypes {
      ...TypeRef
    }
  }

  fragment InputValue on __InputValue {
    name
    description
    type { ...TypeRef }
    defaultValue
  }

  fragment TypeRef on __Type {
    kind
    name
    ofType {
      kind
      name
      ofType {
        kind
        name
        ofType {
          kind
          name
          ofType {
            kind
            name
            ofType {
              kind
              name
              ofType {
                kind
                name
                ofType {
                  kind
                  name
                }
              }
            }
          }
        }
      }
    }
  }
"
```

```
E, [2018-02-02T15:06:21.982268 #11632] ERROR -- : Query is invalid: field "inners" type must return GraphQL::BaseType, not NilClass (nil)
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:132:in `validate_type'
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:67:in `visit'
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:53:in `block in visit'
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:53:in `each'
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:53:in `visit'
(...)/gems/graphql-1.7.4/lib/graphql/schema/traversal.rb:32:in `initialize'
(...)/gems/graphql-1.7.4/lib/graphql/schema.rb:588:in `new'
(...)/gems/graphql-1.7.4/lib/graphql/schema.rb:588:in `rebuild_artifacts'
(...)/gems/graphql-1.7.4/lib/graphql/schema.rb:237:in `types'
(...)/gems/graphql-1.7.4/lib/graphql/schema/validation.rb:133:in `block in <module:Rules>'
(...)/gems/graphql-1.7.4/lib/graphql/schema/validation.rb:19:in `block in validate'
(...)/gems/graphql-1.7.4/lib/graphql/schema/validation.rb:19:in `each'
(...)/gems/graphql-1.7.4/lib/graphql/schema/validation.rb:19:in `reduce'
(...)/gems/graphql-1.7.4/lib/graphql/schema/validation.rb:19:in `validate'
(...)/gems/graphql-1.7.4/lib/graphql/schema.rb:198:in `define'
(...)/gems/graphql-1.7.4/lib/graphql/define/instance_definable.rb:226:in `define'
(...)/app/api/admin/graph/schema.rb:5:in `<module:DataHub>'
(...)/app/api/admin/graph/schema.rb:4:in `<top (required)>'
```

Any ideas what might be wrong?

**Comment by axos88** [comment]
Let me know if you can successfully repro

**Comment by rmosolgo** [comment]
GraphQL::Function is out, GraphQL::Schema::Resolver is in: http://graphql-ruby.org/type_definitions/resolvers.html

If someone experiences this in the class-based API, feel free to reopen this and we can hunt it further!
