### ISSUE TITLE
scalar coercion borks if argument passed in via variable

### ISSUE THREAD

**Issue by axos88** [rmosolgo/graphql-ruby#1269]
A mutation, 

```
AddMember = GraphQL::Relay::Mutation.define do
      name 'addMemberToAgentGroup'

      input_field :group_id, !ObjectId, 'The id of the group to add the agent(s) for'
      input_field :agent_ids, !types[!ObjectId]

      return_field :agentGroup, Type, property: :data

      resolve ->(_obj, args, ctx) do
        (...)
      end
end
```

having an argument of type:

```
    ObjectId = GraphQL::ScalarType.define do
      name "ObjectId"
      description "Hexadecimal representation of a 12-byte hexadecimal id, consisting of: a 4-byte value representing the seconds since the Unix epoch, a 3-byte machine identifier, a 2-byte process id, and a 3-byte counter, starting with a random value."

      coerce_input ->(value, ctx) do
        value.to_s.downcase.tap do |v|
          raise GraphQL::CoercionError, " '#{v}' is not a 12-byte hexadecimal string" unless OBJECT_ID_REGEX.match(v)
        end
      end

      coerce_result ->(value, ctx) { value.to_s.downcase }
    end
```

will return the coercion result if passed in as a literal, although the message too is duplicated:

```
mutation {
  addMemberToAgentGroup(input: {
    group_id: "invalid",
    agent_ids: []
  }) {
    agentGroup {
      id
      members {
        data {
          id
        }
      }      
    }    
  }
}
```

```
{
  "errors": [
    {
      "message": " 'invalid' is not a 12-byte hexadecimal string",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "fields": [
        "mutation",
        "addMemberToAgentGroup",
        "input"
      ]
    },
    {
      "message": " 'invalid' is not a 12-byte hexadecimal string",
      "locations": [
        {
          "line": 2,
          "column": 32
        }
      ],
      "fields": [
        "mutation",
        "addMemberToAgentGroup",
        "input",
        "group_id"
      ]
    }
  ]
}
```

But returns an exception if the argument is sent in as a variable:

```
mutation($input: addMemberToAgentGroupInput! ) {
  addMemberToAgentGroup(input: $input) {
    agentGroup {
      id
      members {
        data {
          id
        }
      }      
    }
    
  }
}
```

```
{
  "input": {
    "group_id": "invalid",
    "agent_ids": []
  }
}
```

```
E, [2018-02-08T10:50:36.926115 #72653] ERROR -- :  'invalid' is not a 12-byte hexadecimal string
<PROJECT ROOT>/app/api/admin/graph/common/object_id.rb:11:in `block (3 levels) in <module:Common>'
<PROJECT ROOT>/app/api/admin/graph/common/object_id.rb:10:in `tap'
<PROJECT ROOT>/app/api/admin/graph/common/object_id.rb:10:in `block (2 levels) in <module:Common>'
<GEM ROOT>/graphql-1.7.9/lib/graphql/scalar_type.rb:112:in `coerce_non_null_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/scalar_type.rb:117:in `validate_non_null_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/base_type.rb:135:in `validate_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/non_null_type.rb:61:in `validate_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/input_object_type.rb:143:in `block in validate_non_null_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/input_object_type.rb:142:in `each'
<GEM ROOT>/graphql-1.7.9/lib/graphql/input_object_type.rb:142:in `map'
<GEM ROOT>/graphql-1.7.9/lib/graphql/input_object_type.rb:142:in `validate_non_null_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/base_type.rb:135:in `validate_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/non_null_type.rb:61:in `validate_input'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/variables.rb:32:in `block in initialize'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/variables.rb:18:in `each'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/variables.rb:18:in `each_with_object'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/variables.rb:18:in `initialize'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query.rb:186:in `new'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query.rb:186:in `block in variables'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query.rb:348:in `with_prepared_ast'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query.rb:185:in `variables'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/validation_pipeline.rb:85:in `ensure_has_validated'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query/validation_pipeline.rb:34:in `valid?'
<GEM ROOT>/graphql-1.7.9/lib/graphql/query.rb:222:in `valid?'
<GEM ROOT>/graphql-1.7.9/lib/graphql/analysis/analyze_query.rb:11:in `block (2 levels) in analyze_multiplex'
<GEM ROOT>/graphql-1.7.9/lib/graphql/analysis/analyze_query.rb:10:in `map'
<GEM ROOT>/graphql-1.7.9/lib/graphql/analysis/analyze_query.rb:10:in `block in analyze_multiplex'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:57:in `block in trace'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:71:in `call_tracers'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:57:in `trace'
<GEM ROOT>/graphql-1.7.9/lib/graphql/analysis/analyze_query.rb:8:in `analyze_multiplex'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/multiplex.rb:173:in `block in instrument_and_analyze'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:70:in `block in call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:58:in `call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:69:in `call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:58:in `call_hooks'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/multiplex.rb:166:in `instrument_and_analyze'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:57:in `block in trace'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:71:in `call_tracers'
<GEM ROOT>/graphql-1.7.9/lib/graphql/tracing.rb:57:in `trace'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/multiplex.rb:58:in `run_queries'
<GEM ROOT>/graphql-1.7.9/lib/graphql/execution/multiplex.rb:48:in `run_all'
<GEM ROOT>/graphql-1.7.9/lib/graphql/schema.rb:299:in `block in multiplex'
<GEM ROOT>/graphql-1.7.9/lib/graphql/schema.rb:612:in `with_definition_error_check'
<GEM ROOT>/graphql-1.7.9/lib/graphql/schema.rb:298:in `multiplex'
<GEM ROOT>/graphql-1.7.9/lib/graphql/schema.rb:275:in `execute'
<PROJECT ROOT>/app/api/admin/graphql.rb:33:in `block (2 levels) in <class:GraphQL>'

(...)

```

**Comment by axos88** [comment]
Workaround:

```    
# PLEASE KILL ME FOR THIS! # Ugly workaround for https://github.com/rmosolgo/graphql-ruby/issues/1269
    module GraphQLRuby1269Hack
      def self.graphqlize_value(value)
        case value
          when Array then "[" + value.map { |v| graphqlize_value(v)}.join(',') + "]"
          when Hash then "{" + value.map { |k,v| "#{k}: #{graphqlize_value(v)}" }.join(',') + "}"
          else value.inspect
        end
      end

      def self.inline_variables(query, vars)
        vars.each do |key, value|
          binding.pry
          query.gsub!(/(query|mutation)\s*\(([\$\s\w,\:\!]*),?\s*\$#{key}\s*:\s*[\w\!]+\s*,?\s*([\$\s\w,\:\!]*)\)?/, '\1(\2, \3)')
          query.gsub!(/\$#{key}/, graphqlize_value(value))
        end

        query.gsub!(/(query|mutation)\s*\(\s+,(.*)\)/,'\1 (\2)')
        query.gsub!(/(query|mutation)\s*\((.*),\s+\)/,'\1 (\2)')
        query.gsub!(/(query|mutation)\s*\(\)/,'\1')
      end
    end
```

**Comment by axos88** [comment]
Possibly related to #988

**Comment by rmosolgo** [comment]
Oh bummer, that error isn't rescued properly, is it? 😖  Thanks for the detailed bug report!

**Comment by axos88** [comment]
Why was this closed? Is it fixed?

**Comment by rmosolgo** [comment]
No, sorry, I hit the wrong buttom, thanks @willianvdv!

**Comment by axos88** [comment]
@rmosolgo any progress on this?
