### ISSUE TITLE
Invalid query throwing exception instead of GraphQL Error

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-ruby#127]
Howdy! Just a quick bug I found. This query here...

```
query SimpleQuery {
  ...node
}
```

...is obviously invalid, but instead of throwing a proper GraphQL error, it throws an exception:

```
NoMethodError: undefined method `type' for nil:NilClass
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:22:in `block (2 levels) in validate'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:20:in `each'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:20:in `block in validate'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:67:in `call'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:67:in `block in apply_hooks'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:67:in `each'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:67:in `reduce'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:67:in `apply_hooks'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:62:in `end_visit'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/language/visitor.rb:47:in `visit'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/static_validation/validator.rb:26:in `validate'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/query.rb:72:in `validation_errors'
/usr/local/var/rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/graphql-0.12.0/lib/graphql/query.rb:41:in `result'
```

Just thought I'd log it here! Thanks again for all your hard work @rmosolgo :heart:

**Comment by rmosolgo** [comment]
Thanks for the great info on replicating the problem, that made it a breeze to track down!  Fixed in 695a782

It was waiting too late to detect undefined fragments so no-good data could get too far along in the validation process. Now, we detect it sooner and skip the fragment spread if it's no good!
