### ISSUE TITLE
[BUG] Calling present? on a object of type GraphQL::ObjectType causes a GraphQL::DoubleNonNullTypeError exception

### ISSUE THREAD

**Issue by hazefully** [rmosolgo/graphql-ruby#1289]
I believe this issue is caused by the fact that `present?` and `blank?` is defined in the following way:
```
  def present?
    !blank?
  end

  def blank?
    respond_to?(:empty?) ? !!empty? : !self
  end
```
and the `!` is overloaded to call `to_non_null_type` when called within the context of GraphQL::BaseType, which means this issue affects all type classes.

To reproduce:
```
ExampleType = GraphQL::ObjectType.define do
  name "ExampleType"
  description "An example type"

  field :test, types.String, "Test field" do
    resolve -> (_obj, _args, _ctx) do
      "Test"
    end
  end
end

ExampleType.present?
```
Exception backtrace:
```
GraphQL::DoubleNonNullTypeError: You tried to add a non-null constraint twice (!! instead of !)
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/graphql-1.7.9/lib/graphql/non_null_type.rb:41:in `initialize'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/graphql-1.7.9/lib/graphql/base_type.rb:70:in `new'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/graphql-1.7.9/lib/graphql/base_type.rb:70:in `to_non_null_type'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/graphql-1.7.9/lib/graphql/define/non_null_with_bang.rb:12:in `!'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/activesupport-3.2.22.1/lib/active_support/core_ext/object/blank.rb:21:in `present?'
	from (irb):12
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/railties-3.2.22.1/lib/rails/commands/console.rb:47:in `start'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/railties-3.2.22.1/lib/rails/commands/console.rb:8:in `start'
	from /home/hazefully/.rvm/gems/ruby-2.1.10/gems/railties-3.2.22.1/lib/rails/commands.rb:41:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'
```
Ruby version: ruby 2.1.10p492
Rails version: Rails 3.2.22.1
GraphQL version: graphql 1.7.9

**Comment by rmosolgo** [comment]
Thanks for the detailed report, working hard to replace the overloaded `!` in version 1.8.0, see https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/schema/class_based_api.md

In the meantime, I guess you have to work around with other checks like `.nil?` :S
