### ISSUE TITLE
Guide: Pusher Implementation

### ISSUE THREAD

**Issue by dpaola2** [rmosolgo/graphql-ruby#1314]
I have a schema defined like so:

```
CustomerSchema = GraphQL::Schema.define do
...
  use GraphQL::Pro::Subscriptions, redis: Rails.configuration.graphql_subscriptions_redis
...
end
```

I've added a `mount CustomerSchema.pusher_webhooks_client, at: "/pusher_webhooks"` as per the documentation.

When I load my rails app, I see this exception: `undefined method `pusher_webhooks_client'`.

**Comment by dpaola2** [comment]
Here's the page I'm following: http://graphql-ruby.org/subscriptions/pusher_implementation.html

**Comment by rmosolgo** [comment]
Sorry to hear it! could you please share the full error message and stack trace?

**Comment by dpaola2** [comment]
```
/Users/davepaola/src/genesis/config/routes.rb:783:in `block (2 levels) in <top (required)>': undefined method `pusher_webhooks_client' for #<GraphQL::Schema:0x007fa2c32de520> (NoMethodError)
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:940:in `block in constraints'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:816:in `scope'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/mapper.rb:940:in `constraints'
	from /Users/davepaola/src/genesis/config/routes.rb:782:in `block in <top (required)>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `instance_exec'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:434:in `eval_block'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/actionpack-4.2.3/lib/action_dispatch/routing/route_set.rb:412:in `draw'
	from /Users/davepaola/src/genesis/config/routes.rb:2:in `<top (required)>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `block in load'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:268:in `load'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `each'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:16:in `reload!'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:26:in `block in updater'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/file_update_checker.rb:75:in `execute'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:27:in `updater'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/routes_reloader.rb:7:in `execute_if_updated'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application/finisher.rb:69:in `block in <module:Finisher>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `instance_exec'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:30:in `run'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:55:in `block in run_initializers'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:228:in `block in tsort_each'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:431:in `each_strongly_connected_component_from'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:349:in `block in each_strongly_connected_component'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `call'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:347:in `each_strongly_connected_component'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:226:in `tsort_each'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/tsort.rb:205:in `tsort_each'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/initializable.rb:54:in `run_initializers'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/application.rb:352:in `initialize!'
	from /Users/davepaola/src/genesis/config/environment.rb:5:in `<top (required)>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `block in require'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:240:in `load_dependency'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/activesupport-4.2.3/lib/active_support/dependencies.rb:274:in `require'
	from /Users/davepaola/src/genesis/config.ru:3:in `block in <main>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:55:in `instance_eval'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:55:in `initialize'
	from /Users/davepaola/src/genesis/config.ru:in `new'
	from /Users/davepaola/src/genesis/config.ru:in `<main>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:49:in `eval'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:49:in `new_from_string'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/builder.rb:40:in `parse_file'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/server.rb:300:in `build_app_and_options_from_config'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/server.rb:209:in `app'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/server.rb:61:in `app'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/rack-1.6.6/lib/rack/server.rb:337:in `wrapped_app'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/server.rb:139:in `log_to_stdout'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/server.rb:78:in `start'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:80:in `block in server'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `tap'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:75:in `server'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/railties-4.2.3/lib/rails/commands.rb:17:in `<top (required)>'
	from /Users/davepaola/src/genesis/bin/rails:9:in `require'
	from /Users/davepaola/src/genesis/bin/rails:9:in `<top (required)>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `load'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/rails.rb:28:in `call'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client/command.rb:7:in `call'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/client.rb:30:in `run'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/bin/spring:49:in `<top (required)>'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `load'
	from /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/spring-1.7.1/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/davepaola/src/genesis/bin/spring:13:in `require'
	from /Users/davepaola/src/genesis/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
```

**Comment by rmosolgo** [comment]
Thanks for sharing that. Does your routes file have the required setup: 

``` ruby 
# config/routes.rb

# Include GraphQL::Pro's routing extensions:
using GraphQL::Pro::Routes
```

?

**Comment by dpaola2** [comment]
That was indeed the problem. Thanks -- does that line exist somewhere in the docs?
