### ISSUE TITLE
On a subscription: undefined method `smembers' for nil:NilClass

### ISSUE THREAD

**Issue by dpaola2** [rmosolgo/graphql-ruby#1322]
Here's my schema:

```ruby
CustomerSchema = GraphQL::Schema.define do                                                                                                                                            
  ...  
  use GraphQL::Pro::Subscriptions, redis: $graphql_subscription_redis                                                                                                                 
  subscription EdenGraph::SubscriptionType
end
```

My subscription type:

```ruby
EdenGraph::SubscriptionType = GraphQL::ObjectType.define do                                                                                                                           
  name "Subscription"                                                                                                                                                                 
  field :ticketWasChanged, !EdenGraph::Customer::Quest::TicketType, "A quest ticket was changed"                                                                                      
end                                                                                                                                                                                   
```

In my model:

```ruby
CustomerSchema.subscriptions.trigger("ticketWasChanged", {id: self.id}, self)
```

The error:

```ruby
NoMethodError at /customer
==========================

> undefined method `smembers' for nil:NilClass

app/models/quest/ticket.rb, line 124
------------------------------------

``` ruby
  119         self.completed_at = nil
  120       end
  121     end
  122   
  123     def trigger_change_event
> 124       CustomerSchema.subscriptions.trigger("ticketWasChanged", {id: self.id}, self)
  125     end
  126   
  127   end
```

App backtrace
-------------

 - app/models/quest/ticket.rb:124:in `trigger_change_event'
 - app/interactors/quest/tickets/edit_column.rb:20:in `call'
 - app/interactors/sql_transactional_interactor.rb:18:in `block in wrap_in_sql_transaction'
 - app/interactors/sql_transactional_interactor.rb:17:in `wrap_in_sql_transaction'
 - app/interactors/transactional_interactor.rb:22:in `block in wrap_in_interactor_transaction'
 - app/interactors/interactor_transaction.rb:12:in `wrap'
 - app/interactors/transactional_interactor.rb:20:in `wrap_in_interactor_transaction'
 - app/interactors/interactor_rocktopus_adapter.rb:29:in `block in deliver_rocktopus_messages'
 - app/lib/rocktopus/message_queue_transaction.rb:10:in `wrap'
 - app/interactors/interactor_rocktopus_adapter.rb:27:in `deliver_rocktopus_messages'
 - app/interactors/quest/tickets/change_state.rb:16:in `call'
 - app/interactors/sql_transactional_interactor.rb:18:in `block in wrap_in_sql_transaction'
 - app/interactors/sql_transactional_interactor.rb:17:in `wrap_in_sql_transaction'
 - app/interactors/transactional_interactor.rb:22:in `block in wrap_in_interactor_transaction'
 - app/interactors/interactor_transaction.rb:12:in `wrap'
 - app/interactors/transactional_interactor.rb:20:in `wrap_in_interactor_transaction'
 - app/interactors/interactor_rocktopus_adapter.rb:29:in `block in deliver_rocktopus_messages'
 - app/lib/rocktopus/message_queue_transaction.rb:10:in `wrap'
 - app/interactors/interactor_rocktopus_adapter.rb:27:in `deliver_rocktopus_messages'
 - app/graph/types/eden_graph/customer/mutations/quest/tickets/update_state.rb:16:in `block (2 levels) in <top (required)>'
 - app/controllers/api/customer_graphql_queries_controller.rb:36:in `customer_schema_execute'
 - app/controllers/api/customer_graphql_queries_controller.rb:14:in `create'
 - app/lib/actor_tracking.rb:20:in `block (2 levels) in use_actor'
 - app/lib/actor_tracking.rb:33:in `use_actor_timezone'
 - app/lib/actor_tracking.rb:20:in `block in use_actor'
 - app/lib/actor_tracking.rb:18:in `use_actor'
 - app/controllers/api/customer_graphql_queries_controller.rb:78:in `track_current_actor'
 - app/middleware/strip_x_forwarded_host.rb:11:in `call'

Full backtrace
--------------

 - graphql-pro (1.6.4) lib/graphql/pro/subscriptions/redis_storage.rb:58:in `each_subscription_id'
 - graphql-pro (1.6.4) lib/graphql/pro/subscriptions.rb:24:in `execute_all'
 - graphql (1.7.12) lib/graphql/subscriptions.rb:52:in `trigger'
 - app/models/quest/ticket.rb:124:in `trigger_change_event'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:226:in `block in halting_and_conditional'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `block in call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:504:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
 - activerecord (4.2.3) lib/active_record/callbacks.rb:302:in `create_or_update'
 - activerecord (4.2.3) lib/active_record/persistence.rb:120:in `save'
 - activerecord (4.2.3) lib/active_record/validations.rb:37:in `save'
 - activerecord (4.2.3) lib/active_record/attribute_methods/dirty.rb:21:in `save'
 - activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block (2 levels) in save'
 - activerecord (4.2.3) lib/active_record/transactions.rb:351:in `block in with_transaction_returning_status'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
 - activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
 - activerecord (4.2.3) lib/active_record/transactions.rb:348:in `with_transaction_returning_status'
 - activerecord (4.2.3) lib/active_record/transactions.rb:286:in `block in save'
 - activerecord (4.2.3) lib/active_record/transactions.rb:301:in `rollback_active_record_state!'
 - activerecord (4.2.3) lib/active_record/transactions.rb:285:in `save'
 - app/interactors/quest/tickets/edit_column.rb:20:in `call'
 - interactor (3.1.0) lib/interactor.rb:143:in `block in run!'
 - interactor (3.1.0) lib/interactor/hooks.rb:213:in `block in with_hooks'
 - app/interactors/sql_transactional_interactor.rb:18:in `block in wrap_in_sql_transaction'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:211:in `transaction'
 - activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
 - app/interactors/sql_transactional_interactor.rb:17:in `wrap_in_sql_transaction'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - app/interactors/transactional_interactor.rb:22:in `block in wrap_in_interactor_transaction'
 - app/interactors/interactor_transaction.rb:12:in `wrap'
 - app/interactors/transactional_interactor.rb:20:in `wrap_in_interactor_transaction'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - app/interactors/interactor_rocktopus_adapter.rb:29:in `block in deliver_rocktopus_messages'
 - app/lib/rocktopus/message_queue_transaction.rb:10:in `wrap'
 - app/interactors/interactor_rocktopus_adapter.rb:27:in `deliver_rocktopus_messages'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - interactor (3.1.0) lib/interactor/hooks.rb:224:in `run_around_hooks'
 - interactor (3.1.0) lib/interactor/hooks.rb:211:in `with_hooks'
 - interactor (3.1.0) lib/interactor.rb:142:in `run!'
 - interactor (3.1.0) lib/interactor.rb:115:in `run'
 - interactor (3.1.0) lib/interactor.rb:50:in `call'
 - app/interactors/quest/tickets/change_state.rb:16:in `call'
 - interactor (3.1.0) lib/interactor.rb:143:in `block in run!'
 - interactor (3.1.0) lib/interactor/hooks.rb:213:in `block in with_hooks'
 - app/interactors/sql_transactional_interactor.rb:18:in `block in wrap_in_sql_transaction'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `block in transaction'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/transaction.rb:184:in `within_new_transaction'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/database_statements.rb:213:in `transaction'
 - activerecord (4.2.3) lib/active_record/transactions.rb:220:in `transaction'
 - app/interactors/sql_transactional_interactor.rb:17:in `wrap_in_sql_transaction'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - app/interactors/transactional_interactor.rb:22:in `block in wrap_in_interactor_transaction'
 - app/interactors/interactor_transaction.rb:12:in `wrap'
 - app/interactors/transactional_interactor.rb:20:in `wrap_in_interactor_transaction'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - app/interactors/interactor_rocktopus_adapter.rb:29:in `block in deliver_rocktopus_messages'
 - app/lib/rocktopus/message_queue_transaction.rb:10:in `wrap'
 - app/interactors/interactor_rocktopus_adapter.rb:27:in `deliver_rocktopus_messages'
 - interactor (3.1.0) lib/interactor/hooks.rb:263:in `run_hook'
 - interactor (3.1.0) lib/interactor/hooks.rb:223:in `block (2 levels) in run_around_hooks'
 - interactor (3.1.0) lib/interactor/hooks.rb:224:in `run_around_hooks'
 - interactor (3.1.0) lib/interactor/hooks.rb:211:in `with_hooks'
 - interactor (3.1.0) lib/interactor.rb:142:in `run!'
 - interactor (3.1.0) lib/interactor.rb:115:in `run'
 - interactor (3.1.0) lib/interactor.rb:50:in `call'
 - app/graph/types/eden_graph/customer/mutations/quest/tickets/update_state.rb:16:in `block (2 levels) in <top (required)>'
 - apollo-tracing (1.3.0) lib/apollo_tracing.rb:83:in `block in instrument'
 - graphql (1.7.12) lib/graphql/relay/mutation/resolve.rb:18:in `call'
 - graphql (1.7.12) lib/graphql/field.rb:244:in `resolve'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:254:in `call'
 - graphql (1.7.12) lib/graphql/schema/middleware_chain.rb:45:in `invoke_core'
 - graphql (1.7.12) lib/graphql/schema/middleware_chain.rb:38:in `invoke'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:108:in `resolve_field'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:72:in `block (2 levels) in resolve_selection'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `block in trace'
 - graphql (1.7.12) lib/graphql/tracing.rb:71:in `call_tracers'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `trace'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:64:in `resolve_selection'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `block in trace'
 - graphql (1.7.12) lib/graphql/tracing.rb:71:in `call_tracers'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `trace'
 - graphql (1.7.12) lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:108:in `begin_query'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:174:in `block in instrument_and_analyze'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:70:in `block in call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:70:in `block in call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:70:in `block in call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:58:in `call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:69:in `call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:69:in `call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:69:in `call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:58:in `call_hooks'
 - graphql (1.7.12) lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:166:in `instrument_and_analyze'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `block in trace'
 - graphql (1.7.12) lib/graphql/tracing.rb:71:in `call_tracers'
 - graphql (1.7.12) lib/graphql/tracing.rb:57:in `trace'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:58:in `run_queries'
 - graphql (1.7.12) lib/graphql/execution/multiplex.rb:48:in `run_all'
 - graphql (1.7.12) lib/graphql/schema.rb:299:in `block in multiplex'
 - graphql (1.7.12) lib/graphql/schema.rb:612:in `with_definition_error_check'
 - graphql (1.7.12) lib/graphql/schema.rb:298:in `multiplex'
 - graphql (1.7.12) lib/graphql/schema.rb:275:in `execute'
 - app/controllers/api/customer_graphql_queries_controller.rb:36:in `customer_schema_execute'
 - app/controllers/api/customer_graphql_queries_controller.rb:14:in `create'
 - actionpack (4.2.3) lib/action_controller/metal/implicit_render.rb:4:in `send_action'
 - actionpack (4.2.3) lib/abstract_controller/base.rb:198:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/rendering.rb:10:in `process_action'
 - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:115:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:553:in `block (2 levels) in compile'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:496:in `block (2 levels) in around'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:311:in `block (2 levels) in halting'
 - app/lib/actor_tracking.rb:20:in `block (2 levels) in use_actor'
 - activesupport (4.2.3) lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
 - app/lib/actor_tracking.rb:33:in `use_actor_timezone'
 - app/lib/actor_tracking.rb:20:in `block in use_actor'
 - audited (4.6.0) lib/audited/audit.rb:137:in `as_user'
 - app/lib/actor_tracking.rb:18:in `use_actor'
 - app/controllers/api/customer_graphql_queries_controller.rb:78:in `track_current_actor'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:430:in `block in make_lambda'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:310:in `block in halting'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:495:in `block in around'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:496:in `block (2 levels) in around'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:311:in `block (2 levels) in halting'
 - audited (4.6.0) lib/audited/sweeper.rb:14:in `around'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:453:in `block in make_lambda'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:310:in `block in halting'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:495:in `block in around'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:503:in `call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:88:in `run_callbacks'
 - actionpack (4.2.3) lib/abstract_controller/callbacks.rb:19:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/rescue.rb:29:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
 - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `block in instrument'
 - activesupport (4.2.3) lib/active_support/notifications/instrumenter.rb:20:in `instrument'
 - activesupport (4.2.3) lib/active_support/notifications.rb:164:in `instrument'
 - actionpack (4.2.3) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
 - actionpack (4.2.3) lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
 - activerecord (4.2.3) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
 - actionpack (4.2.3) lib/abstract_controller/base.rb:137:in `process'
 - actionview (4.2.3) lib/action_view/rendering.rb:30:in `process'
 - rack-mini-profiler (0.10.7) lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
 - actionpack (4.2.3) lib/action_controller/metal.rb:196:in `dispatch'
 - actionpack (4.2.3) lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
 - actionpack (4.2.3) lib/action_controller/metal.rb:237:in `block in action'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:76:in `dispatch'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:45:in `serve'
 - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:43:in `block in serve'
 - actionpack (4.2.3) lib/action_dispatch/journey/router.rb:30:in `serve'
 - actionpack (4.2.3) lib/action_dispatch/routing/route_set.rb:821:in `call'
 - dragonfly (1.0.12) lib/dragonfly/middleware.rb:14:in `call'
 - scout_apm (2.4.3) lib/scout_apm/instant/middleware.rb:53:in `call'
 - scout_apm (2.4.3) lib/scout_apm/middleware.rb:17:in `call'
 - rack-host-redirect (1.2.1) lib/rack/host_redirect.rb:19:in `call'
 - twilio-ruby (3.16.1) lib/rack/twilio_webhook_authentication.rb:28:in `call'
 - app/middleware/strip_x_forwarded_host.rb:11:in `call'
 - warden (1.2.3) lib/warden/manager.rb:35:in `block in call'
 - warden (1.2.3) lib/warden/manager.rb:34:in `call'
 - rack (1.6.6) lib/rack/etag.rb:24:in `call'
 - rack (1.6.6) lib/rack/conditionalget.rb:38:in `call'
 - rack (1.6.6) lib/rack/head.rb:13:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/params_parser.rb:27:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/flash.rb:260:in `call'
 - rack (1.6.6) lib/rack/session/abstract/id.rb:225:in `context'
 - rack (1.6.6) lib/rack/session/abstract/id.rb:220:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/cookies.rb:560:in `call'
 - activerecord (4.2.3) lib/active_record/query_cache.rb:36:in `call'
 - activerecord (4.2.3) lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
 - activerecord (4.2.3) lib/active_record/migration.rb:377:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
 - activesupport (4.2.3) lib/active_support/callbacks.rb:84:in `run_callbacks'
 - actionpack (4.2.3) lib/action_dispatch/middleware/callbacks.rb:27:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/reloader.rb:73:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
 - better_errors (2.4.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.4.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.4.0) lib/better_errors/middleware.rb:57:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
 - web-console (2.2.1) lib/web_console/middleware.rb:39:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
 - railties (4.2.3) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (4.2.3) lib/rails/rack/logger.rb:20:in `block in call'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `block in tagged'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:26:in `tagged'
 - activesupport (4.2.3) lib/active_support/tagged_logging.rb:68:in `tagged'
 - railties (4.2.3) lib/rails/rack/logger.rb:20:in `call'
 - quiet_assets (1.1.0) lib/quiet_assets.rb:27:in `call_with_quiet_assets'
 - actionpack (4.2.3) lib/action_dispatch/middleware/request_id.rb:21:in `call'
 - rack (1.6.6) lib/rack/methodoverride.rb:22:in `call'
 - rack (1.6.6) lib/rack/runtime.rb:18:in `call'
 - activesupport (4.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
 - dragonfly (1.0.12) lib/dragonfly/cookie_monster.rb:9:in `call'
 - actionpack (4.2.3) lib/action_dispatch/middleware/static.rb:116:in `call'
 - rack (1.6.6) lib/rack/sendfile.rb:113:in `call'
 - rack-cors (0.4.0) lib/rack/cors.rb:80:in `call'
 - honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:34:in `block in call'
 - honeybadger (3.1.2) lib/honeybadger/agent.rb:321:in `with_rack_env'
 - honeybadger (3.1.2) lib/honeybadger/rack/error_notifier.rb:31:in `call'
 - honeybadger (3.1.2) lib/honeybadger/rack/user_feedback.rb:31:in `call'
 - honeybadger (3.1.2) lib/honeybadger/rack/user_informer.rb:21:in `call'
 - rack-mini-profiler (0.10.7) lib/mini_profiler/profiler.rb:282:in `call'
 - railties (4.2.3) lib/rails/engine.rb:518:in `call'
 - railties (4.2.3) lib/rails/application.rb:165:in `call'
 - rack (1.6.6) lib/rack/lock.rb:17:in `call'
 - rack (1.6.6) lib/rack/content_length.rb:15:in `call'
 - rack (1.6.6) lib/rack/handler/webrick.rb:88:in `service'
 - /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
 - /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
 - /Users/davepaola/.rbenv/versions/2.3.4/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'

```

**Comment by dpaola2** [comment]
Seems like an issue with my Pusher implementation. Closing.
