### ISSUE TITLE
non-deterministic errors executing the introspection query on rubinius

### ISSUE THREAD

**Issue by alexandrz** [rmosolgo/graphql-ruby#135]
Sometimes it works, sometimes it returns error:

```
Something went wrong during query execution: undefined method `shift' on nil:NilClass.
```

sometimes it raises exception:

```
     NoMethodError:
       undefined method `<<' on nil:NilClass.
     # kernel/delta/kernel.rb:78:in `<< (method_missing)'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/implementation_validator.rb:17:in `must_respond_to'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/type_validator.rb:5:in `validate'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/type_reducer.rb:70:in `validate_type'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/type_reducer.rb:7:in `initialize'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/type_reducer.rb:61:in `reduce_type'
     # /root/.rbenv/versions/rbx-2.5.2/gems/gems/graphql-0.12.0/lib/graphql/schema/type_reducer.rb:36:in `find_types'
```

**Comment by rmosolgo** [comment]
:sob: I get occasional errors from rbx-2 on TravisCI too. But in parsing: 

https://travis-ci.org/rmosolgo/graphql-ruby/jobs/120708602#L257
https://travis-ci.org/rmosolgo/graphql-ruby/jobs/120709119#L613

Re-running makes them go away ....! :confounded:

**Comment by rmosolgo** [comment]
It's been a long time, do these still pop up for you?

**Comment by rmosolgo** [comment]
Feel free to reopen this if someone on Rubinius is still running into this issue!
