### ISSUE TITLE
Syntax error on class_eval - max_complexity

### ISSUE THREAD

**Issue by timscott** [rmosolgo/graphql-ruby#1438]
I'm giving 1.8 a spin. I upgraded to `1.8.0.pre10`. I get this error at startup:

```bash
/Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql.rb:18:in `class_eval': (eval):3: syntax error, unexpected & (SyntaxError)
ition.max_complexity=(*args, &Proc.new)
                              ^
(eval):5: syntax error, unexpected ')', expecting '='
inition.max_complexity=(*args)
                              ^
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql.rb:18:in `block in def_delegators'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql.rb:15:in `each'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql.rb:15:in `def_delegators'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql/schema.rb:640:in `singleton class'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql/schema.rb:634:in `<class:Schema>'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql/schema.rb:68:in `<module:GraphQL>'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql/schema.rb:36:in `<top (required)>'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `block in require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:258:in `load_dependency'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/activesupport-5.1.2/lib/active_support/dependencies.rb:292:in `require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/graphql-1.8.0.pre10/lib/graphql.rb:100:in `<top (required)>'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:91:in `block (2 levels) in require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `each'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:86:in `block in require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `each'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler/runtime.rb:75:in `require'
	from /Users/tscott/.rvm/gems/ruby-2.4.0/gems/bundler-1.14.6/lib/bundler.rb:107:in `require'
```

**Comment by rmosolgo** [comment]
Sorry, it looks like an error in our patched version of `Forwardable`. Can you use any Ruby version _except_ 2.4.0 ? There's a [special patch](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql.rb#L9-L12) because of a performance regression in that module in 2.4.0, but obviously the patch is broken 😩
