### ISSUE TITLE
RSpec failure when running single test

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#1451]
I am hitting an error when running single spec file with rspec but the error disappears when doing full suite run. This started happening after moving to class-based API. Any pointers to resolve would be helpful. 

Failure/Error: field model_name, self.graphql_type, null: false

ArgumentError:
  missing positional argument `type`

# /Users/hemantv/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.0.pre10/lib/graphql/schema/field.rb:60:in `initialize'
# /Users/hemantv/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.0.pre10/lib/graphql/schema/member/accepts_definition.rb:108:in `initialize'
# /Users/hemantv/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.0.pre10/lib/graphql/schema/member/has_fields.rb:12:in `new'
# /Users/hemantv/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.0.pre10/lib/graphql/schema/member/has_fields.rb:12:in `field'
# /Users/hemantv/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.0.pre10/lib/graphql/schema/mutation.rb:94:in `field'
# ./app/graphql/mutations/base/base_create_update_mutation.rb:25:in `setup'

**Comment by rmosolgo** [comment]
Is it possible that `self.graphql_type` is returning `nil`?
