### ISSUE TITLE
broken ActiveRecord connection doesn't handle/raise error up

### ISSUE THREAD

**Issue by modosc** [rmosolgo/graphql-ruby#1464]
consider a schema with a typo in the property:
```
connection :questions, Types::QuestionType.connection_type, property: :questoins
```
trying to execute a query against the `questions` connection eventually causes this:
```
     NoMethodError:
       undefined method `map' for #<GraphQL::ExecutionError:0x007f9d71af7420>
       Did you mean?  tap
     # /Users/jon/.rvm/gems/ruby-2.4.1@swoop/gems/graphql-1.7.14/lib/graphql/relay/edges_instrumentation.rb:51:in `build_edges'
     # /Users/jon/.rvm/gems/ruby-2.4.1@swoop/gems/graphql-1.7.14/lib/graphql/relay/edges_instrumentation.rb:37:in `resolve'
     # /Users/jon/.rvm/gems/ruby-2.4.1@swoop/gems/graphql-1.7.14/lib/graphql/field.rb:246:in `call'
     # /Users/jon/.rvm/gems/ruby-2.4.1@swoop/gems/graphql-1.7.14/lib/graphql/field.rb:246:in `resolve'
     # /Users/jon/.rvm/gems/ruby-2.4.1@swoop/gems/graphql-1.7.14/lib/graphql/execution/execute.rb:254:in `call'
     # etc...
```
and the only thing populated in the `errors` key is the above issue - the underlying `ActiveRecord` failure is swallowed up. 

i think what happens is at [this point](https://github.com/rmosolgo/graphql-ruby/blob/v1.7.14/lib/graphql/relay/edges_instrumentation.rb#L50) `items` is being resolved to a `GraphQL::ExecutionError` - i don't know why this happens or why it's not raised but it's for sure not being handled correctly.

i tried getting a test to duplicate this but i had little success, and i don't know if this issue is present on `1.8`.

**Comment by modosc** [comment]
locally i patched `build_edges` like so:
```
        def build_edges(items, connection)
          items.respond_to?(:map) ?
          items&.map { |item| @edge_class.new(item, connection) } :
          items
        end
```
not sure if this is ok though.

**Comment by rmosolgo** [comment]
I made a short script to try this on the latest: 

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.10.4"
  gem "activerecord", require: "active_record"
  gem "pg"
end

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  username: "postgres",
  database: "graphql_ruby_test"
)

ActiveRecord::Schema.define do
  self.verbose = false
  create_table :items, force: true do |t|
    t.column :name, :string, null: false
  end
end

class Item < ActiveRecord::Base
end

class ItemType < GraphQL::Schema::Object
  field :name, String, null: true
end

class Query < GraphQL::Schema::Object
  field :things, ItemType.connection_type, null: true
end

class Schema < GraphQL::Schema
  query Query
end

p Schema.execute('query { things(first: 10) { edges { node { name } } } }', root_value: Item).to_h
```

It raises a more helpful error now: 

```ruby
	 6: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:732:in `block in run_extensions_before_resolve'
	 5: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:735:in `run_extensions_before_resolve'
	 4: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:732:in `block (2 levels) in run_extensions_before_resolve'
	 3: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:732:in `block (2 levels) in run_extensions_before_resolve'
	 2: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:713:in `block in with_extensions'
	 1: from /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:695:in `block in public_send_field'
/Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.10.4/lib/graphql/schema/field.rb:612:in `resolve_field_method':         Failed to implement Query.things, tried: (RuntimeError)

        - `Query#things`, which did not exist
        - `Class#things`, which did not exist
        - Looking up hash key `:things` or `"things"` on `Item`, but it wasn't a Hash

        To implement this field, define one of the methods above (and check for typos)
```

I don't think there's anything else to do there. 

In any case, I think the patch above is :+1: ! Please open another issue if you're still running into this problem.
