### ISSUE TITLE
Upgrader convert Field to 1.8.0 not work.

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1519]
before: 

```rb

GuardianTaskFeedField = GraphQL::Field.define do
  type FeedGuardianTaskType
  argument :id, types.ID

  resolve ->(_obj, args, ctx) {
    feed_id = args[:id]
    Feed[feed_id]
  }
end
```

After

```rb
class GuardianTaskFeedField < GraphQL::Schema::Field
  type FeedGuardianTaskType
  argument :id, ID, required: false

  resolve ->(_obj, args, ctx) {
    feed_id = args[:id]
    Feed[feed_id]
  }
end
```

error message:

```
NoMethodError: undefined method `type' for GuardianTaskFeedField:Class
    app/graph/fields/guardian_task_feed_field.rb:5:in `<class:GuardianTaskFeedField>'
    app/graph/fields/guardian_task_feed_field.rb:4:in `<top (required)>'
    app/graph/types/roots/query_type.rb:2:in `block in <top (required)>'
    app/graph/types/roots/query_type.rb:2:in `each'
    app/graph/types/roots/query_type.rb:2:in `<top (required)>'
    app/graph/schema.rb:2:in `<top (required)>'
```

**Comment by rmosolgo** [comment]
This isn't going to work, you can keep the old way and hook it up with the `field(..., field:)` option, or switch by hand to `GraphQL::Schema::Resolver` (http://graphql-ruby.org/type_definitions/resolvers.html)
