### ISSUE TITLE
Upgrade to 1.8.0, and with new class/method definition, broken graphql IDE

### ISSUE THREAD

**Issue by zw963** [rmosolgo/graphql-ruby#1521]
When click refresh button, could not got correct schema.

**Comment by zw963** [comment]
The reason caused this is:

I define mutation with following class:

```rb
class Mutation < GraphQL::Schema::Object
   ...
end
```

response

```
I, [2018-05-21T20:08:55.696875 #11071]  INFO -- : Started POST "/graphql" for 127.0.0.1 at 2018-05-21 20:08:55 +0800
I, [2018-05-21T20:08:55.697385 #11071]  INFO -- : Processing by GraphqlController#execute as */*
I, [2018-05-21T20:08:55.697469 #11071]  INFO -- :   Parameters: {"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n", "graphql"=>{"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"}}
I, [2018-05-21T20:08:55.697663 #11071]  INFO -- : Host: localhost:8000
I, [2018-05-21T20:08:55.697689 #11071]  INFO -- : X-Consumer-ID:
I, [2018-05-21T20:08:55.697708 #11071]  INFO -- : X-Consumer-Custom-ID:
I, [2018-05-21T20:08:55.866864 #11071]  INFO -- : Completed 200 OK in 169ms (Views: 51.8ms)
```

graphQL IDE could not fetch schema, but, seem like rails app is worked. (test can pass)

After revert to old format, graphql ide work again.

```rb
MutationType = GraphQL::ObjectType.define do
  name 'Mutation'

  # 主题
  field :createSubject, CreateSubjectMutation.field
  field :deleteSubject, DeleteSubjectMutation.field
  field :sortSubject, SortSubjectMutation.field

  field :createActivity, field: CreateActivityMutation.field
  field :deleteActivity, field: DeleteActivityMutation.field
  field :updateActivity, field: UpdateActivityMutation.field
 # ....
```



if revert to use old form, it work.

**Comment by Willianvdv** [comment]
@zw963 have you figured out what the problem was?

**Comment by zw963** [comment]
@Willianvdv , no, GraphQL IDE just not working.

current, i only update `graphql/types/` types define, that seem like safe

**Comment by rmosolgo** [comment]
I bet it has somethign to do with the `field(...)` calls in the mutation class. I would have expected some kind of dramatic failure, thought! 

Things like `DeleteSubjectMutation` and `UpdateActivityMutation`, are they using the old `GraphQL::Relay::Mutation`, or the new `GraphQL::Schema::RelayClassicMutation`? 

If they're using the old way, try adding a `field:` keyword before all of them. If they're using the new way, use `mutation: DeleteSubjectMutation` (no `field` before or after) instead.

**Comment by zw963** [comment]
> Things like DeleteSubjectMutation and UpdateActivityMutation, are they using the old GraphQL::Relay::Mutation,

Use old `GraphQL::Relay::Mutation`. 

> If they're using the old way, try adding a field: keyword before all of them. 

if not add, will broken Graph with following exception:

```sh
ArgumentError: A GraphQL::Field was passed as the second argument, use the `field:` keyword for this instead.
```

so, all `field:` is added, but schema not working.

I retry again with following step:

1. run `rake graphql:upgrade:member[app/graph/types/roots/mutation_type.rb]`
2. add `field: ` to resolve exception
3. rename old `MutationType` to new `class Mutation` (Without `Type` prefix), form compability.

This time, i got many error like following:

```sh
Error:
CreateGuardianTest#test_auth_会调用_createGuardianMutation,_创建一个指定手机号码的_guardian:
RuntimeError: Unexpected scope type: Mutation
    app/controllers/graphql_controller.rb:12:in `execute'
    test/graph/queries/mutations/create_guardian_test.rb:13:in `block in <class:CreateGuardianTest>'
```

Following is all diff:

```diff
diff --git a/app/graph/schema.rb b/app/graph/schema.rb
index 0a43673..ec00408 100644
--- a/app/graph/schema.rb
+++ b/app/graph/schema.rb
@@ -7,7 +7,7 @@ require 'types/objects/feed/feed_guardian_task_type'
 
 Schema = GraphQL::Schema.define do
   query QueryType
-  mutation MutationType
+  mutation Mutation
   resolve_type lambda {|_type, obj, _ctx|
     if obj[:type] == Feed::TYPE_TEACHER_ACTIVITY
       FeedActivityType
diff --git a/app/graph/types/roots/mutation_type.rb b/app/graph/types/roots/mutation_type.rb
index f035436..6a878e6 100644
--- a/app/graph/types/roots/mutation_type.rb
+++ b/app/graph/types/roots/mutation_type.rb
@@ -2,59 +2,48 @@
 Dir[Rails.root.join('app', 'graph', 'mutations', '*.rb')].each { |file| require file }
 
 # fields按照a..z排列便于查看
-MutationType = GraphQL::ObjectType.define do
-  name 'Mutation'
-
+class Mutation < Types::BaseObject
   # 主题
-  field :createSubject, CreateSubjectMutation.field
-  field :deleteSubject, DeleteSubjectMutation.field
-  field :sortSubject, SortSubjectMutation.field
-
-  field :createActivity, field: CreateActivityMutation.field
-  field :deleteActivity, field: DeleteActivityMutation.field
-  field :updateActivity, field: UpdateActivityMutation.field
-
-  # 动态
-  field :createChildFeed, field: CreateChildFeedMutation.field
-  field :updateChildFeed, field: UpdateChildFeedMutation.field
+  field :create_subject, field: CreateSubjectMutation.field, null: true
+  field :delete_subject, field: DeleteSubjectMutation.field, null: true
+  field :sort_subject, field: SortSubjectMutation.field, null: true
 
-  # 这个接口, 兼具删除亲子任务(GuardianTaskFeed)和在园动态(ChildFeed)
-  field :deleteChildFeed, field: DeleteChildFeedMutation.field
+  field :create_activity, field: CreateActivityMutation.field
+  field :delete_activity, field: DeleteActivityMutation.field
+  field :update_activity, field: UpdateActivityMutation.field
 
-  # 采集
-  field :createCollection, field: CreateCollectionMutation.field
-  field :deleteCollection, field: DeleteCollectionMutation.field
-  field :createCollections, field: CreateCollectionsMutation.field
+  field :delete_collection, field: DeleteCollectionMutation.field
+  field :create_collections, field: CreateCollectionsMutation.field
 
   # 家长
-  field :createGuardian, field: CreateGuardianMutation.field
-  field :updateGuardianRole, field: UpdateGuardianRoleMutation.field
+  field :create_guardian, field: CreateGuardianMutation.field
+  field :update_guardian_role, field: UpdateGuardianRoleMutation.field
 
   # 学生
-  field :createStudents, CreateStudentsMutation.field
-  field :updateStudent, UpdateStudentMutation.field
-  field :deleteStudent, DeleteStudentMutation.field
+  field :create_students, field: CreateStudentsMutation.field, null: true
+  field :update_student, field: UpdateStudentMutation.field, null: true
+  field :delete_student, field: DeleteStudentMutation.field, null: true
 
   # 教师
-  field :updateTeacher, UpdateTeacherMutation.field
-  field :createTeacher, CreateTeacherMutation.field
+  field :update_teacher, field: UpdateTeacherMutation.field, null: true
+  field :create_teacher, field: CreateTeacherMutation.field, null: true
 
   # 孩子
-  field :createChild, field: CreateChildMutation.field
-  field :updateChild, UpdateChildMutation.field
-  field :createChildHobby, field: CreateChildHobbyMutation.field
+  field :create_child, field: CreateChildMutation.field
+  field :update_child, field: UpdateChildMutation.field, null: true
+  field :create_child_hobby, field: CreateChildHobbyMutation.field
 
   # 照片
-  field :updateImage, field: UpdateImageMutation.field
-  field :deleteImage, field: DeleteImageMutation.field
-  field :recruitImage, field: RecruitImageMutation.field
+  field :update_image, field: UpdateImageMutation.field
+  field :delete_image, field: DeleteImageMutation.field
+  field :recruit_image, field: RecruitImageMutation.field
 
   # 亲子任务
-  field :createGuardianTaskFeed, field: CreateGuardianTaskFeedMutation.field
-  field :updateGuardianTaskFeed, field: UpdateGuardianTaskFeedMutation.field
+  field :create_guardian_task_feed, field: CreateGuardianTaskFeedMutation.field
+  field :update_guardian_task_feed, field: UpdateGuardianTaskFeedMutation.field
 
   # 邀请家人
-  field :createGuardianInvitation, field: CreateGuardianInvitationMutation.field
-  field :createChildrenGuardian, field: CreateChildrenGuardianMutation.field
-  field :cancelGuardianInvitation, field: CancelGuardianInvitationMutation.field
+  field :create_guardian_invitation, field: CreateGuardianInvitationMutation.field
+  field :create_children_guardian, field: CreateChildrenGuardianMutation.field
+  field :cancel_guardian_invitation, field: CancelGuardianInvitationMutation.field
 end
```

**Comment by zw963** [comment]
Following is one broken test  mutation definition example:

```rb
CancelGuardianInvitationMutation = GraphQL::Relay::Mutation.define do
  name 'CancelGuardianInvitation'
  ...
end
```

It use old form.

**Comment by zw963** [comment]
>> . If they're using the new way, use mutation: DeleteSubjectMutation (no field before or after) instead.

I try this new solution, change one my old mutation to use new class form,  it is not work too.
please see #1561

**Comment by rmosolgo** [comment]
I hope you found a solution here, but I'm going to close the issue as stale.
