### ISSUE TITLE
Upgreader breaks on certain fields

### ISSUE THREAD

**Issue by iGEL** [rmosolgo/graphql-ruby#1531]
This definition:
```ruby
Types::DebitType = GraphQL::ObjectType.define do
  name "Debit"
  field :invoice_type do
    type !types.String
    resolve ->(*_) { "debit" }
  end
end
```
causes
```
- Transforming member app/graphql/types/base_interface.rb
- Transforming member app/graphql/types/debit_type.rb
rake aborted!
TypeError: no implicit conversion from nil to integer
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:511:in `[]'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:511:in `apply'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:812:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:813:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:813:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:817:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:817:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:817:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:817:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:813:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:813:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:813:in `apply_transforms'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:785:in `block in upgrade'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:784:in `each'
/bundle/gems/graphql-1.8.0/lib/graphql/upgrader/member.rb:784:in `upgrade'
```
Additional problem is, that the file was empty afterwards. I think, you should try to keep the file untouched until the very end to prevent data loss. Luckily I didn't had any uncommitted changes.

**Comment by Willianvdv** [comment]
Hello @iGEL, could you file a PR with a failing spec? It would really help us!

**Comment by bessey** [comment]
I ran into a lot of problems (this was around pre10/11) with resolvers using the `-> (*)` signature, or variants (e.g. `-> (obj, *)`. In the end I added a type transform to make them into normal signature items like so:

```ruby
class ResolverArityTransform < GraphQL::Upgrader::Transform
  def apply(input_text)
    regexs = [/->\s*\((.+?),\s*\*\s*\)/]
    regexs.inject(input_text) do |next_text, reg|
      input_text.gsub(reg, "-> (\\1, _, _)")
    end
  end
end
```
Perhaps this is your issue

**Comment by rmosolgo** [comment]
Closing as stale.
