### ISSUE TITLE
New API: Mutation doesn't resolve if no arguments declared in mutation class

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-ruby#1542]
@rmosolgo Hey, this used to work in the old setup but not with new class based API (or may be I am doing something wrong). 

Consider this mutation, with no arguments supplied:

```rb
class FooMutation < Base::Mutation
  graphql_name 'Foo'
  description 'returns foo'

  field :foo, String, null: false
  
  def resolve 
    "bar"
  end
end
```

Failing code:

```rb
# field.rb
puts "method", @method_sym
puts "kwargs", ruby_kwargs.inspect

if ruby_kwargs.any?
  obj.public_send(@method_sym, **ruby_kwargs)
else
  # seems to work if we pass an empty hash but then it fails on query calls
  obj.public_send(@method_sym)
end
```

```rb
# relay_classic_mutation.rb
def resolve_mutation(kwargs)
  # This is handled by Relay::Mutation::Resolve, a bit hacky, but here we are.
  puts "resolve", kwargs.inspect
  kwargs.delete(:client_mutation_id)
  resolve(**kwargs)
end
```

Stacktrace:

```bash
ArgumentError (wrong number of arguments (given 0, expected 1)):
api :
api : /Users/admin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.8.0/lib/graphql/schema/relay_classic_mutation.rb:30:in `resolve_mutation'
api : /Users/admin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.8.0/lib/graphql/schema/field.rb:367:in `public_send'
api : /Users/admin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.8.0/lib/graphql/schema/field.rb:367:in `public_send_field'
api : /Users/admin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.8.0/lib/graphql/schema/field.rb:288:in `resolve_field'
api : /Users/admin/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-batch-0.3.9/lib/graphql/batch/setup.rb:19:in `call'
```

**Comment by gauravtiwari** [comment]
Ahh yes, that's probably it. Shall I make a PR? I am not very familiar with the codebase though 😄 .

**Comment by gauravtiwari** [comment]
I guess we can just pass a default param here: 

```rb
   def resolve_mutation(kwargs = {})
        # This is handled by Relay::Mutation::Resolve, a bit hacky, but here we are.
        kwargs.delete(:client_mutation_id)
        resolve(**kwargs)
      end
```

What do you think?

**Comment by gauravtiwari** [comment]
Because it seems when there is no argument it's passing no argument to `resolve_mutation` - `ArgumentError (wrong number of arguments (given 0, expected 1)):`
