### ISSUE TITLE
GraphQL 1.8 execution errors out when fetching edges after installing Pro

### ISSUE THREAD

**Issue by mohamadbitar** [rmosolgo/graphql-ruby#1582]
After getting the `graphql-pro` gem and initializing authorization using the Pundit library, when fetching edges on a query I get an execution error.

```graphql
query{
  salesLead(id:"U2FsZXNMZWFkLTI"){
    id
    feed {
      edges {
        node {
          ... on Note {
            id
          }
        }
      }
    }
  }
}
```

On the console I get:

```bash
   No connection implementation to wrap Sequel::Postgres::Dataset (#<Sequel::Postgres::Dataset:0x00007f01785d4d48>)
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/relay/base_connection.rb:36:in `connection_for_nodes'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/relay/connection_resolve.rb:47:in `build_connection'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/relay/connection_resolve.rb:33:in `call'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/field.rb:247:in `resolve'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/execution/execute.rb:262:in `call'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/execution/execute.rb:107:in `block in resolve_field'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/tracing.rb:57:in `block in trace'
     /usr/local/bundle/gems/graphql-1.8.1/lib/graphql/tracing.rb:73:in `block (2 levels) in call_tracers'
     ... and 159 more lines
```

I don't know if it has anything to do with it, but we have migrated to graphql 1.8 about a month ago and we are using class-based syntax

Any support to figuring this out would be appreicated

**Comment by rmosolgo** [comment]
🤔  hmmm, thanks for sharing that stack trace. I wonder if it's related to GraphQL-Pro's ActiveRecord support, if it somehow messed up Sequel. I'll take a look and follow up here!

**Comment by mohamadbitar** [comment]
Yeah that could be the case, thanks for the support :slightly_smiling_face:

**Comment by rmosolgo** [comment]
Hey, I'm sorry I didn't follow up sooner. I hope you found a solution here! If not, please feel free to reopen this issue with the latest info.
