### ISSUE TITLE
Unexpected Scope type: Types::MutationType

### ISSUE THREAD

**Issue by jacobsmith** [rmosolgo/graphql-ruby#1646]
Hello - 

  I'm attempting my first mutation with graphql and running in to an odd error that I can't seem to find many issues about online. I have a feeling it has to do with trying to use the new class-based syntax since most of the issues I've found tend to lean towards the older syntax.

Anyway, I'm getting the following error:

```
#<RuntimeError: Unexpected scope type: Types::MutationType>
```

Significant files are:

```
# mutation_type.rb

class Types::MutationType < GraphQL::Schema::Object
  field :update_page, Types::PageType, mutation: Mutations::UpdatePage
end
```

```
# base_mutation.rb

class Mutations::BaseMutation < GraphQL::Schema::Mutation
end
```

```
# update_page.rb

class Mutations::UpdatePage < Mutations::BaseMutation
  argument :id      , 'ID'      , required: true
  argument :display , 'Boolean' , required: true

  field :id         , ID      , null: false
  field :display    , Boolean , null: false

  def resolve(id:, display:)
    page = Page.find(id)
    page.update(display: display)

    {
      id: page.id,
      display: page.display
    }
  end
end
```

The GraphQL query the client is sending is:

```
  mutation updatePage($id: String!, $display: Boolean!) {
    updatePage(id: $id, display: $display) {
      id
      display
    }
  }
```

and the full stacktrace is:

```
["/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/internal_representation/scope.rb:33:in `initialize'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/internal_representation/rewrite.rb:188:in `new'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/internal_representation/rewrite.rb:188:in `enter'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:65:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:65:in `block in apply_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:65:in `each'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:65:in `reduce'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:65:in `apply_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:54:in `begin_visit'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:45:in `visit_node'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:47:in `block in visit_node'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:47:in `each'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:47:in `visit_node'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/language/visitor.rb:39:in `visit'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/static_validation/validator.rb:39:in `block in validate'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/static_validation/validator.rb:25:in `validate'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/query/validation_pipeline.rb:80:in `ensure_has_validated'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/query/validation_pipeline.rb:34:in `valid?'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/query.rb:228:in `valid?'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/analysis/analyze_query.rb:11:in `block (2 levels) in analyze_multiplex'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/analysis/analyze_query.rb:10:in `map'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/analysis/analyze_query.rb:10:in `block in analyze_multiplex'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/analysis/analyze_query.rb:8:in `analyze_multiplex'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/multiplex.rb:173:in `block in instrument_and_analyze'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:58:in `call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:58:in `call_hooks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/multiplex.rb:166:in `instrument_and_analyze'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `block in trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:71:in `call_tracers'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/tracing.rb:57:in `trace'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/multiplex.rb:58:in `run_queries'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/execution/multiplex.rb:48:in `run_all'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/schema.rb:340:in `block in multiplex'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/schema.rb:975:in `with_definition_error_check'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/schema.rb:339:in `multiplex'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/graphql-1.8.3/lib/graphql/schema.rb:316:in `execute'",
 "/Users/jacobsmith/Code/magazine/magazine-api/app/controllers/graphql_controller.rb:11:in `execute'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:194:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/rendering.rb:30:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:132:in `run_callbacks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/abstract_controller/callbacks.rb:41:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/rescue.rb:22:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `block in instrument'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/notifications/instrumenter.rb:23:in `instrument'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/notifications.rb:168:in `instrument'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.0/lib/active_record/railties/controller_runtime.rb:24:in `process_action'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/abstract_controller/base.rb:134:in `process'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionview-5.2.0/lib/action_view/rendering.rb:32:in `process'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal.rb:191:in `dispatch'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_controller/metal.rb:252:in `dispatch'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:34:in `serve'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:52:in `block in serve'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `each'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/journey/router.rb:35:in `serve'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/routing/route_set.rb:840:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/olive_branch-2.1.2/lib/olive_branch/middleware.rb:58:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/tempfile_reaper.rb:15:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/etag.rb:25:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/conditional_get.rb:38:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/head.rb:12:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:232:in `context'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/session/abstract/id.rb:226:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/cookies.rb:670:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activerecord-5.2.0/lib/active_record/migration.rb:559:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/callbacks.rb:98:in `run_callbacks'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/web-console-3.5.1/lib/web_console/middleware.rb:135:in `call_app'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/web-console-3.5.1/lib/web_console/middleware.rb:28:in `block in call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `catch'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/web-console-3.5.1/lib/web_console/middleware.rb:18:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/rack/logger.rb:38:in `call_app'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `block in call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `block in tagged'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:28:in `tagged'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/tagged_logging.rb:71:in `tagged'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/rack/logger.rb:26:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/method_override.rb:22:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/runtime.rb:22:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/activesupport-5.2.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/executor.rb:14:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/actionpack-5.2.0/lib/action_dispatch/middleware/static.rb:127:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-2.0.5/lib/rack/sendfile.rb:111:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/railties-5.2.0/lib/rails/engine.rb:524:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/puma-3.11.2/lib/puma/configuration.rb:225:in `call'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/puma-3.11.2/lib/puma/server.rb:624:in `handle_request'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/puma-3.11.2/lib/puma/server.rb:438:in `process_client'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/puma-3.11.2/lib/puma/server.rb:302:in `block in run'",
 "/Users/jacobsmith/.rvm/gems/ruby-2.3.3/gems/puma-3.11.2/lib/puma/thread_pool.rb:120:in `block in spawn_thread'"]
```

in a super brief exchange with @rmosolgo on slack, he seemed to think it's an internal error from the validation step. I'm going to dig into this a bit more in the meantime and will update the issue with any revelations I find.

**Comment by jacobsmith** [comment]
Okay, I've determined that 

`lib/graphql/internal_representation/scope.rb`

is being called with a `type_defn` of `Types::MutationType`, which is not a descendant of `GraphQL::BaseType` and therefore is hitting the `raise "Unexpected scope type..."` code.

**Comment by jacobsmith** [comment]
Okay, I found out that I wasn't using the Apollo Client correctly and variables were not properly being passed. However, even after updating that, I'm still hitting the "Unexpected scope type" and `type_defn` equals `Types::MutationType`

**Comment by rmosolgo** [comment]
So weird! somehow the validation context got a reference to the class-based type instead of the result of its `.graphql_definition` method. 

Here's that line where the wrong thing is put into scope:

**Comment by jacobsmith** [comment]
Sure thing!

```
# schema.rb

MagazineApiSchema = GraphQL::Schema.define do
  mutation(Types::MutationType)
  query(Types::QueryType)

  resolve_type ->(record, _args, _ctx) do
    if record.class.ancestors.include?(ProfileComponent::Text)
      Types::ProfileComponent::BasicText
    elsif record.class.ancestors.include?(ProfileComponent::Contact)
      Types::ProfileComponent::Contact
    else
      puts "#{ record.inspect } from api_schema"
    end
  end
end
```

( the resolve type is because I was getting errors with an interface at one point - it was also within the first couple hours of even trying to hook up graphql, so it might not be necessary now)

```
[10] pry(#<GraphQL::InternalRepresentation::Scope>)> p MagazineApiSchema.mutation
Types::MutationType
=> Types::MutationType
[11] pry(#<GraphQL::InternalRepresentation::Scope>)> p MagazineApiSchema.mutation.class.name
"Class"
=> "Class"
```

**Comment by rmosolgo** [comment]
Thanks, that's great! 

I think the problem is that a Schema made with `.define` is not properly converting the root types into legacy-style types. 

Could you try switching your schema to be a class? You can see an example here: http://graphql-ruby.org/schema/definition.html

If that's not possible, you could also try adding `.graphql_definition` to the root types, for example: 

```ruby
query(Types::QueryType.graphql_definition)
# same thing for mutation
```

That work-around might do for a while, but class-based is the future, so if you can make the switch, I recommend it! Let me know if either of those help.

**Comment by jacobsmith** [comment]
@rmosolgo thank you so much! Converting the Schema over to use the class-based syntax worked just fine! Now I just have to debug apollo caching to make the UI update properly, but that's my problem, not yours! =P

Thanks so much for your work and help - do you have a donate area or something like that? I'd love to show my thanks in a more tangible way than just Internet thanks - you saved me hours of debugging! (:

**Comment by rmosolgo** [comment]
Glad to hear it worked! I don't have a donate button, but if you'd like to support graphql-ruby development and get some other goodies, your company could sign up for GraphQL-Pro: http://graphql.pro :)
