### ISSUE TITLE
Returning a type defined in a different file consistently fails.

### ISSUE THREAD

**Issue by Rob117** [rmosolgo/graphql-ruby#1659]
I have three very simple files.

query_type.rb
```
class Types::QueryType < Types::BaseObject
  field :allFlashcards, [FlashcardType], null: true,
                                     description: 'Flashcards belonging to a particular user'
  field :allDecks, [DeckType], null: true, description: 'Decks belonging to a particular user'

  def all_flashcards
    Flashcard.limit(3)
  end

  def all_decks
    Deck.limit(2)
  end
end
```

flashcard_type.rb
```
class Types::FlashcardType < Types::BaseObject
  graphql_name 'Flashcard'
  description 'A flashcard belonging to a user and deck'
  field :keyword_text, String, description: 'The main part to be translated', null: false
  field :keyword_meaning, String, description: 'The translation', null: false
  field :keyword_locale, String, description: 'The language the keyword was recognized as', null: false
  field :example_usage, String, description: 'The example sentence containing the keyword', null: false
  field :front_note, String, description: 'Custom note on the front of the card', null: false
  field :back_note, String, description: 'Custom note on the back of the card', null: false
  field :client_id, Int, description: 'Sent from the client to prevent duplicates', null: true
  field :sequential_id, Int, description: 'unique id for card tracking', null: false
  field :owning_deck, Types::DeckType, description: 'deck for this card', null: false

  def owning_deck
    object.deck
  end
end
```
deck_type.rb
```
class Types::DeckType < Types::BaseObject
  graphql_name 'Deck'
  description 'A deck belonging to a user'
  field :name, String, description: 'Deck name', null: false
  field :sequential_id, Int, description: 'Unique id for deck tracking', null: false
  field :client_id, Int, description: 'Sent from the client to prevent duplicates', null: true
end
```
The problem appears to come from the flashcard type file. If I remove the line about owning_deck, everything comes out very smoothly. If I try to include the Types::DeckType line, however, I get an error:

```
NameError (uninitialized constant Types::QueryType::DeckType):
  
app/graphql/types/query_type.rb:4:in `<class:QueryType>'
app/graphql/types/query_type.rb:1:in `<top (required)>'
app/graphql/vision_schema.rb:3:in `<class:VisionSchema>'
app/graphql/vision_schema.rb:1:in `<top (required)>'
app/controllers/graphql_controller.rb:15:in `execute'
```

I've also tried removing the Types:: prefix, to no avail. Am I simply doing something wrong, or is this a bug?

**Comment by rmosolgo** [comment]
The last line in the backtrace is `query_type.rb:4`, what's on that line? 

If you make the following change: 

```diff 
- field :allDecks, [DeckType], null: true, description: 'Decks belonging to a particular user'
+ field :allDecks, [Types::DeckType], null: true, description: 'Decks belonging to a particular user'
```

Does the situation change?

**Comment by Rob117** [comment]
Yeah, that worked. Why does that field need the Types prefix but the return type above it (Flashcard) doesn't?

**Comment by rmosolgo** [comment]
🤷‍♂️  Dunno, weird Rails stuff. I almost always put the prefix because Rails autoloading is so hard to debug.
