### ISSUE TITLE
Better error traceback please~

### ISSUE THREAD

**Issue by xpol** [rmosolgo/graphql-ruby#1720]
With code:

```ruby
  field :all_options, [Types::OptionType, null: true], null: false, description: 'Get all options'

  def all_options(obj, args, ctx)
    ::Option.all
  end
```

I got the follow error:

```
ArgumentError (wrong number of arguments (given 0, expected 3)):
  app/graphql/types/query_type.rb:338:in `all_options'
  app/controllers/graphql_controller.rb:14:in `execute'
```

But I just don't know where cause the error... because the error does not have details information about where the code cause it.

**Comment by xpol** [comment]
Ok Its due to the updater did not output correct args types for me.

```ruby
def all_options(obj, args, ctx)
 # ...
end
```
Should be 
```ruby
def all_options(**args)
 # ...
end
```
