### ISSUE TITLE
Internal failure when trying to add a field named "method"

### ISSUE THREAD

**Issue by blackchestnut** [rmosolgo/graphql-ruby#1830]
I have problem with https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L438
when trying to create a field with name "method":
```
class Types::NotificationActionType < Types::BaseObject
  description 'Notification Action'

  field :url, String,
    null: false,
    description: 'Action rest-API url'

  field :method, String,           # <-----------
    null: false,
    description: 'Method for API url (GET/POST)'
end
```
Unfortunately I can't change the name of the field, because I already have a public api on graphql (1.7.13)
Is there a workaround here?
Thanks!

**Gems versions:**
- graphiql-rails (1.4.11)
- graphql (1.8.8)

**Backtrace:**
```
wrong number of arguments (given 0, expected 1)
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/field.rb:438:in `method'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/field.rb:438:in `public_send'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/field.rb:438:in `public_send_field'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/field.rb:346:in `block in resolve_field'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema.rb:1013:in `after_lazy'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/field.rb:333:in `resolve_field'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/field.rb:248:in `call'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/field.rb:248:in `resolve'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:295:in `call'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:108:in `block in resolve_field'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/tracing.rb:62:in `block in trace'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/tracing.rb:62:in `trace'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:107:in `resolve_field'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:64:in `each'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:64:in `resolve_selection'
/Users/slash/.rvm/gems/ruby-2.5.1/gems/graphql-1.8.8/lib/graphql/execution/execute.rb:260:in `resolve_value'
```

**Comment by blackchestnut** [comment]
I found a temporary way to workaround the issue:
```diff
class Types::NotificationActionType < Types::BaseObject
  description 'Notification Action'

  field :url, String,
    null: false,
    description: 'Action API url'

  field :method, String,
    null: false,
    description: 'Method for API url (GET/POST)',
+   method: :api_method
end
```

**Comment by rmosolgo** [comment]
Yes, that's the way to do it! See also https://github.com/rmosolgo/graphql-ruby/issues/1320#issuecomment-369693708

Glad you found something that works and thanks for sharing it. Feel free to update the docs if you think it belongs somewhere.
