### ISSUE TITLE
1.8.10: undefined method `unwrap' for nil:NilClass

### ISSUE THREAD

**Issue by tjhorner** [rmosolgo/graphql-ruby#1899]
Whenever any query is executed, I get the error `undefined method 'unwrap' for nil:NilClass`. But here's the catch: it only happens in production! So I think it has something to do with class caching.

(This is the same issue as #1463, but the [proposed fix](https://github.com/rmosolgo/graphql-ruby/issues/1463#issuecomment-386024338) did not work, so this may be another underlying issue.)

## Versions

- `graphql`: 1.8.10
- Ruby: 2.4.0
- Rails: 5.2.1

## Stack Trace

The error seems to happen here:

https://github.com/rmosolgo/graphql-ruby/blob/c67fae0e77c70222a54565f38039c05f9efc8e61/lib/graphql/static_validation/type_stack.rb#L110

I attempted to debug it myself, but to no avail.

```
undefined method `unwrap' for nil:NilClass
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/static_validation/type_stack.rb:110:in `push'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/static_validation/type_stack.rb:200:in `call'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:65:in `block in apply_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:65:in `each'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:65:in `reduce'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:65:in `apply_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:54:in `begin_visit'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:45:in `visit_node'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `each'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `visit_node'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `each'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:47:in `visit_node'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/language/visitor.rb:39:in `visit'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/static_validation/validator.rb:39:in `block in validate'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:62:in `block in trace'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:76:in `call_tracers'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:62:in `trace'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/static_validation/validator.rb:25:in `validate'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/query/validation_pipeline.rb:73:in `ensure_has_validated'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/query/validation_pipeline.rb:45:in `internal_representation'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/query.rb:205:in `irep_selection'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/schema/member/instrumentation.rb:22:in `before_query'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:58:in `public_send'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:58:in `block in call_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:57:in `each'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:57:in `call_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:70:in `call_hooks'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/multiplex.rb:166:in `instrument_and_analyze'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:62:in `block in trace'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:76:in `call_tracers'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/tracing.rb:62:in `trace'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/multiplex.rb:58:in `run_queries'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/execution/multiplex.rb:48:in `run_all'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/schema.rb:342:in `block in multiplex'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/schema.rb:1079:in `with_definition_error_check'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/schema.rb:341:in `multiplex'
/usr/local/bundle/gems/graphql-1.8.10/lib/graphql/schema.rb:318:in `execute'
/usr/src/app/app/controllers/graphql_controller.rb:11:in `execute'
```

The schema in question:

```ruby
class MyActualSchema < GraphQL::Schema
  max_depth 50
  # Both `Types::MutationType` and `Types::QueryType` are defined, and both work in development.
  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

And `graphql_controller.rb:11`:

```ruby
# Where MyActualSchema is the name of my schema class
result = MyActualSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
```

I suspected originally it was because I was using an undefined type somewhere but that doesn't seem to be the case. This only happens with `RAILS_ENV=production`, so classes are cached among other things. Any help would be greatly appreciated.

**Comment by klenis** [comment]
Got the same error. In my case the issue was that the type class conflicted with a model in Rails and namespacing was missing from a GraphQL definition.

ActiveRecord
```
app/models/product.rb
```

GraphQL
```
app/graphql/types/product.rb
```

Namespace missing in GraphQL definition

```
class Types::ProductEdge < GraphQL::Types::Relay::BaseEdge
  node_type(Product)
end
```

The solution was to be specific and add namespace

```
class Types::ProductEdge < GraphQL::Types::Relay::BaseEdge
  node_type(Types::Product)
end
```

Hope this helps :)

**Comment by tjhorner** [comment]
I thought that as well, but everything was already prefixed with `Types::` and all the GQL types are `ModelType` (where the AR model would be `Model`), so that couldn't conflict with my ActiveRecord model names. Thank you for the suggestion, but it seems my problem is different :(

**Comment by rmosolgo** [comment]
Sorry I didn't help on this sooner! I'm going to close it as stale. If you're still having trouble, could you please reopen this with the latest stack trace and error message?
