### ISSUE TITLE
[pro] Pundit integration issue with connections

### ISSUE THREAD

**Issue by cheerfulstoic** [rmosolgo/graphql-ruby#1974]
I've been working on this issue for a couple of days and maybe it's time to just ask a question to see if you have an answer ;)

I have a `used_by` field which returns a connection (specifically an anonymous subclass which we define in our app from an `ActiveRecordConnection` class which inherits from `GraphQL::Types::Relay::BaseConnection`).  We've been trying to get Pundit integration working, but when we have it on it seems to be able to get `usedBy { edges { node { id } } }` but not `usedBy { nodes { id } }`.

Specifically the error that it gives is `Pundit error: Pundit::NotDefinedError, unable to find scope User::UserPolicy::Scope`.  I tracked it down and that was due to an array of two `User` objects being passed to pundit to get the scope.  If three users are passed in it would give an error about `User::User::UserPolicy::Scope`.  So basically it seems like for the `usedBy.edges.node` it is using the ActiveRecord relation which is being returned from the method on the GraphQL type class, but for `usedBy.nodes` it is turning the relation into into an `Array` which in being given to Pundit.

This all seems to happen just when we're trying to use the Pundit integration.  I've tracked the thing which is creating the array as being in `ColumnValueConnection#next_page_and_nodes` and I think maybe the problem is that it should be using the Pundit scope before it's doing the pagination.  Maybe the pro pagination is different in this regard?  Does this ring a bell?  Again, I can keep digging, but I wanted to check to see if the answer was obvious

**Comment by cheerfulstoic** [comment]
By the way, in case it's helpful one place that I looked was here:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L357

At that point, `v` is a `User::ActiveRecord_Relation` relation when `ctx.path` is `['product', 'usedBy']` and `v` is an `Array` later when `ctx.path` is `['product', 'usedBy', 'nodes']`

**Comment by rmosolgo** [comment]
Wow, ok, thanks for the great writeup! I haven't seen something like this before. 

Could you share the whole backtrace of the error you mention above? It seems like the wrong value (an Array, like you said) is being passed to Pundit. 

> `ColumnValueConnection#next_page_and_nodes`

I see a call to `sliced_nodes` there, which goes to the super class, and I think that one applies the cursors, so that might be what creates the Array.

**Comment by cheerfulstoic** [comment]
:+1: Will do when I get back to work on Monday, thanks!  This is actually happening (IIRC) when cursors aren't being applied.  If I put in an `after` I think the problem went away.  Again, I'll check on Monday

**Comment by cheerfulstoic** [comment]
Here's the error and the backtrace (`User` attributes removed)

```
          GraphQL::Pro::PunditIntegration::PolicyNotFoundError:
            No policy found for:

            - Type: User
            - Runtime value: `[#<User ID: 10, ...>, #<User ID: 11, ...>]`

            Pundit error: Pundit::NotDefinedError, unable to find scope `User::UserPolicy::Scope` for `[#<User ID: 10, ...>, #<User ID: 11, ...>]`
          # /usr/local/bundle/gems/graphql-pro-1.9.2/lib/graphql/pro/pundit_integration.rb:120:in `rescue in scope_by_policy'
          # /usr/local/bundle/gems/graphql-pro-1.9.2/lib/graphql/pro/pundit_integration.rb:114:in `scope_by_policy'
          # /usr/local/bundle/gems/graphql-pro-1.9.2/lib/graphql/pro/pundit_integration.rb:111:in `scope_items'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/field.rb:402:in `block in apply_scope'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:1013:in `after_lazy'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/field.rb:401:in `apply_scope'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/field.rb:353:in `block in resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:1013:in `after_lazy'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/field.rb:338:in `resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/member/instrumentation.rb:74:in `call'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/member/instrumentation.rb:74:in `call'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/field.rb:248:in `resolve'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:295:in `call'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/middleware_chain.rb:51:in `block in invoke_core'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/rescue_middleware.rb:35:in `call'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/middleware_chain.rb:51:in `invoke_core'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:108:in `block in resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `block in trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:71:in `call_tracers'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:107:in `resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `each'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:260:in `resolve_value'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:254:in `resolve_value'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:189:in `continue_resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:160:in `continue_or_wait'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:133:in `resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `each'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:260:in `resolve_value'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:276:in `resolve_value'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:254:in `resolve_value'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:189:in `continue_resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:160:in `continue_or_wait'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:133:in `resolve_field'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `each'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:64:in `resolve_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `block in trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:71:in `call_tracers'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:108:in `begin_query'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:80:in `map'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:175:in `block in instrument_and_analyze'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:167:in `instrument_and_analyze'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `block in trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:71:in `call_tracers'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/tracing.rb:57:in `trace'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:58:in `run_queries'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/execution/multiplex.rb:48:in `run_all'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:342:in `block in multiplex'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:1079:in `with_definition_error_check'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:341:in `multiplex'
          # /usr/local/bundle/gems/graphql-1.8.11/lib/graphql/schema.rb:318:in `execute'
          # ./spec/support/helpers/graphql_helper.rb:23:in `rutilus_schema_result'
          # ./spec/graphql/types/interfaces/product_like_spec.rb:8:in `block (2 levels) in <top (required)>'
          # ./spec/support/helpers/graphql_helper.rb:45:in `block (2 levels) in result_path'
          # ./spec/graphql/types/interfaces/product_like_spec.rb:114:in `block (6 levels) in <top (required)>'
          # ./spec/spec_helper.rb:58:in `block (2 levels) in <top (required)>'
          # ------------------
          # --- Caused by: ---
          # Pundit::NotDefinedError:
          #   unable to find scope `User::UserPolicy::Scope` for `[#<User ID: 10, ...>, #<User ID: 11, ...>]`
          #   /usr/local/bundle/gems/pundit-2.0.0/lib/pundit/policy_finder.rb:45:in `scope!'
```

**Comment by rmosolgo** [comment]
Thanks! Let me dig in a bit 👷

**Comment by rmosolgo** [comment]
Could you share your `field(...)` configuration for this field (the one that returns a user connection)? I'm not able to replicate the issue with a simple relation + pundit scoping, so maybe that will help!

**Comment by rmosolgo** [comment]
I'm sorry to come back to this so long after the fact ... but I never got the email, was it sent? 🙈  

If you're still having this problem, please do let me know at rmosolgo@graphql.pro or open a new issue!
