### ISSUE TITLE
Undefined Method role for GraphQL::Pro::Access::Instrumentation::RuntimeTypeGate

### ISSUE THREAD

**Issue by ijones16** [rmosolgo/graphql-ruby#1988]
- graphql (1.8.8)
- graphql-batch (0.3.5)
- graphql-pro (1.7.12)
- rails (5.0.7)
- cancancan (2.1.3)

Im trying to add a union type to my app and Im getting an odd error: `> undefined method 'role' for #<GraphQL::Pro::Access::Instrumentation::RuntimeTypeGate:0x007fcfc3698508>`

I followed the documentation with adding a `Types::BaseUnion`

heres my `tracklist_types.rb` file:
```
class Types::TracklistType < Types::BaseUnion
  description "Tracklist of a Playlist"
  possible_types Types::CourseType, Types::LessonType
end
```

and my type thats using it `playlist.rb`:
```
class Types::Playlist < Types::BaseObject
  # ...
  field :tracklists, [Types::TracklistType]
  # ...
end
```

and the query:
```
{
  playlists{
    tracklists{
      ... on Lesson {
          title
        }      
    }
  }
}
```

<details>
  <summary>Stack Trace</summary>

```
  | [888000b4-79c7-4b97-a24b-41097e39cac2] method=POST path=/graphql format=*/* controller=graphql action=execute status=500 error='NoMethodError:undefined method `role' for #<GraphQL::Pro::Access::Instrumentation::RuntimeTypeGate:0x007fcfc3698508>' duration=1587.91 view=0.00 db=84.81
88000b4-79c7-4b97-a24b-41097e39cac2] 
MethodError - undefined method `role' for #<GraphQL::Pro::Access::Instrumentation::RuntimeTypeGate:0x007fcfc3698508>:
graphql-pro (1.7.12) lib/graphql/pro/access/can_can_strategy.rb:15:in `scope'
graphql-pro (1.7.12) lib/graphql/pro/access/instrumentation/merged_gate.rb:39:in `scope'
graphql-pro (1.7.12) lib/graphql/pro/access/instrumentation/merged_gate.rb:27:in `allowed_value'
graphql-pro (1.7.12) lib/graphql/pro/access/instrumentation/authorized_resolve.rb:57:in `call'
graphql-pro (1.7.12) lib/graphql/pro/access/instrumentation/authorized_resolve.rb:61:in `call'
graphql-pro (1.7.12) lib/graphql/pro/access/instrumentation/authorized_resolve.rb:29:in `call'
graphql (1.8.8) lib/graphql/schema/member/instrumentation.rb:74:in `call'
graphql (1.8.8) lib/graphql/field.rb:248:in `resolve'
graphql (1.8.8) lib/graphql/execution/execute.rb:295:in `call'
graphql (1.8.8) lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
graphql (1.8.8) lib/graphql/schema/middleware_chain.rb:38:in `invoke'
graphql (1.8.8) lib/graphql/execution/execute.rb:108:in `block in resolve_field'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `block in trace'
graphql (1.8.8) lib/graphql/tracing.rb:76:in `call_tracers'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `trace'
graphql (1.8.8) lib/graphql/execution/execute.rb:107:in `resolve_field'
graphql (1.8.8) lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
graphql (1.8.8) lib/graphql/execution/execute.rb:64:in `resolve_selection'
graphql (1.8.8) lib/graphql/execution/execute.rb:260:in `resolve_value'
graphql (1.8.8) lib/graphql/execution/execute.rb:189:in `continue_resolve_field'
graphql (1.8.8) lib/graphql/execution/execute.rb:160:in `continue_or_wait'
graphql (1.8.8) lib/graphql/execution/execute.rb:239:in `block in resolve_value'
graphql (1.8.8) lib/graphql/execution/execute.rb:232:in `resolve_value'
graphql (1.8.8) lib/graphql/execution/execute.rb:189:in `continue_resolve_field'
graphql (1.8.8) lib/graphql/execution/execute.rb:160:in `continue_or_wait'
graphql (1.8.8) lib/graphql/execution/execute.rb:133:in `resolve_field'
graphql (1.8.8) lib/graphql/execution/execute.rb:71:in `block in resolve_selection'
graphql (1.8.8) lib/graphql/execution/execute.rb:64:in `resolve_selection'
graphql (1.8.8) lib/graphql/execution/execute.rb:36:in `block in resolve_root_selection'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `block in trace'
graphql (1.8.8) lib/graphql/tracing.rb:76:in `call_tracers'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `trace'
graphql (1.8.8) lib/graphql/execution/execute.rb:32:in `resolve_root_selection'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:108:in `begin_query'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:81:in `block in run_as_multiplex'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:80:in `run_as_multiplex'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:69:in `block (2 levels) in run_queries'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:174:in `block in instrument_and_analyze'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:70:in `call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:70:in `call_hooks'
graphql (1.8.8) lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:166:in `instrument_and_analyze'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:68:in `block in run_queries'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `block in trace'
graphql (1.8.8) lib/graphql/tracing.rb:76:in `call_tracers'
graphql (1.8.8) lib/graphql/tracing.rb:62:in `trace'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:58:in `run_queries'
graphql (1.8.8) lib/graphql/execution/multiplex.rb:48:in `run_all'
graphql (1.8.8) lib/graphql/schema.rb:342:in `block in multiplex'
graphql (1.8.8) lib/graphql/schema.rb:1057:in `with_definition_error_check'
graphql (1.8.8) lib/graphql/schema.rb:341:in `multiplex'
graphql (1.8.8) lib/graphql/schema.rb:318:in `execute'
app/controllers/graphql_controller.rb:12:in `execute'
actionpack (5.0.7.1) lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
actionpack (5.0.7.1) lib/abstract_controller/base.rb:188:in `process_action'
scout_apm (2.4.9) lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:72:in `process_action'
actionpack (5.0.7.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.0.7.1) lib/abstract_controller/callbacks.rb:20:in `block in process_action'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:126:in `call'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:455:in `call'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:101:in `__run_callbacks__'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.1) lib/abstract_controller/callbacks.rb:19:in `process_action'
actionpack (5.0.7.1) lib/action_controller/metal/rescue.rb:20:in `process_action'
actionpack (5.0.7.1) lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
activesupport (5.0.7.1) lib/active_support/notifications.rb:164:in `block in instrument'
activesupport (5.0.7.1) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
activesupport (5.0.7.1) lib/active_support/notifications.rb:164:in `instrument'
actionpack (5.0.7.1) lib/action_controller/metal/instrumentation.rb:30:in `process_action'
actionpack (5.0.7.1) lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
activerecord (5.0.7.1) lib/active_record/railties/controller_runtime.rb:18:in `process_action'
scout_apm (2.4.9) lib/scout_apm/instruments/action_controller_rails_3_rails4.rb:83:in `process_action'
actionpack (5.0.7.1) lib/abstract_controller/base.rb:126:in `process'
actionview (5.0.7.1) lib/action_view/rendering.rb:30:in `process'
actionpack (5.0.7.1) lib/action_controller/metal.rb:190:in `dispatch'
actionpack (5.0.7.1) lib/action_controller/metal.rb:262:in `dispatch'
actionpack (5.0.7.1) lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
actionpack (5.0.7.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'
actionpack (5.0.7.1) lib/action_dispatch/journey/router.rb:39:in `block in serve'
actionpack (5.0.7.1) lib/action_dispatch/journey/router.rb:26:in `serve'
actionpack (5.0.7.1) lib/action_dispatch/routing/route_set.rb:727:in `call'
scout_apm (2.4.9) lib/scout_apm/instruments/rails_router.rb:29:in `call_with_scout_instruments'
omniauth (1.8.1) lib/omniauth/strategy.rb:190:in `call!'
omniauth (1.8.1) lib/omniauth/strategy.rb:168:in `call'
bullet (5.3.0) lib/bullet/rack.rb:10:in `call'
server_timing (1.0.1) lib/server_timing/middleware.rb:8:in `call'
scout_apm (2.4.9) lib/scout_apm/instant/middleware.rb:53:in `call'
scout_apm (2.4.9) lib/scout_apm/middleware.rb:17:in `call'
warden (1.2.7) lib/warden/manager.rb:36:in `block in call'
warden (1.2.7) lib/warden/manager.rb:35:in `call'
rack (2.0.6) lib/rack/etag.rb:25:in `call'
rack (2.0.6) lib/rack/conditional_get.rb:38:in `call'
rack (2.0.6) lib/rack/head.rb:12:in `call'
rack (2.0.6) lib/rack/session/abstract/id.rb:232:in `context'
rack (2.0.6) lib/rack/session/abstract/id.rb:226:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/cookies.rb:613:in `call'
activerecord (5.0.7.1) lib/active_record/migration.rb:553:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:97:in `__run_callbacks__'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
activesupport (5.0.7.1) lib/active_support/callbacks.rb:90:in `run_callbacks'
actionpack (5.0.7.1) lib/action_dispatch/middleware/callbacks.rb:36:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
better_errors (1.1.0) lib/better_errors/middleware.rb:84:in `protected_app_call'
better_errors (1.1.0) lib/better_errors/middleware.rb:79:in `better_errors_call'
better_errors (1.1.0) lib/better_errors/middleware.rb:56:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
lograge (0.3.1) lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
railties (5.0.7.1) lib/rails/rack/logger.rb:24:in `block in call'
activesupport (5.0.7.1) lib/active_support/tagged_logging.rb:69:in `block in tagged'
activesupport (5.0.7.1) lib/active_support/tagged_logging.rb:26:in `tagged'
activesupport (5.0.7.1) lib/active_support/tagged_logging.rb:69:in `tagged'
railties (5.0.7.1) lib/rails/rack/logger.rb:24:in `call'
ahoy_matey (2.1.0) lib/ahoy/engine.rb:20:in `call_with_quiet_ahoy'
request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
request_store_rails (1.0.3) lib/request_store_rails/middleware.rb:17:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/request_id.rb:24:in `call'
rack (2.0.6) lib/rack/method_override.rb:22:in `call'
rack (2.0.6) lib/rack/runtime.rb:22:in `call'
activesupport (5.0.7.1) lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/executor.rb:12:in `call'
actionpack (5.0.7.1) lib/action_dispatch/middleware/static.rb:136:in `call'
rack (2.0.6) lib/rack/sendfile.rb:111:in `call'
hirefire-resource (0.4.2) lib/hirefire/middleware.rb:41:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (2.7.2) lib/honeybadger/config.rb:192:in `with_request'
honeybadger (2.7.2) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/user_feedback.rb:28:in `call'
honeybadger (2.7.2) lib/honeybadger/rack/user_informer.rb:18:in `call'
rack-cors (1.0.1) lib/rack/cors.rb:93:in `call'
webpacker (3.4.1) lib/webpacker/dev_server_proxy.rb:18:in `perform_request'
rack-proxy (0.6.4) lib/rack/proxy.rb:57:in `call'
scout_apm (2.4.9) lib/scout_apm/instruments/middleware_summary.rb:58:in `call'
railties (5.0.7.1) lib/rails/engine.rb:522:in `call'
rack-rewrite (1.5.1) lib/rack/rewrite.rb:24:in `call'
puma (3.12.0) lib/puma/configuration.rb:225:in `call'
puma (3.12.0) lib/puma/server.rb:658:in `handle_request'
puma (3.12.0) lib/puma/server.rb:472:in `process_client'
puma (3.12.0) lib/puma/server.rb:332:in `block in run'
puma (3.12.0) lib/puma/thread_pool.rb:133:in `block in spawn_thread'
```

</details>

**Comment by rmosolgo** [comment]
Hey! Sorry about the bug and thanks for posting a detailed report. 

It looks like you're using the new class-based API to define your schema ✨ but using the previous graphql-pro cancan integration. Is that right? Would it be an option to upgrade to the [new CanCan integration](http://graphql-ruby.org/authorization/can_can_integration), built for class-based schemas? 

If not, could you share your schema configuration where you're hooking up graphql-pro authorization?

**Comment by ijones16** [comment]
Yeah. It looks like that was the issue. 

Cheers!
