### ISSUE TITLE
Using group throws undefined method `to_i' for {1=>1, 14=>1}:Hash Did you mean?  to_s

### ISSUE THREAD

**Issue by jchatel** [rmosolgo/graphql-ruby#2041]
I have a ConnectionType where I need to rely on a query containing a group.

Problem is that doing count on this returns a hash instead of an int.

It's a well-known problem of pagination gems (e.g. https://github.com/mislav/will_paginate/issues/167)

Not sure if / how this can be solved here?

**Comment by rmosolgo** [comment]
Hi, I can't debug without a full error message and stack trace. If you'd like to look into this together, please reopen with example Ruby code and a full backtrace.

**Comment by fedefa** [comment]
@rmosolgo Having the same issue, the issue is easy to reproduce returning a connection that is based on a grouped AR collection, for example you can have something like this:

```
type Types::UserType.connection_type, null: false

def resolve
 User.select('json_agg(id)').group(:name)
end 
```
 
Could you help me please?

Here is the stack trace:


```
[2022-12-16T11:37:24.705-03:00] ERROR: undefined method `to_i' for #<Hash:0x00000001270d9fd0>
Did you mean?  to_s
               to_a
               to_h
[2022-12-16T11:37:24.705-03:00] ERROR: /Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/types/int.rb:24:in `coerce_result'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:694:in `continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:525:in `block (3 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:522:in `block (2 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:434:in `evaluate_selection'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:368:in `block (2 levels) in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:752:in `block (3 levels) in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:751:in `block (2 levels) in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:200:in `tap_or_each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:742:in `block in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:728:in `continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:525:in `block (3 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:522:in `block (2 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:434:in `evaluate_selection'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:368:in `block (2 levels) in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:752:in `block (3 levels) in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:751:in `block (2 levels) in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:200:in `tap_or_each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:742:in `block in continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:728:in `continue_field'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:525:in `block (3 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:522:in `block (2 levels) in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:438:in `block in evaluate_selection'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema/member/has_arguments.rb:246:in `block (3 levels) in coerce_arguments'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema/member/has_arguments.rb:227:in `block (2 levels) in coerce_arguments'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema/member/has_arguments.rb:226:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema/member/has_arguments.rb:226:in `block in coerce_arguments'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema/member/has_arguments.rb:255:in `coerce_arguments'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/arguments_cache.rb:52:in `dataload_for'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:437:in `evaluate_selection'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:368:in `block (2 levels) in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `evaluate_selections'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:241:in `block (4 levels) in run_eager'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:240:in `block (3 levels) in run_eager'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:238:in `block (2 levels) in run_eager'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:200:in `tap_or_each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:229:in `block in run_eager'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:220:in `run_eager'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:74:in `block (6 levels) in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/tracing.rb:65:in `trace'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:73:in `block (5 levels) in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:61:in `block (4 levels) in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `each_with_index'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `block (3 levels) in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:44:in `block in run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/tracing.rb:65:in `trace'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:37:in `run_all'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema.rb:1005:in `multiplex'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/graphql-2.0.15/lib/graphql/schema.rb:981:in `execute'
/Users/fjfarina/Workspace/arc-api/app/controllers/graphql_controller.rb:16:in `block in execute'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/paper_trail-13.0.0/lib/paper_trail/request.rb:107:in `with'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/paper_trail-13.0.0/lib/paper_trail.rb:77:in `request'
/Users/fjfarina/Workspace/arc-api/app/controllers/graphql_controller.rb:15:in `execute'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/abstract_controller/base.rb:194:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:132:in `run_callbacks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/notifications.rb:168:in `instrument'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/abstract_controller/base.rb:134:in `process'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal.rb:191:in `dispatch'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_controller/metal.rb:252:in `dispatch'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/journey/router.rb:35:in `each'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/journey/router.rb:35:in `serve'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/routing/route_set.rb:840:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bullet-7.0.4/lib/bullet/rack.rb:12:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/flipper-0.25.4/lib/flipper/middleware/memoizer.rb:72:in `memoized_call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/flipper-0.25.4/lib/flipper/middleware/memoizer.rb:37:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-attack-6.6.1/lib/rack/attack.rb:103:in `call'
/Users/fjfarina/Workspace/arc-api/lib/webhook_middleware.rb:27:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activerecord-5.2.8.1/lib/active_record/migration.rb:559:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/bugsnag-6.24.2/lib/bugsnag/integrations/rack.rb:51:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/lograge-0.12.0/lib/lograge/rails_ext/rack/logger.rb:18:in `call_app'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/railties-5.2.8.1/lib/rails/rack/logger.rb:28:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/activesupport-5.2.8.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/actionpack-5.2.8.1/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/railties-5.2.8.1/lib/rails/engine.rb:524:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/rack-attack-6.6.1/lib/rack/attack.rb:127:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/configuration.rb:252:in `call'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/request.rb:77:in `block in handle_request'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/request.rb:76:in `handle_request'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/server.rb:443:in `process_client'
/Users/fjfarina/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/puma-5.6.5/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by rmosolgo** [comment]
Hey @fedefa , could you please open a new issue for the trouble you've encountered? Be sure to include the query you used and the response you _expected_ from GraphQL-Ruby in this case.

**Comment by fedefa** [comment]
Hi @rmosolgo! Sorry but this bug was not a library issue. The error was happening since we defined a custom GraphQL::Types::Relay::PageInfo with a "total_count" that doesn't support grouped AR collections. Thank you for your quick response!
