### ISSUE TITLE
Broken Node Interface in new interpreter runtime

### ISSUE THREAD

**Issue by Kenneth-KT** [rmosolgo/graphql-ruby#2082]
New interpreter from release 1.9.0 (#1884) has broken the node interface.

Given node interface fields are included in schema and new interpreter is enabled:
```ruby
  field :node, field: GraphQL::Relay::Node.field
  field :nodes, field: GraphQL::Relay::Node.plural_field

  use GraphQL::Execution::Interpreter
```
and `object_from_id` is implemented as a debugger call:
```ruby
def self.object_from_id(id, query_ctx)
    byebug
end
```

When present with query below:
```GraphQL
{
  nodes(ids: ["any string"]) {
    id
  }
}
```

It responds with error below:
```json
{
  "error": {
    "message": "Failed to build return type for Query.nodes from nil: Unexpected type input:  (NilClass)",
    "backtrace": [
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema/member/build_type.rb:80:in `parse_type'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema/field.rb:393:in `type'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter/runtime.rb:141:in `block in evaluate_selections'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter/runtime.rb:115:in `each'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter/runtime.rb:115:in `evaluate_selections'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter/runtime.rb:53:in `run_eager'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:57:in `block in trace'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:71:in `call_tracers'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:57:in `trace'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter.rb:72:in `evaluate'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/interpreter.rb:45:in `begin_query'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:112:in `begin_query'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:83:in `map'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:182:in `block in instrument_and_analyze'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:57:in `block in trace'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:71:in `call_tracers'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/tracing.rb:57:in `trace'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:59:in `run_queries'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/execution/multiplex.rb:49:in `run_all'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema.rb:375:in `block in multiplex'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema.rb:1197:in `with_definition_error_check'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema.rb:374:in `multiplex'",
      "/gems/graphql-1.9.0.pre2/lib/graphql/schema.rb:351:in `execute'",
      "/app/app/controllers/graphql_controller.rb:15:in `execute'",
      ".... omitted"
    ]
  },
  "data": {}
}
```

And the `byebug` debugger call was never triggered.

Expect it to trigger debugger call without errors.

It is reproducible in RubyGem version 1.9.pre2 and 1.9.pre3 using ruby version 2.5.3.

After disabling new interpreter by removing `use GraphQL::Execution::Interpreter`, it successfully triggers the debugger call.

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! 

There's a work-around listed here: https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/interpreter.md#installation. Could you give it a try and see if it fixes this for you?

But maybe the library can be improved so that the suggested code change is not required. I will take another look before releasing.

**Comment by rmosolgo** [comment]
The previous config will be supported with a warning in the next version. Thanks for reporting this!
