### ISSUE TITLE
1.9 series breaks schema introspection with skylight enabled

### ISSUE THREAD

**Issue by simoleone** [rmosolgo/graphql-ruby#2125]
I was trying to upgrade from the 1.8 releases to the 1.9 releases and we use skylight like this....
```ruby
class OurSchema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  mutation(Types::MutationType)
  query(Types::QueryType)
  use(GraphQL::Tracing::SkylightTracing, set_endpoint_name: true)
end
```

Normal queries seem to work fine, but when graphiql or another tool issue a schema introspection query, things blow up like this:
```
undefined method `kind' for #<LateBoundType @name=__Schema>
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/platform_tracing.rb:38:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:62:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:197:in `block (2 levels) in evaluate_selections'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:337:in `block in resolve_with_directives'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:343:in `run_directive'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:337:in `resolve_with_directives'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:195:in `block in evaluate_selections'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:115:in `each'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:115:in `evaluate_selections'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter/runtime.rb:53:in `run_eager'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:62:in `block in trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:76:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/backtrace/tracer.rb:45:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/skylight_tracing.rb:52:in `block in platform_trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/skylight-core-4.0.0.beta/lib/skylight/core/instrumentable.rb:113:in `instrument'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/skylight_tracing.rb:51:in `platform_trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:62:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter.rb:72:in `evaluate'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/interpreter.rb:45:in `begin_query'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:112:in `begin_query'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:83:in `map'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:182:in `block in instrument_and_analyze'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:62:in `block in trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:76:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/backtrace/tracer.rb:30:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `block in call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/skylight_tracing.rb:52:in `block in platform_trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/skylight-core-4.0.0.beta/lib/skylight/core/instrumentable.rb:113:in `instrument'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/skylight_tracing.rb:51:in `platform_trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:78:in `call_tracers'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/tracing.rb:62:in `trace'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/execution/multiplex.rb:49:in `run_all'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/schema.rb:376:in `block in multiplex'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/schema.rb:1205:in `with_definition_error_check'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/schema.rb:375:in `multiplex'
/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.2/lib/graphql/schema.rb:352:in `execute'
/Development/the-app//app/controllers/graphql_controller.rb:37:in `execute'
```

The issue only occurs when both `use GraphQL::Execution::Interpreter` and `use(GraphQL::Tracing::SkylightTracing, set_endpoint_name: true)` are present, disabling either one makes the issue go away.

Let me know if I can provide more information!

**Comment by rmosolgo** [comment]
Thanks for sharing the error message and stack trace, I'll take a look soon! 

My guess is that we have to account for those LateBoundTypes. I think this: 

https://github.com/rmosolgo/graphql-ruby/blob/25be1b945ccab3c3515309e6d4148d09d4ba5b2e/lib/graphql/tracing/platform_tracing.rb#L37

Should get the same treatment as: 

https://github.com/rmosolgo/graphql-ruby/blob/25be1b945ccab3c3515309e6d4148d09d4ba5b2e/lib/graphql/execution/interpreter/runtime.rb#L368-L374
