### ISSUE TITLE
Schema::Subscription fails when no arguments

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#2130]
Oops, it should be `def subscribe(args = {})` for example:

```
Unexpected error while processing request: wrong number of arguments (given 0, expected 1)
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/subscription.rb:60:in `subscribe'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/subscription.rb:47:in `resolve_subscribe'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/subscription.rb:42:in `public_send'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/subscription.rb:42:in `resolve'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/resolver.rb:92:in `public_send'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/resolver.rb:92:in `block (3 levels) in resolve_with_support'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema.rb:1132:in `after_lazy'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/resolver.rb:78:in `block (2 levels) in resolve_with_support'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema.rb:1132:in `after_lazy'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/resolver.rb:71:in `block in resolve_with_support'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema.rb:1132:in `after_lazy'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/resolver.rb:60:in `resolve_with_support'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:603:in `public_send'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:603:in `block in public_send_field'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:616:in `with_extensions'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:591:in `public_send_field'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:462:in `block in resolve_field'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema.rb:1132:in `after_lazy'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/field.rb:450:in `resolve_field'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/subscriptions/instrumentation.rb:47:in `call'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/subscriptions/instrumentation.rb:47:in `call'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/member/instrumentation.rb:74:in `call'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/field.rb:248:in `resolve'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/execution/execute.rb:314:in `call'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
    /Users/mayesa/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0/gems/graphql-1.9.1/lib/graphql/schema/middleware_chain.rb:51:in `block in invoke_core
```

**Comment by mayesa** [comment]
thx @rmosolgo
