### ISSUE TITLE
1.9.3 Tracers are broken when using node/nodes

### ISSUE THREAD

**Issue by askn** [rmosolgo/graphql-ruby#2153]
Hello, we use graphql 1.9.3 with new interpreter and tracers are broken.

It responds with error below:
```
NoMethodError:
       undefined method `graphql_name' for nil:NilClass
     # /Users/askingedik/.rvm/gems/ruby-2.6.0/gems/graphql-1.9.3/lib/graphql/tracing/data_dog_tracing.rb:48:in `platform_field_key'
     # /Users/askingedik/.rvm/gems/ruby-2.6.0/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:36:in `trace'
     # /Users/askingedik/.rvm/gems/ruby-2.6.0/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
```
Field is here:
``` ruby
#<GraphQL::Schema::Field:0x00007f8abc45b638
 @complexity=1,
 @connection=false,
 @deprecation_reason=nil,
 @description="Fetches an object given its ID.",
 @extensions=[],
 @extras=[],
 @field=nil,
 @function=nil,
 @graphql_definition=
  #<GraphQL::Field:0x00007f8abcabab50
   @arguments=
    {"id"=>
      #<GraphQL::Argument:0x00007f8abcaba920
       @as=nil,
       @clean_type=nil,
       @description="ID of the object.",
       @dirty_type=
        #<Proc:0x00007f8abcaba830@/Users/askingedik/.rvm/gems/ruby-2.6.0/gems/graphql-1.9.3/lib/graphql/schema/argument.rb:88 (lambda)>,
       @metadata=
        {:type_class=>
          #<GraphQL::Schema::Argument:0x00007f8abc45ac10
           @as=nil,
           @default_value=:__no_default__,
           @description="ID of the object.",
           @keyword=:id,
           @name="id",
           @null=false,
           @owner=#<GraphQL::Schema::Field:0x00007f8abc45b638 ...>,
           @prepare=nil,
           @type=#<GraphQL::Schema::NonNull @of_type=GraphQL::Types::ID>,
           @type_expr="ID!">},
       @name="id",
       @prepare_proc=GraphQL::Argument::DefaultPrepare>},
   @clean_type=nil,
   @complexity=1,
   @connection=false,
   @connection_max_page_size=nil,
   @description="Fetches an object given its ID.",
   @dirty_type=
    #<Proc:0x00007f8abcaba9c0@/Users/askingedik/.rvm/gems/ruby-2.6.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:337 (lambda)>,
   @edge_class=nil,
   @introspection=false,
   @lazy_resolve_proc=GraphQL::Field::DefaultLazyResolve,
   @metadata={:type_class=>#<GraphQL::Schema::Field:0x00007f8abc45b638 ...>},
   @name="node",
   @relay_node_field=true,
   @resolve_proc=
    #<Method: #<GraphQL::Schema::Field:0x00007f8abc45b638 ...>.resolve_field>,
   @subscription_scope=nil,
   @trace=nil>,
 @introspection=false,
 @max_page_size=nil,
 @method_str="node",
 @method_sym=:node,
 @name="node",
 @original_name="node",
 @own_arguments=
  {"id"=>
    #<GraphQL::Schema::Argument:0x00007f8abc45ac10
     @as=nil,
     @default_value=:__no_default__,
     @description="ID of the object.",
     @keyword=:id,
     @name="id",
     @null=false,
     @owner=#<GraphQL::Schema::Field:0x00007f8abc45b638 ...>,
     @prepare=nil,
     @type=#<GraphQL::Schema::NonNull @of_type=GraphQL::Types::ID>,
     @type_expr="ID!">},
 @owner=nil,
 @relay_node_field=true,
 @relay_nodes_field=false,
 @resolve=nil,
 @resolve_proc=nil,
 @resolver_class=nil,
 @resolver_method="node",
 @return_type_expr=GraphQL::Types::Relay::Node,
 @return_type_null=true,
 @scope=nil,
 @subscription_scope=nil,
 @trace=nil,
 @type=GraphQL::Types::Relay::Node,
 @underscored_name="node">
```
Thanks.

**Comment by rmosolgo** [comment]
🤦‍♂️ Thanks, seems like we need to set the `@owner` during `add_field`.
