### ISSUE TITLE
Subscriptions and subscribe method

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#2208]
I got subscriptions to work for quite a while now and I realised the other day we have now 2 callbacks `subscribe` and `update`

Somehow, I can't get the `subscribe` payload send to cable.

Here is my cable log:

<img width="809" alt="Screenshot 2019-03-29 at 2 51 40 PM" src="https://user-images.githubusercontent.com/38907720/55233783-41f61700-5232-11e9-9d5f-2e566d3b774c.png">

Here is my code:

```ruby
# app/graphql/types/subscription_type.rb

module Types
  class SubscriptionType < BaseObject
    field :node_changed, subscription: Subscriptions::NodeChanged
  end
end
```

```ruby
# app/graphql/subscriptions/node_changed.rb

module Subscriptions
  class NodeChanged < BaseSubscription
    description 'Changes to an object.'

    field :test,
          String,
          null: true,
          description: 'Debug value'

    argument :id,
             ID,
             required: true,
             description: 'The node ID'

    def subscribe(id:)
      pp '-' * 100
      pp "subscribe(id: #{id})"
      pp '-' * 100
      {
        test: "subscribe #{id}"
      }
    end
  end
end
```

``` ruby
# app/channels/graphql_channel.rb

class GraphqlChannel < ApplicationCable::Channel
  def subscribed
    @subscription_ids = []
  end

  def execute(data)
      pp "* GOT REQUEST ---"

    variables = SayduckSchema.ensure_hash(data['variables'])

    result = SayduckSchema.execute(query: data['query'],
                                   operation_name: data['operationName'],
                                   variables: variables,
                                   context: context)

    if result.context[:subscription_id]
      @subscription_ids << result.context[:subscription_id]
    end

    data = {
      result: result.subscription? ? { data: nil } : result.to_h,
      more: result.subscription?
    }

      pp "* TRANSMIT ---"

    transmit(data)
  end

  def unsubscribed
    @subscription_ids.each do |sid|
      SayduckSchema.subscriptions.delete_subscription(sid)
    end
  end

  private

  def context
    {
      channel: self
    }
  end
end
```

That's what I see on my console:

```bash
GraphqlChannel#execute({"query"=>"subscription MaterialChanged($id: ID!) {\n  nodeChanged(id: $id) {\n    node {\n      ... on Material {\n        ...MaterialFields\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n\nfragment MaterialFields on Material {\n  albedoColour\n  albedoTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  hasAlbedoTransparency\n  displayPosition\n  emissiveColour\n  emissiveTextureIntensity\n  emissiveTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  id\n  libraryOwner {\n    id\n    __typename\n  }\n  tiling\n  tilingOffset\n  tilingRotation\n  metalnessTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  metalness\n  name\n  normalTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  normalTextureIntensity\n  occlusionTextureIntensity\n  occlusionTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  ormTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  tiledAlbedoTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  tiledEmissiveTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  tiledNormalTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  tiledOrmTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  preview {\n    asset {\n      ...SharedAssetFields\n      __typename\n    }\n    __typename\n  }\n  roughness\n  roughnessTextureAsset {\n    ...SharedAssetFields\n    __typename\n  }\n  updatedAt\n  uuid\n  __typename\n}\n\nfragment SharedAssetFields on SharedAsset {\n  contentType\n  fileMeta\n  fingerprint\n  id\n  styles {\n    name\n    url\n    __typename\n  }\n  updatedAt\n  __typename\n}\n", "variables"=>{"id"=>"TWF0ZXJpYWwtYzQyZDI3MDAtMzQ0OS0wMTM3LTA4YWQtMGM4NTkwOWQ4YmYw"}, "operationName"=>"MaterialChanged"})
"* GOT REQUEST ---"
"----------------------------------------------------------------------------------------------------"
"subscribe(id: TWF0ZXJpYWwtYzQyZDI3MDAtMzQ0OS0wMTM3LTA4YWQtMGM4NTkwOWQ4YmYw)"
"----------------------------------------------------------------------------------------------------"
"* TRANSMIT ---"
GraphqlChannel transmitting {:result=>{:data=>nil}, :more=>true}
GraphqlChannel is streaming from graphql-subscription:ffd35155-16e3-42c8-b5b6-f522af1277d9
GraphqlChannel is streaming from graphql-event::nodeChanged:id:TWF0ZXJpYWwtYzQyZDI3MDAtMzQ0OS0wMTM3LTA4YWQtMGM4NTkwOWQ4YmYw
```

**Comment by sayduck-daniel** [comment]
Edit: removed all code not helping here.

I guess my problem here is how can I send the subscribe payload on the transmit? Shouldn't it be there already?

**Comment by rmosolgo** [comment]
Hi, are you using the new interpreter runtime? It's only supported on that runtime and also there's a module to extend in your subscription root (https://graphql-ruby.org/queries/interpreter.html#installation)

**Comment by sayduck-daniel** [comment]
Ok, got it now.

But it seems it is not working as expected for NodeField. I must be doing something wrong:



```ruby
module Types
  class QueryType < BaseObject
    add_field GraphQL::Types::Relay::NodeField
  end
end
```


``` ruby
class SayduckSchema < GraphQL::Schema
  max_depth 10
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Subscriptions::ActionCableSubscriptions
  use GraphQL::Tracing::ScoutTracing
  use GraphQL::Backtrace
  use BatchLoader::GraphQL

  query Types::QueryType
  # (...)
```

```graphql
query getStuff {
  node(id: "U291cmNlRmlsZS0wZTBlZTFjMC00YTBmLTAxMzYtYmMyMy0wYzg1OTA5ZDhiZjA=") {
    id
    __typename
  }
}
```

```bash
undefined method `graphql_name' for nil:NilClass
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/scout_tracing.rb:31:in `platform_field_key'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:36:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:197:in `block (2 levels) in evaluate_selections'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:337:in `block in resolve_with_directives'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:343:in `run_directive'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:337:in `resolve_with_directives'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:195:in `block in evaluate_selections'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:115:in `each'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:115:in `evaluate_selections'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:53:in `run_eager'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `block in trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/backtrace/tracer.rb:45:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/scout_tracing.rb:26:in `block in platform_trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/tracer.rb:34:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/tracer.rb:44:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/scout_tracing.rb:25:in `platform_trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter.rb:72:in `evaluate'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/interpreter.rb:45:in `begin_query'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:112:in `begin_query'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:83:in `map'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:182:in `block in instrument_and_analyze'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `block in trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/backtrace/tracer.rb:30:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/scout_tracing.rb:26:in `block in platform_trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/tracer.rb:34:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/tracer.rb:44:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/scout_tracing.rb:25:in `platform_trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `trace'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/schema.rb:376:in `block in multiplex'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/schema.rb:1205:in `with_definition_error_check'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/schema.rb:375:in `multiplex'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.3/lib/graphql/schema.rb:352:in `execute'
/Users/daniel/.rvm/rubies/ruby-2.6.1/lib/ruby/2.6.0/forwardable.rb:230:in `execute'
/Users/daniel/GitHub/sayduck-api-rails/app/graphql/sayduck_schema.rb:22:in `execute_from_hash'
/Users/daniel/GitHub/sayduck-api-rails/app/controllers/graphql_controller.rb:32:in `execute_query'
/Users/daniel/GitHub/sayduck-api-rails/app/controllers/graphql_controller.rb:10:in `execute'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:194:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/notifications.rb:168:in `instrument'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/railties/controller_runtime.rb:24:in `process_action'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/abstract_controller/base.rb:134:in `process'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionview-5.2.2/lib/action_view/rendering.rb:32:in `process'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal.rb:191:in `dispatch'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_controller/metal.rb:252:in `dispatch'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `each'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/journey/router.rb:35:in `serve'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/routing/route_set.rb:840:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/instant/middleware.rb:53:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/scout_apm-2.4.21/lib/scout_apm/middleware.rb:17:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:232:in `context'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/session/abstract/id.rb:226:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/cookies.rb:670:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-attack-5.4.2/lib/rack/attack.rb:182:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/etag.rb:25:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/conditional_get.rb:38:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/head.rb:12:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activerecord-5.2.2/lib/active_record/migration.rb:559:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/airbrake-8.1.4/lib/airbrake/rack/middleware.rb:67:in `call!'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/airbrake-8.1.4/lib/airbrake/rack/middleware.rb:55:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:38:in `call_app'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `block in call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2/lib/rails/rack/logger.rb:26:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/runtime.rb:22:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/activesupport-5.2.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/actionpack-5.2.2/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-2.0.6/lib/rack/sendfile.rb:111:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/rack-cors-1.0.2/lib/rack/cors.rb:97:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/railties-5.2.2/lib/rails/engine.rb:524:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/puma-3.12.0/lib/puma/configuration.rb:225:in `call'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/puma-3.12.0/lib/puma/server.rb:658:in `handle_request'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/puma-3.12.0/lib/puma/server.rb:472:in `process_client'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/puma-3.12.0/lib/puma/server.rb:332:in `block in run'
/Users/daniel/.rvm/gems/ruby-2.6.1/gems/puma-3.12.0/lib/puma/thread_pool.rb:133:in `block in spawn_thread'
Completed 500 Internal Server Error in 6ms (Views: 1.0ms | ActiveRecord: 0.0ms)
```

Is there something else missing here?

**Comment by rmosolgo** [comment]
Should be fixed in 1.9.4 by https://github.com/rmosolgo/graphql-ruby/pull/2156, could you try using `gem "graphql", github: "master"` and see if that fixes it?

**Comment by sayduck-daniel** [comment]
Did not test the `subscribe` yet but the Node field came back to normal

**Comment by sayduck-daniel** [comment]
`subscribe` works well :) thanks for the help

**Comment by sayduck-daniel** [comment]
@rmosolgo Do you have any idea when 1.9.4 is gonna be released?
