### ISSUE TITLE
New interpreter crashing on some connection types

### ISSUE THREAD

**Issue by kidcosmic** [rmosolgo/graphql-ruby#2211]
graphql-ruby 1.9.3

Crash:
```
undefined method `new' for nil:NilClass
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/types/relay/base_connection.rb:111:in `block (2 levels) in edges'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/types/relay/base_connection.rb:111:in `map'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/types/relay/base_connection.rb:111:in `block in edges'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema.rb:1132:in `after_lazy'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/types/relay/base_connection.rb:110:in `edges'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:497:in `public_send'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:497:in `block in resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:629:in `block in with_extensions'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:648:in `block (2 levels) in run_extensions_before_resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:651:in `run_extensions_before_resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:648:in `block in run_extensions_before_resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field_extension.rb:50:in `resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:646:in `run_extensions_before_resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:628:in `with_extensions'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/schema/field.rb:480:in `resolve'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:198:in `block (3 levels) in evaluate_selections'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `block in trace'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/tracing.rb:62:in `trace'
/Users/z/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/gems/graphql-1.9.3/lib/graphql/execution/interpreter/runtime.rb:197:in `block (2 levels) in evaluate_selections'
```

**Comment by rmosolgo** [comment]
Hi, sorry for the late response here! If you'd like to keep debugging this, could you please reopen it with a bit more information? 


- After updating to the latest graphql-ruby, could you share the new stack trace? 
- Could you share an example query string that demonstrates this issue? 
- Could you share the `field ...` definition which is used in the example query string? 

Sorry about the hangup here! Happy to dig in deeper if you don't mind sharing that stuff & reopening the issue.
