### ISSUE TITLE
Cursor generation broken in `GraphQL::Relay::AddRange` when context is passed

### ISSUE THREAD

**Issue by sumeetattree** [rmosolgo/graphql-ruby#2254]
`graphql v1.9.3`

I was trying to create a mutation and have it return relay cursor. Following along with the example given here: [GraphQL Ruby Api](https://graphql-ruby.org/api-doc/1.9.3/GraphQL/Relay/RangeAdd.html#edge-instance_method)

```rb
# From the api docs
post = Post.find(args[:postId])
comments = post.comments
new_comment = comments.build(body: args[:body])
new_comment.save!

range_add = GraphQL::Relay::RangeAdd.new(
  parent: post,
  collection: comments,
  item: new_comment,
  context: ctx,
)

response = {
  post: post,
  commentsConnection: range_add.connection,
  newCommentEdge: range_add.edge,
}
```

Here's the code sample I was trying to get working
```rb
# create_game.rb
def resolve(**attrs)
  game = Game.create(attrs);
  range_add = GraphQL::Relay::RangeAdd.new(
    collection: organization.games, # Game.all yields the same error
    item: game,
    context: context # removing context fixes the error
  )

  { game_edge: range_add.edge }
end
```

When context is passed to `GraphQL::Relay::RangeAdd.new()` cursor generation breaks with:
```rb
E GraphqlController -- Can't generate cursor, item not found in connection: #<Game:0x00007f7ff725c3e8>
E GraphqlController -- /Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/relay/relation_connection.rb:12:in `cursor_from_node'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/relay/edge.rb:15:in `cursor'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/schema/field.rb:536:in `public_send'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/schema/field.rb:536:in `resolve_field_method'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/schema/field.rb:500:in `block in resolve'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/schema/field.rb:621:in `with_extensions'
/Users/sumeet/.gem/ruby/2.4.4/gems/graphql-1.9.3/lib/graphql/schema/field.rb:480:in `resolve'
```

**Comment by rmosolgo** [comment]
Thanks for the detailed bug report! I'll try to take a look soon.

**Comment by rmosolgo** [comment]
Do you have a `max_page_size` set in your schema? If so, I bet it's coming from this:

https://github.com/rmosolgo/graphql-ruby/blob/7124873a489e21a5d81970cd0afc86e4e922578e/lib/graphql/relay/base_connection.rb#L64

The max_page_size is applied to the connection which trims the new node out of it. I think your work-around is sufficient for now (leaving out `context`), if I ever hear of this bug again I'll look for a better fix. 

Thanks again for the detailed report!

**Comment by miraymazlumoglu** [comment]
Hey @rmosolgo we have a similar problem in our codebase, I just wanted to let you know:

this is the original code which we call from our mutation:

```
      context[:response_builder]
        .add_errors_from_model(safe_tree)
        .add_return_field(:tree, safe_tree)
        .add_return_field_for_range_addition(
          :tree_edge,
          context.query.root_value.object,
          context.query.root_value.object.trees,
          safe_tree,
        )
        .add_return_field(:query, context.query.root_value.object)
```
which calls 

```
      def add_return_field_for_range_addition(key, parent, collection, new_item)
        range_add = GraphQL::Relay::RangeAdd.new(
          parent: parent,
          collection: collection,
          item: new_item,
          context: @ctx,
        )

        add_return_field(@range_add_definitions[key][:connection_key], collection)
        add_return_field(@range_add_definitions[key][:edge_key], range_add.edge)

        self
      end
```

and our max_page_size size is set to 100. this results in a similar issue reported above, we solved this problem by passing only the tree connection with safe_tree's id which you can see below:


```
      context[:response_builder]
        .add_errors_from_model(safe_tree)
        .add_return_field(:tree, safe_tree)
        .add_return_field_for_range_addition(
          :tree_edge,
          context.query.root_value.object,
          context.query.root_value.object.trees.where(id: safe_tree.id), // this is where we did the trick
          safe_tree,
        )
        .add_return_field(:query, context.query.root_value.object)
```
