### ISSUE TITLE
[pro] Operationstore sync endpoint is causing a Puma error

### ISSUE THREAD

**Issue by orionmcc** [rmosolgo/graphql-ruby#2265]
Hi. I'm attempting to implement the OperationStore in our code base (Kickstarter) and I'm getting the following error.

```
Puma caught this error: can't modify frozen String (FrozenError)
/Users/orionmcclelland/dev/kickstarter/app/middleware/request_id_middleware.rb:35:in `sub!'
/Users/orionmcclelland/dev/kickstarter/app/middleware/request_id_middleware.rb:35:in `block in call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `block in each'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `block in each'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/body_proxy.rb:36:in `each'
/Users/orionmcclelland/dev/kickstarter/app/middleware/request_id_middleware.rb:34:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/activesupport-5.1.6.2/lib/active_support/cache/strategy/local_cache_middleware.rb:27:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/executor.rb:12:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/actionpack-5.1.6.2/lib/action_dispatch/middleware/static.rb:125:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-utf8_sanitizer-1.3.2/lib/rack/utf8_sanitizer.rb:19:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/raindrops-0.19.0/lib/raindrops/middleware.rb:116:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/ksr-6.6.5/lib/ksr/middleware/authenticated_raindrops.rb:17:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/honeybadger-3.3.1/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/honeybadger-3.3.1/lib/honeybadger/agent.rb:337:in `with_rack_env'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/honeybadger-3.3.1/lib/honeybadger/rack/error_notifier.rb:30:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/honeybadger-3.3.1/lib/honeybadger/rack/user_feedback.rb:31:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/honeybadger-3.3.1/lib/honeybadger/rack/user_informer.rb:20:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/rack-canonical-host-0.2.3/lib/rack/canonical_host.rb:19:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.1.6.2/lib/rails/engine.rb:522:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `public_send'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/railties-5.1.6.2/lib/rails/railtie.rb:185:in `method_missing'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/orionmcclelland/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Any thoughts?

**Comment by rmosolgo** [comment]
Hey! It looks like some middleware in your app is _assuming_ some string will be mutable, but instead it's immutable. It might be due to the `# frozen_string_literal: true` magic comment which is in every Ruby file in graphql-ruby and graphql-pro. (It's recommended preparation for Ruby 3.) 

It's hard to tell what string is causing this error without seeing the relevant code, could you share the relevant bits of that middleware? 

In any case, there are a few possible fixes: 

- Fix the source code to _not_ return frozen strings 
- Change the middleware to handle frozen string with `str = str.dup if str.frozen?` or something similar 
- Change the middleware to use non-destructive modifications so that frozen or unfrozen strings are equally supported (ie, using `.sub` instead of `.sub!`)

I hope those basic pointers help, happy to investigate specific solutions if you don't mind sharing `app/middleware/request_id_middleware.rb`, at least the bit with the error!

**Comment by orionmcc** [comment]
Ok, that makes sense. I'll modify the middle ware to be more compliant. Thanks!
