### ISSUE TITLE
Subscription trigger crash with multiple resources

### ISSUE THREAD

**Issue by Loschcode** [rmosolgo/graphql-ruby#2282]
In a ` CreateTicket` mutation I decided to send a whole list of resources through websockets. I use ActiveRecord and it's already setup / working for other stuff.

```
{
  tickets_connection: current_identity.tickets
}.tap do |payload|
  MySchema.subscriptions.trigger('subscribeToTickets', {}, payload, scope: current_identity.id)
end
```

This is at the end of the mutation so it returns the `current_identity.tickets` which's a list of ` Type::Tickets`  through `TicketsConnection` but when it goes through  the  sockets it crashes like so

```
[ActionCable] Broadcasting to graphql-event:7ef5e61d-1085-4666-ac1e-1b4888a3aa2d:subscribeToTickets:: "{\"tickets_connection\":\"#<Ticket::ActiveRecord_Associations_CollectionProxy:0x00007fd1277bea80>\",\"__sym_keys__\":[\"tickets_connection\"]}"
There was an exception - RuntimeError(No connection implementation to wrap String (#<Ticket::ActiveRecord_Associations_CollectionProxy:0x00007fd1277bea80>))
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/relay/base_connection.rb:36:in `connection_for_nodes'
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/schema/field/connection_extension.rb:35:in `after_resolve'
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/schema/field.rb:636:in `block (2 levels) in with_extensions'
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/schema/field.rb:633:in `each'
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/schema/field.rb:633:in `each_with_index'
/Users/loschcode/.rvm/gems/ruby-2.5.1/gems/graphql-1.9.3/lib/graphql/schema/field.rb:633:in `block in with_extensions'
```

What am I doing wrong here? Is it normal behavior?

**Comment by nekogami** [comment]
I guess your subscription is suppose to return  [Type::Tickets] right ?
Then I guess the problem is that you are returning a Hash containing that array inside a key

```
  MySchema.subscriptions.trigger('subscribeToTickets', {}, current_identity.tickets, scope: current_identity.id)
```

I'd guess that this should work ?

**Comment by rmosolgo** [comment]
I have the same question as @nekogami, please share the definition of the `SubscribeToTickets` subscription and reopen if you'd like to debug further!
