### ISSUE TITLE
[Pro] Don't raise an exception when a policy cannot be found

### ISSUE THREAD

**Issue by tiffwu** [rmosolgo/graphql-ruby#2290]
### Issue

I'm looking to take advantage of the Pundit integration, but need a way to prevent the `PolicyNotFoundError` if there isn't a matching Pundit policy for a particular GraphQL object type. 

Our BaseObject:
```ruby
class Types::BaseObject < GraphQL::Schema::Object
  include GraphQL::Pro::PunditIntegration::ObjectIntegration

  # Require no permissions by default
  pundit_role nil
end
```

### Error
```
GraphQL::Pro::PunditIntegration::PolicyNotFoundError at /graphql
================================================================

> No policy found for:

- Type: StartupProductScreenshot
- Runtime value: `#<ActiveRecord::Associations::CollectionProxy [#<ProductScreenshot id: 1, startup_id: 6702, startup_type: "Startup", height: nil, width: nil, created_at: "2019-05-09 00:09:39", updated_at: "2019-05-09 00:09:39", image_file_name: "screenshot_1.jpg", image_content_type: "image/jpeg", image_file_size: 63551, image_updated_at: "2019-05-09 00:09:37">, #<ProductScreenshot id: 2, startup_id: 6702, startup_type: "Startup", height: nil, width: nil, created_at: "2019-05-09 00:09:40", updated_at: "2019-05-09 00:09:40", image_file_name: "screenshot_2.jpg", image_content_type: "image/jpeg", image_file_size: 54488, image_updated_at: "2019-05-09 00:09:39">]>`

app/controllers/graphql_controller.rb, line 27
----------------------------------------------
   22               except: admin_rules,
   23             }
   24           end
   25           GraphqlSchema.multiplex(queries)
   26         else
>  27           GraphqlSchema.execute(
   28             params[:query],
   29             operation_name: params[:operationName],
   30             variables: ensure_hash(params[:variables]),
   31             context: context,
   32             except: admin_rules,
```

### Backtrace 
```
Full backtrace
--------------

 - graphql-pro (1.10.5) lib/graphql/pro/pundit_integration.rb:144:in `rescue in scope_by_pundit_policy'
 - graphql-pro (1.10.5) lib/graphql/pro/pundit_integration.rb:127:in `scope_by_pundit_policy'
 - graphql-pro (1.10.5) lib/graphql/pro/pundit_integration.rb:116:in `scope_items'
 - graphql (1.9.4) lib/graphql/schema/field/scope_extension.rb:13:in `after_resolve'
 - graphql (1.9.4) lib/graphql/schema/field.rb:621:in `block (2 levels) in with_extensions'
 - graphql (1.9.4) lib/graphql/schema/field.rb:618:in `block in with_extensions'
 - graphql (1.9.4) lib/graphql/schema.rb:1132:in `after_lazy'
 - graphql (1.9.4) lib/graphql/schema/field.rb:617:in `with_extensions'
 - graphql (1.9.4) lib/graphql/schema/field.rb:581:in `public_send_field'
 - graphql (1.9.4) lib/graphql/schema/field.rb:441:in `block in resolve_field'
 - graphql (1.9.4) lib/graphql/schema.rb:1132:in `after_lazy'
 - graphql (1.9.4) lib/graphql/schema/field.rb:425:in `resolve_field'
 - graphql (1.9.4) lib/graphql/schema/member/instrumentation.rb:80:in `call'
 - graphql (1.9.4) lib/graphql/field.rb:248:in `resolve'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:318:in `call'
 - graphql (1.9.4) lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
 - graphql (1.9.4) lib/graphql/schema/middleware_chain.rb:38:in `invoke'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:129:in `block in resolve_field'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `block in trace'
 - graphql (1.9.4) lib/graphql/tracing.rb:76:in `call_tracers'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `trace'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:128:in `resolve_field'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:85:in `resolve_selection'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:281:in `resolve_value'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:210:in `continue_resolve_field'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:181:in `continue_or_wait'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:154:in `resolve_field'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:85:in `resolve_selection'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `block in trace'
 - graphql (1.9.4) lib/graphql/tracing.rb:76:in `call_tracers'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `trace'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
 - graphql (1.9.4) lib/graphql/execution/execute.rb:31:in `begin_query'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:112:in `begin_query'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:182:in `block in instrument_and_analyze'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
 - graphql (1.9.4) lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `block in trace'
 - graphql (1.9.4) lib/graphql/tracing.rb:76:in `call_tracers'
 - graphql (1.9.4) lib/graphql/tracing.rb:62:in `trace'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:59:in `run_queries'
 - graphql (1.9.4) lib/graphql/execution/multiplex.rb:49:in `run_all'
 - graphql (1.9.4) lib/graphql/schema.rb:376:in `block in multiplex'
 - graphql (1.9.4) lib/graphql/schema.rb:1205:in `with_definition_error_check'
 - graphql (1.9.4) lib/graphql/schema.rb:375:in `multiplex'
 - graphql (1.9.4) lib/graphql/schema.rb:352:in `execute'
 - app/controllers/graphql_controller.rb:27:in `execute'
```

### Versions

GraphQL-Ruby 1.9.4
GraphQL Pro 1.10.5

**Comment by rmosolgo** [comment]
Yes, it scopes by default. You can bypass it on a field-by-field basis: 

https://graphql-ruby.org/authorization/pundit_integration.html#bypassing-scopes

Or if you don't want scoping at all, you can override that default value in the base class like this: 

https://graphql-ruby.org/fields/introduction.html#field-parameter-default-values

Does that help?

**Comment by rmosolgo** [comment]
I hope that helps! I added this error so that it would be _hard_ to accidentally forget a policy. Let me know if those other options don't work well for you.
