### ISSUE TITLE
GraphQL::LoadApplicationObjectFailedError not being rescued by nested `loads:` in InputObject

### ISSUE THREAD

**Issue by celsworth** [rmosolgo/graphql-ruby#2355]
After https://github.com/rmosolgo/graphql-ruby/pull/2323, my `loads:` in nested InputObjects are working, which is great.

But I see odd behaviour when the object I'm attempting to load does not exist..

When the `loads:` is on an argument directly in a mutation, a top-level `errors` key is returned with sensible looking information (No object found). This is ok :)

But when it is in a nested InputObject, the resulting `GraphQL::LoadApplicationObjectFailedError` does not seem to be handled, and it bubbles up to my web layer, resulting in an error 500?

It seems I can't even catch this error myself in my resolver, which makes me think the loading behaviour is happening outside the scope of the query or something.

**Comment by rmosolgo** [comment]
Thanks for reporting this! I guess it needs to be fixed to handle that correctly. 

If you want to get started, you could add a failing test case alongside the one added previously: 

https://github.com/rmosolgo/graphql-ruby/blob/e9c6a480a135d5403b7b5b2b6e57eac3c3e338c7/spec/graphql/schema/input_object_spec.rb#L155-L168

Or, if you could share the full error message and backtrace that you get, that would help figure out where the `rescue` should go.

**Comment by celsworth** [comment]
Hi @rmosolgo, thanks for taking a look at this :)

Here's the backtrace;

```
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/member/has_arguments.rb:134:in `load_application_object_failed'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/member/has_arguments.rb:99:in `block in load_application_object'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema.rb:1146:in `after_lazy'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/member/has_arguments.rb:96:in `load_application_object'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/input_object.rb:31:in `block in initialize'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/input_object.rb:21:in `each'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema/input_object.rb:21:in `initialize'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:111:in `new'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:111:in `from_arguments'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:44:in `coerce'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:34:in `coerce'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:80:in `block in from_arguments'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:64:in `each'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:64:in `from_arguments'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:44:in `coerce'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:34:in `coerce'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:80:in `block in from_arguments'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:64:in `each'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/literal_input.rb:64:in `from_arguments'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query/arguments_cache.rb:14:in `block (2 levels) in build'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/query.rb:240:in `arguments_for'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:45:in `arguments_for'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/query_complexity.rb:80:in `get_complexity'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/query_complexity.rb:36:in `on_leave_field'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:240:in `public_send'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:240:in `block in call_analyzers'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:239:in `each'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:239:in `call_analyzers'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:117:in `on_field'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:101:in `each'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:168:in `on_abstract_node'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:70:in `on_operation_definition'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/language/visitor.rb:68:in `visit'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast/visitor.rb:37:in `visit'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:71:in `block in analyze_query'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `block in trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:58:in `analyze_query'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:34:in `block (2 levels) in analyze_multiplex'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:32:in `map'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:32:in `block in analyze_multiplex'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `block in trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/analysis/ast.rb:31:in `analyze_multiplex'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/multiplex.rb:185:in `block in instrument_and_analyze'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `block in trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/tracing.rb:62:in `trace'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema.rb:384:in `block in multiplex'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema.rb:1219:in `with_definition_error_check'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema.rb:383:in `multiplex'
/Users/chris/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.7/lib/graphql/schema.rb:360:in `execute'
```

**Comment by celsworth** [comment]
Hold tight, I think I'm barking up the wrong tree somewhat. Upon trying to put together a minimal reproduction test case, I've discovered that the problem goes away if I remove one of my query analysers. I'll post an update when I've narrowed this down :)

**Comment by celsworth** [comment]
Ok, here we go. Narrowed it down to the QueryComplexity analyser. With it in, an error is raised from this minimal case; comment it out and the correct result is returned with no error raised.

```ruby
require 'graphql'

class Types
  class TestType < GraphQL::Schema::Object
  end

  class TestIo < GraphQL::Schema::InputObject
    argument :test_id, ID, loads: Types::TestType, required: true
  end
end

class Query < GraphQL::Schema::Object
  field :test, String, null: false do
    argument :input, Types::TestIo, required: true
  end

  def test(input:)
  end
end

class Schema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  query Query

  # remove this and the problem goes away
  query_analyzer GraphQL::Analysis::AST::QueryComplexity

  def self.object_from_id(id, _query_ctx)
    nil # fake that no object can ever be looked up
  end
end

p Schema.execute(query: 'query { test(input: { testId: "1" }) }').to_h
```

**Comment by rmosolgo** [comment]
I replicated the error on 1.9.7

<details>
<summary>Backtrace</summary>

<p>

```


Error:
GraphQL::Schema::InputObject::prepare: / loads: / as:#test_0003_handles not-found with max complexity analyzer running:
GraphQL::LoadApplicationObjectFailedError: No object found for `instrumentId: "Instrument/Nonsense"`
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/member/has_arguments.rb:134:in `load_application_object_failed'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/member/has_arguments.rb:99:in `block in load_application_object'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema.rb:1146:in `after_lazy'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/member/has_arguments.rb:96:in `load_application_object'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/input_object.rb:31:in `block in initialize'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/input_object.rb:21:in `each'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/input_object.rb:21:in `initialize'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:111:in `new'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:111:in `from_arguments'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:44:in `coerce'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:34:in `coerce'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:80:in `block in from_arguments'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:64:in `each'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/literal_input.rb:64:in `from_arguments'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/arguments_cache.rb:14:in `block (2 levels) in build'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/query.rb:240:in `arguments_for'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:45:in `arguments_for'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/query_complexity.rb:80:in `get_complexity'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/query_complexity.rb:36:in `on_leave_field'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:240:in `public_send'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:240:in `block in call_analyzers'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:239:in `each'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:239:in `call_analyzers'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:117:in `on_field'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:79:in `public_send'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:79:in `visit_node'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:101:in `each'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:168:in `on_abstract_node'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:70:in `on_operation_definition'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:79:in `public_send'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:79:in `visit_node'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/language/visitor.rb:68:in `visit'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast/visitor.rb:37:in `visit'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:71:in `block in analyze_query'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:58:in `analyze_query'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:34:in `block (2 levels) in analyze_multiplex'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:32:in `map'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:32:in `block in analyze_multiplex'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/analysis/ast.rb:31:in `analyze_multiplex'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/multiplex.rb:185:in `block in instrument_and_analyze'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `block in trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:76:in `call_tracers'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/tracing.rb:62:in `trace'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/multiplex.rb:59:in `run_queries'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/multiplex.rb:49:in `run_all'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema.rb:384:in `block in multiplex'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema.rb:1219:in `with_definition_error_check'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema.rb:383:in `multiplex'
    /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema.rb:360:in `execute'
    /Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `execute'
    /Users/rmosolgo/code/graphql-ruby/spec/graphql/schema/input_object_spec.rb:164:in `block (3 levels) in <top (required)>'
```

</p>
</details>

But on master, the new test passed OK. 

Also, I reran your replication script (thank you!) and it works now:

```
$ ruby test.rb
{"data"=>nil, "errors"=>[{"message"=>"No object found for `testId: \"1\"`", "locations"=>[{"line"=>1, "column"=>9}], "path"=>["test"]}]}
```

So, somewhere along the line, this was fixed 🍻 ! Please open another issue if you run into a similar problem after upgrading.
