### ISSUE TITLE
can't modify frozen GraphQL::Language::Nodes::Document

### ISSUE THREAD

**Issue by chmorik** [rmosolgo/graphql-ruby#2411]
I get
can't modify frozen GraphQL::Language::Nodes::Document
when I execute
client.schema.dump!
Back trace is
[0] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/graphql-1.9.9/lib/graphql/language/nodes.rb:77:in `to_query_string'"
[1] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/graphlient-0.3.2/lib/graphlient/adapters/http/faraday_adapter.rb:12:in `block in execute'"
[2] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/connection.rb:384:in `block in run_request'"
[3] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/connection.rb:398:in `block in build_request'"
[4] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/request.rb:26:in `block in create'"
[5] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/request.rb:25:in `tap'"
[6] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/request.rb:25:in `create'"
[7] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/connection.rb:394:in `build_request'"
[8] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/connection.rb:379:in `run_request'"
[9] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/faraday-0.15.4/lib/faraday/connection.rb:175:in `post'"
[10] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/graphlient-0.3.2/lib/graphlient/adapters/http/faraday_adapter.rb:9:in `execute'"
[11] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/graphql-client-0.14.0/lib/graphql/client.rb:77:in `dump_schema'"
[12] = "/home/shachar/.rvm/gems/ruby-2.6.3/gems/graphlient-0.3.2/lib/graphlient/schema.rb:23:in `dump!'"

Currently roll backing to graphql 1.9.8 solve the issue but is there a way to fix at next version?
10x

**Comment by rmosolgo** [comment]
I think the newly-released GraphQL-Client 0.15.0 should fix this. Please try the new version of `graphql-client` and let me know if you still have trouble! See https://github.com/github/graphql-client/pull/218
