### ISSUE TITLE
[Resolvers] When forgetting type: `ArgumentError: Failed to build return type for Query.communities from nil`

### ISSUE THREAD

**Issue by vfonic** [rmosolgo/graphql-ruby#2424]
I forgot to add `type [Types::CommunityType], null: false` on top of my (community) resolver class and it took me a while to figure out what the issue was, because the error message didn't mention anything about missing `type`:

> ArgumentError: Failed to build return type for Query.communities from nil: Unexpected type input:  (NilClass)
from /Users/viktor/.rvm/gems/ruby-2.6.3/gems/graphql-1.9.9/lib/graphql/schema/member/build_type.rb:80:in `parse_type'
Caused by RuntimeError: Unexpected type input:  (NilClass)
from /Users/viktor/.rvm/gems/ruby-2.6.3/gems/graphql-1.9.9/lib/graphql/schema/member/build_type.rb:80:in `parse_type'

I also tried with the latest `master` ([982a75] as of this writing).

It would be great if the error message would be more meaningful.
I tried to figure out myself what needs to be changed to have this error message in the right place, but couldn't figure it out.

**Comment by rmosolgo** [comment]
Thanks for reporting this! I agree that the error message could be better.
