### ISSUE TITLE
NewRelicTracing incompatible with new interpreter

### ISSUE THREAD

**Issue by markiz** [rmosolgo/graphql-ruby#2434]
Getting an exception like this when both NewRelicTracing and GraphQL::Execution::Interpreter are enabled:

```
undefined method `graphql_name' for #<GraphQL::Schema::NonNull:0x00007fbb6aecdd30>
Did you mean?  graphql_definition
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/new_relic_tracing.rb:51:in `platform_field_key'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/platform_tracing.rb:37:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:62:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter/runtime.rb:401:in `block in after_lazy'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/lazy.rb:41:in `value'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter/resolve.rb:37:in `resolve'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter/resolve.rb:11:in `resolve_all'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter.rb:94:in `block in sync_lazies'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:62:in `block in trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:62:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/interpreter.rb:51:in `finish_multiplex'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:88:in `run_as_multiplex'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:186:in `block in instrument_and_analyze'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:62:in `block in trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:76:in `call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `block in call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:78:in `call_tracers'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/tracing.rb:62:in `trace'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/schema.rb:389:in `block in multiplex'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/schema.rb:1276:in `with_definition_error_check'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/schema.rb:388:in `multiplex'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.9.8/lib/graphql/schema.rb:365:in `execute'
/Users/mark/.rvm/rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `execute'
/Users/mark/code/sg/sg-graph-server/app/controllers/graphql_controller.rb:13:in `block in execute'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/newrelic_rpm-6.5.0.357/lib/new_relic/agent/datastores.rb:122:in `wrap'
/Users/mark/code/sg/sg-graph-server/app/controllers/graphql_controller.rb:11:in `execute'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rollbar-2.21.0/lib/rollbar/middleware/rails/rollbar.rb:25:in `block in call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rollbar-2.21.0/lib/rollbar.rb:145:in `scoped'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rollbar-2.21.0/lib/rollbar/middleware/rails/rollbar.rb:22:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rollbar-2.21.0/lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/rack-cors-1.0.3/lib/rack/cors.rb:95:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/puma-3.12.1/lib/puma/server.rb:659:in `handle_request'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/puma-3.12.1/lib/puma/server.rb:473:in `process_client'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'
/Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
```

Corresponding `type` for the call (that's missing the `graphql_name`) looks like this: `#<GraphQL::Schema::NonNull @of_type=Types::ConfigurableProductType>`

**Comment by rmosolgo** [comment]
Thanks for sharing this! I thought I understood the problem so I tried to replicate it in 8da577346. But, I wasn't successful - my test passed. So, I'm not sure _quite_ what's going wrong. 

Could you share your `field ...` configuration for the field that returns that type? If you don't mind, sharing the resolver for that field would be helpful too, at least whatever part of the resolver uses GraphQL-Batch (if you use that, or another batch loader).

**Comment by markiz** [comment]
I'll try my best to isolate, there's quite a bit going on in the actual code :)

**Comment by markiz** [comment]
@rmosolgo 
Sorry for the large example, but it's the smallest I could do :)
https://gist.github.com/markiz/315051ed474706506ef4e1df800797e8

The issue might have been with our connection implementation, which is pretty similar to standard connection impl, but adds stronger constraint for non-null entries (I couldn't reproduce with the default connection impl).

However, without new interpreter it works fine and without newrelic tracing it works fine, which makes me think there is an issue somewhere.

**Comment by markiz** [comment]
After updating graphql dep to 1.9.9... it seems to work? 😃 
I could pinpoint the fix to https://github.com/rmosolgo/graphql-ruby/commit/801abaa1974a49e951465171cc9c7a7a4f9aef33 (prev commit, 130df7f30ce79e0e5b73a30ce147fc288f6e0b59 is still broken), but I don't understand how exactly that helped.
