### ISSUE TITLE
Uninitialized constant Types::QuotationReturnType

### ISSUE THREAD

**Issue by SrbModi** [rmosolgo/graphql-ruby#2436]
I am trying to create a query to return a filtered list of quotations from a "quotations" table. 

The code is inside an engine name "cpq" (hence the namespacing, ignore it :P)

types/quotation_type.rb
```
module Cpq

  module Types

    class QuotationType < ::Cpq::Types::BaseObject
      field :id,              ID,                             null: false
      field :inc_id,          Integer,                        null: false
      field :name,            String,                         null: false
      field :description,     String,                         null: true
      field :buyer_id,        ID,                             null: true
      field :seller_address,  String,                         null: true
      field :buyer_address,   String,                         null: true
      field :quotation_no,    String,                         null: false
      field :updated_at,      ::Types::DateTimeType,          null: false
    end

    class QuotationReturnType < ::Cpq::Types::BaseObject
      field :success,         Boolean,                        null: false
      field :quotation_data,  [::Cpq::Types::QuotationType],  null: true
      field :page,            Integer,                        null: true
      field :total,           Integer,                        null: true
      field :total_count,     Integer,                        null: true
    end

  end
end
```

types/query_type.rb

```
Cpq::Types::QueryType = GraphQL::ObjectType.define do
  
name "Query"

  field :quotations do
    type ::Cpq::Types::QuotationReturnType
     
    argument :id, types.ID
    argument :name, types.String
    argument :buyer_ids, types[types.ID]
    argument :statuses, types[types.String]
    argument :page, types.String
    argument :page_limit, types.String
    argument :sort_by, types.String
    ...
    ...
   resolve -> (obj, args, ctx) {
      quotation_ids = []
      quotation_ids << args[:id] if args[:id].present?
      name = args[:name]
      ...
      ...
    return {
          success: true,
          page: page,
          total: total,
          total_count: total_count,
          data: quotation.as_json(::Cpq::Quotation.as_json_query)
      }
    }

    end
end
```

However, on hitting the query "quotations", i get an error 
```
Traceback (most recent call last):
       10: from -e:1:in `<main>'
        9: from /Users/sourabhmodi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        8: from /Users/sourabhmodi/.rvm/rubies/ruby-2.5.0/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        7: from /Users/sourabhmodi/Documents/workspace/rails/Cogoport-api/bin/rails:9:in `<top (required)>'
        6: from /Users/sourabhmodi/.rvm/gems/ruby-2.5.0/gems/railties-5.0.7/lib/rails/commands.rb:18:in `<top (required)>'
        5: from /Users/sourabhmodi/.rvm/gems/ruby-2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
        4: from /Users/sourabhmodi/.rvm/gems/ruby-2.5.0/gems/railties-5.0.7/lib/rails/commands/commands_tasks.rb:78:in `console'
        3: from /Users/sourabhmodi/.rvm/gems/ruby-2.5.0/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
        2: from /Users/sourabhmodi/.rvm/gems/ruby-2.5.0/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
        1: from (irb):14
NameError (uninitialized constant Cpq::Types::QuotationReturnType)
```

When I try it on console, I realised that once I access the type Cpq::Types::QuotationType before, then it is able to access the class QuotationReturnType. But its gives me an error if I simply try accessing Cpq::Types::QuotationReturnType. Probably unable to load it or something.
Confused. Please help.

P.S. I am new to graphql, so please ignore any naive/redundant code, if mentioned.

**Comment by SrbModi** [comment]
Resolved! Had to do with rails name spacing. Not an issue of graphql.

**Comment by thibaultadet** [comment]
@SrbModi I know it's been almost 2 years but I have a similar issue, could you point me towards a solution ? Thanks !
