### ISSUE TITLE
Subscriptions incompatible with multiple Postgres schemas? 

### ISSUE THREAD

**Issue by gopeter** [rmosolgo/graphql-ruby#2444]
I'm building a multi-tenant Rails app with [`apartment`](https://github.com/influitive/apartment) and I'm using the one-schema-per-tenant-solution.

Everything works really great except subscriptions. While Actioncable work's with this approach (which I got from [here](https://github.com/influitive/apartment/issues/391)) ...

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user, :tenant

    def connect
      self.tenant = request.subdomain
      Apartment::Tenant.switch(tenant)!
      self.current_user = find_verified_user
    end

    private

    def find_verified_user
      env['warden'].session_serializer.fetch('user') ||
        reject_unauthorized_connection
    end
  end
end
```

... this one doesn't: `MyApp.subscriptions.trigger('somethingChanged', {}, self)` (I'm running this in an `after_commit` hook), because this function queries the record in the public schema. 

`self`, which is a model that is actually created, exists in my tenant database, but not in the public schema ... and that's why my hook always ends up in a `Record not found` error.

Is there any way to tell `graphql-ruby` about the right schema? 

Thanks in advance! :-)

**Comment by gopeter** [comment]
Oh, and I'm using `'graphql 1.9.4'` and `graphql-pro`, but did not migrated to the class-based syntax yet.

**Comment by gopeter** [comment]
Thanks you very much, I'll give it a try! I just wondered about that since the entire app is on the right schema, just the subscription trigger isn't. 

Maybe there is some middleware on the `graphql-ruby` side that runs before my custom one?

```
module MyAppApi
  class Application < Rails::Application
    config.middleware.use Apartment::Elevators::Generic, GetTenant
  end
end
```

I'll let you know once I tried it. Thanks again! 😄

**Comment by gopeter** [comment]
Thanks again for your help! 

I tried your first approach, but unfortunately the `trigger` method is already aware of the right tenant. This one ... 

```ruby
class MultiTenantActionCableSubscriptions < GraphQL::Subscriptions::ActionCableSubscriptions
  def trigger(name, args, obj)
    Rails.logger.info Apartment::Tenant.current
    super 
  end 
end 
```

... returns the right tenant/schema. So I tried you second approach, but I'm not really sure where to override the `execute` method. I thought I can override it in my `MultiTenantActionCableSubscriptions` also , but the code doesn't get executed at all:

```ruby
class MultiTenantActionCableSubscriptions < GraphQL::Subscriptions::ActionCableSubscriptions
  def execute_all(subscription_id, event, object)
    Rails.logger.info Apartment::Tenant.current # no output/`There was an exception - ActiveRecord::RecordNotFound ...` fires first?
    Apartment::Tenant.switch!('debd')
    super
  end
end
```

I also tried `execute_all`, but this also return the right tenant 🤔

**Comment by gopeter** [comment]
Oh sorry, actually I tried `execute`, just copied the wrong snippet. That's what I meant with "...the code doesn't get executed at all", since I don't get any logger info in the console, just this:

```
  IssueComment Load (0.7ms)  SELECT "issue_comments".* FROM "issue_comments" WHERE "issue_comments"."id" = $1 LIMIT $2  [["id", 19], ["LIMIT", 1]]
There was an exception - ActiveRecord::RecordNotFound(Couldn't find IssueComment with 'id'=19)
```

But the database record is persisted. I thought that this could be a race condition maybe, but the `COMMIT` log runs before the broadcast everytime, so this shouldn't be the case 😞🤔

**Comment by gopeter** [comment]
Now it gets even crazier: I've restarted the Rails server and added a new comment on the frontend (which creates a new database record and calls the `subscription.trigger` in an `after_commit` hook) – and everything went well! But adding a second one throws the error again. 

But it's not reproducible. Sometimes the first hit works, sometimes I get `ActiveRecord::RecordNotFound` immediately. So maybe it's related to some kind of concurrency issue? 

That's my "debug" code:

```ruby
class MultiTenantActionCableSubscriptions < GraphQL::Subscriptions::ActionCableSubscriptions
  def write_subscription(query, events)
    Rails.logger.info '######################## write_subscription'
    Rails.logger.info Apartment::Tenant.current
    Rails.logger.info '######################## write_subscription'
    super
  end

  def execute_all(event, object)
    Rails.logger.info '######################## execute_all'
    Rails.logger.info Apartment::Tenant.current
    Rails.logger.info '######################## execute_all'
    super
  end

  def execute(subscription_id, event, object)
    Rails.logger.info '######################## execute'
    Rails.logger.info Apartment::Tenant.current
    Rails.logger.info '######################## execute'
    super
  end
end
```

Here's a (slightly shortened) log of the actions that happened.

```
Started GET "/cable?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY2OTAyODc0fQ.m9I8FdfzVgfcEbWU3oakgHo4fSsqNH-zdzaWSl-b5Fk" for ::1 at 2019-08-27 10:45:34 +0200
Started GET "/cable/?token=eyJhbGciOiJIUzI1NiJ9.eyJpZCI6MSwiZXhwIjoxNTY2OTAyODc0fQ.m9I8FdfzVgfcEbWU3oakgHo4fSsqNH-zdzaWSl-b5Fk" [WebSocket] for ::1 at 2019-08-27 10:45:34 +0200
Successfully upgraded to WebSocket (REQUEST_METHOD: GET, HTTP_CONNECTION: Upgrade, HTTP_UPGRADE: websocket)
Started POST "/graphql" for 127.0.0.1 at 2019-08-27 10:45:34 +0200
  User Load (1.1ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
Registered connection (Z2lkOi8vZG9ja2V0LWFwaS9Vc2VyLzE)
Processing by V1::GraphqlController#execute as */*
  Parameters: {"_json"=>[{"operationName"=>"GetIssueComments", "variables"=>{"id"=>"1758"}, "query"=>"query GetIssueComments($id: ID!) {\n  issue(id: $id) {\n    id\n    comments {\n      totalCount\n      edges {\n        node {\n          id\n          description\n          user {\n            id\n            firstname\n            lastname\n            email\n            __typename\n          }\n          created_at\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}], "graphql"=>{"_json"=>[{"operationName"=>"GetIssueComments", "variables"=>{"id"=>"1758"}, "query"=>"query GetIssueComments($id: ID!) {\n  issue(id: $id) {\n    id\n    comments {\n      totalCount\n      edges {\n        node {\n          id\n          description\n          user {\n            id\n            firstname\n            lastname\n            email\n            __typename\n          }\n          created_at\n          __typename\n        }\n        __typename\n      }\n      __typename\n    }\n    __typename\n  }\n}\n"}]}}
GraphqlChannel is transmitting the subscription confirmation
  User Load (1.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Issue Load (0.8ms)  SELECT "issues".* FROM "issues" WHERE (id = '1758') ORDER BY "issues"."id" ASC LIMIT $1  [["LIMIT", 1]]
  IssueComment Load (0.5ms)  SELECT "issue_comments".* FROM "issue_comments" WHERE "issue_comments"."issue_id" = $1  [["issue_id", 1758]]
   (1.4ms)  SELECT COUNT(*) FROM (SELECT 1 AS one FROM "issue_comments" WHERE "issue_comments"."issue_id" = $1 ORDER BY issue_comments.id asc LIMIT $2 OFFSET $3) subquery_for_count  [["issue_id", 1758], ["LIMIT", 999999], ["OFFSET", 0]]
  IssueComment Load (0.7ms)  SELECT issue_comments.*, issue_comments.id AS cursor_0 FROM "issue_comments" WHERE "issue_comments"."issue_id" = $1 ORDER BY issue_comments.id asc  [["issue_id", 1758]]
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 1]]
Completed 200 OK in 25ms (Views: 0.6ms | ActiveRecord: 5.2ms | Allocations: 6693)

GraphqlChannel#execute({"query"=>"subscription SubscribeIssueComments($issueId: ID!) {\n  issueCommentChanged: issueCommentChanged(issueId: $issueId) {\n    id\n    description\n    user {\n      id\n      firstname\n      lastname\n      email\n      __typename\n    }\n    created_at\n    __typename\n  }\n}\n", "variables"=>{"issueId"=>"1758"}, "operationName"=>"SubscribeIssueComments"})
######################## write_subscription
debd
######################## write_subscription
GraphqlChannel transmitting {:result=>{:data=>nil}, :more=>true}
GraphqlChannel is streaming from graphql-subscription:b2f68b89-42bc-4949-92fe-939223ca4137
GraphqlChannel is streaming from graphql-event::issueCommentChanged:issueId:1758
Started POST "/graphql" for 127.0.0.1 at 2019-08-27 10:45:37 +0200
Processing by V1::GraphqlController#execute as */*
  Parameters: {"_json"=>[{"operationName"=>"CreateIssueComment", "variables"=>{"issueComment"=>{"description"=>"<div>asdf</div>", "user_id"=>"1", "issue_id"=>"1758"}}, "query"=>"mutation CreateIssueComment($issueComment: IssueCommentInput!) {\n  createIssueComment(issueComment: $issueComment) {\n    id\n    __typename\n  }\n}\n"}], "graphql"=>{"_json"=>[{"operationName"=>"CreateIssueComment", "variables"=>{"issueComment"=>{"description"=>"<div>asdf</div>", "user_id"=>"1", "issue_id"=>"1758"}}, "query"=>"mutation CreateIssueComment($issueComment: IssueCommentInput!) {\n  createIssueComment(issueComment: $issueComment) {\n    id\n    __typename\n  }\n}\n"}]}}
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.3ms)  BEGIN
  Issue Load (0.4ms)  SELECT "issues".* FROM "issues" WHERE "issues"."id" = $1 LIMIT $2  [["id", 1758], ["LIMIT", 1]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  IssueComment Create (3.7ms)  INSERT INTO "issue_comments" ("description", "issue_id", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["description", "<div>asdf</div>"], ["issue_id", 1758], ["user_id", 1], ["created_at", "2019-08-27 08:45:37.685110"], ["updated_at", "2019-08-27 08:45:37.685110"]]
   (1.0ms)  COMMIT
  Project Load (0.4ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2  [["id", 176], ["LIMIT", 1]]
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  Rendering issue_comment_mailer/comment_added_mail.html.erb within layouts/mailer
  Rendered issue_comment_mailer/comment_added_mail.html.erb within layouts/mailer (Duration: 2.2ms | Allocations: 231)
  Rendering issue_comment_mailer/comment_added_mail.text.erb within layouts/mailer
  Rendered issue_comment_mailer/comment_added_mail.text.erb within layouts/mailer (Duration: 0.5ms | Allocations: 82)
IssueCommentMailer#comment_added_mail: processed outbound mail in 45.8ms
[ ... lots of email stuff ...]
<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1>New Issue comment was created</h1>
<p>
  &lt;div&gt;asdf&lt;/div&gt;
</p>
  </body>
</html>

----==_mimepart_5d64edb1c074e_8ab93fdaefb24288548a7--

######################## execute_all
debd
######################## execute_all
[ActionCable] Broadcasting to graphql-event::issueCommentChanged:issueId:1758: "{\"__gid__\":\"Z2lkOi8vZG9ja2V0LWFwaS9Jc3N1ZUNvbW1lbnQvMjU\"}"
Completed 200 OK in 805ms (Views: 0.2ms | ActiveRecord: 6.7ms | Allocations: 25446)


  IssueComment Load (0.7ms)  SELECT "issue_comments".* FROM "issue_comments" WHERE "issue_comments"."id" = $1 LIMIT $2  [["id", 25], ["LIMIT", 1]]
######################## execute
debd
######################## execute
  User Load (0.4ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1  [["id", 1]]
[ActionCable] Broadcasting to graphql-subscription:b2f68b89-42bc-4949-92fe-939223ca4137: {:result=>{"data"=>{"issueCommentChanged"=>{"id"=>"25", "description"=>"<div>asdf</div>", "user"=>{"id"=>"1", "firstname"=>"Peter", "lastname"=>"Oesteritz", "email"=>"peter.oesteritz@debd.com", "__typename"=>"User"}, "created_at"=>"2019-08-27 08:45:37 UTC", "__typename"=>"IssueComment"}}}, :more=>true}
GraphqlChannel transmitting {"result"=>{"data"=>{"issueCommentChanged"=>{"id"=>"25", "description"=>"<div>asdf</div>", "user"=>{"id"=>"1", "firstname"=>"Peter", "lastname"=>"Oesteritz", "email"=>"peter.oesteritz@debd.com", "__typename"=>"User"}, "created_at"=>"2019-08-27 08:45:37 UTC", "__typename"=>"IssueComment"}}}, "more... (via streamed from graphql-subscription:b2f68b89-42bc-4949-92fe-939223ca4137)
Started POST "/graphql" for 127.0.0.1 at 2019-08-27 10:45:49 +0200
Processing by V1::GraphqlController#execute as */*
  Parameters: {"_json"=>[{"operationName"=>"CreateIssueComment", "variables"=>{"issueComment"=>{"description"=>"<div>f3fwaef</div>", "user_id"=>"1", "issue_id"=>"1758"}}, "query"=>"mutation CreateIssueComment($issueComment: IssueCommentInput!) {\n  createIssueComment(issueComment: $issueComment) {\n    id\n    __typename\n  }\n}\n"}], "graphql"=>{"_json"=>[{"operationName"=>"CreateIssueComment", "variables"=>{"issueComment"=>{"description"=>"<div>f3fwaef</div>", "user_id"=>"1", "issue_id"=>"1758"}}, "query"=>"mutation CreateIssueComment($issueComment: IssueCommentInput!) {\n  createIssueComment(issueComment: $issueComment) {\n    id\n    __typename\n  }\n}\n"}]}}
  User Load (0.5ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
   (0.3ms)  BEGIN
  Issue Load (1.2ms)  SELECT "issues".* FROM "issues" WHERE "issues"."id" = $1 LIMIT $2  [["id", 1758], ["LIMIT", 1]]
  CACHE User Load (0.0ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 1], ["LIMIT", 1]]
  IssueComment Create (1.7ms)  INSERT INTO "issue_comments" ("description", "issue_id", "user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5) RETURNING "id"  [["description", "<div>f3fwaef</div>"], ["issue_id", 1758], ["user_id", 1], ["created_at", "2019-08-27 08:45:49.341157"], ["updated_at", "2019-08-27 08:45:49.341157"]]
   (2.3ms)  COMMIT
  Project Load (0.4ms)  SELECT "projects".* FROM "projects" WHERE "projects"."id" = $1 LIMIT $2  [["id", 176], ["LIMIT", 1]]
  User Load (0.3ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 LIMIT $2  [["id", 3], ["LIMIT", 1]]
  Rendering issue_comment_mailer/comment_added_mail.html.erb within layouts/mailer
  Rendered issue_comment_mailer/comment_added_mail.html.erb within layouts/mailer (Duration: 0.1ms | Allocations: 8)
  Rendering issue_comment_mailer/comment_added_mail.text.erb within layouts/mailer
  Rendered issue_comment_mailer/comment_added_mail.text.erb within layouts/mailer (Duration: 0.1ms | Allocations: 5)
IssueCommentMailer#comment_added_mail: processed outbound mail in 5.9ms

[ ... lots of email stuff ...]

<!DOCTYPE html>
<html>
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <style>
      /* Email styles need to be inline */
    </style>
  </head>

  <body>
    <h1>New Issue comment was created</h1>
<p>
  &lt;div&gt;f3fwaef&lt;/div&gt;
</p>
  </body>
</html>

----==_mimepart_5d64edbd55dce_8ab93fdaefb28a54550ea--

######################## execute_all
debd
######################## execute_all
[ActionCable] Broadcasting to graphql-event::issueCommentChanged:issueId:1758: "{\"__gid__\":\"Z2lkOi8vZG9ja2V0LWFwaS9Jc3N1ZUNvbW1lbnQvMjY\"}"
Completed 200 OK in 638ms (Views: 0.2ms | ActiveRecord: 6.8ms | Allocations: 10409)


  IssueComment Load (1.3ms)  SELECT "issue_comments".* FROM "issue_comments" WHERE "issue_comments"."id" = $1 LIMIT $2  [["id", 26], ["LIMIT", 1]]
There was an exception - ActiveRecord::RecordNotFound(Couldn't find IssueComment with 'id'=26)
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:339:in `raise_record_not_found_exception!'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:443:in `find_one'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:425:in `find_with_ids'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation/finder_methods.rb:69:in `find'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/querying.rb:21:in `find'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/core.rb:160:in `find'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:130:in `locate'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:155:in `block in locate'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:165:in `block in unscoped'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/scoping/default.rb:34:in `block in unscoped'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation.rb:398:in `block in scoping'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation.rb:772:in `_scoping'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/relation.rb:398:in `scoping'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activerecord-6.0.0/lib/active_record/scoping/default.rb:34:in `unscoped'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:165:in `unscoped'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:155:in `locate'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/globalid-0.4.2/lib/global_id/locator.rb:17:in `locate'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.10/lib/graphql/subscriptions/serialize.rb:59:in `load_value'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.10/lib/graphql/subscriptions/serialize.rb:19:in `load'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.10/lib/graphql/subscriptions/action_cable_subscriptions.rb:123:in `block (2 levels) in write_subscription'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/channel/streams.rb:157:in `block in stream_decoder'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:59:in `block in invoke'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:41:in `block in work'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:40:in `work'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:58:in `invoke'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:53:in `block in async_invoke'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

**Comment by gopeter** [comment]
OK, thanks! I'll have a look at this and update the issue once I found a solution, since this could be interesting for other users of `apartment` too :-)

**Comment by gopeter** [comment]
It's working now! But I really don't know why 😅 

```ruby
module MultiTenantSerializer
  def self.load(value)
    Apartment::Tenant.switch(Apartment::Tenant.current) { GraphQL::Subscriptions::Serialize.load(value) }
  end

  def self.dump(obj)
    GraphQL::Subscriptions::Serialize.dump(obj)
  end
end
```

I did my debugging inside `self.load` as usual (`Rails.logger.info Apartment::Tenant.current`) and got the right tenant. But since the `load` (or `load_value`) function isn't aware of the tenant, I just tried to execute it inside the `switch`-block of the `apartment` gem which works very well (for my surprise).

Nice that it's working now, but it would be good to know why :-) I'm calling `switch!` before (otherwise `Apartment::Tenant.current` wouldn't return the right one), and the `switch` method does basically the same (https://github.com/influitive/apartment/blob/development/lib/apartment/adapters/abstract_adapter.rb#L81).

Anyway, thank you very much for your time and your help, which I really appreciate.

**Comment by gopeter** [comment]
Hi @dittonjs. Hmmm, while thinking about this, setting the tenant by `Apartment::Tenant.current` isn't really logical – but it worked for me. I think it might be due to concurrency/multi-threading, which isn't reproducible (at least I'm not aware of any possibilities to do so). A better solution would be to call the method that originally returned the tenant. For me, it's a custom class that I'm using as an Apartment elevator:

`/app/lib/get_tenant.rb`:
```ruby 
class GetTenant
  def self.call(request)
    excluded_subdomains = %w[admin www]

    if Rails.env.production?
      url =
        if (request.referer && URI.parse(request.referer).host != 'localhost')
          URI.parse(request.referer).host
        else
          URI.parse(request.base_url).host
        end

      request_subdomain = url.split('.').first
      tenant = excluded_subdomains.include?(request_subdomain) ? nil : request_subdomain

      tenant.presence
    else
      # dev/test mode
      'debd'
    end
  end
end
```

`/config/application.rb`:
```ruby
# Load the right tenant for the current subdomain
config.middleware.use Apartment::Elevators::Generic, GetTenant
```

My `/app/channels/application_cable/connection.rb` looks like:
```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      Apartment::Tenant.switch!(find_tenant)
      self.current_user = find_verified_user
    end

    private

    def find_tenant
      GetTenant.call(request)
    end

    def find_verified_user
      token = JsonWebToken.decode(request.query_parameters['token'])
      User.find(token[:id])
    rescue StandardError
      reject_unauthorized_connection
    end
  end
end
```

I'm not sure how to get the `request` object inside my custom serializer, but if there is a way, I would use me `GetTenant` class there again. I'm also not sure about the performance impact.

**Comment by gopeter** [comment]
To all who may use my solution above: this also doesn't work in all cases, so I had to overwrite internal methods (as @rmosolgo already said here):

> Yeah, it certainly seems like it has to do with how action cable listeners are executed. You can in the backtrace that a thread is picked out of a thread pool. One interesting line from that backtrace is:
> 
> ```
> /Users/peter_goebel/.rvm/gems/ruby-2.6.1/gems/graphql-1.9.10/lib/graphql/subscriptions/serialize.rb:19:in `load'
> ```
> 
> This error isn't coming from query execution, it's coming from loading objects by ID, at `@serializer.load`:
> 
> https://github.com/rmosolgo/graphql-ruby/blob/96b253f91b310c52812e0a18517a757269f2ed5f/lib/graphql/subscriptions/action_cable_subscriptions.rb#L123
> 
> So, I think you'd have to make sure that it's on the right tenant _there_, which is actually _before_ the call to `#execute`! You could try customizing the serializer or customizing the subscriptions class, but I don't see a quick and easy way to insert code inside that block, besides overriding the whole method and reimplementing it with what you need.

To make tenants work, I had to do the following:

1. Create a new initializer (`config/initializers/graphql_monkey_patch.rb`) with the following content:

```ruby
GraphQL::Subscriptions::ActionCableSubscriptions.class_eval do
  SUBSCRIPTION_PREFIX = 'graphql-subscription:'
  EVENT_PREFIX = 'graphql-event:'

  def write_subscription(query, events)
    channel = query.context.fetch(:channel)
    subscription_id = query.context[:subscription_id] ||= build_id
    stream = query.context[:action_cable_stream] ||= SUBSCRIPTION_PREFIX + subscription_id
    channel.stream_from(stream)
    @subscriptions[subscription_id] = query
    events.each do |event|
      # the magic happens here at `@serializer.load` where we add `query.context` as a second argument
      channel
        .stream_from(EVENT_PREFIX + event.topic, coder: ActiveSupport::JSON) do |message|
        execute(subscription_id, event, @serializer.load(message, query.context))
        nil
      end
    end
  end
end
```

2. create a custom serializer which uses the new argument

```ruby
module MultiTenantSerializer
  def self.load(value, context)
    Apartment::Tenant.switch(context.fetch(:current_user)[:tenant]) { GraphQL::Subscriptions::Serialize.load(value) }
  end

  def self.dump(obj)
    GraphQL::Subscriptions::Serialize.dump(obj)
  end
end

use GraphQL::Subscriptions::ActionCableSubscriptions, serializer: MultiTenantSerializer
```

3. pass the tenant to the context (context now looks a little bit screwed up because of another nested `current_user` variable, but this is just to illustrate how it all work together):

```ruby
module ApplicationCable
  class Connection < ActionCable::Connection::Base
    identified_by :current_user

    def connect
      tenant = find_tenant
      Apartment::Tenant.switch!(tenant)
      self.current_user = { current_user: find_verified_user, tenant: tenant }
    end

    private

    def find_tenant
      GetTenant.call(request)
    end

    def find_verified_user
      token = JsonWebToken.decode(request.query_parameters['token'])
      User.find(token[:id])
    rescue StandardError
      reject_unauthorized_connection
    end
  end
end
```

Attention: the monkey patch has to be checked and reviewed for every future update!

**Comment by rmosolgo** [comment]
👋 I just opened a PR to improve support for this a bit (no more monkey patch required) and add a doc. If anyone has a minute to review it, I'd appreciate it! #3574

**Comment by jonian** [comment]
Adding another solution for tenant switching in subscriptions as I didn't like the official solution using TenantSelectionTracer described [here](https://graphql-ruby.org/subscriptions/multi_tenant.html#choosing-a-tenant-for-execution) because it switches tenant on queries and mutations and that is already handled by a rack middleware.

```ruby
module ApplicationCable
  class Connection < Evince::Cable::Connection::Base
    identified_by :current_user, :tenant

    def connect
      self.tenant = Tenant.identify request.params[:tenant]
      self.current_user = User.identify request.params[:ticket]
    end
   
    # Solution taken from https://anycable.io/blog/multi-tenancy-vs-cables
    # in rails 7.0 you can use the `around_command` callback
    def dispatch_websocket_message(*)
      Tenant.switch(tenant) do
        super
      end
    end
  end
end
```

```ruby
class MultiTenantActionCableSubscriptions < GraphQL::Subscriptions::ActionCableSubscriptions
  def execute_update(subscription_id, event, object)
    query_data = read_subscription(subscription_id)

    if query_data.nil?
      delete_subscription(subscription_id)
      return nil
    end

    tenant = query_data.dig(:context, :tenant)

    Tenant.switch(tenant) do
      super
    end
  end
end
```

```ruby
class MultiTenantSerializer
  class << self
    def dump(obj)
      GraphQL::Subscriptions::Serialize.dump(obj)
    end

    def load(string, context)
      Tenant.switch(context[:tenant]) do
        GraphQL::Subscriptions::Serialize.load(string)
      end
    end
  end
end
```

```ruby
class MySchema < GraphQL::Schema
  use MultiTenantActionCableSubscriptions, serializer: MultiTenantSerializer
end
```

@rmosolgo since rails 7 added the `around_command` callback and we don't have to override the `dispatch_websocket_message` method, can we have the same for `GraphQL::Subscriptions` so we don't have to override `execute_update` ?
