### ISSUE TITLE
Zeitwerk / Rails 6 Runtime Error Duplicate Type

### ISSUE THREAD

**Issue by hybridindie** [rmosolgo/graphql-ruby#2448]
I get the following stack trace in development whenever I edit any Type or Query in my application. Restarting the application fixes the issue until a new edit occurs.

_I'm not sure if this is related to #1505 or not but the fixes/workarounds described there do not work._

Rails 6.0.0
graphql-ruby 1.9.10
(GraphQL-batch and a custom authorization plugin/extension were disabled)
puma 4.1.0 (noted here cause there is discussion around possible thread issues from #1505)

Stacktrace
```
Duplicate type definition found for name 'Account' at 'Field AccountsConnection.nodes's return type' (Types::AccountType, Types::AccountType)
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:172:in `visit'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:188:in `each'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:188:in `visit_fields'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:147:in `visit'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:188:in `each'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:188:in `visit_fields'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:147:in `visit'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:128:in `block in visit'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:128:in `each'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:128:in `visit'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:47:in `initialize'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:1259:in `new'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:1259:in `rebuild_artifacts'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:806:in `to_graphql'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/member/accepts_definition.rb:120:in `to_graphql'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:735:in `graphql_definition'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/2.6.0/forwardable.rb:224:in `execute'
/Users/johnd/Development/IBM/service-portfolio/app/controllers/graphql_controller.rb:11:in `execute'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:196:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:135:in `run_callbacks'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/notifications.rb:180:in `instrument'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activerecord-6.0.0/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/abstract_controller/base.rb:136:in `process'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionview-6.0.0/lib/action_view/rendering.rb:39:in `process'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal.rb:191:in `dispatch'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_controller/metal.rb:252:in `dispatch'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/routing/route_set.rb:837:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-jwt_auth-0.3.6/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-jwt_auth-0.3.6/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/builder.rb:153:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-jwt_auth-0.3.6/lib/warden/jwt_auth/middleware.rb:23:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/cookies.rb:648:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:132:in `call_app'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:28:in `block in call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `catch'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/web-console-4.0.1/lib/web_console/middleware.rb:17:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:38:in `call_app'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `block in call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/rack/logger.rb:26:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actionpack-6.0.0/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-6.0.0/lib/rails/engine.rb:526:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:68:in `block in call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `each'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/rack-2.0.7/lib/rack/urlmap.rb:53:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-4.1.0/lib/puma/configuration.rb:228:in `call'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-4.1.0/lib/puma/server.rb:664:in `handle_request'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-4.1.0/lib/puma/server.rb:467:in `process_client'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-4.1.0/lib/puma/server.rb:328:in `block in run'
/Users/johnd/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/puma-4.1.0/lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Completed 500 Internal Server Error in 17ms (Views: 0.4ms | ActiveRecord: 2.3ms | Allocations: 13969)
```

The current workaround is to add `config.autoloader = :classic` to the `config/application.rb` but you obviously loose the benefits of the Zeitwerk gem.

**Comment by rmosolgo** [comment]
Hi, thanks for the report! 

When you use `autoloader = :classic`, it works fine, is that right?

**Comment by hybridindie** [comment]
yes, that is the work around

**Comment by rmosolgo** [comment]
Cool. Well, I'll add it to the heap of autoloading issues I'm hoping to fix in #2363 . 

There is a way you could help resolve this issue -- if you could create a reproducible case, that would be a big help. For example, if you could make a fresh Rails app, and add a GraphQL setup that demonstrates this bug, and then share that code on GitHub along with the steps to show the bug, then I could try out that app when I'm working on improving the schema boot.

Otherwise, I'll continue focusing on #2363 and just _hope_ that it fixes the problem 🤞 !

**Comment by hybridindie** [comment]
README has all the instructions for reproducing the error https://github.com/hybridindie/graphql_error

**Comment by rmosolgo** [comment]
Thanks! I'll take a look at it when my PR is passing.

**Comment by srgoldman** [comment]
@hybridindie Do you get warnings like: 
```
DEPRECATION WARNING: Initialization autoloaded the constants Types, Types::BaseObject, Mutations, Mutations::BaseMutation,...
```
when you run specs?

**Comment by hybridindie** [comment]
@srgoldman I'm actually out of town until Monday 9/2, if this is still an open question I'm be happy to check it out.

**Comment by srgoldman** [comment]
@hybridindie I managed to reproduce my issue and opened a separate github issue #2456  for it but they might be related.

**Comment by fxn** [comment]
Hey! The error raises right after `GraphqlErrorSchema` is reloaded:

```
Zeitwerk@rails.main: constant GraphqlErrorSchema loaded from file /Users/fxn/tmp/graphql_error/app/graphql/graphql_error_schema.rb
Duplicate type definition found for name 'Account' at 'Field AccountsConnection.nodes's return type' (Types::AccountType, Types::AccountType)
```

You can see this by throwing

```ruby
Rails.autoloaders.log!
```

in _config/application.rb_.

I see in the source code this comment:

```ruby
# If the previous entry in the map isn't the same object we just found, raise.
```

Could it be the case that the gem caches the class object that was once stored in the `Account` constant?

If that cache is not invalidated on reload, in the request after the edition `Account` is reloaded, and therefore the class object `Account` stores now is a different object (does not pass `equal?`). If the previous object was cached, it is no longer reachable through the constant, but it's alive and its name is still "Account".

Does that help?

**Comment by rmosolgo** [comment]
👋  Thanks again for the detailed writeup and reproduction here, @hybridindie . I finally had a chance to clone your repo and try it. I was able to replicate the issue when I pulled the repo: 

```
Processing by GraphqlController#execute as */*
  Parameters: {"query"=>"{\n  accounts(first: 5) {\n    nodes {\n      name\n    }\n  }\n}\n", "variables"=>{}, "graphql"=>{"query"=>"{\n  accounts(first: 5) {\n    nodes {\n      name\n    }\n  }\n}\n", "variables"=>{}}}
Duplicate type definition found for name 'Account' at 'Field AccountsConnection.nodes's return type' (Types::AccountType, Types::AccountType)
/Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:172:in `visit'
/Users/rmosolgo/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
```

And I was able to fix it by updating to the latest graphql-ruby and using the new runtime modules: 

```diff 
-gem 'graphql'
+gem 'graphql', "1.10.2"
```

```diff 
 class GraphqlErrorSchema < GraphQL::Schema
   mutation(Types::MutationType)
   query(Types::QueryType)
+
+  use GraphQL::Execution::Interpreter
+  use GraphQL::Analysis::AST
 end
```

After that, I could edit `query_type.rb` and resend queries without restarting the schema.

So, my recommendation is to update and migrate to those new modules 😅 . I realize it's no small undertaking, but it really _is_ required because of the design issue in the previous implementation. As @fxn pointed out, there was a lot of caching going on previously, and these new modules have been rolled out to simplify that. 

@fxn, thanks for taking a look here and helping out. `Rails.autoloader.log!` may come in handy in the future, too, give GraphQL-Ruby's knack for loading issues 😬 

@hybridindie , if you start on a migration and run into any trouble, please do open an issue with the problem you encounter. I'd be happy to help on that migration path if I can!
