### ISSUE TITLE
All GraphQL queries fail with JRuby 9.2.8.0 

### ISSUE THREAD

**Issue by jessicaspeir** [rmosolgo/graphql-ruby#2451]
I'm trying to upgrade my app from JRuby 9.2.6.0 to 9.2.8.0 (we had to skip 9.2.7.0 because of several bugs). Everything works great on 9.2.6.0 but on 9.2.8.0 every query (including the queries to get the schema fail with this error:

```
yield called out of block :
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/field.rb:623:in `with_extensions' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/field.rb:598:in `public_send_field' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/field.rb:456:in `block in resolve_field' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema.rb:1206:in `after_lazy' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/field.rb:440:in `resolve_field' &
org/jruby/RubyMethod.java:132:in `call' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/member/instrumentation.rb:80:in `call' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/field.rb:248:in `resolve' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:321:in `call' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema/middleware_chain.rb:38:in `invoke' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:129:in `block in resolve_field' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `block in trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:76:in `call_tracers' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:128:in `resolve_field' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:92:in `block in resolve_selection' &
org/jruby/RubyHash.java:1417:in `each' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:85:in `resolve_selection' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `block in trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:76:in `call_tracers' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:49:in `resolve_root_selection' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/execute.rb:31:in `begin_query' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:112:in `begin_query' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex' &
org/jruby/RubyArray.java:2584:in `map' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:62:in `block in run_queries' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:186:in `block in instrument_and_analyze' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:29:in `block in apply_instrumenters' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:46:in `block in each_query_call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:61:in `block in run_queries' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `block in trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:76:in `call_tracers' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/tracing.rb:62:in `trace' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:59:in `run_queries' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/execution/multiplex.rb:49:in `run_all' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema.rb:392:in `block in multiplex' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema.rb:1279:in `with_definition_error_check' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema.rb:391:in `multiplex' &
C:/Tools/JRuby/jruby-9.2.8.0/lib/ruby/gems/shared/gems/graphql-1.9.9/lib/graphql/schema.rb:368:in `execute' &
```

I've truncated the stack trace where it starts to get into our code, it fails on the call to `MySchema.execute`.

This failure occurs on both graphql versions 1.9.9 and 1.9.10. 

I recognize that this is most likely (definitely) an issue with JRuby, but I don't know enough about this code to open an issue with them. I'm mostly posting here to see if anyone else is having this issue with JRuby 9.2.8.0, and if you have any insight on what I can pass on to the JRuby folks to get help them track down the issue.

Thanks!

**Comment by rmosolgo** [comment]
Hi, thanks for the report! Unfortunately, we haven't run our tests on JRuby for quite a while :cry: #1408  

Looking at the lines in question, here's the `yield`: 

https://github.com/rmosolgo/graphql-ruby/blob/24629b3d5824fcd377d934bacea8a96f0cc18403/lib/graphql/schema/field.rb#L623

And here's the call to that method: 

https://github.com/rmosolgo/graphql-ruby/blob/24629b3d5824fcd377d934bacea8a96f0cc18403/lib/graphql/schema/field.rb#L598

It seems like JRuby is upset about the `yield` call because it doesn't know about the block passed to that method. But, we _did_ pass a block to the method, so why can't it `yield` to it? Maybe that's a JRuby issue 😖

**Comment by jessicaspeir** [comment]
@rmosolgo thanks for the quick response! Can I help with getting the tests running on JRuby again? We have had success with JRuby 9.2.6.0, so maybe that version would pass your tests? We are heavily dependent on both JRuby and graphql-ruby so it's slightly concerning that you aren't able to get tests passing...

I'll open a JRuby bug to see if they can figure it out.

**Comment by rmosolgo** [comment]
Getting the tests running on JRuby would be awesome! Ideally, it would be as easy as adding some new runs to `.travis.yml`, like this one: 

https://github.com/rmosolgo/graphql-ruby/blob/869484464958cd6c5ec286260d5d5f9ba4cb51b1/.travis.yml#L79-L80

You might add: 

```
- rvm:  jruby-9.2.6.0
  gemfile: Gemfile 
```

For a basic run. If you want to _also_ test Rails, you could pick one of the rails gemfiles (eg `gemfile: gemfiles/rails_5.2.gemfile`) and you might have to do some database-related setup, depending how JRuby does with the default SQLite backend. 

If you want to give it a try, please open a PR and I'll help if I can!

**Comment by enebo** [comment]
We had omitted passing block through in one code path in refinements code in the JIT.  So this is fixed now.  For posterity this was only observable in the default mixed mode.  Had people been using only the interpreter it would have been working (not saying you should but many people run CI with --dev to get faster CI runs).
