### ISSUE TITLE
Defined but empty schema.query type is not considered invalid

### ISSUE THREAD

**Issue by chrisbutcher** [rmosolgo/graphql-ruby#2461]
# Expected behaviour

```ruby
schema_doc = "type Query { }"
GraphQL::Schema.from_definition(schema_doc) # I would expect this to 💥 
```

In accordance with the js reference implementation:

```javascript
import { buildSchema } from 'graphql';
const typeDefs = `type Query { }`;
buildSchema(typeDefs); // 💥 
```
```
/.../node_modules/graphql/language/parser.js:1433
  throw (0, _error.syntaxError)(lexer.source, token.start, "Expected ".concat(kind, ", found ").concat((0, _lexer.getTokenDesc)(token)));
  ^
GraphQLError: Syntax Error: Expected Name, found }
    at syntaxError (/.../graphql/error/syntaxError.js:24:10)
    at expectToken (/.../graphql/language/parser.js:1433:32)
    at parseName (/.../graphql/language/parser.js:98:15)
    at parseFieldDefinition (/.../graphql/language/parser.js:870:14)
    at many (/.../graphql/language/parser.js:1521:16)
    at parseFieldsDefinition (/.../graphql/language/parser.js:859:50)
    at parseObjectTypeDefinition (/.../graphql/language/parser.js:813:16)
    at parseTypeSystemDefinition (/.../graphql/language/parser.js:711:16)
    at parseDefinition (/.../graphql/language/parser.js:144:16)
    at many (/.../graphql/language/parser.js:1521:16)
```

# Actual behaviour

```ruby
schema_doc = "type Query { }"
=> "type Query { }"
[11] pry(main)> GraphQL::Schema.from_definition(schema_doc)
=> #<GraphQL::Schema ...> # ❌
```

Parsing the schema works, since the schema.query is defined and that's all the gem expects.

**Comment by dteoh** [comment]
This change introduced in 1.9.14 is wrong, it goes against the spec. Issue opened here: https://github.com/rmosolgo/graphql-ruby/issues/2549
