### ISSUE TITLE
Triggering event in GraphqlChannel unsubscribed leads to crash.

### ISSUE THREAD

**Issue by aspectgfg** [rmosolgo/graphql-ruby#2478]
This looks like a race condition. Triggering an event in `GraphqlChannel.unsubscribe` causes a crash. 

Code:

Same `GraphqlChannel` as docs,  except in unsubscribe we do as follows (tried putting trigger before and after the delete_subscription):

```ruby
def unsubscribed
    @subscription_ids.each { |sid|
      RelevntApiSchema.subscriptions.delete_subscription(sid)
    }
    if @chat_id
      RelevntApiSchema.subscriptions.trigger("chat", {chat_id: @chat_id}, {event: "presence_leave", user: current_user })
      $redis.srem("#{@chat_id}:presence", current_user.id.to_s)
    end
  end
```

Stack Trace:

```
There was an exception - NoMethodError(undefined method `query_string' for nil:NilClass)
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.11/lib/graphql/subscriptions/action_cable_subscriptions.rb:133:in `read_subscription'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.11/lib/graphql/subscriptions.rb:85:in `execute'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.11/lib/graphql/subscriptions/action_cable_subscriptions.rb:123:in `block (2 levels) in write_subscription'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/channel/streams.rb:157:in `block in stream_decoder'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:59:in `block in invoke'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:41:in `block in work'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/activesupport-6.0.0/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:40:in `work'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:58:in `invoke'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/actioncable-6.0.0/lib/action_cable/server/worker.rb:53:in `block in async_invoke'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:348:in `run_task'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:337:in `block (3 levels) in create_worker'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `loop'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:320:in `block (2 levels) in create_worker'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `catch'
/Users/z/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/concurrent-ruby-1.1.5/lib/concurrent/executor/ruby_thread_pool_executor.rb:319:in `block in create_worker'
```

Only fix I have is to wrap the trigger event in a thread with a sleep 1:
```ruby
def unsubscribed
    @subscription_ids.each { |sid|
      RelevntApiSchema.subscriptions.delete_subscription(sid)
    }
    if @chat_id
      Thread.new do
        sleep 1
        RelevntApiSchema.subscriptions.trigger("chat", {chat_id: @chat_id}, {event: "presence_leave", user: current_user })
      end
      $redis.srem("#{@chat_id}:presence", current_user.id.to_s)
    end
  end
```

**Comment by rmosolgo** [comment]
Thanks for sharing the details here! I bet it's confused because ActionCable hasn't let go of the subscription yet (since `unsubscribe` hasn't returned). Another work-around might be to put the `.trigger` call in a background job. (That would give you a little more confidence that you didn't lose it during a deploy, for example.)
