### ISSUE TITLE
key not found: :channel

### ISSUE THREAD

**Issue by hugoh59** [rmosolgo/graphql-ruby#2585]
Trying to run my subscription in Graphiql and getting "key not found: :channel" error message. It seems to come from the graphql gem.

**Comment by rmosolgo** [comment]
Please share the full error message and stacktrace if you want to debug something. It's impossible for me to understand what's going on if you don't share any context!

**Comment by jesster2k10** [comment]
Hey there, I got the same issue despite including the channel in the context hash. I think it might be related to this issue #1038 and #1051 which I believe there has been no update on.

I haven't been able to test my subscriptions at all since it fails to work with GraphiQL and using GraphQL playground doesn't work either.

My setup looks like this:

```ruby
# channels/graphql_channel.rb

class GraphqlChannel < ApplicationCable::Channel
  def subscribed
    @subscription_ids = []
  end

  # rubocop:disable Metrics/AbcSize, Metrics/MethodLength
  def execute(data)
    query = data['query']
    variables = ensure_hash(data['variables'])
    operation_name = data['operationName']
    context = {
      # current_user: current_user,
      # Make sure the channel is in the context
      current_user: current_user,
      channel: self,
    }

    result = MurchBackendSchema.execute(
      query: query,
      context: context,
      variables: variables,
      operation_name: operation_name
    )

    payload = {
      result: result.subscription? ? { data: nil } : result.to_h,
      more: result.subscription?
    }

    # Track the subscription here so we can remove it
    # on unsubscribe.
    if result.context[:subscription_id]
      @subscription_ids << context[:subscription_id]
    end

    transmit(payload)
  end
  # rubocop:enable Metrics/AbcSize, Metrics/MethodLength

  def unsubscribed
    @subscription_ids.each do |sid|
      MurchBackendSchema.subscriptions.delete_subscription(sid)
    end
  end

  private

  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end
end
```

```ruby
# murch_backend_schema.rb

class MurchBackendSchema < GraphQL::Schema
  use GraphQL::Batch
  use GraphQL::Subscriptions::ActionCableSubscriptions, redis: Redis.new

  max_depth 10
  default_max_page_size 15

  mutation(Types::MutationType)
  query(Types::QueryType)
  subscription(Types::SubscriptionType)
end
```


```ruby
# types/subscription_type.rb

module Types
  class SubscriptionType < GraphQL::Schema::Object
    include Common::Authenticator
    include Common::ErrorHandler

    # rubocop:disable Layout/HashAlignment
    field :chat_message_received, Types::Chat::ChatMessageType, null: false,
      description: "A message was sent to one of the viewer's chats",
      subscription_scope: :current_user_id do
        argument :chat_id, ID, required: true
      end
    # rubocop:enable Layout/HashAlignment

    def chat_message_received(chat_id:)
      object
    #   require_authorization!
    #   current_profile.chats.find chat_id
    # rescue StandardError
    #   raise GraphQL::ExecutionError, "Cannot subscribe to chat: #{chat_id}"
    end
  end
end
```

Error
![Screenshot 2020-01-05 at 12 44 28](https://user-images.githubusercontent.com/6454286/71780332-1d954b00-2fb9-11ea-8c27-1ca5285462f5.png)

**Comment by jesster2k10** [comment]
Full backtrace:

```json
"error": {
    "message": "key not found: :channel",
    "backtrace": [
      "/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'",
      "/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `fetch'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/subscriptions/action_cable_subscriptions.rb:116:in `write_subscription'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/subscriptions/instrumentation.rb:34:in `after_query'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:82:in `public_send'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:82:in `block in call_after_hooks'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:80:in `each'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:80:in `call_after_hooks'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:74:in `call_hooks'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/tracing.rb:62:in `block in trace'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/tracing.rb:76:in `call_tracers'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/tracing.rb:62:in `trace'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/multiplex.rb:59:in `run_queries'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/execution/multiplex.rb:49:in `run_all'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:392:in `block in multiplex'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:1279:in `with_definition_error_check'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:391:in `multiplex'",
      "/Library/Ruby/Gems/2.6.0/gems/graphql-1.9.10/lib/graphql/schema.rb:368:in `execute'",
      "/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/forwardable.rb:230:in `execute'",
      "/Users/jesseonolememen/Projects/murch/backend/app/controllers/graphql_controller.rb:14:in `execute'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:194:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rendering.rb:30:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:109:in `block in run_callbacks'",
      "/Library/Ruby/Gems/2.6.0/gems/react-rails-2.6.0/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:118:in `block in run_callbacks'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:136:in `run_callbacks'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/callbacks.rb:41:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/rescue.rb:22:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `block in instrument'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications/instrumenter.rb:23:in `instrument'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/notifications.rb:168:in `instrument'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal/params_wrapper.rb:256:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/railties/controller_runtime.rb:24:in `process_action'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/abstract_controller/base.rb:134:in `process'",
      "/Library/Ruby/Gems/2.6.0/gems/actionview-5.2.3/lib/action_view/rendering.rb:32:in `process'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:191:in `dispatch'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_controller/metal.rb:252:in `dispatch'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:52:in `dispatch'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:34:in `serve'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:52:in `block in serve'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `each'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/journey/router.rb:35:in `serve'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/routing/route_set.rb:840:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/apollo_upload_server-1.0.0/lib/apollo_upload_server/middleware.rb:16:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'",
      "/Library/Ruby/Gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'",
      "/Library/Ruby/Gems/2.6.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/tempfile_reaper.rb:15:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/etag.rb:25:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/conditional_get.rb:38:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/head.rb:12:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/http/content_security_policy.rb:18:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:232:in `context'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/session/abstract/id.rb:226:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/cookies.rb:670:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/activerecord-5.2.3/lib/active_record/migration.rb:559:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/callbacks.rb:98:in `run_callbacks'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:38:in `call_app'",
      "/Library/Ruby/Gems/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `block in call'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `block in tagged'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:28:in `tagged'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/tagged_logging.rb:71:in `tagged'",
      "/Library/Ruby/Gems/2.6.0/gems/railties-5.2.3/lib/rails/rack/logger.rb:26:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/method_override.rb:22:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/runtime.rb:22:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/activesupport-5.2.3/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/executor.rb:14:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:23:in `_call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-livereload-0.3.17/lib/rack/livereload.rb:14:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/actionpack-5.2.3/lib/action_dispatch/middleware/static.rb:127:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-2.0.7/lib/rack/sendfile.rb:111:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-cors-1.0.3/lib/rack/cors.rb:95:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/webpacker-4.0.7/lib/webpacker/dev_server_proxy.rb:29:in `perform_request'",
      "/Library/Ruby/Gems/2.6.0/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/railties-5.2.3/lib/rails/engine.rb:524:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/puma-3.12.1/lib/puma/configuration.rb:227:in `call'",
      "/Library/Ruby/Gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:660:in `handle_request'",
      "/Library/Ruby/Gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:474:in `process_client'",
      "/Library/Ruby/Gems/2.6.0/gems/puma-3.12.1/lib/puma/server.rb:334:in `block in run'",
      "/Library/Ruby/Gems/2.6.0/gems/puma-3.12.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
    ]
  },

```

**Comment by chandeeland** [comment]
I have reproduced the same error.  When I set a `channel` key to my graphql_controller.rb `context` it progresses to another error because I'm not sure how to instantiate a new channel instance.  I believe the problem is that the request is being handled via the controller instead of the channel which set's a context = { channel: self }

**Comment by rmosolgo** [comment]
When you're using ActionCable for subscriptions, you have to send `subscription { ... }` operations _to ActionCable_, not to a Rails controller. For example, the JavaScript client I maintain in this project provides Apollo plugins to do that. 

If you want to debug further, please share a full stack trace.

**Comment by petrbela** [comment]
I was running into the same problem, turned out Apollo client still executes subscription requests during SSR (I wrongly assumed subscriptions only run on the client). Since `graphql-ruby-client` only runs on the client (and therefore it doesn't make sense to [split](https://www.apollographql.com/docs/react/data/subscriptions/#3-split-communication-by-operation-recommended) the requests, the easiest fix for me was to add `skip: typeof window === 'undefined'` wherever I was using `useSubscription` so that it avoids subscription requests on the server altogether.

**Comment by penso** [comment]
> When you're using ActionCable for subscriptions, you have to send `subscription { ... }` operations _to ActionCable_, not to a Rails controller. For example, the JavaScript client I maintain in this project provides Apollo plugins to do that.
> 
> If you want to debug further, please share a full stack trace.

Makes perfect sense @rmosolgo, but I think it'd make things way easier if the server error was something like "Subscriptions don't work through Rails controllers, please use ActionCable" instead of `KeyError` (current error doesn't even say anything about channels).
