### ISSUE TITLE
rescue_from not being called when failing to load an argument that is part of an Input

### ISSUE THREAD

**Issue by thornomad** [rmosolgo/graphql-ruby#2629]
It seems `ApiSchema.rescue_from` is not being called when an argument fails to load that is _part of an input object_; however, it does get called the argument is just a base argument on a mutation for example).

#### example argument, loading a `Person`

```ruby
  argument :person_id, ID, 
    required: true, 
    as: :person, 
    loads: Types::PersonType,
```

**[1]** If I place this call in the mutation class directly, and then attempt the mutation with a malformed `person_id` argument, the `rescue_from` is called correctly.  Expected behavior.

**[2]** However, if I place this _same_ argument call inside an `Input` and then attempt the mutation with an invalid `person_id` variable it is not finding `rescue_from` and I am getting a regular unhandled error.

Hope this makes sense!

#### full backtrace
```text
RuntimeError at /v2
===================

> A GraphQL::Pro::Encoder failed to decode a cipher, can't do anything with the result

app/graphql/api_schema/global_identifier.rb, line 30
----------------------------------------------------

   27       def decode_from_id(gid)
   28         begin
   29           decoded_string = VersionedEncoder.decode(gid)
>  30           model_id, model_name = decoded_string.split(SEPERATOR)
   31   


App backtrace
-------------

 - app/graphql/api_schema/global_identifier.rb:30:in `decode_from_id'
 - app/graphql/api_schema/global_identifier.rb:67:in `object_from_id'
 - app/controllers/graphql_controller.rb:18:in `execute'
 - app/controllers/api/v2/api_controller.rb:63:in `set_current_user'

Full backtrace
--------------

 - graphql-pro (1.11.0) lib/graphql/pro/encoder/decode_failed.rb:7:in `method_missing'
 - app/graphql/api_schema/global_identifier.rb:30:in `decode_from_id'
 - app/graphql/api_schema/global_identifier.rb:67:in `object_from_id'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema.rb:559:in `object_from_id'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema/member/has_arguments.rb:85:in `object_from_id'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema/member/has_arguments.rb:90:in `load_application_object'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema/input_object.rb:31:in `block in initialize'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema/input_object.rb:21:in `initialize'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/input_object_type.rb:102:in `coerce_non_null_input'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/base_type.rb:169:in `coerce_input'
 - /Users/damon/.rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `coerce_input'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query/variables.rb:38:in `block in initialize'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query/variables.rb:19:in `initialize'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query.rb:221:in `block in variables'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query.rb:385:in `with_prepared_ast'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query.rb:220:in `variables'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query/validation_pipeline.rb:80:in `ensure_has_validated'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query/validation_pipeline.rb:35:in `valid?'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/query.rb:256:in `valid?'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/analysis/analyze_query.rb:11:in `block (2 levels) in analyze_multiplex'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/analysis/analyze_query.rb:10:in `block in analyze_multiplex'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:62:in `block in trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:76:in `call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `block in call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/errors.rb:34:in `trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:62:in `trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/analysis/analyze_query.rb:8:in `analyze_multiplex'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/multiplex.rb:185:in `block in instrument_and_analyze'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:62:in `block in trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `block (2 levels) in call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:76:in `call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `block in call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/errors.rb:34:in `trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:78:in `call_tracers'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/tracing.rb:62:in `trace'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/multiplex.rb:59:in `run_queries'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/execution/multiplex.rb:49:in `run_all'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema.rb:393:in `block in multiplex'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema.rb:1289:in `with_definition_error_check'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema.rb:392:in `multiplex'
 -  () Users/damon/.gem/ruby/2.6.3/bundler/gems/graphql-ruby-87942848cf1f/lib/graphql/schema.rb:369:in `execute'
 - /Users/damon/.rubies/ruby-2.6.3/lib/ruby/2.6.0/forwardable.rb:230:in `execute'
 - app/controllers/graphql_controller.rb:18:in `execute'
 - actionpack (5.2.3) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
 - actionpack (5.2.3) lib/abstract_controller/base.rb:194:in `process_action'
 - actionpack (5.2.3) lib/action_controller/metal/rendering.rb:30:in `process_action'
 - actionpack (5.2.3) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
 - activesupport (5.2.3) lib/active_support/callbacks.rb:109:in `block in run_callbacks'
 - app/controllers/api/v2/api_controller.rb:63:in `set_current_user'
 - activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 - sentry-raven (2.7.3) lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
 - activesupport (5.2.3) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
 - activesupport (5.2.3) lib/active_support/callbacks.rb:136:in `run_callbacks'
 - actionpack (5.2.3) lib/abstract_controller/callbacks.rb:41:in `process_action'
 - actionpack (5.2.3) lib/action_controller/metal/rescue.rb:22:in `process_action'
 - actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
 - activesupport (5.2.3) lib/active_support/notifications.rb:168:in `block in instrument'
 - activesupport (5.2.3) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
 - activesupport (5.2.3) lib/active_support/notifications.rb:168:in `instrument'
 - actionpack (5.2.3) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
 - actionpack (5.2.3) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
 - activerecord (5.2.3) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
 - actionpack (5.2.3) lib/abstract_controller/base.rb:134:in `process'
 - actionpack (5.2.3) lib/action_controller/metal.rb:191:in `dispatch'
 - actionpack (5.2.3) lib/action_controller/metal.rb:252:in `dispatch'
 - actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
 - actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:34:in `serve'
 - actionpack (5.2.3) lib/action_dispatch/journey/router.rb:52:in `block in serve'
 - actionpack (5.2.3) lib/action_dispatch/journey/router.rb:35:in `serve'
 - actionpack (5.2.3) lib/action_dispatch/routing/route_set.rb:840:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:14:in `block in call'
 - skylight-core (3.1.5) lib/skylight/core/fanout.rb:25:in `instrument'
 - skylight-core (3.1.5) lib/skylight/core/probes/action_dispatch/routing/route_set.rb:13:in `call'
 - rack (2.0.7) lib/rack/etag.rb:25:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - rack (2.0.7) lib/rack/conditional_get.rb:38:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - rack (2.0.7) lib/rack/head.rb:12:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - activerecord (5.2.3) lib/active_record/migration.rb:559:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
 - activesupport (5.2.3) lib/active_support/callbacks.rb:98:in `run_callbacks'
 - actionpack (5.2.3) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:84:in `protected_app_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:79:in `better_errors_call'
 - better_errors (2.1.1) lib/better_errors/middleware.rb:57:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - railties (5.2.3) lib/rails/rack/logger.rb:38:in `call_app'
 - railties (5.2.3) lib/rails/rack/logger.rb:26:in `block in call'
 - activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `block in tagged'
 - activesupport (5.2.3) lib/active_support/tagged_logging.rb:28:in `tagged'
 - activesupport (5.2.3) lib/active_support/tagged_logging.rb:71:in `tagged'
 - railties (5.2.3) lib/rails/rack/logger.rb:26:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - request_store (1.4.1) lib/request_store/middleware.rb:19:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/request_id.rb:27:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/action_dispatch/request_id.rb:12:in `call'
 - rack (2.0.7) lib/rack/runtime.rb:22:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - activesupport (5.2.3) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/executor.rb:14:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - actionpack (5.2.3) lib/action_dispatch/middleware/static.rb:127:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - rack (2.0.7) lib/rack/sendfile.rb:111:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - rack-cors (1.0.3) lib/rack/cors.rb:95:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - hirefire-resource (0.4.2) lib/hirefire/middleware.rb:41:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - sentry-raven (2.7.3) lib/raven/integrations/rack.rb:51:in `call'
 - skylight-core (3.1.5) lib/skylight/core/probes/middleware.rb:26:in `call'
 - railties (5.2.3) lib/rails/engine.rb:524:in `call'
 - puma (3.11.0) lib/puma/configuration.rb:225:in `call'
 - puma (3.11.0) lib/puma/server.rb:624:in `handle_request'
 - puma (3.11.0) lib/puma/server.rb:438:in `process_client'
 - puma (3.11.0) lib/puma/server.rb:302:in `block in run'
 - puma (3.11.0) lib/puma/thread_pool.rb:120:in `block in spawn_thread'

```

**Comment by rmosolgo** [comment]
Yes, this makes sense. Thanks for sharing the full backtrace, it looks like variable initialization isn't quite properly wrapped. Similar to the just-opened #2627. I think it needs a little retooling because its `rescue` is covering too small a slice of code 🤔 .
