### ISSUE TITLE
`loads:` option on nested input doesn't resolve lazy values

### ISSUE THREAD

**Issue by tjwallace** [rmosolgo/graphql-ruby#2671]
#2323 fixed `loads:` on nested input objects, but if your `Schema.object_from_id` function returns a lazy value, it won't be resolved by the time the mutation's `#resolve` function is called.

**Comment by rmosolgo** [comment]
Thanks for reporting this! I suppose the first step here is to add a failing test to the suite, then we can find some place to add the waiting. It'll be a little tricky since the `load_application_object` call happens in `#initialize`. But recently, we added `.prepare` to InputObjects, that might offer a spot to do this.

**Comment by lucthev** [comment]
I'm not sure https://github.com/rmosolgo/graphql-ruby/pull/2834 fixed this issue — when I [modify some of the input object specs](https://github.com/rmosolgo/graphql-ruby/compare/master...lucthev:lt/lazy-input-loads) to use lazy-loading, they still fail.

<details>
  <summary>Sample failure (using TESTING_INTERPRETER=1)</summary>

```
Error:
GraphQL::Schema::InputObject::prepare: / loads: / as:#test_0003_handles not-found with max complexity analyzer running:
NoMethodError: undefined method `key?' for #<GraphQL::Execution::Lazy:0x00007f9ebcc92978>
    graphql-ruby/lib/graphql/schema/input_object.rb:29:in `block in initialize'
    graphql-ruby/lib/graphql/schema/input_object.rb:25:in `each'
    graphql-ruby/lib/graphql/schema/input_object.rb:25:in `initialize'
    graphql-ruby/lib/graphql/schema/input_object.rb:213:in `new'
    graphql-ruby/lib/graphql/schema/input_object.rb:213:in `coerce_input'
    graphql-ruby/lib/graphql/schema/non_null.rb:54:in `coerce_input'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:107:in `block (3 levels) in coerce_arguments'
    graphql-ruby/lib/graphql/execution/errors.rb:30:in `with_error_handling'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:102:in `block (2 levels) in coerce_arguments'
    graphql-ruby/lib/graphql/schema.rb:114:in `after_lazy'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:100:in `block in coerce_arguments'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:75:in `each'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:75:in `map'
    graphql-ruby/lib/graphql/schema/member/has_arguments.rb:75:in `coerce_arguments'
    graphql-ruby/lib/graphql/execution/interpreter/arguments_cache.rb:15:in `block (3 levels) in initialize'
    graphql-ruby/lib/graphql/execution/interpreter/arguments_cache.rb:31:in `fetch'
    graphql-ruby/lib/graphql/query.rb:251:in `arguments_for'
    graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:442:in `arguments'
    graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:171:in `block in evaluate_selections'
    graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:124:in `each'
    graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'
    graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:60:in `run_eager'
    graphql-ruby/lib/graphql/execution/interpreter.rb:71:in `block in evaluate'
    graphql-ruby/lib/graphql/tracing.rb:67:in `block in trace'
    graphql-ruby/lib/graphql/tracing.rb:81:in `call_tracers'
    graphql-ruby/lib/graphql/tracing.rb:67:in `trace'
    graphql-ruby/lib/graphql/execution/interpreter.rb:70:in `evaluate'
    graphql-ruby/lib/graphql/execution/interpreter.rb:43:in `begin_query'
    graphql-ruby/lib/graphql/execution/multiplex.rb:113:in `begin_query'
    graphql-ruby/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
    graphql-ruby/lib/graphql/execution/multiplex.rb:83:in `map'
    graphql-ruby/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
    graphql-ruby/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
    graphql-ruby/lib/graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    graphql-ruby/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
    graphql-ruby/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
    graphql-ruby/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
    graphql-ruby/lib/graphql/tracing.rb:67:in `block in trace'
    graphql-ruby/lib/graphql/tracing.rb:81:in `call_tracers'
    graphql-ruby/lib/graphql/tracing.rb:67:in `trace'
    graphql-ruby/lib/graphql/execution/multiplex.rb:59:in `run_queries'
    graphql-ruby/lib/graphql/execution/multiplex.rb:49:in `run_all'
    graphql-ruby/lib/graphql/schema.rb:1626:in `multiplex'
    graphql-ruby/lib/graphql/schema.rb:1597:in `execute'
    graphql-ruby/spec/graphql/schema/input_object_spec.rb:196:in `block (3 levels) in <top (required)>'
```
</details>

Is this indeed the same issue? I can open another, if necessary.

**Comment by rmosolgo** [comment]
I don't know if it's exactly the same or not, but it sounds like there's still work to do here!
