### ISSUE TITLE
Mutations returning a scalar value cause NoMethodError

### ISSUE THREAD

**Issue by ooxif** [rmosolgo/graphql-ruby#2679]
# Versions
ruby: 2.7.0
rails: 6.0.2.1
graphql: 1.9.18

# Repro

graphql/types/mutation_type.rb

```ruby
module Types
  class MutationType < Types::BaseObject
    field :foo, mutation: Mutations::Foo
  end
end
```

graphql/mutations/foo.rb

```ruby
module Mutations
  class Foo < BaseMutation
    null false
    type Boolean

    def resolve
      true
    end
  end
end
```

# Stacktrace

```
NoMethodError: undefined method `[]=' for true:TrueClass
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/relay/mutation/resolve.rb:51:in `build_result'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/relay/mutation/resolve.rb:29:in `block in call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema.rb:1257:in `after_lazy'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/relay/mutation/resolve.rb:27:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/field.rb:248:in `resolve'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:321:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `block in trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:76:in `call_tracers'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:128:in `resolve_field'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:85:in `each'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `block in trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:76:in `call_tracers'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/execute.rb:31:in `begin_query'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:112:in `begin_query'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:84:in `block in run_as_multiplex'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:83:in `map'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:83:in `run_as_multiplex'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:186:in `block in instrument_and_analyze'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `block in trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:76:in `call_tracers'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/tracing.rb:62:in `trace'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/execution/multiplex.rb:49:in `run_all'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema.rb:403:in `block in multiplex'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema.rb:1330:in `with_definition_error_check'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema.rb:402:in `multiplex'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/graphql-1.9.18/lib/graphql/schema.rb:379:in `execute'
/usr/local/lib/ruby/2.7.0/forwardable.rb:235:in `execute'
/path/to/app/app/controllers/concerns/graphql_controller_concern.rb:41:in `execute_single'
/path/to/app/app/controllers/concerns/graphql_controller_concern.rb:10:in `execute'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:196:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:135:in `run_callbacks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `block in instrument'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `instrument'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:136:in `process'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:191:in `dispatch'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:252:in `dispatch'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `each'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:837:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/etag.rb:27:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/conditional_get.rb:40:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/head.rb:14:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:567:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/lograge-0.11.2/lib/lograge/rails_ext/rack/logger.rb:15:in `call_app'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/runtime.rb:24:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/activesupport-6.0.2.1/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/rack-2.1.1/lib/rack/sendfile.rb:113:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/path/to/app/app/lib/rescue_middleware.rb:9:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/configuration.rb:228:in `call'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:681:in `handle_request'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:472:in `process_client'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/server.rb:328:in `block in run'
/path/to/app/vendor/bundle/ruby/2.7.0/gems/puma-4.3.1/lib/puma/thread_pool.rb:134:in `block in spawn_thread'"
```

Can class-based mutations have `type` and return a scalar value?

https://github.com/rmosolgo/graphql-ruby/blob/v1.9.18/lib/graphql/relay/mutation/resolve.rb#L47

I don't use `clientMutationId` at all, so returning a scalar value suffice my project.

**Comment by rmosolgo** [comment]
Hi, thanks for the detailed bug report! 

One of the _features_ of a Relay mutation is the generated payload type which is returned from the mutation. If you don't want that generated payload type, how about using `GraphQL::Schema::Mutation` which doesn't add `client_mutation_id`?  Would that other class work for you? 

Alternatively, you could add  a single return field like 

```ruby 
field :success, Boolean, null: false 
```

and return a Hash to satisfy it, like: 

```ruby 
def resolve 
  { success: true }
end 
```

That way, the mutation would comply with Relay Classic conventions.

(You can even see how, a few lines before the code you linked, there's an assertion that the returned value is a Hash! Perhaps that assertion should be made in this case.)

**Comment by ooxif** [comment]
Thanks for letting me know!
I didn't know `GraphQL::Schema::Mutation`.
I changed `Mutations::BaseMutation` to be extended from `GraphQL::Schema::Mutation` and removed `input_object_class` DSL.
Now it looks good to me!
