### ISSUE TITLE
Is it possible to add GraphQL Ruby in a Rails Engine to be mounted in the main app?

### ISSUE THREAD

**Issue by naoufalelh** [rmosolgo/graphql-ruby#2682]
I was wondering if i can add and use GraphQL in a Rails Engine.
after a `bundle install` in a Rails engine i tried `rails generate graphql:install` and i got this error:
```
Traceback (most recent call last):
        17: from bin/rails:12:in `<main>'
        16: from bin/rails:12:in `require'
        15: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/engine/commands.rb:19:in `<top (required)>'
        14: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/engine/commands.rb:19:in `require'
        13: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/commands/generate.rb:13:in `<top (required)>'
        12: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/railties-4.2.10/lib/rails/generators.rb:157:in `invoke'
        11: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/base.rb:466:in `start'
        10: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/group.rb:232:in `dispatch'
         9: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `invoke_all'
         8: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `map'
         7: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `each'
         6: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:133:in `block in invoke_all'
         5: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/invocation.rb:126:in `invoke_command'
         4: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/thor-0.20.0/lib/thor/command.rb:27:in `run'
         3: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.4/lib/generators/graphql/install_generator.rb:94:in `create_folder_structure'
         2: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.4/lib/generators/graphql/core.rb:33:in `schema_file_path'
         1: from /Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.4/lib/generators/graphql/core.rb:50:in `schema_name'
/Users/naoufal/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0/gems/graphql-1.9.4/lib/generators/graphql/core.rb:50:in `require': cannot load such file -- /Users/naoufal/myengine/config/application (LoadError)
```

**Comment by rmosolgo** [comment]
Hi! Sorry about the hangup. I think GraphQL should work fine inside an engine, although maybe the generators won't work, since the file layout is different. Please try adding the various classes yourself and let me know if it doesn't work!

**Comment by fameoflight** [comment]
@fedeaux any chance you have sample repository. Thank you in advance

**Comment by Pistos** [comment]
I had to do another file, as well:

```shell
cd engine_dir
touch config/application.rb config/boot.rb test/dummy/Gemfile
```
