### ISSUE TITLE
Broken AST analysis with graphql-ruby 1.10.2 and ruby 2.7.0

### ISSUE THREAD

**Issue by amkisko** [rmosolgo/graphql-ruby#2717]
Used https://graphql-ruby.org/queries/ast_analysis.html
```ruby
class UserSchema < GraphQL::Schema
  use(GraphQL::Analysis::AST)
  query_analyzer(QueryAnalyzer)
...
```

```ruby
class QueryAnalyzer < GraphQL::Analysis::AST::Analyzer
  def initialize(query)
    super
  end

  def on_enter_field(node, parent, visitor)
  end

  def on_leave_field(node, parent, visitor)
  end

  def result
  end
end
```

Now produces error:
```
undefined method `call' for QueryAnalyzer:Class
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/reducer_state.rb:15:in `call'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:81:in `block in visit_analyzers'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:80:in `each'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:80:in `visit_analyzers'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:68:in `reduce_node'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:55:in `block (2 levels) in analyze_query'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:54:in `each'
~/.rvm/gems/ruby-2.7.0/gems/graphql-1.10.2/lib/graphql/analysis/analyze_query.rb:54:in `block in analyze_query'
```

**Comment by amkisko** [comment]
@rmosolgo any breaking changes for AST analysers introduced?

**Comment by amkisko** [comment]
Adding
```ruby
  def initialize
    super
    @analysis_engine = GraphQL::Analysis::AST
  end
```
to UserSchema definition fixed the problem :|

**Comment by rmosolgo** [comment]
Weird, are you using `use GraphQL::Execution::Interpreter` in your schema definition?

**Comment by amkisko** [comment]
> GraphQL::Execution::Interpreter

Nope, I have basic generated schema definition as it is in first message.

**Comment by rmosolgo** [comment]
Oh, ok, thanks! Thanks for sharing your work-around, I'll look for a fix here.

**Comment by pocke** [comment]
Hi. I have the same issue and I created a small reproduce code.

```ruby
require 'graphql'

class QueryType < GraphQL::Schema::Object
  field :id, ID, null: false, resolve: -> (_, _, _) { "1" }
end

class MyAstAnalyzer < GraphQL::Analysis::AST::Analyzer
  def result
  end
end

class Schema < GraphQL::Schema
  use GraphQL::Analysis::AST
  query QueryType
  query_analyzer MyAstAnalyzer
end

p Schema.analysis_engine
p Schema.to_graphql.analysis_engine

pp Schema.execute(query: <<~GQL)
  query {
    id
  }
GQL
```

```
GraphQL::Analysis::AST
GraphQL::Analysis
Traceback (most recent call last):
        38: from main.rb:21:in `<main>'
        37: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:1528:in `execute'
        36: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/schema.rb:1557:in `multiplex'
        35: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:49:in `run_all'
        34: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:59:in `run_queries'
        33: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
        32: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
        31: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
        30: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
        29: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
        28: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        27: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        26: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        25: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        24: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        23: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        22: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        21: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        20: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        19: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
        18: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:8:in `analyze_multiplex'
        17: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
        16: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
        15: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
        14: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:10:in `block in analyze_multiplex'
        13: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:10:in `map'
        12: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:12:in `block (2 levels) in analyze_multiplex'
        11: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:41:in `analyze_query'
        10: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
         9: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
         8: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
         7: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:54:in `block in analyze_query'
         6: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:54:in `each'
         5: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:55:in `block (2 levels) in analyze_query'
         4: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:68:in `reduce_node'
         3: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:80:in `visit_analyzers'
         2: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:80:in `each'
         1: from /home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/analyze_query.rb:81:in `block in visit_analyzers'
/home/pocke/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.3/lib/graphql/analysis/reducer_state.rb:15:in `call': undefined method `call' for MyAstAnalyzer:Class (NoMethodError)
```

It prints the result on v1.9.x, but it fails on v1.10.x. I've confirmed the error on 1.10.0 and 1.10.3.
1.10.1 and 1.10.2 have another error about ruby2_keyword.


And the code has debug prints for `analysis_engine`.
On v1.19, `Schema.analysis_engine` and `Schema.to_graphql.analysis_engine` are the same, which is `GraphQL::Analysis::AST`.
But `Schema.to_graphql.analysis_engine` is `GraphQL::Analysis` on v1.10. I guess it is the cause.



I've confirmed the following patch solves the problem.


```diff
diff --git a/lib/graphql/schema.rb b/lib/graphql/schema.rb
index ae016b0c4..6bd4c5a98 100644
--- a/lib/graphql/schema.rb
+++ b/lib/graphql/schema.rb
@@ -896,6 +896,7 @@ module GraphQL
         schema_defn.cursor_encoder = cursor_encoder
         schema_defn.tracers.concat(tracers)
         schema_defn.query_analyzers.concat(query_analyzers)
+        schema_defn.analysis_engine = analysis_engine
 
         schema_defn.middleware.concat(all_middleware)
         schema_defn.multiplex_analyzers.concat(multiplex_analyzers)
```

I'll open a pull request with the patch if you'd like.

Thanks!

**Comment by amkisko** [comment]
@pocke you are welcome, please open a pull request with the patch! :)
