### ISSUE TITLE
Query analysis is broken with the new interpreter

### ISSUE THREAD

**Issue by vfonic** [rmosolgo/graphql-ruby#2787]
Possibly related/duplicate: 
https://github.com/rmosolgo/graphql-ruby/issues/2717

I've upgraded from 1.10.1 to 1.10.3 (same issue on 1.10.2) and now I'm receiving errors if I use query analizer like explained in the docs:
https://graphql-ruby.org/queries/complexity_and_depth.html

```rb
class MySchema < GraphQL::Schema
  log_query_complexity = GraphQL::Analysis::QueryComplexity.new { |query, complexity| Rails.logger.info("[GraphQL Query Complexity] #{complexity}  | staff? #{query.context[:current_user].staff?}")}
  query_analyzer(log_query_complexity)
end
```

Here are the smallest repro steps:

```sh
rails new arithmetics_ql
cd arithmetics_ql
echo "gem 'graphql'" >> Gemfile
bundle install
rails g graphql:install
open app/graphql/arithmetics_ql_schema.rb
# add the following code snippet:
#  log_query_complexity = GraphQL::Analysis::QueryComplexity.new { |query, complexity| Rails.logger.info("[GraphQL Query Complexity] #{complexity}  | staff? #{query.context[:current_user].staff?}")}
#  query_analyzer(log_query_complexity)
rails console
> ArithmeticsQlSchema.execute(%{{testField}})
```

Output:

```
 > ArithmeticsQlSchema.execute(%{{testField}})
Traceback (most recent call last):
        1: from (irb):1
NoMethodError (undefined method `new' for #<GraphQL::Analysis::QueryComplexity:0x00007fd275bc0648>)
```

Edit:
Commenting out the new interpreter makes the issue go away:

```rb
  # use GraphQL::Execution::Interpreter
```

**Comment by swalkinshaw** [comment]
I'm guessing 1.10.2 or .3 defaulted to the new AST analysis engine. `GraphQL::Analysis::QueryComplexity` is the old version.

If you use https://graphql-ruby.org/api-doc/1.10.3/GraphQL/Analysis/AST/QueryComplexity it should work. However it doesn't take a block like the old one.

So you'll need to subclass it and override the `result` method to log the complexity.

```ruby
class MyComplexityAnalyzer < GraphQL::Analysis::AST::QueryComplexity
  def result
    Rails.logger.info("[GraphQL Query Complexity] #{max_possible_complexity} | staff? #{query.context[:current_user].staff?}"
  end
end

class MySchema < GraphQL::Schema
  query_analyzer(MyComplexityAnalyzer)
end
```

Looks like that docs page should be updated to use the new AST analyzers though.

**Comment by rmosolgo** [comment]
Sorry about the stale docs -- @swalkinshaw  is right about the proper approach. I've updated the docs in 85512cfee. 


Honestly, I'm amazed it _worked_ in 1.10.1. I would have expected this check to raise an error: 

https://github.com/rmosolgo/graphql-ruby/blob/4b60c207dac820fd8d2f0be9e6a436d8616f863e/lib/graphql/execution/multiplex.rb#L177-L185

If you want to share the full error message, I'll try to find the codepath that isn't properly covered. Otherwise, using `AST` analyzers should do the trick!

**Comment by vfonic** [comment]
As a side note: When I was using 1.10.1, I was still using the old interpreter.

Here's the full output of the rake task simply running the above query on schema:

```
NoMethodError: undefined method `new' for #<GraphQL::Analysis::QueryComplexity:0x00007fb8386a1880>
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:58:in `block (2 levels) in analyze_query'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:58:in `map'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:58:in `block in analyze_query'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
.../graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:56:in `analyze_query'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:32:in `block (2 levels) in analyze_multiplex'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:30:in `map'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:30:in `block in analyze_multiplex'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
.../graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
.../graphql-1.10.3/lib/graphql/analysis/ast.rb:29:in `analyze_multiplex'
.../graphql-1.10.3/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
.../graphql-1.10.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
.../graphql-1.10.3/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
.../graphql-1.10.3/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
.../graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
.../graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
.../graphql-1.10.3/lib/graphql/execution/multiplex.rb:59:in `run_queries'
.../graphql-1.10.3/lib/graphql/execution/multiplex.rb:49:in `run_all'
.../graphql-1.10.3/lib/graphql/schema.rb:1557:in `multiplex'
.../graphql-1.10.3/lib/graphql/schema.rb:1528:in `execute'
.../arithmetics_ql/lib/tasks/arithmeticalize.rake:3:in `block (2 levels) in <main>'
.../railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:23:in `block in perform'
.../railties-6.0.2.1/lib/rails/commands/rake/rake_command.rb:20:in `perform'
.../railties-6.0.2.1/lib/rails/command.rb:48:in `invoke'
.../railties-6.0.2.1/lib/rails/commands.rb:18:in `<main>'
.../bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
.../bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
.../bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
.../bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
.../bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
.../activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `block in require'
.../activesupport-6.0.2.1/lib/active_support/dependencies.rb:291:in `load_dependency'
.../activesupport-6.0.2.1/lib/active_support/dependencies.rb:325:in `require'
.../arithmetics_ql/bin/rails:9:in `<top (required)>'
.../spring-2.1.0/lib/spring/client/rails.rb:28:in `load'
.../spring-2.1.0/lib/spring/client/rails.rb:28:in `call'
.../spring-2.1.0/lib/spring/client/command.rb:7:in `call'
.../spring-2.1.0/lib/spring/client.rb:30:in `run'
.../spring-2.1.0/bin/spring:49:in `<top (required)>'
.../spring-2.1.0/lib/spring/binstub.rb:11:in `load'
.../spring-2.1.0/lib/spring/binstub.rb:11:in `<top (required)>'
.../arithmetics_ql/bin/spring:15:in `require'
.../arithmetics_ql/bin/spring:15:in `<top (required)>'
```
