### ISSUE TITLE
Automatic Connection Wrapping does not work with String Type References

### ISSUE THREAD

**Issue by mintyfresh** [rmosolgo/graphql-ruby#2837]
**Describe the bug**
ActiveRecord relations are not automatically wrapped in a `Connection` object when returned from a resolver which defines a type using a String reference.

**Versions**

`graphql` version: 1.10.2
`rails`: 6.0.2.1
`graphql-batch`: 0.4.2

**GraphQL schema**
I'm not able to provide actual code or schema as examples here, however, I can provide examples that mimic the issue.

```ruby
class Types::UserType < Types::BaseObject
  field :id, ID, null: false
  field :orders, resolver: Resolvers::UserOrdersResolver
end

class Types::OrderType < Types::BaseObject
  field :id, ID, null: false
  field :owner, type: Types::UserType, null: false
end

module Types
  # Defined to allow reference to type by String.
  OrderConnectionType = Types::OrderType.connection_type
end

class Resolvers::UserOrdersResolver < Resolvers::BaseResolver
  # Referencing type by String to mitigate cyclic dependency.
  type 'Types::OrderConnectionType', null: false

  def resolve
    object.orders
  end
end
```

**Steps to reproduce**
Define a resolver that returns a Connection type, referencing the type by String.

**Expected behavior**
The ActiveRecord relation is automatically wrapped by a Connection object.

**Actual behavior**
ActiveRecord relation is not wrapped in a Connection object.

<details>
<summary>Click to view exception backtrace</summary>

```
undefined method `edge_nodes' for #<ActiveRecord::Relation []>
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/relation/delegation.rb:108:in `method_missing'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/types/relay/base_connection.rb:105:in `nodes'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:680:in `public_send'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:680:in `block in public_send_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:701:in `block in with_extensions'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:720:in `block (2 levels) in run_extensions_before_resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:723:in `run_extensions_before_resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:720:in `block in run_extensions_before_resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field_extension.rb:50:in `resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:718:in `run_extensions_before_resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:700:in `with_extensions'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:668:in `public_send_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:525:in `block (2 levels) in resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema.rb:1851:in `after_lazy'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:515:in `block in resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema.rb:1851:in `after_lazy'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/field.rb:509:in `resolve_field'
/Users/mintyfresh/api/app/graphql/error_handling_instrumentation.rb:13:in `call'
/Users/mintyfresh/api/app/graphql/error_handling_instrumentation.rb:13:in `block in instrument'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/member/instrumentation.rb:80:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/field.rb:136:in `resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:321:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block (2 levels) in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:80:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:50:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:49:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:128:in `resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:85:in `each'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:284:in `resolve_value'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:278:in `resolve_value'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:213:in `continue_resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:184:in `continue_or_wait'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:154:in `block in resolve_field'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy.rb:41:in `value'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:40:in `block (2 levels) in resolve_in_place'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:39:in `each'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:39:in `each_with_index'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:39:in `block in resolve_in_place'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy.rb:41:in `value'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:81:in `deep_sync'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy/resolve.rb:29:in `resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/lazy.rb:20:in `resolve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:73:in `block in lazy_resolve_root_selection'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block (2 levels) in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:80:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:72:in `lazy_resolve_root_selection'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/execute.rb:35:in `finish_multiplex'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:88:in `run_as_multiplex'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:62:in `block (2 levels) in run_queries'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:196:in `block in instrument_and_analyze'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block (2 levels) in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:80:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `block in call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/newrelic_rpm-6.8.0.360/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:82:in `call_tracers'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/tracing.rb:66:in `trace'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema.rb:1541:in `multiplex'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/graphql-1.10.2/lib/graphql/schema.rb:1512:in `execute'
/Users/mintyfresh/api/app/controllers/api/base_graphql_controller.rb:31:in `execute_single_query'
/Users/mintyfresh/api/app/controllers/api/base_graphql_controller.rb:11:in `execute'
/Users/mintyfresh/api/app/controllers/api/v1/graphql_controller.rb:6:in `execute'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:196:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/mintyfresh/api/app/controllers/application_controller.rb:135:in `block in set_current_locale'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/i18n-1.8.2/lib/i18n.rb:313:in `with_locale'
/Users/mintyfresh/api/app/controllers/application_controller.rb:135:in `set_current_locale'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/notifications.rb:180:in `instrument'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/abstract_controller/base.rb:136:in `process'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionview-6.0.2.1/lib/action_view/rendering.rb:39:in `process'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:191:in `dispatch'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_controller/metal.rb:252:in `dispatch'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/mapper.rb:48:in `serve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/routing/route_set.rb:837:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/bullet-6.1.0/lib/bullet/rack.rb:15:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-attack-6.2.1/lib/rack/attack.rb:156:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server/middleware.rb:20:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-attack-6.2.1/lib/rack/attack.rb:170:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/deflater.rb:45:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/tempfile_reaper.rb:17:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/etag.rb:27:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/conditional_get.rb:40:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/head.rb:14:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activerecord-6.0.2.1/lib/active_record/migration.rb:567:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:38:in `call_app'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `block in call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/activesupport-6.0.2.1/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/rack/logger.rb:26:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/sprockets-rails-3.2.1/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/request_id.rb:27:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/method_override.rb:24:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/runtime.rb:24:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/static.rb:126:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-2.1.2/lib/rack/sendfile.rb:113:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/actionpack-6.0.2.1/lib/action_dispatch/middleware/host_authorization.rb:83:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/hirefire-resource-0.7.4/lib/hirefire/middleware.rb:38:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/rack-cors-1.1.0/lib/rack/cors.rb:100:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/railties-6.0.2.1/lib/rails/engine.rb:526:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/puma-4.3.3/lib/puma/configuration.rb:228:in `call'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/puma-4.3.3/lib/puma/server.rb:682:in `handle_request'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/puma-4.3.3/lib/puma/server.rb:472:in `process_client'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/puma-4.3.3/lib/puma/server.rb:328:in `block in run'
/Users/mintyfresh/.rvm/gems/ruby-2.6.5/gems/puma-4.3.3/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

</details>

**Comment by rmosolgo** [comment]
Interesting, thanks for the report! The wrapper code is usually applied here: 

https://github.com/rmosolgo/graphql-ruby/blob/8010c6243b95a9285cb3c112f388df60045e72ea/lib/graphql/schema/field.rb#L277-L281

But maybe `connection?` is returning false in this case:

https://github.com/rmosolgo/graphql-ruby/blob/8010c6243b95a9285cb3c112f388df60045e72ea/lib/graphql/schema/field.rb#L112-L129


As a work-around, you could try adding `connection: true` to the Resolver's field options: 

```ruby
class Resolvers::UserOrdersResolver < Resolvers::BaseResolver
  # ...
  def self.field_options 
    # work around https://github.com/rmosolgo/graphql-ruby/issues/2837
    super.merge(connection: true) 
  end 
end
```

I hope that helps! I'll try to take a look soon.

**Comment by rmosolgo** [comment]
Oh, I see, the handling for strings should be improved to remove `Type`, the way `graphql_name` does: 

https://github.com/rmosolgo/graphql-ruby/blob/c25a5e4a4abf94d30b7f679d9dd6eac6d8572cd9/lib/graphql/schema/member/build_type.rb#L113-L114

vs

https://github.com/rmosolgo/graphql-ruby/blob/c25a5e4a4abf94d30b7f679d9dd6eac6d8572cd9/lib/graphql/schema/member/base_dsl_methods.rb#L106-L112

**Comment by thijsnado** [comment]
This seems to also be an issue if you defined fields like:

```ruby
  field :my_collection, "Types::MyCollectionConnectionType", null: "false"
```

**Comment by rmosolgo** [comment]
Since adding `connection: true` seems to work fine, and this issue hasn't gotten much attention over the years, I'm not planning to change the behavior here. If anyone wants to improve the logic as described above, I'd welcome a PR. 

For now, here's a short script describing the work-around of adding explicit `connection: true` to the field definition when using a string to reference the connection type by name: 

```ruby 
require "bundler/inline"

gemfile do
  gem "graphql", "1.13.7"
end

class Schema < GraphQL::Schema
  class Thing < GraphQL::Schema::Object
    field :name, String
  end

  ThingConnectionType = Thing.connection_type

  class Query < GraphQL::Schema::Object
    field :things, "Schema::ThingConnectionType", null: false, connection: true

    def things
      [{ name: "A"}, { name: "B" }, { name: "C" }]
    end
  end

  query(Query)
end

pp Schema.execute("{ things { nodes { name } } }")
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"things"=>{"nodes"=>[{"name"=>"A"}, {"name"=>"B"}, {"name"=>"C"}]}}}>
```
