### ISSUE TITLE
OperationStore might be incompatible with Interpreter as of graphql-ruby 1.10.5 / graphql-pro 1.13.2

### ISSUE THREAD

**Issue by markiz** [rmosolgo/graphql-ruby#2857]
**Describe the bug**

As a part of the test suite, we're checking that adding a persisted operation works:

```ruby
      operation_store.upsert_client(client_name, client_secret)
      operation_store.add(
        body: 'query lookupPSQ($query: String) { productSearchQuery(query:$query) { query redirectUrl } }',
        client_name: client_name,
        operation_alias: operation_alias
      )
```

Previously (in graphql 1.9.x / graphql-pro 1.11), this test ran successfully. Now it fails, but only when Interpreter is enabled.

**Versions**

`graphql` version: 1.10.5
`rails` (or other framework): 6.0.2
`graphql-pro`: 1.13.2

**GraphQL schema**

```ruby
# Only including plugins here
class GraphSchema < GraphQL::Schema
  mutation(Types::RootMutationType)
  query(Types::RootQueryType)
  # GraphQL::Batch setup:
  use(GraphQL::Batch)
  # Use persistent operation store
  use(GraphQL::Pro::OperationStore)
  # Use new GraphQL interpreter (experimental)
  use(GraphQL::Execution::Interpreter)
  # New relic monitoring
  use(GraphQL::Tracing::NewRelicTracing, set_transaction_name: false)
end
```

**Expected behavior**

No errors.

**Actual behavior**

```
     RuntimeError:
       Unexpected scope type: Types::RootQueryType

     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/internal_representation/scope.rb:33:in `initialize'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/internal_representation/rewrite.rb:90:in `new'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/internal_representation/rewrite.rb:90:in `push_root_node'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/internal_representation/rewrite.rb:68:in `on_operation_definition'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/base_visitor.rb:76:in `on_operation_definition'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:79:in `public_send'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:79:in `visit_node'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:101:in `each'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:123:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/definition_dependencies.rb:38:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:79:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:26:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/fragments_are_used.rb:6:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/fragments_are_finite.rb:6:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/fragment_names_are_unique.rb:17:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/rules/no_definitions_are_present.rb:34:in `on_document'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:79:in `public_send'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:79:in `visit_node'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/language/visitor.rb:68:in `visit'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/validator.rb:42:in `block in validate'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `block in trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `block (2 levels) in call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:81:in `call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `block in call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing/new_relic_tracing.rb:45:in `block in platform_trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/newrelic_rpm-6.9.0.363/lib/new_relic/agent/method_tracer_helpers.rb:30:in `trace_execution_scoped'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing/new_relic_tracing.rb:44:in `platform_trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `block in call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-pro-1.13.2/lib/graphql/pro/operation_store/query_instrumentation.rb:19:in `trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:83:in `call_tracers'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/tracing.rb:67:in `trace'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-1.10.5/lib/graphql/static_validation/validator.rb:25:in `validate'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-pro-1.13.2/lib/graphql/pro/operation_store/validate.rb:38:in `validate'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-pro-1.13.2/lib/graphql/pro/operation_store/add_operation.rb:12:in `call'
     # /Users/mark/.rvm/gems/ruby-2.6.3@sg-graph-server/gems/graphql-pro-1.13.2/lib/graphql/pro/operation_store.rb:126:in `add'
     # ./spec/graphql/cached_query_spec.rb:21:in `block (3 levels) in <top (required)>'

```

</details>

**Comment by rmosolgo** [comment]
Huh, I _thought_ it raised a nice error in this case, but maybe not. 

In 1.10+, `Execution::Interpreter` _also_ [requires `Analysis::AST`](https://github.com/rmosolgo/graphql-ruby/blob/master/CHANGELOG.md#breaking-changes-2). Try adding this: 

```diff 
    # Use new GraphQL interpreter (experimental)
    use(GraphQL::Execution::Interpreter)
+   use(GraphQL::Analysis::AST)
```

Does that work for you? 

(If you're not ready to migrate to that analysis implementation, you can revert to graphql-ruby 1.9.x, which supports `Interpreter` with the _old_ analysis module. The reason it changed in 1.10 is because, in that latest version, it no longer builds legacy-compat objects with `.graphql_definition`.)

**Comment by markiz** [comment]
Looks like that helped indeed!
