### ISSUE TITLE
Generating schema.json with RakeTask (no Rails)

### ISSUE THREAD

**Issue by Baloicchi** [rmosolgo/graphql-ruby#2858]
Hi, I am currently trying to generate a .json of my schema. I'm not using Rails, and it appears resources for just plain Ruby are kind of scarce. I'm fairly new to this as well, so please pardon any mistakes.

Current version is `1.10.5` 

My Rakefile has something like this:

```ruby
GraphQL::RakeTask.new(
  schema_name: "Schema",
  idl_outfile: 'schema_test.graphql',
  json_outfile: 'schema_test.json')
```

When I run ``` rake graphql:schema:json --trace ``` I get something like this:

<details>
<summary>Error</summary>

```
** Invoke graphql:schema:json (first_time)
** Execute graphql:schema:json
rake aborted!
NameError: uninitialized constant Schema
/Users/baloi/.rvm/gems/ruby-2.5.1/gems/graphql-1.10.5/lib/graphql/rake_task.rb:32:in `const_get'
/Users/baloi/.rvm/gems/ruby-2.5.1/gems/graphql-1.10.5/lib/graphql/rake_task.rb:32:in `block in <class:RakeTask>'
/Users/baloi/.rvm/gems/ruby-2.5.1/gems/graphql-1.10.5/lib/graphql/rake_task.rb:104:in `write_outfile'
/Users/baloi/.rvm/gems/ruby-2.5.1/gems/graphql-1.10.5/lib/graphql/rake_task.rb:132:in `block (3 levels) in define_task'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `block in execute'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `each'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:251:in `execute'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:195:in `block in invoke_with_call_chain'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/monitor.rb:226:in `mon_synchronize'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:188:in `invoke_with_call_chain'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/task.rb:181:in `invoke'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:160:in `invoke_task'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `each'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:116:in `block in top_level'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:125:in `run_with_threads'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:110:in `top_level'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:83:in `block in run'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/lib/rake/application.rb:80:in `run'
/Users/baloi/.rvm/rubies/ruby-2.5.1/lib/ruby/gems/2.5.0/gems/rake-12.3.0/exe/rake:27:in `<top (required)>'
/Users/baloi/.rvm/rubies/ruby-2.5.1/bin/rake:23:in `load'
/Users/baloi/.rvm/rubies/ruby-2.5.1/bin/rake:23:in `<main>'
Tasks: TOP => graphql:schema:json
```
</details>

The problem definitely lies in the ```schema_name``` that I am passing. My initial assumption was the ```Schema``` class that inherits from ```GraphQL::Schema```, but it appears that this is not the case.

Any idea on what I should be passing? Please let me know if there is a need to provide any additional information.

**Comment by swalkinshaw** [comment]
> The problem definitely lies in the schema_name that I am passing. My initial assumption was the Schema class that inherits from GraphQL::Schema, but it appears that this is not the case.

That's correct. You should be passing in the *class name* of your schema (which inherits from GraphQL::Schema).

In a non-Rails project you may need to manually `require` your schema file. Rails has autoloading so it's automatically done.

**Comment by Baloicchi** [comment]
It seems that I needed to include the module in my string, so I changed the string to something like ```MyModule::Schema``` and the .json has been generated. Really appreciate the response! Will be closing the issue now.
