### ISSUE TITLE
ISO8601DateTime validation explodes when given an array

### ISSUE THREAD

**Issue by benhutton** [rmosolgo/graphql-ruby#2901]
**Describe the bug**

When invalid array input is passed into a `ISO8601DateTime` field, rather than returning a properly-handled graphql validation error, an uncaught exception occurs.

**Versions**

`graphql` version: 1.10.7
`rails` (or other framework): we're not on a framework

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
class RootQuery < Types::BaseObject
  field :foo, String, null: true do
    argument :date, GraphQL::Types::ISO8601DateTime, required: false
  end

  def foo(*args)
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
{
  foo(date: [1, 2])
}
```

```json
"Internal Server Error"
```

**Steps to reproduce**

Pass an array in where a date should be

**Expected behavior**

We should get a graphql validation error. No uncaught exception

**Actual behavior**

```
TypeError: no implicit conversion of Array into String
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/types/iso_8601_date_time.rb:53:in `match'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/types/iso_8601_date_time.rb:53:in `iso8601'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/types/iso_8601_date_time.rb:53:in `coerce_input'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/scalar_type.rb:55:in `call'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/scalar_type.rb:55:in `coerce_non_null_input'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/scalar_type.rb:72:in `validate_non_null_input'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/base_type.rb:157:in `validate_input'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:45:in `block in recursively_validate'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:73:in `maybe_raise_if_invalid'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:44:in `recursively_validate'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:15:in `block in validate'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:14:in `catch'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/literal_validator.rb:14:in `validate'
/home/ben/.rbenv/versions/2.6.5/lib/ruby/gems/2.6.0/gems/graphql-1.10.7/lib/graphql/static_validation/validation_context.rb:39:in `validate_... (warning: truncated).
```

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it should return a nice GraphQL error. 

_This_ method should check that the incoming value is a string: 

```
lib/graphql/types/iso_8601_date_time.rb:53:in `coerce_input'
```
