### ISSUE TITLE
Issues with multiple definition errors on new project

### ISSUE THREAD

**Issue by reinvanimschoot** [rmosolgo/graphql-ruby#2942]
**Describe the bug**

When I start my rails graphql api I am getting a series of `Multiple definitions for` errors.

**Versions**

`graphql` version: "~> 1.10"
`rails` (or other framework): "Rails 6.0.2.2"

**GraphQL schema**

Api schema:

```ruby
class AssuredFlowApiSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  # Opt in to the new runtime (default in future graphql-ruby versions)
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST

  # Add built-in connections for pagination
  use GraphQL::Pagination::Connections

  # Relay Object Identification:

  # Return a string UUID for `object`
  def self.id_from_object(object, _type_definition, _query_ctx)
    GraphQL::Schema::UniqueWithinType.encode(object.class.name, object.id)
  end

  # Given a string UUID, find the object
  def self.object_from_id(_id, _query_ctx)
    return unless node_id.present?

    record_class, record_id = GraphQL::Schema::UniqueWithinType.decode(node_id)

    record_class = record_class.safe_constantize

    record_class&.find_by id: record_id
  end

  # Object Resolution
  def self.resolve_type(_type, _obj, _ctx)
    type_class = "::Types::#{object.class}Type".safe_constantize

    raise ArgumentError, "Cannot resolve type for class #{object.class.name}" unless type_class.present?

    type_class
  end
end
```

graphql controller:

```ruby

require "jwt"

class GraphqlController < ApplicationController
  # If accessing from outside this domain, nullify the session
  # This allows for outside API access while preventing CSRF attacks,
  # but you'll have to authenticate your user separately
  # protect_from_forgery with: :null_session

  def execute
    variables = ensure_hash(params[:variables])
    query = params[:query]
    operation_name = params[:operationName]

    current_user = get_current_user_from_headers

    context = {
      current_user: current_user
    }
    result = AssuredFlowApiSchema.execute(query, variables: variables, context: context, operation_name: operation_name)
    render json: result
  rescue StandardError => e
    raise e unless Rails.env.development?

    handle_error_in_development e
  end

  private

  # Handle form data, JSON body, or a blank value
  def ensure_hash(ambiguous_param)
    case ambiguous_param
    when String
      if ambiguous_param.present?
        ensure_hash(JSON.parse(ambiguous_param))
      else
        {}
      end
    when Hash, ActionController::Parameters
      ambiguous_param
    when nil
      {}
    else
      raise ArgumentError, "Unexpected parameter: #{ambiguous_param}"
    end
  end

  def handle_error_in_development(e)
    logger.error e.message
    logger.error e.backtrace.join("\n")

    render json: { errors: [{ message: e.message, backtrace: e.backtrace }], data: {} }, status: 500
  end

  def get_authorization_header
    request.headers["Authorization"] || nil
  end

  def decode_authorization_token
    authorization_header = get_authorization_header

    return nil unless authorization_header

    begin
      token = authorization_header.split(" ")[1]
      payload, = JWT.decode token, "mytemporarysecret", true, { algorithm: "HS256" }
      payload
    rescue StandardError
      nil
    end
  end

  def get_current_user_from_headers
    payload = decode_authorization_token

    return nil unless payload

    begin
      User.find(payload["user_id"])
    rescue StandardError
      nil
    end
  end
end
```

**Steps to reproduce**

After having done `graphql:install --relay` and making use of the built-in graphql generators, I am now facing an issue where for almost every mutation I add, I get the following error:

```Multiple definitions for `UpdateModelPayload`. Previously found #<Class:0x00007fd0ad6faf60> (Class), then found #<Class:0x00007fd0ad8763f8> (Class) at Mutation.updateModelType```

The strange thing is that I haven't explicitly defined a Payload type for any model anywhere.
It feels as though everything is being aded twice?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
Multiple definitions for `UpdateValvePayload`. Previously found #<Class:0x00007fd0ad6faf60> (Class), then found #<Class:0x00007fd0ad8763f8> (Class) at Mutation.updateValveType
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1841:in `add_type'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1863:in `block in add_type'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1859:in `each'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1859:in `add_type'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1723:in `block in add_type_and_traverse'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1723:in `each'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1723:in `add_type_and_traverse'
/Users/rein/.gem/ruby/2.6.3/gems/graphql-1.10.8/lib/graphql/schema.rb:1064:in `mutation'
/Users/rein/code/assured-flow-api/app/graphql/assured_flow_api_schema.rb:2:in `<class:AssuredFlowApiSchema>'
/Users/rein/code/assured-flow-api/app/graphql/assured_flow_api_schema.rb:1:in `<main>'
/Users/rein/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/rein/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/rein/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/rein/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/rein/.gem/ruby/2.6.3/gems/bootsnap-1.4.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/rein/.gem/ruby/2.6.3/gems/zeitwerk-2.3.0/lib/zeitwerk/kernel.rb:16:in `require'
/Users/rein/code/assured-flow-api/app/controllers/graphql_controller.rb:19:in `execute'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/abstract_controller/base.rb:196:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/rendering.rb:30:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
/Users/rein/.gem/ruby/2.6.3/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/abstract_controller/callbacks.rb:41:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/rescue.rb:22:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
/Users/rein/.gem/ruby/2.6.3/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `block in instrument'
/Users/rein/.gem/ruby/2.6.3/gems/activesupport-6.0.2.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/Users/rein/.gem/ruby/2.6.3/gems/activesupport-6.0.2.2/lib/active_support/notifications.rb:180:in `instrument'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/activerecord-6.0.2.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/abstract_controller/base.rb:136:in `process'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal.rb:191:in `dispatch'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_controller/metal.rb:252:in `dispatch'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:51:in `dispatch'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb:49:in `block in serve'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb:32:in `each'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/journey/router.rb:32:in `serve'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/routing/route_set.rb:837:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/rack-2.2.2/lib/rack/etag.rb:27:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/rack-2.2.2/lib/rack/conditional_get.rb:40:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/rack-2.2.2/lib/rack/head.rb:12:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/activerecord-6.0.2.2/lib/active_record/migration.rb:567:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
/Users/rein/.gem/ruby/2.6.3/gems/activesupport-6.0.2.2/lib/active_support/callbacks.rb:101:in `run_callbacks'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
/Users/rein/.gem/ruby/2.6.3/gems/actionpack-6.0.2.2/lib/action_dispatch/middleware/executor.rb:14:in `call'
```

</details>

**Additional context**

If there is anything else you'd like me to provide, let me know!

**Comment by dznicol** [comment]
I am seeing very similar behaviour. I appreciate this issue is closed but do you have any advice on what to look for to resolve this error?

**Comment by bubbaspaarx** [comment]
Also experiencing this behaviour. It's resolved with a restart of our local server but any change we make, even if it's not graphql related will cause this type of error without restarting the server. as soon as the server is restarted it works as intended
