### ISSUE TITLE
Duplicate type definition found ...

### ISSUE THREAD

**Issue by breathe** [rmosolgo/graphql-ruby#2970]
**Describe the bug**

I've started (randomly) getting errors like this in our bug catcher -- it happens only _sometimes_.  We've been using rails-graphql for awhile without ever encountering this issue -- and it started a few days ago.

I updated from graphql-ruby 1.10.2 to 1.10.10 -- and issue has occurred in both versions.

![image](https://user-images.githubusercontent.com/434034/83341722-e8f59900-a2a3-11ea-9b02-78aa382a6e6f.png)

![image](https://user-images.githubusercontent.com/434034/83341496-69ff6100-a2a1-11ea-809d-16a3acb61176.png)

```
Duplicate type definition found for name 'Location' at 'Field Query.location's return type' (Types::LocationType, Types::LocationType)
```

**Versions**

`graphql` version:  `graphql (1.10.10)`
`rails` (or other framework): `rails (4.2.8)
other applicable versions (`graphql-batch`, etc)

```
    apollo_upload_server (2.0.0.beta.3)
      graphql (>= 1.8)
      rails (>= 4.2)
```

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

Not using intertpreter

production.rb config related to rails autoloader ...

```
    config.cache_classes = true

    # Eager load code on boot. This eager loads most of Rails and
    # your application in memory, allowing both threaded web servers
    # and those relying on copy on write to perform better.
    # Rake tasks automatically ignore this option for performance.
    config.eager_load = true

    # Full error reports are disabled and caching is turned on.
    config.consider_all_requests_local = false
    config.action_controller.perform_caching = true
```

Graphql Type where `Query.location` is defined ...

```ruby

class Types::QueryType < Types::BaseObject
  # Add root-level fields here.
  # They will be entry points for queries on your schema.
  field :brand, Types::BrandType, null: true do
    argument :id, ID, required: true, description: "snip"
    argument :id_type, Types::IdTypesEnum, required: true, description: "snip"
  end

  field :location, Types::LocationType, null: false do
    argument :id, ID, required: true, description: "snip"
  end

  field :locations, [Types::LocationType], null: false do
    argument :ids, [ID], required: true, description: "snip"
  end

  field :search_locations, Types::SearchResultContainerType, null: false do
    argument :search_term, String, required: true, description: "snip"
    argument :page, Int, required: false, description: "snip"
  end

  field :search_sync_histories, Types::SearchSyncHistoryContainerType, null: false do
    argument :search_query, Inputs::SearchQueryInput, required: true, description: "snip"
    argument :page, Int, required: true, description: "snip"
  end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query UseLocationQuery($id: ID!) {
  location(id: $id) {
    ...AllLocationInfoFragment
    __typename
  }
}

fragment AllLocationInfoFragment on Location {
  id
  name
  posId
  isDirty
  blockMmv1Push
  closureDaysRemaining
  defaultItemTaxRate
  defaultSelectedPriceSource
  priceElevationPercentage
  mappingTableForPriceSyncing
  availableFetchSources
  availablePushTargets
  syncState {
    orderSource
    operationState
    operationOutputs
    subOperations {
      operationName
      operationState
      operationOutputs
      __typename
    }
    __typename
  }
  syncHistory {
    requestedBy
    scheduledDate
    orderSource
    operationType
    operationState
    operationOutputs
    pushedLocationStateRevision
    subOperations {
      operationName
      operationState
      operationOutputs
      __typename
    }
    __typename
  }
  orderSources {
    id
    name
    displayName
    isLive
    closureDaysRemaining
    __typename
  }
  deliverySchedule {
    ref
    menuName
    menuHours {
      day
      closeAllDay
      timePeriods {
        open
        close
        __typename
      }
      __typename
    }
    __typename
  }
  __typename
}
```

**Steps to reproduce**

It just happens randomly ... if i hit the endpoint with above query -- the vast majority of requests succeed ... Not really sure what could be going on ...
**Expected behavior**

I wouldn't get this error sporadically ...

**Actual behavior**

I get this error sporadically ...

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
RuntimeError
mmv2:graphql operation_name: "UseLocationQuery"
Duplicate type definition found for name 'Location' at 'Field Query.location's return type' (Types::LocationType, Types::LocationType)
May 30th, 2020, 17:59:21 MDT

STACKTRACE

vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:172:in `visit': Duplicate type definition found for name 'Location' at 'Field Query.location's return type' (Types::LocationType, Types::LocationType) (RuntimeError)
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:209:in `visit_field_on_type'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:189:in `block in visit_fields'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:188:in `each'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:188:in `visit_fields'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:147:in `visit'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:128:in `block in visit'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:128:in `each'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:128:in `visit'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/traversal.rb:47:in `initialize'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:1932:in `new'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:1932:in `rebuild_artifacts'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:1001:in `to_graphql'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema/member/accepts_definition.rb:120:in `to_graphql'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:910:in `graphql_definition'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:1631:in `multiplex'
    from vendor/bundle/ruby/2.4.0/gems/graphql-1.10.10/lib/graphql/schema.rb:1604:in `execute'
    from app/controllers/token_api/graphql_controller.rb:64:in `execute'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:198:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rendering.rb:10:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:117:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
    from vendor/bundle/ruby/2.4.0/gems/react-rails-2.5.0/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/core_ext/time/zones.rb:48:in `use_zone'
    from vendor/bundle/ruby/2.4.0/gems/browser-timezone-rails-1.0.1/lib/browser-timezone-rails.rb:15:in `set_time_zone'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:432:in `block in make_lambda'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:312:in `block in halting'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:497:in `block in around'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:505:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/callbacks.rb:19:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rescue.rb:29:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `block in instrument'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/notifications.rb:164:in `instrument'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/abstract_controller/base.rb:137:in `process'
    from vendor/bundle/ruby/2.4.0/gems/actionview-4.2.8/lib/action_view/rendering.rb:30:in `process'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:196:in `dispatch'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_controller/metal.rb:237:in `block in action'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:43:in `serve'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:43:in `block in serve'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `each'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/journey/router.rb:30:in `serve'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/routing/route_set.rb:817:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/apollo_upload_server-2.0.0.beta.3/lib/apollo_upload_server/middleware.rb:20:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/rack/agent_hooks.rb:30:in `traced_call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/rack/browser_monitoring.rb:32:in `traced_call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
    from vendor/bundle/ruby/2.4.0/gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/etag.rb:24:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/conditionalget.rb:38:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/head.rb:13:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from lib/conditionally_disable_deep_munge_middleware.rb:30:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/flash.rb:260:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:225:in `context'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/session/abstract/id.rb:220:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/cookies.rb:560:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/query_cache.rb:36:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activerecord-4.2.8/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/callbacks.rb:81:in `run_callbacks'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/bugsnag-6.11.1/lib/bugsnag/integrations/rack.rb:46:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:38:in `call_app'
    from vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `block in call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `block in tagged'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:26:in `tagged'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/tagged_logging.rb:68:in `tagged'
    from vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/rack/logger.rb:20:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/request_store-1.4.1/lib/request_store/middleware.rb:19:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/request_id.rb:21:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/methodoverride.rb:22:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/runtime.rb:18:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/activesupport-4.2.8/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/actionpack-4.2.8/lib/action_dispatch/middleware/static.rb:120:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-1.6.11/lib/rack/sendfile.rb:113:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/rack-cors-0.4.1/lib/rack/cors.rb:81:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/hirefire-resource-0.7.2/lib/hirefire/middleware.rb:38:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/engine.rb:518:in `call'
    from vendor/bundle/ruby/2.4.0/gems/railties-4.2.8/lib/rails/application.rb:165:in `call'
    from vendor/bundle/ruby/2.4.0/gems/newrelic_rpm-6.4.0.356/lib/new_relic/agent/instrumentation/middleware_tracing.rb:99:in `call'
    from vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/configuration.rb:228:in `call'
    from vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:657:in `handle_request'
    from vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:467:in `process_client'
    from vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/server.rb:328:in `block in run'
    from vendor/bundle/ruby/2.4.0/gems/puma-4.0.1/lib/puma/thread_pool.rb:135:in `block in spawn_thread'


```

</details>

**Additional context**

I am pretty new to ruby -- learned by doing on an existing large rails application -- and am not at all an expert with the rails auto-loading magic ...  All the types are defined using pattern like in the above -- using syntax like

```
class Types::LocationType < Types::BaseObject
...
end
```

rather than:

```
module Types
  class LocationType < Types::BaseObject
  ...
  end
end
```

And similarly:

```
class Mutations::UpdateLocation < Mutations::BaseMutation
...
end
```

And

```
class Inputs::LocationInput < Types::BaseInputObject
...
end
```

With a directory structure like this 

I honestly have no idea if anything about the directory structure could somehow be related to the issue (the level of loathing i have for the rails autoloading mechanism is extremely high ...) ...

```
➤ tree app/graphql/
app/graphql/
├── gql_location/
            ... service implementation stuff - no rails-graphql classes
├── gql_location.rb
├── inputs
│   ├── location_input.rb
      ....
├── my_application_schema.rb
├── mutations
│   ├── base_mutation.rb
│   ├── update_location.rb
      ....
└── types
    ├── base_argument.rb
    ├── base_enum.rb
    ├── base_field.rb
    ├── base_input_object.rb
    ├── base_interface.rb
    ├── base_object.rb
    ├── base_scalar.rb
    ├── base_union.rb
    ├── brand_type.rb
    ├── location_type.rb
     ...
```

Thanks and please let me know if I can supply any additional information to help understand this ...

**Comment by rmosolgo** [comment]
Hi, sorry for the trouble and thanks for the detailed report. I have two suggestions: 

1. Since you're already on 1.10, I recommend the new runtime modules which were implemented to address this problem (https://github.com/rmosolgo/graphql-ruby/issues/1505#issuecomment-585299090)
2. Or, if that's not an option, try the workaround here: https://github.com/rmosolgo/graphql-ruby/issues/1505#issuecomment-538442074

If you adopt one of those and run into this problem again, please let me know!
