### ISSUE TITLE
"uninitialized constant GraphQL::StaticValidation::Message" Error. Bug in GraphQL version comparison

### ISSUE THREAD

**Issue by kryptonat** [rmosolgo/graphql-ruby#3013]
**Describe the bug**

I get the following error

```
NameError:
  uninitialized constant GraphQL::StaticValidation::Message
```

Error can be traced back to graphql-pro source code for `graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb`

```
module GraphQL
  module Pro
    class Repository
      class OperationsMustBeUniquelyNamed
        if GraphQL::VERSION > "1.9"
          include GraphQL::StaticValidation::Error::ErrorHelper
          ERROR_METHOD = :error
        else
          include GraphQL::StaticValidation::Message::MessageHelper
          ERROR_METHOD = :message
        end
...
```

Version comparisons done via string comparison is a bug.

```
irb
irb(main):001:0> "1.10.9" > "1.9"
=> false
```

**Versions**

`graphql` version: 1.10.9
`graphql-pro` version: 1.9.9

**Steps to reproduce**

Simply requiring `graphql-pro` gem gives an error

```
require 'graphql-pro'
```

**Expected behavior**

graphql-pro uses `GraphQL::StaticValidation::Error::ErrorHelper` instead of the deprecated `GraphQL::StaticValidation::Message::MessageHelper` class

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

```
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb:10:in `<class:OperationsMustBeUniquelyNamed>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb:5:in `<class:Repository>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb:4:in `<module:Pro>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb:3:in `<module:GraphQL>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository/operations_must_be_uniquely_named.rb:2:in `<top (required)>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository.rb:3:in `require'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro/repository.rb:3:in `<top (required)>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro.rb:14:in `require'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql/pro.rb:14:in `<top (required)>'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql-pro.rb:2:in `require'
# /Users/natalie.wong/.gem/ruby/2.6.6/gems/graphql-pro-1.9.9/lib/graphql-pro.rb:2:in `<top (required)>'
```

**Comment by rmosolgo** [comment]
Sorry for the hangup! This check was improved back in graphql-pro v1.11.0. Can you upgrade to that version and see if it fixes it for you? 

If you're not able to upgrade for some reason, please let me know. Either we'll find a solution, or I'll patch 1.9.9 and cut a new release.

**Comment by rmosolgo** [comment]
Let me know if you have trouble after updating!
