### ISSUE TITLE
Create Mutation With Array values - "undefined method `to_i' for [1, 2]:Array\nDid you mean?  to_s\n 

### ISSUE THREAD

**Issue by dmc2015** [rmosolgo/graphql-ruby#3042]
**Describe the bug**

I am trying to do a mutation that creates, but also has an array that contains ids.

With this current setup, I get this error.

```
{
  "errors": [
    {
      "message": "undefined method `to_i' for [1, 2]:Array\nDid you mean?  to_s\n               to_a\n               to_h",
```

I understand that it doesn't like my `[Integer]` in my mutation but I am not sure what exactly it wants.

I tried to change it to `enum`, but I got this error:

```
{
  "errors": [
    {
      "message": "uninitialized constant Mutations::CreateProduct::Enum",
```
**Versions**

graphql (1.11.1)
rails (6.0.3.2)

**GraphQL schema**

```ruby
module Types
  class ProductType < Types::BaseObject
    field :id, ID, null: false
    field :name, String, null: true
    field :rating, Integer, null: true
    field :industry_ids, Integer, null: true
    field :tag_ids, Integer, null: true
    field :submitted_by, Integer, null: true
    field :confirmed, Boolean, null: true
    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
    field :updated_at, GraphQL::Types::ISO8601DateTime, null: false
    field :company_id, Integer, null: true
  end
end
```

**GraphQL Mutation**
```ruby
module Mutations
  class CreateProduct < BaseMutation
    argument :name, String, required: true
    argument :submitted_by, Integer, required: true
    argument :industry_ids, [Integer], required: false
    argument :tag_ids, [Integer], required: false
    argument :confirmed, Boolean, required: false
    argument :company_id, Integer, required: true

    field :product, Types::ProductType, null: true
    field :errors, [String], null: false


    def resolve(name:, submitted_by:, industry_ids:, tag_ids:, confirmed: false, company_id:)
      product = Product.create({name: name, submitted_by: submitted_by, industry_ids: industry_ids, tag_ids: tag_ids, confirmed: confirmed, company_id: company_id})
      binding.pry
      if product.persisted?
        { product: product, errors: [] }
      else
        GraphQL::ExecutionError.new(user.errors.full_messages.join(','))
      end

    end
  end
end
```

Mutation Request
```
mutation CreateProduct {
  createProduct (input: {
    name: "Don",
    submittedBy: 1,
    industryIds: [1,2],
    tagIds: [1,2],
    confirmed: false,
    companyId: 1,
    # industries: [{id: 11, name: "peta", company_id: 1, product_carrier_id: 2, product_id: 3}]
  }) {
    product {
      name
      id
      industryIds
      tagIds
    }
    errors
  }
}
```

It seems like the root of the error is coming from here:

`https://github.com/rmosolgo/graphql-ruby/blob/a1df05cf467aefc97d96ef4990b917e861807a11/lib/graphql/execution/interpreter/runtime.rb#L301`

**Comment by rmosolgo** [comment]
Did the original error contain more of the backtrace? If so, could you add it in a comment or update the original post to include it?

**Comment by dmc2015** [comment]
@rmosolgo 

Full log:

```
{
  "errors": [
    {
      "message": "undefined method `to_i' for [1, 2]:Array\nDid you mean?  to_s\n               to_a\n               to_h",
      "backtrace": [
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/types/int.rb:17:in `coerce_result'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:304:in `continue_field'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:236:in `block (4 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:384:in `resolve_with_directives'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:219:in `block (2 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `each'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:336:in `block in continue_field'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:331:in `continue_field'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:236:in `block (4 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:384:in `resolve_with_directives'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:219:in `block (2 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `each'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:336:in `block in continue_field'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:331:in `continue_field'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:236:in `block (4 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:384:in `resolve_with_directives'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:219:in `block (2 levels) in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:459:in `after_lazy'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:177:in `block in evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `each'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:124:in `evaluate_selections'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter/runtime.rb:60:in `run_eager'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/tracing.rb:66:in `trace'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter.rb:72:in `evaluate'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/interpreter.rb:45:in `begin_query'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:112:in `begin_query'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:82:in `map'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/tracing.rb:66:in `trace'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:58:in `run_queries'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/execution/multiplex.rb:48:in `run_all'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/schema.rb:1642:in `multiplex'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/graphql-1.11.1/lib/graphql/schema.rb:1613:in `execute'",
        "/Users/donmclamb/dev/rails/your_cause/app/controllers/graphql_controller.rb:15:in `execute'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:195:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rendering.rb:30:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:135:in `run_callbacks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/abstract_controller/callbacks.rb:41:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/rescue.rb:22:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `block in instrument'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/notifications.rb:180:in `instrument'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-6.0.3.2/lib/active_record/railties/controller_runtime.rb:27:in `process_action'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/abstract_controller/base.rb:136:in `process'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:190:in `dispatch'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_controller/metal.rb:254:in `dispatch'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:33:in `serve'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:49:in `block in serve'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `each'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/journey/router.rb:32:in `serve'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/routing/route_set.rb:834:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:36:in `block in call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `catch'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/warden-1.2.8/lib/warden/manager.rb:34:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activerecord-6.0.3.2/lib/active_record/migration.rb:567:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:101:in `run_callbacks'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:37:in `call_app'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `block in call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/rack/logger.rb:26:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/activesupport-6.0.3.2/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/executor.rb:14:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/static.rb:126:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/actionpack-6.0.3.2/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/railties-6.0.3.2/lib/rails/engine.rb:527:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'",
        "/Users/donmclamb/.rbenv/versions/2.5.0/lib/ruby/gems/2.5.0/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"
      ]
    }
  ],
  "data": {}
}****
```

**Comment by rmosolgo** [comment]
Thanks for sharing that! I don't see anything that looks wrong in the code or the backtrace. I tried to replicate with this script: 

<detail>
<summary>array_test.rb</summary>
<p>
```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.11.1"
end

class ProductType < GraphQL::Schema::Object
  field :name, String, null: false
  field :id, Integer, null: false
  field :industry_ids, [Integer], null: false
  field :tag_ids, [Integer], null: false
end

class CreateProduct < GraphQL::Schema::RelayClassicMutation
  argument :name, String, required: true
  argument :submitted_by, Integer, required: true
  argument :industry_ids, [Integer], required: false
  argument :tag_ids, [Integer], required: false
  argument :confirmed, Boolean, required: false
  argument :company_id, Integer, required: true

  field :product, ProductType, null: true
  field :errors, [String], null: false


  def resolve(name:, submitted_by:, industry_ids:, tag_ids:, confirmed: false, company_id:)
    product = {id: 1, name: name, submitted_by: submitted_by, industry_ids: industry_ids, tag_ids: tag_ids, confirmed: confirmed, company_id: company_id}
    { product: product, errors: [] }
  end
end

class Query < GraphQL::Schema::Object
  field :noop, Boolean, null: true
end

class Mutation < GraphQL::Schema::Object
  field :createProduct, mutation: CreateProduct
end

class ArrayTestSchema < GraphQL::Schema
  query(Query)
  mutation(::Mutation)

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
end

pp ArrayTestSchema.execute <<-GRAPHQL
mutation CreateProduct {
  createProduct (input: {
    name: "Don",
    submittedBy: 1,
    industryIds: [1,2],
    tagIds: [1,2],
    confirmed: false,
    companyId: 1,
    # industries: [{id: 11, name: "peta", company_id: 1, product_carrier_id: 2, product_id: 3}]
  }) {
    product {
      name
      id
      industryIds
      tagIds
    }
    errors
  }
}
GRAPHQL
```
</p>
</detail>

But it works fine for me: 

```
$ ruby array_test.rb
#<GraphQL::Query::Result @query=... @to_h={"data"=>{"createProduct"=>{"product"=>{"name"=>"Don", "id"=>1, "industryIds"=>[1, 2], "tagIds"=>[1, 2]}, "errors"=>[]}}}>
```

What happens when you run that example script? Does it work for you? 

Do you see any differences be

----- 

Aha! 

It's the object type. Update your field configurations like this: 

```diff
-    field :industry_ids, Integer, null: true
+    field :industry_ids, [Integer], null: true
-    field :tag_ids, Integer, null: true
+    field :tag_ids, [Integer], null: true
```

The mutation returned an object whose `#tag_ids` method returned an array, but the GraphQL type was configured to expect an integer there. 

Does that fix it for you?

**Comment by dmc2015** [comment]
@rmosolgo Yeah, that was it I set it right for the mutation but I forgot to change it for the `Type`

Thanks!
