### ISSUE TITLE
GraphQL::Schema::Subscription::NoUpdateError

### ISSUE THREAD

**Issue by durcak** [rmosolgo/graphql-ruby#3044]
**Describe the bug**

I am using graphql subscriptions with lots `:not_update` calls in resolvers and in my datadog logs I see lots of errors:
`GraphQL::Schema::Subscription::NoUpdateError`

**Versions**

`graphql` version: 1.10.13
`rails`: 6.0.3.2

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
class Product < GraphQL::Schema::Object
  field :id, ID, null: false, hash_key: :id
  # …
end

class ApplicationSchema < GraphQL::Schema
  query Types::RootQueryType
  mutation Mutations::RootMutation
  subscription Types::RootSubscriptionType

  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Subscriptions::ActionCableSubscriptions
  use GraphQL::Backtrace
  use GraphQL::Batch
  use GraphQL::Cache
  use GraphQL::Execution::Errors

  max_depth Constants::GraphqlMaxDepth.call.result
  # max_complexity Constants::GraphqlMaxComplexity.call.result

  rescue_from Pundit::NotAuthorizedError do |exception, _object, _arguments, _context|
    log_exception(exception, false)
    graphql_error(I18n.t('security.forbidden.message'), 403)
  end

  rescue_from FindCurrentUser::UserNotExistError do |exception, _object, _arguments, _context|
    log_exception(exception, false)
    graphql_error(I18n.t('security.not_authorized.message'), 401)
  end

  rescue_from ActiveRecord::RecordInvalid do |exception, _object, arguments, _context|
    handle_subject_errors(exception&.record, exception&.record&.errors, arguments, exception)
  end

  rescue_from ActiveRecord::RecordNotFound do |exception, _object, arguments, _context|
    handle_subject_errors(nil, nil, arguments, exception)
  end

  rescue_from ActiveRecord::RecordNotDestroyed do |exception, _object, arguments, _context|
    handle_subject_errors(exception&.record, exception&.record&.errors, arguments, exception)
  end

  rescue_from Errors::ServiceError do |exception, _object, arguments, _context|
    handle_subject_errors(exception&.subject, exception&.errors, arguments, exception)
  end

  rescue_from Stripe::CardError do |exception, _object, arguments, _context|
    handle_subject_errors(nil, nil, arguments, exception)
  end

  graphql_definition
end
```
**Steps to reproduce**

Return `:no_ update` in subscription `update` method.

**Expected behavior**

There should be no error in logs.

**Actual behavior**

No rescue from raised error.

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
GraphQL::Schema::Subscription::NoUpdateError: GraphQL::Schema::Subscription::NoUpdateError
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/subscription.rb:68:in `resolve_update'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/subscription.rb:42:in `public_send'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/subscription.rb:42:in `resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/resolver.rb:95:in `public_send'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/resolver.rb:95:in `block (3 levels) in resolve_with_support'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema.rb:112:in `after_lazy'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/resolver.rb:83:in `block (2 levels) in resolve_with_support'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema.rb:112:in `after_lazy'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/resolver.rb:76:in `block in resolve_with_support'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema.rb:112:in `after_lazy'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/resolver.rb:65:in `resolve_with_support'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:577:in `public_send'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:577:in `block (2 levels) in resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:742:in `block in with_extensions'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:761:in `block (2 levels) in run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:761:in `block (2 levels) in run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:764:in `run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:761:in `block in run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field_extension.rb:50:in `resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:759:in `run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:761:in `block in run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field_extension.rb:50:in `resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:759:in `run_extensions_before_resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:741:in `with_extensions'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:562:in `block in resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema.rb:112:in `after_lazy'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/schema/field.rb:559:in `resolve'
/app/vendor/ruby/2.7.0/bundler/gems/graphql-pundit-26e2cf265954/lib/graphql-pundit/scope.rb:37:in `resolve'
/app/vendor/ruby/2.7.0/bundler/gems/graphql-pundit-26e2cf265954/lib/graphql-pundit/authorization.rb:44:in `block in resolve'
/app/vendor/ruby/2.7.0/bundler/gems/graphql-pundit-26e2cf265954/lib/graphql-pundit/authorization.rb:52:in `resolve_helper'
/app/vendor/ruby/2.7.0/bundler/gems/graphql-pundit-26e2cf265954/lib/graphql-pundit/authorization.rb:44:in `resolve'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/execution/interpreter/runtime.rb:224:in `block (5 levels) in evaluate_selections'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:82:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:84:in `block in call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing/platform_tracing.rb:50:in `block in trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing/data_dog_tracing.rb:37:in `block in platform_trace'
/app/vendor/ruby/2.7.0/gems/ddtrace-0.38.0/lib/ddtrace/tracer.rb:283:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing/data_dog_tracing.rb:18:in `platform_trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing/platform_tracing.rb:49:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:84:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:84:in `block in call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/backtrace/tracer.rb:45:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:84:in `call_tracers'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/tracing.rb:68:in `trace'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/execution/interpreter/runtime.rb:223:in `block (4 levels) in evaluate_selections'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/query.rb:354:in `block in with_error_handling'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/execution/errors.rb:41:in `with_error_handling'
/app/vendor/ruby/2.7.0/gems/graphql-1.10.13/lib/graphql/query.rb:353:in `with_error_h
```

</details>

**Comment by rmosolgo** [comment]
Was that the full error backtrace? It looks like it was truncated, since the last line ends with 
`with_error_h` instead of `with_error_handling'`. 

I'd love to see the rest of the backtrace if you can share it. I expect to see either a `Schema.execute` call or a `Subscriptions#trigger` call, which begins the GraphQL execution. Those parts of the backtrace will show whether the expected `rescue` was engaged or not. Here's the rescue I'm looking for: 

https://github.com/rmosolgo/graphql-ruby/blob/a1df05cf467aefc97d96ef4990b917e861807a11/lib/graphql/subscriptions.rb#L120-L122

**Comment by rmosolgo** [comment]
Just another ping here -- is there anything more in that backtrace?

**Comment by durcak** [comment]
Hi, I couldn't get rest of the backtrace from datadog, But I think, that could be datadog tracer bug, because errors are only in a graphql AMP service and not in logs. So it is weird.
