### ISSUE TITLE
NameError: uninitialized constant GraphQL::Relay::GlobalIdResolve

### ISSUE THREAD

**Issue by kleverigheid** [rmosolgo/graphql-ruby#307]
I followed the instructions in the readme and got this error when tried to create schema:
```ruby
Schema = GraphQL::Schema.define do
  query QueryType
  max_depth 8
end
```

```
NameError: uninitialized constant GraphQL::Relay::GlobalIdResolve
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:147:in `block (3 levels) in <module:Rules>'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:147:in `any?'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:147:in `block (2 levels) in <module:Rules>'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:147:in `any?'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:147:in `block in <module:Rules>'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:18:in `block in validate'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:18:in `each'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:18:in `reduce'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema/validation.rb:18:in `validate'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/schema.rb:115:in `define'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/graphql-0.19.2/lib/graphql/define/instance_definable.rb:124:in `define'
	from (irb):2
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console.rb:65:in `start'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/console_helper.rb:9:in `start'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:78:in `console'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands/commands_tasks.rb:49:in `run_command!'
	from /Users/kleverigheid/.rvm/gems/ruby-2.3.1/gems/railties-5.0.0.1/lib/rails/commands.rb:18:in `<top (required)>'
	from /Users/kleverigheid/Developer/GitHub/blog/bin/rails:9:in `<top (required)>'
	from /Users/kleverigheid/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /Users/kleverigheid/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from -e:1:in `<main>'
```

##### post_type.rb
```ruby
PostType = GraphQL::ObjectType.define do
  name 'Post'
  description 'A blog post'

  field :id, !types.ID
  field :title, !types.String
  field :content, !types.String
  field :author_id, !types.ID
end
```

##### query_type.rb
```ruby
QueryType = GraphQL::ObjectType.define do
  name 'Query'
  description 'The query root of this schema'

  field :post do
    type PostType
    argument :id, !types.ID
    resolve -> (obj, args, ctx) {
      Post.find(args['id'])
    }
  end
end
```

##### Gemfile
```ruby
source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.0', '>= 5.0.0.1'
# Use postgresql as the database for Active Record
gem 'pg', '~> 0.18'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
# gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

gem 'faker'
gem 'graphql'
gem 'graphql-relay'
```

**Comment by rmosolgo** [comment]
Could you remove `gem "graphql-relay"` from your Gemfile and try again? That gem is built into `graphql` in recent versions (since 0.18, I think)

**Comment by kleverigheid** [comment]
It works. But what if I need to use `graphql-relay` gem?

**Comment by rmosolgo** [comment]
> use `graphql-relay` 

As described on [its homepage](https://github.com/rmosolgo/graphql-relay-ruby), everything from `graphql-relay` has been merged into `graphql`. You won't need to use it!

**Comment by kleverigheid** [comment]
Thanks!
