### ISSUE TITLE
Subscriptions trigger arbitrarily throws an ActiveRecord::RecordNotFound exception

### ISSUE THREAD

**Issue by arimendelow** [rmosolgo/graphql-ruby#3087]
**Describe the bug**

For some reason that I've been unable to identify, the subscriptions trigger arbitrarily throws an `ActiveRecord::RecordNotFound` exception, even though the object definitely exists.

**Versions**

`graphql` version: 1.11.2
`rails` (or other framework): 6.0.3.2

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
module Types
  class NotificationAlertType < GraphQL::Schema::Object
    field :notification, Types::NotificationType, null: false
    field :operation, String, null: false, description: "'CREATE' or 'DELETE'"
  end
end

module Types
  class NotificationType < GraphQL::Schema::Object
    field :notifiable, Types::NotifiableType, null: false
    field :created_at, GraphQL::Types::ISO8601DateTime, null: false
  end
end

module Types
  class NotifiableType < Types::BaseUnion
    description "Objects for which there can be notifications"
    possible_types Types::CommentType, Types::ReactionType, Types::SavedType, Types::UserRelationshipType

    def self.resolve_type(object, context)
      if object.is_a?(Comment)
        Types::CommentType
      elsif object.is_a?(Reaction)
        Types::ReactionType
      elsif object.is_a?(Saved)
        Types::SavedType
      elsif object.is_a?(UserRelationship)
        Types::UserRelationshipType
      end
    end
  end
end
```

**Steps to reproduce**

My testcase is that upon a user relationship being created, a corresponding notification being created. In the rails console, I've been running `user.follow user2` etc.

When a new relationship is created, the callback executes the following method:

```ruby
module NotificationHelpers
  def NotificationHelpers.create_notification(for_user, notifiable_id, notifiable_type, from_user)
    notification = for_user.notifications.create(
      notifiable_id: notifiable_id,
      notifiable_type: notifiable_type,
      from_user: from_user
    )

    puts "123notification: #{notification.inspect}"

    GraphqlSchema.subscriptions.trigger(
      # Field name
      'new_notification',
      # Arguments
      {},
      # Object
      {operation: "CREATE", notification: notification}
      # scope: for_user_id
    )
  end
end
```

**Expected behavior**

I expect the subscription to broadcast as expected.

**Actual behavior**

An `ActiveRecord::RecordNotFound` exception is arbitrarily thrown, even though the object exists.

You can see below that the object exists, and is logged before the trigger is called:

`123notification: #<Notification id: 694, notifiable_type: "UserRelationship", notifiable_id: 246, from_user_id: 2, for_user_id: 1, created_at: "2020-08-16 19:31:41", updated_at: "2020-08-16 19:31:41">`

`There was an exception - ActiveRecord::RecordNotFound(Couldn't find Notification with 'id'=694)`

It is seemingly arbitrary when this exception is thrown, as I can't reliably reproduce it.

From the rails console:

```ruby
2.7.1 :021 > user2.follow user
   (0.1ms)  BEGIN
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."username" ASC LIMIT $2  [["id", 2], ["LIMIT", 1]]
  UserRelationship Create (0.2ms)  INSERT INTO "user_relationships" ("follower_id", "followed_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4) RETURNING "id"  [["follower_id", 2], ["followed_id", 1], ["created_at", "2020-08-16 19:31:41.619529"], ["updated_at", "2020-08-16 19:31:41.619529"]]
  UserRelationship Load (0.1ms)  SELECT "user_relationships".* FROM "user_relationships" WHERE "user_relationships"."id" = $1 LIMIT $2  [["id", 246], ["LIMIT", 1]]
  User Load (0.2ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."username" ASC LIMIT $2  [["id", 1], ["LIMIT", 1]]
  Notification Create (0.4ms)  INSERT INTO "notifications" ("notifiable_type", "notifiable_id", "from_user_id", "for_user_id", "created_at", "updated_at") VALUES ($1, $2, $3, $4, $5, $6) RETURNING "id"  [["notifiable_type", "UserRelationship"], ["notifiable_id", 246], ["from_user_id", 2], ["for_user_id", 1], ["created_at", "2020-08-16 19:31:41.623225"], ["updated_at", "2020-08-16 19:31:41.623225"]]
123notification: #<Notification id: 694, notifiable_type: "UserRelationship", notifiable_id: 246, from_user_id: 2, for_user_id: 1, created_at: "2020-08-16 19:31:41", updated_at: "2020-08-16 19:31:41">
[ActionCable] Broadcasting to graphql-event::newNotification:: "{\"operation\":\"CREATE\",\"notification\":{\"__gid__\":\"Z2lkOi8vcmFpbHMtZGV2aXNlLWdyYXBocWwvTm90aWZpY2F0aW9uLzY5NA\"},\"__sym_keys__\":[\"operation\",\"notification\"]}"
   (3.4ms)  COMMIT
  User Load (0.2ms)  SELECT "users".* FROM "users" INNER JOIN "user_relationships" ON "users"."id" = "user_relationships"."followed_id" WHERE "user_relationships"."follower_id" = $1 ORDER BY "users"."username" ASC LIMIT $2  [["follower_id", 2], ["LIMIT", 11]]
 => #<ActiveRecord::Associations::CollectionProxy [#<User id: 1, first_name: "Ari", last_name: "Mendelow", username: "arimendelow", email: "ari@mendelow.me", jti: "0194d01d-1fe6-481b-aa23-c9c97310a054", role: "admin", created_at: "2020-08-11 00:45:36", updated_at: "2020-08-16 19:26:50", provider: nil, uid: nil, last_opened_notifications: nil>]> 
```

Backtrace:

<details>
<summary>Click to view exception backtrace</summary>

```
  Notification Load (0.2ms)  SELECT "notifications".* FROM "notifications" WHERE "notifications"."id" = $1 LIMIT $2  [["id", 694], ["LIMIT", 1]]
There was an exception - ActiveRecord::RecordNotFound(Couldn't find Notification with 'id'=694)
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/finder_methods.rb:339:in `raise_record_not_found_exception!'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/finder_methods.rb:451:in `find_one'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/finder_methods.rb:433:in `find_with_ids'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation/finder_methods.rb:69:in `find'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/querying.rb:21:in `find'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/core.rb:160:in `find'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:130:in `locate'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:155:in `block in locate'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:165:in `block in unscoped'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/scoping/default.rb:34:in `block in unscoped'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation.rb:407:in `block in scoping'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation.rb:784:in `_scoping'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/relation.rb:407:in `scoping'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.2/lib/active_record/scoping/default.rb:34:in `unscoped'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:165:in `unscoped'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:155:in `locate'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/globalid-0.4.2/lib/global_id/locator.rb:17:in `locate'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/serialize.rb:64:in `load_value'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/serialize.rb:85:in `block in load_value'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/serialize.rb:78:in `each'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/serialize.rb:78:in `load_value'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/serialize.rb:22:in `load'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/graphql-1.11.2/lib/graphql/subscriptions/action_cable_subscriptions.rb:145:in `block in setup_stream'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/channel/streams.rb:157:in `block in stream_decoder'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker.rb:59:in `block in invoke'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker.rb:41:in `block in work'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `block in with_database_connections'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `block in tag'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `block in tagged'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:28:in `tagged'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/tagged_logging.rb:80:in `tagged'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/connection/tagged_logger_proxy.rb:24:in `tag'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker/active_record_connection_management.rb:16:in `with_database_connections'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/engine.rb:62:in `block (4 levels) in <class:Engine>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/execution_wrapper.rb:88:in `wrap'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/engine.rb:57:in `block (3 levels) in <class:Engine>'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `instance_exec'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.2/lib/active_support/callbacks.rb:139:in `run_callbacks'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker.rb:40:in `work'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker.rb:58:in `invoke'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/actioncable-6.0.3.2/lib/action_cable/server/worker.rb:53:in `block in async_invoke'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:363:in `run_task'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:352:in `block (3 levels) in create_worker'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `loop'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:335:in `block (2 levels) in create_worker'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `catch'
/Users/arimendelow/.rvm/gems/ruby-2.7.1/gems/concurrent-ruby-1.1.7/lib/concurrent-ruby/concurrent/executor/ruby_thread_pool_executor.rb:334:in `block in create_worker'
```

</details>

**Comment by rmosolgo** [comment]
My first guess is that it's a race condition regarding `COMMIT`: 

```
123notification: #<Notification id: 694, notifiable_type: "UserRelationship", notifiable_id: 246, from_user_id: 2, for_user_id: 1, created_at: "2020-08-16 19:31:41", updated_at: "2020-08-16 19:31:41">
[ActionCable] Broadcasting to graphql-event::newNotification:: "{\"operation\":\"CREATE\",\"notification\":{\"__gid__\":\"Z2lkOi8vcmFpbHMtZGV2aXNlLWdyYXBocWwvTm90aWZpY2F0aW9uLzY5NA\"},\"__sym_keys__\":[\"operation\",\"notification\"]}"
   (3.4ms)  COMMIT
```

See how the ActionCable broadcast happens _before_ the database actually `COMMIT`s the transaction? 

I bet that another Ruby process tries to look up the record by ID _before_ the `COMMIT` happens, and in that case, it fails to find the new record since it wasn't committed. 

See also: https://github.com/mperham/sidekiq/issues/322, https://github.com/rmosolgo/graphql-ruby/issues/1363

If you're able to demonstrate that this keeps happening _after_ the `COMMIT` finishes, please let me know!

**Comment by arimendelow** [comment]
Yup, using `after_commit` worked! Thanks!
