### ISSUE TITLE
RuntimeError when variable type in query isn't found

### ISSUE THREAD

**Issue by dylanahsmith** [rmosolgo/graphql-ruby#309]
cc @jamesmacaulay who noticed this bug

Here is a example that reproduces the unexpected RuntimeError:

```ruby
require 'graphql'

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :test, types.String do
    argument :message, types.String
    resolve -> (obj, args, ctx) {
      "hello"
    }
  end
end

Schema = GraphQL::Schema.define do
  query QueryType
end

query = '
query Test($message: Stringy!) {
  test(message: $message)
}
'

Schema.execute(query, variables: { 'message' => 'hi' })
```

The variable message references a type Stringy that doesn't exist, which I would have expected to be a validation error.  Instead, a RuntimeError is thrown

```
/Users/dylansmith/src/graphql-ruby/lib/graphql/schema/type_map.rb:18:in `[]': No type found for 'Stringy' (RuntimeError)
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/static_validation/rules/variables_are_input_types.rb:16:in `validate_is_input_type'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/static_validation/rules/variables_are_input_types.rb:8:in `block in validate'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:73:in `block in apply_hooks'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:73:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:73:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:73:in `apply_hooks'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:61:in `begin_visit'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:51:in `visit_node'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `block in visit_node'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `visit_node'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `block in visit_node'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:53:in `visit_node'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/language/visitor.rb:45:in `visit'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/static_validation/validator.rb:33:in `validate'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:160:in `document_valid?'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:147:in `valid?'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:74:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/schema.rb:134:in `execute'
	from tmp/test.rb:24:in `<main>'
```

**Comment by rmosolgo** [comment]
😖  brb
