### ISSUE TITLE
create mutations have begin returning "nil cannot be coerced into fixnum"

### ISSUE THREAD

**Issue by Plummat** [rmosolgo/graphql-ruby#311]
happened after I updated today to .19.3, any clues?

**Comment by rmosolgo** [comment]
could you share the stack trace?

**Comment by rmosolgo** [comment]
Also your mutation definition, if you don't mind

**Comment by Plummat** [comment]
this is where it breaks:

```
 Prequalification Load (0.6ms)  SELECT "prequalifications".* FROM "prequalifications" WHERE "prequalifications"."deleted_at" IS NULL AND "prequalifications"."opportunity_id" = $1 OFFSET 0  [["opportunity_id", 88019]]
Completed 500 Internal Server Error in 15297ms (ActiveRecord: 357.3ms)

TypeError (nil can't be coerced into Fixnum):
  app/controllers/queries_controller.rb:8:in `create'
```

mutation: 
```ruby
CreatePrequalificationMutation = GraphQL::Relay::Mutation.define do
  name "CreatePrequalificationMutation"
  description "Creates a New Prequalification"

  input_field :id, !types.ID
  input_field :opportunity_id, !types.ID

  return_field :prequalification, PrequalificationType.edge_type
  return_field :opportunity, OpportunityType
  return_field :product, ProductType

  resolve -> (_object, inputs, _ctx) {
    prequalification = Prequalification.find_or_initialize_by(product_id: inputs[:id], opportunity_id: inputs[:opportunity_id])
    if prequalification.new_record?
      prequalification.save!
    end
    prequalification.move_to_interested
    connection = GraphQL::Relay::RelationConnection.new(prequalification.opportunity.prequalifications, {})
    prequal_edge = GraphQL::Relay::Edge.new(prequalification, connection)
    { prequalification: prequal_edge, opportunity: prequalification.opportunity, product: prequalification.product }
  }
end
```

**Comment by Plummat** [comment]
It also saves just fine, it occurs after the mutation returns

**Comment by rmosolgo** [comment]
Nothing else after this? 

```
TypeError (nil can't be coerced into Fixnum):
  app/controllers/queries_controller.rb:8:in `create'
```

(I'm hoping to see some lines of the gem's stack trace there)

**Comment by rmosolgo** [comment]
What version were you on before?

**Comment by Plummat** [comment]
Thats all I have... was 0.18.15 previosuly

**Comment by rmosolgo** [comment]
I suspect I somehow broke these, I've broken this before (and last time I added a test 😖)

```ruby
  connection = GraphQL::Relay::RelationConnection.new(prequalification.opportunity.prequalifications, {})
  prequal_edge = GraphQL::Relay::Edge.new(prequalification, connection)
```

**Comment by Plummat** [comment]
Perhaps. I also noticed that it it breaks only on occasion, but it's only RANGE_ADD mutations(and thusly, the connection and edge responses) that seem broken

**Comment by rmosolgo** [comment]
> only on occasion

hmmmm

does it depend on the fields in the query? (Without the stack trace, that might give an indication what triggers the failure)

**Comment by rmosolgo** [comment]
I'm trying to look for something but having trouble :( There aren't even that many commits: https://github.com/rmosolgo/graphql-ruby/commits/master/lib/graphql/relay

If you can figure out how to get the full stack trace, that would be awesome, or if you can try incrementing versions one by one, and see which one breaks it, that might help me track it down. Sorry, I'm coming up empty!

**Comment by Plummat** [comment]
```

File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/relay/relation_connection.rb" line 9 in +
2
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/relay/relation_connection.rb" line 9 in cursor_from_node
3
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/relay/edge.rb" line 14 in cursor
4
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/field/resolve.rb" line 52 in public_send
5
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/field/resolve.rb" line 52 in call
6
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/field.rb" line 162 in resolve
7
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 81 in block in get_middleware_proc_from_field_resolve
8
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/schema/middleware_chain.rb" line 24 in call
9
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/schema/rescue_middleware.rb" line 34 in call
10
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/schema/middleware_chain.rb" line 24 in call
11
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 69 in get_raw_value
12
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 18 in result
13
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 22 in block in result
14
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each
15
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each_with_object
16
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in result
17
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/value_resolution.rb" line 81 in non_null_result
18
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/value_resolution.rb" line 23 in result
19
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 46 in get_finished_value
20
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 19 in result
21
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 22 in block in result
22
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each
23
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each_with_object
24
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in result
25
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/value_resolution.rb" line 81 in non_null_result
26
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/value_resolution.rb" line 23 in result
27
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 46 in get_finished_value
28
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/field_resolution.rb" line 19 in result
29
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 22 in block in result
30
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each
31
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in each_with_object
32
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/selection_resolution.rb" line 15 in result
33
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution/operation_resolution.rb" line 19 in result
34
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/serial_execution.rb" line 25 in execute
35
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/executor.rb" line 33 in execute
36
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query/executor.rb" line 15 in result
37
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/query.rb" line 82 in result
38
File "/u/apps/shared/bundle/ruby/2.3.0/gems/graphql-0.19.2/lib/graphql/schema.rb" line 134 in execute
39
File "/u/apps/releases/20161014193717/app/controllers/queries_controller.rb", line 8 in create
```
(went back to 19.2, was still happening)

**Comment by rmosolgo** [comment]
Thanks for the stack trace, that's so helpful! I'll look as soon as i get a chance.

**Comment by rmosolgo** [comment]
It must be when you ask for the cursor of an edge who isn't a member of the connection:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/relay/relation_connection.rb#L9

**Comment by Plummat** [comment]
I'm not sure I totally follow - I am missing a connection?

**Comment by rmosolgo** [comment]
it seems like `prequalification` isn't found in `prequalification.opportunity.prequalifications`. 

Sounds crazy but nil is coming from here:

```ruby
paged_nodes_array.index(item) + 1
#                           ^. 
#                             ` Returns nil, can't add nil + 1
```

you could try something like 

```
   prequalification.move_to_interested
   prequalification.reload 
    connection = GraphQL::Relay::RelationConnection.new(prequalification.opportunity.prequalifications, {})
    prequal_edge = GraphQL::Relay::Edge.new(prequalification, connection)
```

just in case `prequalifications` was cached in memory by active record!

**Comment by Plummat** [comment]
hmm, not helping, I'll look some more

**Comment by Plummat** [comment]
Ok. figured this out. Prequalification becomes a different type in my app under certain situations(prequal->class that inherits from prequal) and then, like you said, it does not see it in cursor_from_node. I think to account for this could you map through the ids of the paged nodes array, and then find the index of the items id.

**Comment by rmosolgo** [comment]
Glad we got to the bottom of it!
