### ISSUE TITLE
proxy_to_depth': undefined method `map' for #<GraphQL::Relay::ArrayConnection:0x00007f8df3904178> (NoMethodError)

### ISSUE THREAD

**Issue by rstawarz** [rmosolgo/graphql-ruby#3222]
**Describe the bug**

Unable to access the `nodes` field on a relay connection type if the name of the type ends in "Connection", this exception is raised when it is: `proxy_to_depth': undefined method `map' for #<GraphQL::Relay::ArrayConnection:0x00007f8df3904178> (NoMethodError)`

**Versions**

`graphql` version:  1.11.6 
`rails` (or other framework): with and without rails

**GraphQL schema**

I've boiled down the schema to the bare minimum below that will recreate the problem when querying for `stuff.nodes`

```ruby
class TypeWithNameEndingInConnection < GraphQL::Schema::Object
  field :id, ID, "The ID", null: false
end

class QueryType < GraphQL::Schema::Object
  field :stuff, TypeWithNameEndingInConnection.connection_type, null: false, connection: true
  
  def stuff
    return []
  end
end

class MySchema < GraphQL::Schema
  query QueryType
end
```

**GraphQL query**

This query fails with the exception:

```graphql
{ stuff { nodes { id } } }
```
💥  undefined method `map' for #<GraphQL::Relay::ArrayConnection:0x00007fa9fb8c4428>

However this query succeeds:

```graphql
{ stuff { edges: { node { id } } } }
```

```json
{"data":{"stuff":{"edges":[]}}}
```

**Steps to reproduce**
Run this script
```
require "graphql"

class TypeWithNameEndingInConnection < GraphQL::Schema::Object
  field :id, ID, "The ID", null: false

  def id
    42
  end
end

class QueryType < GraphQL::Schema::Object
  field :stuff, TypeWithNameEndingInConnection.connection_type, null: false, connection: true

  def stuff
    return []
  end
end

class MySchema < GraphQL::Schema
  query QueryType
end

def execute(query)
  begin
    puts "*"*50
    puts "executing: #{query}"
    result = MySchema.execute(query)
    puts result.to_json
  rescue => e
    puts e
    puts e.backtrace
  end
end

execute("{ stuff { nodes { id } } }")

execute("{ stuff { edges { node { id } } } }")
```

**Expected behavior**
The result should be an empty array

**Actual behavior**

What specifically went wrong?
An Exception is raised:

```
undefined method `map' for #<GraphQL::Relay::ArrayConnection:0x00007fad3f0cc710>
Did you mean?  tap
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema/member/instrumentation.rb:98:in `proxy_to_depth'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema/member/instrumentation.rb:85:in `call'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/field.rb:136:in `resolve'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:321:in `call'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:128:in `resolve_field'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `each'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:284:in `resolve_value'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:278:in `resolve_value'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:213:in `continue_resolve_field'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:184:in `continue_or_wait'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:157:in `resolve_field'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `each'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `resolve_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:31:in `begin_query'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:112:in `begin_query'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `map'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1656:in `multiplex'
/Users/rstawarz/.rbenv/versions/2.6.4/lib/ruby/gems/2.6.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1627:in `execute'
test.rb:26:in `<main>'
```

</details>

**Additional context**

It works when you query for `edges` but not for the `nodes` shortcut field

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed writeup. I've got a fix in the works over at #3223. On that branch, I get the expected output for your script: 

```
% ruby connection_test.rb
**************************************************
executing: { stuff { nodes { id } } }
{"data":{"stuff":{"nodes":[]}}}
**************************************************
executing: { stuff { edges { node { id } } } }
{"data":{"stuff":{"edges":[]}}}
```

After it's merged, you can give it a spin with: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby"
```

And let me know if that doesn't work for you!

It'll be released to rubygems soon with v1.11.7.
