### ISSUE TITLE
Empty string defaultValues break GraphQL::Schema::Loader

### ISSUE THREAD

**Issue by bitwerx-tyler** [rmosolgo/graphql-ruby#3259]
**Describe the bug**

Calling `GraphQL::Schema::Loader.load(schema)` breaks with a parser error when the schema contains arguments that have a `defaultValue` set to an empty string. It appears that the empty string is interpolated into a query string without escaping any quotations, thus breaking when attempting to parse the query with `racc`. See additional details walking through some code.

**Versions**

`graphql`: 1.11.6
`graphql-client`: 0.16.0
`graphlient`: 0.4.0
`rails`: 6.1.0

**GraphQL schema**
Snippet from introspection query:

```json
{
  "args": [
    {
      "defaultValue": "",
      "description": null,
      "name": "modifiers",
      "type": {
        "kind": "LIST",
        "name": null,
        "ofType": {
          "kind": "INPUT_OBJECT",
          "name": "AnalyticsFieldModifier",
          "ofType": null
        }
      }
    }
  ]
}
```

**Steps to reproduce**

Call `GraphQL::Client.load_schema` with a schema that contains an arg with `defaultValue`: `""`

Under the hood this calls `GraphQL::Schema::Loader.load(schema)` with the schema in `Hash` format

**Expected behavior**

Schema is loaded without any errors

**Actual behavior**

Errors on `GraphQL.parse(graphql_string)` when calling with a malformed `graphql_string` (see additional details below)

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
GraphQL::Client.load_schema(Vetspire::Client.new.schema_filepath)
parser.y:517:in `on_error'
(eval):3:in `_racc_do_parse_c'
(eval):3:in `do_parse'
parser.y:459:in `block in parse_document'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:91:in `trace'
parser.y:455:in `parse_document'
parser.y:466:in `parse'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql.rb:51:in `parse_with_racc'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql.rb:36:in `parse'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:204:in `block in build_arguments'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:188:in `each'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:188:in `build_arguments'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:181:in `block (2 levels) in build_fields'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:304:in `instance_eval'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:304:in `initialize'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/accepts_definition.rb:142:in `initialize'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:123:in `new'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/field.rb:123:in `from_options'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_fields.rb:12:in `field'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:172:in `block in build_fields'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:171:in `each'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:171:in `build_fields'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:134:in `block in define_type'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:126:in `initialize'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:126:in `new'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:126:in `define_type'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:24:in `block in load'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:22:in `each'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/loader.rb:22:in `load'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client.rb:52:in `load_schema'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client.rb:57:in `load_schema'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-client-0.16.0/lib/graphql/client.rb:55:in `load_schema'
(irb):1:in `irb_binding'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/workspace.rb:114:in `eval'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/workspace.rb:114:in `evaluate'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/context.rb:459:in `evaluate'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:541:in `block (2 levels) in eval_input'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:704:in `signal_status'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:538:in `block in eval_input'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:166:in `block (2 levels) in each_top_level_statement'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:151:in `loop'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:151:in `block in each_top_level_statement'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:150:in `catch'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb/ruby-lex.rb:150:in `each_top_level_statement'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:537:in `eval_input'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:472:in `block in run'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:471:in `catch'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:471:in `run'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/2.7.0/irb.rb:400:in `start'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/commands/console/console_command.rb:70:in `start'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/commands/console/console_command.rb:19:in `start'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/commands/console/console_command.rb:102:in `perform'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/command/base.rb:69:in `perform'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/command.rb:50:in `invoke'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<main>'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `block in require'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:299:in `load_dependency'
/Users/bitwerx-tyler/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0/gems/activesupport-6.1.0/lib/active_support/dependencies.rb:332:in `require'
bin/rails:5:in `<main>'
Traceback (most recent call last):
        3: from (irb):1
        2: from (eval):3:in `do_parse'
        1: from (eval):3:in `_racc_do_parse_c'
GraphQL::ParseError (Parse error on ")" (RPAREN) at [1, 33])

```

</details>

**Additional context**

This appears to be coming from string interpolation in `GraphQL::Schema::Loader.build_arguments`:

```ruby
  def build_arguments(arg_owner, args, type_resolver)
    args.each do |arg|
      # kwarg code
      
      if arg["defaultValue"] # Evaluates to true for empty string ("")
        default_value_str = arg["defaultValue"]

        # Interpolation here does not escape the quotations
        dummy_query_str = "query getStuff($var: InputObj = #{default_value_str}) { __typename }"

        # Returns a `GraphQL::Language::Nodes::Document`:
        dummy_query_ast = GraphQL.parse(dummy_query_str)
        
        # More processing
      end
    end
  end
```

Here `arg["defaultValue"]` is `''`, which evaluates to `true`. However, empty strings are simply interpolated into the dummy string without escaping the quotations:

```ruby
dummy_query_str = "query getStuff($var: InputObj = #{default_value_str}) { __typename }"

puts dummy_query_str

# => "query getStuff($var: InputObj = ) { __typename }"
```

Attempting to parse:

```ruby
GraphQL.parse(dummy_query_str)

# =>GraphQL::ParseError (Parse error on ")" (RPAREN) at [1, 33])
```

Apparent solutions:

1) Allow empty strings, escape quotations
2) Explicitly check `defaultValue` not empty before attempting to parse

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report! Where did `"defaultValue": ""` come from? At first glance, it looks like an invalid default value, so I'm interested to know how the schema was configured that it returned it. 

Here's [the spec](http://spec.graphql.org/draft/#sec-The-__InputValue-Type): 

> `defaultValue` may return a String encoding (using the GraphQL language) of the default value used by this input value in the condition a value is not provided at runtime. If this input value has no default value, returns `null`.

From GraphQL-Ruby, I'd expect default values of `""` to be expressed as `"\"\""` in JSON. Here's a quick script to show GraphQL-Ruby's behavior here: 

```ruby 
require "bundler/inline"

gemfile do
  source 'https://rubygems.org'
  gem 'graphql'
end


schema = GraphQL::Schema.from_definition <<-GRAPHQL
type Query {
  field(
    str: String = "",
    list: [String!] = [],
    noDefault: String,
  ): String
}
GRAPHQL

pp schema.execute("{ __type(name: \"Query\") { fields { args { defaultValue } } } }").to_h

# {"data"=>
#   {"__type"=>
#     {"fields"=>
#       [{"args"=>
#          [{"defaultValue"=>"\"\""},
#           {"defaultValue"=>"[]"},
#           {"defaultValue"=>nil}]}]}}}
```

Additionally, since the argument described here has type `[AnalyticsFieldModifier]`, isn't `""` an _invalid_ input for that argument? 

Anyhow, if you don't mind sharing the configuration that produced that introspection result, we can debug further!

**Comment by bitwerx-tyler** [comment]
Hey, thanks for the quick response.

This schema is from a 3rd party API we're integrating with, so I don't have a lot of details about the specific server-side implementation they're using to generate this schema. I'm not super familiar with the GraphQL spec, but based on your comments it *does* look like this is encoded incorrectly (and probably invalid for other reasons as well).

On our end, we're doing something like:

```ruby
schema = JSON.parse(IO.read(schema_filepath))

schema.deep_transform_values! do |value|
  value.to_s.empty? ? nil : value
end

GraphQL::Schema.load_schema(schema)
```

which seems to work, but wasn't sure if there was a better way.

**Comment by rmosolgo** [comment]
:+1: That sounds like a good work-around to me. If you follow up with that third-party API provider and learn that this is something that GraphQL-Ruby _should_ properly support, please let me know! Also, if you're interested in contributing better `defaultValue` validation for `Schema::Loader.load(...)`, I'd welcome a PR for it 👍
