### ISSUE TITLE
Different exceptions for unauthorized objects depending on GraphQL::Execution::Interpreter and GraphQL::Batch

### ISSUE THREAD

**Issue by arathunku** [rmosolgo/graphql-ruby#3266]
**Describe the bug**

I'm observing strange exceptions depending on if I have used "GraphQL::Execution::Interpreter" and/or "GraphQL::Batch"

Without `GraphQL::Execution::Interpreter`, for both async and sync resolve, I'm getting **correct** output

**Versions**

`graphql` version: 1.11.6 and master(commit: `ef9986625009` at the time of report)
`graphql-batch` version: 0.4.3

**GraphQL schema**

Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? **Yes**

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.11.6"
  gem "graphql-batch", "0.4.3"
end

require 'graphql/batch'

class BaseArgument < GraphQL::Schema::Argument
end

class BaseField < GraphQL::Schema::Field
  argument_class(BaseArgument)
end

class BaseInputObject < GraphQL::Schema::InputObject
  argument_class(BaseArgument)
end

class BaseObject < GraphQL::Schema::Object
  field_class(BaseField)
end

class BaseMutation < GraphQL::Schema::Mutation
  field_class(BaseField)
end

class Thing < BaseObject
  field :name, String, null: false

  def self.authorized?(obj, context)
    false
  end
end

class RecordLoader < GraphQL::Batch::Loader
  def initialize(model)
    @model = model
  end

  def perform(ids)
    ids.map { |id| OpenStruct.new(name: id, id: id) }.each { |record| fulfill(record.id, record) }
    ids.each { |id| fulfill(id, nil) unless fulfilled?(id) }
  end
end

class RemoveInput <  BaseInputObject
  argument :thing_id, ID, required: true, loads: Thing
end

class RemoveThings < BaseMutation
  argument :to_remove, [RemoveInput], required: true

  field :success, Boolean, null: false

  def resolve(to_remove: )
    { success: true }
  end
end

class Mutations < BaseObject
  field :remove_things, mutation: RemoveThings
end

class Query < BaseObject
  field :thing, Thing, null: false
end

class Schema < GraphQL::Schema
  query Query
  mutation Mutations
  # When this is enabled, there's:
  #   - for promise based resolve it's throwing undefined method `keyword_arguments'
  #   - for OpenStruct: "An instance of OpenStruct failed Thing's authorization check"
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  use GraphQL::Batch

  def self.object_from_id(id, ctx)
    # Toggle this to see how exception changes
    OpenStruct.new(id: id)
    # RecordLoader.for(Thing).load(id)
  end

  def self.resolve_type(abst_type, obj, ctx)
    Thing
  end
end

pp Schema.execute('mutation { removeThings(toRemove: [{thingId: "stuff"}]) { success } }').to_h
```

**Steps to reproduce**

- run script above

**Expected behavior**

```
{"data"=>{"removeThings"=>nil}}
```

**Actual behavior**

When this is enabled
```
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
```

- for promise based resolve it's throwing undefined method `keyword_arguments' 
-GraphQL::UnauthorizedError:0x00005621558daa50> (NoMethodError)
<details>

```
Traceback (most recent call last):
        29: from test-graphql.rb:98:in `<main>'
        28: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1627:in `execute'
        27: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1656:in `multiplex'
        26: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
        25: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
        24: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        23: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
        22: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
        21: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        20: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        19: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        18: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        17: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        16: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        15: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        14: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        13: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        12: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
        11: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
        10: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:87:in `run_as_multiplex'
         9: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:51:in `finish_multiplex'
         8: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
         7: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
         6: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:94:in `block in sync_lazies'
         5: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/resolve.rb:11:in `resolve_all'
         4: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/resolve.rb:37:in `resolve'
         3: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/lazy.rb:41:in `value'
         2: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:452:in `block in after_lazy'
         1: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:462:in `after_lazy'
/home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:187:in `block (2 levels) in evaluate_selections': undefined method `keyword_arguments' for #<GraphQL::UnauthorizedError:0x00005621558daa50> (NoMethodError)
```

</details>

- for OpenStruct exception: "An instance of OpenStruct failed Thing's authorization check
<details>

```

Traceback (most recent call last):
        57: from test-graphql.rb:100:in `<main>'
        56: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1627:in `execute'
        55: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:1656:in `multiplex'
        54: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
        53: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
        52: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        51: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
        50: from /home/arathunku/uper && pundit_authorized?(obj, context, type: self).asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
        49: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        48: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        47: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        46: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        45: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        44: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        43: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        42: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        41: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        40: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
        39: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
        38: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
        37: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `map'
        36: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
        35: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:112:in `begin_query'
        34: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:45:in `begin_query'
        33: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:72:in `evaluate'
        32: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        31: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
        30: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:59:in `run_eager'
        29: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:127:in `evaluate_selections'
        28: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:127:in `each'
        27: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:175:in `block in evaluate_selections'
        26: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/runtime.rb:473:in `arguments'
        25: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/query.rb:251:in `arguments_for'
        24: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/arguments_cache.rb:27:in `fetch'
        23: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/interpreter/arguments_cache.rb:15:in `block (3 levels) in initialize'
        22: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `coerce_arguments'
        21: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `map'
        20: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `each'
        19: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:125:in `block in coerce_arguments'
        18: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/execution/errors.rb:30:in `with_error_handling'
        17: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:126:in `block (2 levels) in coerce_arguments'
        16: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/non_null.rb:54:in `coerce_input'
        15: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/list.rb:47:in `coerce_input'
        14: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/list.rb:47:in `map'
        13: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/list.rb:47:in `block in coerce_input'
        12: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/non_null.rb:54:in `coerce_input'
        11: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/input_object.rb:213:in `coerce_input'
        10: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `coerce_arguments'
         9: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `map'
         8: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:94:in `each'
         7: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:118:in `block in coerce_arguments'
         6: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:191:in `load_application_object'
         5: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
         4: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:199:in `block in load_application_object'
         3: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
         2: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:209:in `block (2 levels) in load_application_object'
         1: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
/home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.11.6/lib/graphql/schema/member/has_arguments.rb:213:in `block (3 levels) in load_application_object': An instance of OpenStruct failed Thing's authorization check (GraphQL::UnauthorizedError)

```

</details>

- **on master** with async resolver: `ef9986625009/lib/graphql/execution/interpreter/runtime.rb:184:in `block (2 levels) in evaluate_selections': undefined method `empty?' for #<GraphQL::UnauthorizedError:0x00007f22b8034bc0> (NoMethodError)`

<details>

```
Traceback (most recent call last):
        29: from test-graphql.rb:97:in `<main>'
        28: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/schema.rb:1640:in `execute'
        27: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/schema.rb:1669:in `multiplex'
        26: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:48:in `run_all'
        25: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:58:in `run_queries'
        24: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/tracing.rb:66:in `trace'
        23: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
        22: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
        21: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        20: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        19: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        18: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        17: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        16: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        15: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        14: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        13: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        12: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
        11: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
        10: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/multiplex.rb:87:in `run_as_multiplex'
         9: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter.rb:51:in `finish_multiplex'
         8: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
         7: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/tracing.rb:66:in `trace'
         6: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter.rb:94:in `block in sync_lazies'
         5: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter/resolve.rb:11:in `resolve_all'
         4: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter/resolve.rb:37:in `resolve'
         3: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/lazy.rb:41:in `value'
         2: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter/runtime.rb:463:in `block in after_lazy'
         1: from /home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter/runtime.rb:473:in `after_lazy'
/home/arathunku/.asdf/installs/ruby/2.7.1/lib/ruby/gems/2.7.0/bundler/gems/graphql-ruby-ef9986625009/lib/graphql/execution/interpreter/runtime.rb:184:in `block (2 levels) in evaluate_selections': undefined method `empty?' for #<GraphQL::UnauthorizedError:0x00007f22b8034bc0> (NoMethodError)
```

</details>

It looks like there are 2 separate issues here or I'm simply doing something wrong with new Interpreter and authorization checks?

Thank you for any pointers in which direction I should take it - modify my usage / work on PR to address this?

**Comment by rmosolgo** [comment]
Hey, thanks for such a detailed report! I agree, it should work the way you say.

I'm not exactly sure _where_ to start debugging this. All I can say is, somehow, a `GraphQL::UnauthorizedError` is being _returned_ to GraphQL-Ruby's execution code instead of raised (and then rescued). Here some examples about how it's supposed to work: 

https://github.com/rmosolgo/graphql-ruby/blob/c29214a2a8f0a2bc3ee8ef645ea86ebd72a108a6/lib/graphql/schema/object.rb#L41-L45

https://github.com/rmosolgo/graphql-ruby/blob/c29214a2a8f0a2bc3ee8ef645ea86ebd72a108a6/lib/graphql/schema/field.rb#L580-L596

It sounds like something is missing for `loads:` similar to those rescues. For historical/compatibility reasons, `.loads` is implemented in a few different places: 

https://github.com/rmosolgo/graphql-ruby/blob/c29214a2a8f0a2bc3ee8ef645ea86ebd72a108a6/lib/graphql/schema/input_object.rb#L32-L42

https://github.com/rmosolgo/graphql-ruby/blob/c29214a2a8f0a2bc3ee8ef645ea86ebd72a108a6/lib/graphql/schema/member/has_arguments.rb#L111-L121

Those spots probably need some kind of unauthorized error handling, but I'm not exactly sure what...

**Comment by arathunku** [comment]
Thank you @rmosolgo for pointers. I'll finish Rails 6.1 update at $DAYJOB and get back to this issue sometime next week.

**Comment by arathunku** [comment]
I think I've got something "working", in quotes because the fix is not in the places you had mentioned :confused: I've tried handling the error in `has_arguments` and `input_object` but I was constantly getting either `data: nil` + error collected, or nothing at all and mutation continued to run successfully.

My current diff looks like this:

```diff
diff --git a/lib/graphql/execution/interpreter/runtime.rb b/lib/graphql/execution/interpreter/runtime.rb
index 870c375b9..c5bb3fbef 100644
--- a/lib/graphql/execution/interpreter/runtime.rb
+++ b/lib/graphql/execution/interpreter/runtime.rb
@@ -170,13 +170,14 @@ def evaluate_selections(path, scoped_context, owner_object, owner_type, selectio

             begin
               kwarg_arguments = arguments(object, field_defn, ast_node)
-            rescue GraphQL::ExecutionError => e
+            rescue GraphQL::ExecutionError, GraphQL::UnauthorizedError => e
               continue_value(next_path, e, owner_type, field_defn, return_type.non_null?, ast_node)
               next
             end

             after_lazy(kwarg_arguments, owner: owner_type, field: field_defn, path: next_path, scoped_context: context.scoped_context, owner_object: object, arguments: kwarg_arguments) do |resolved_arguments|
-              if resolved_arguments.is_a? GraphQL::ExecutionError
+              case resolved_arguments
+              when GraphQL::ExecutionError, GraphQL::UnauthorizedError
                 continue_value(next_path, resolved_arguments, owner_type, field_defn, return_type.non_null?, ast_node)
                 next
               end
``` 

With all specs passing and my example working correctly with and without "use GraphQL::Execution::Interpreter". I still need to test this with our internal GraphQL API and add proper specs :runner:

**Comment by rmosolgo** [comment]
Glad you found something! That seems like a good solution. I wonder if my mistake was thinking that GraphQL::UnauthorizedError _inherited from_ GraphQL::ExecutionError, but evidently it doesn't.
