### ISSUE TITLE
Class based types not working on legacy defined schema

### ISSUE THREAD

**Issue by jongbeau** [rmosolgo/graphql-ruby#3301]
**Describe the bug**
When using class based object field definitions on a legacy defined schema, the following error happens:
```
graphql-1.11.6/lib/graphql/schema/field.rb:726:in `with_extensions'
/Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:694:in `block in public_send_field': undefined method `object' for nil:NilClass (NoMethodError)
```

This does *not* happen when using legacy defined object types.

**Versions**

`graphql` version: 1.11.6 - but I also tried 1.10, 1.9, and 1.8 and had the same issue.

**Steps to reproduce**

```
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.11.6"
end

LegacyQueryType = GraphQL::ObjectType.define do
  name "Query"
  field :id, !types.String do
    resolve -> (_obj, _args, _ctx) do
      "legacy-test-id"
    end
  end
end

class QueryType < GraphQL::Schema::Object
  field :id, String, null: false

  def id
    "test-id"
  end
end

Schema = GraphQL::Schema.define do
  # query LegacyQueryType
  query QueryType
end

query_str = <<-GRAPHQL
query {
  id
}
GRAPHQL

pp Schema.execute(query_str).to_h
```

Notice that the above script crashes.
If you swap out `query QueryType` with `query LegacyQueryType`, it works and returns the following output:
`{"data"=>{"id"=>"legacy-test-id"}}`

**Actual behavior**

The script crashes:

```
Traceback (most recent call last):
        47: from legacy_schema_test.rb:36:in `<main>'
        46: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:470:in `execute'
        45: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:493:in `multiplex'
        44: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:1984:in `with_definition_error_check'
        43: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:494:in `block in multiplex'
        42: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:48:in `run_all'
        41: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:58:in `run_queries'
        40: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        39: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
        38: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
        37: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
        36: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        35: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
        34: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
        33: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
        32: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
        31: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
        30: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
        29: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
        28: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
        27: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
        26: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
        25: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:82:in `map'
        24: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
        23: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/multiplex.rb:112:in `begin_query'
        22: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:31:in `begin_query'
        21: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:49:in `resolve_root_selection'
        20: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        19: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:56:in `block in resolve_root_selection'
        18: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `resolve_selection'
        17: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:85:in `each'
        16: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:92:in `block in resolve_selection'
        15: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:128:in `resolve_field'
        14: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/tracing.rb:66:in `trace'
        13: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:129:in `block in resolve_field'
        12: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:38:in `invoke'
        11: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/middleware_chain.rb:49:in `invoke_core'
        10: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/execution/execute.rb:321:in `call'
         9: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/field.rb:136:in `resolve'
         8: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/field.rb:136:in `call'
         7: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:545:in `resolve_field'
         6: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
         5: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:551:in `block in resolve_field'
         4: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema.rb:112:in `after_lazy'
         3: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:561:in `block (2 levels) in resolve_field'
         2: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:672:in `public_send_field'
         1: from /Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:726:in `with_extensions'
/Users/jason/.rvm/gems/ruby-2.6.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:694:in `block in public_send_field': undefined method `object' for nil:NilClass (NoMethodError)
```

**Additional context**
I was using a class based schema with version 1.8.3, and this was all working (mixing class based types and legacy based types). However, when trying to upgrade to 1.11.6, it stopped working and I was advised by Robert to go back to the Legacy schema definition because the new class based schemas no longer work with legacy object types:
https://graphql.slack.com/archives/C07MVL1AB/p1611267172004700

**Comment by rmosolgo** [comment]
Hey, thanks for putting all this down in an issue. I spent some time with the example you shared and here's what I've come up with: 


1. I think I was wrong about suggesting `Schema.define`. It's been a while since I worked with any mixed schemas 😅 , sorry I was confused about that. 
2. I think cross-compatible schemas must have broken in 1.10.0. It was _supposed_ to require all-class-based for _Interpreter_ runtime only, but I can't see any way a class-based schema would _ever_ support a mixed schema from 1.10 onward. To demonstrate, I updated your example so it _worked_ on 1.9, but it fails if you switch it to 1.10: 

  <details>
  <summary>Mixed schema on graphql-ruby 1.9</summary>
  <p>
  ```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "1.9.0"
end


LegacyQueryType = GraphQL::ObjectType.define do
  name "Query"
  field :id, !types.String do
    resolve -> (_obj, _args, _ctx) do
      "legacy-test-id"
    end
  end
end

class Schema < GraphQL::Schema
  query LegacyQueryType
end

query_str = <<-GRAPHQL
query {
  id
}
GRAPHQL

p Schema.execute(query_str).to_h
  ```
  </p>
  </details>


Interestingly, this is the _first I've heard_ of this problem. Given how infrequently this has popped up, and the amount of work it would take to improve support for mixed schemas (I just removed all the tests for `.define`), I don't plan to improve this compatibility issue. I think that leaves you with a few options (IIRC you're trying to get on Ruby 3): 

- Fork this project and check out the last tag of 1.8.x, and correct any errors that cause it to fail on Ruby 3. (I have no idea how many there are). If you wanted to contribute those changes back upstream, I'd be happy to cut a new 1.8.x release to rubygems with that improvement. 
- Upgrade to 1.9.x, then fix any Ruby 3 errors -- likewise, I'd be happy to release a new 1.9.x version to rubygems if you wanted me to. 
- Migrate everything to class-based and migrate to 1.10 and beyond

Personally, that last one seems like the best option to me, but given that 1.8.x is working well _enough_ for you now, I just thought I'd mention those other options!
