### ISSUE TITLE
Field extension throws nil error

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#3323]
**Describe the bug**

I have a field extension that does some resolve logic under the hood. I don't yield inside the `#resolve` method of the field extension, and somehow this throws an error later in the `BaseConnection` because the `arguments` variable is `nil`.

**Versions**

`graphql` version: 1.12.3 (but I pinned it down to this commit: https://github.com/rmosolgo/graphql-ruby/commit/147c317cf8d70bfef1628e7b0f849eb2854449c3)
`rails` 5.2.4.4

**GraphQL schema**

```ruby
class MyField < Graphql::MaskedField
  class EagerLoadExtension < GraphQL::Schema::FieldExtension
    def resolve(object:, arguments:, context:, &block)
      Article.all
    end
  end

  def initialize(*args, **kwargs, &block)
    (kwargs[:extensions] ||= []).push(EagerLoadExtension)
    super(*args, **kwargs, &block)
  end
end

class MyQueries < GraphQL::Schema::Object
  field_class MyField
  field :articles, ArticleType.connection_type, null: false
end

class Schema < GraphQL::Schema
  use GraphQL::Execution::Interpreter
  use GraphQL::Analysis::AST
  queries MyQueries
end

class ArticleType < GraphQL::Schema::Object
  field :id, ID, null: false
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  articles { nodes { id } }
}
```

**Steps to reproduce**

Just fire the query

**Expected behavior**

The `arguments` variable should contain the arguments from within the resolve method.

In the docs it says https://graphql-ruby.org/type_definitions/field_extensions.html#modifying-field-execution

> If it doesn’t yield, then the underlying field won’t be called. Whatever #resolve returns will be used for continuing execution.

I don't know if it has anything to do with it, because I'm _returning_ a value, and I don't call the resolve hook.

**Actual behavior**

An error is thrown:

```
     NoMethodError:
       undefined method `[]' for nil:NilClass
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/relay/base_connection.rb:94:in `after'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/relay/relation_connection.rb:142:in `sliced_nodes'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/relay/relation_connection.rb:73:in `paged_nodes'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/relay/base_connection.rb:112:in `edge_nodes'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/types/relay/base_connection.rb:106:in `nodes'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:692:in `public_send'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:692:in `block in public_send_field'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:735:in `block in with_extensions'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:754:in `block (2 levels) in run_extensions_before_resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:757:in `run_extensions_before_resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:754:in `block in run_extensions_before_resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field_extension.rb:50:in `resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:752:in `run_extensions_before_resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:732:in `with_extensions'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:672:in `public_send_field'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:585:in `block in resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema.rb:112:in `after_lazy'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema/field.rb:583:in `resolve'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:226:in `block (5 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/tracing.rb:66:in `trace'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:225:in `block (4 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/query.rb:353:in `block in with_error_handling'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/errors.rb:30:in `with_error_handling'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/query.rb:352:in `with_error_handling'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:224:in `block (3 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:385:in `resolve_with_directives'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:221:in `block (2 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:460:in `after_lazy'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:179:in `block in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:126:in `each'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:126:in `evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:337:in `block in continue_field'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:460:in `after_lazy'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:332:in `continue_field'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:378:in `continue_field'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:238:in `block (4 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:460:in `after_lazy'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:232:in `block (3 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:385:in `resolve_with_directives'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:221:in `block (2 levels) in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:460:in `after_lazy'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:179:in `block in evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:126:in `each'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:126:in `evaluate_selections'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter/runtime.rb:58:in `run_eager'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/tracing.rb:66:in `trace'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter.rb:72:in `evaluate'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/interpreter.rb:45:in `begin_query'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:112:in `begin_query'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:83:in `block in run_as_multiplex'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:82:in `map'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:82:in `run_as_multiplex'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:61:in `block (2 levels) in run_queries'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:174:in `instrument_and_analyze'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:60:in `block in run_queries'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/tracing.rb:66:in `trace'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:58:in `run_queries'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/execution/multiplex.rb:48:in `run_all'
     # /usr/local/bundle/bundler/gems/graphql-ruby-147c317cf8d7/lib/graphql/schema.rb:1656:in `multiplex'
```

**Additional context**
I tried to leave out the irrelevant parts, I hope I didn't make any copy-paste errors.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it shouldn't raise in this case. I'm not exactly sure what the fix will look like, though.

**Comment by 23tux** [comment]
Thank you! Again, much respect for the blazing fast support!
