### ISSUE TITLE
Uninstalling Graphql-ruby on Rails 6.1 Errors on add_root_type query

### ISSUE THREAD

**Issue by grantgould** [rmosolgo/graphql-ruby#3330]
Uninstalling graphql-ruby on Rails 6.1 using Rails generator errors on `add_root_type query`.

**Versions**

`graphql` version: 1.12.0
`rails` version: 6.1.0

**Steps to reproduce**

Installing using `rails g graphql:install` then uninstalling using `rails d graphql:install`.

**Expected behavior**

Removing all files and references of graphql-ruby from rails app.

**Actual behavior**
<details>
<summary>Click to view exception backtrace</summary>

<p>

```
root@8b30fef753e7:/circle# rails g graphql:install
Running via Spring preloader in process 269
      create  app/graphql/types
      create  app/graphql/types/.keep
      create  app/graphql/circle_schema.rb
      create  app/graphql/types/base_object.rb
      create  app/graphql/types/base_argument.rb
      create  app/graphql/types/base_field.rb
      create  app/graphql/types/base_enum.rb
      create  app/graphql/types/base_input_object.rb
      create  app/graphql/types/base_interface.rb
      create  app/graphql/types/base_scalar.rb
      create  app/graphql/types/base_union.rb
      create  app/graphql/types/query_type.rb
add_root_type  query
      create  app/graphql/mutations
      create  app/graphql/mutations/.keep
      create  app/graphql/mutations/base_mutation.rb
      create  app/graphql/types/mutation_type.rb
add_root_type  mutation
      create  app/controllers/graphql_controller.rb
       route  post "/graphql", to: "graphql#execute"
     gemfile  graphiql-rails
       route  graphiql-rails
    generate  graphql:relay
       rails  generate graphql:relay 
Running via Spring preloader in process 295
      create  app/graphql/types/node_type.rb
      insert  app/graphql/types/query_type.rb
      create  app/graphql/types/base_connection.rb
      create  app/graphql/types/base_edge.rb
      insert  app/graphql/types/base_object.rb
      insert  app/graphql/types/base_object.rb
      insert  app/graphql/types/base_union.rb
      insert  app/graphql/types/base_union.rb
      insert  app/graphql/types/base_interface.rb
      insert  app/graphql/types/base_interface.rb
      insert  app/graphql/circle_schema.rb
Gemfile has been modified, make sure you `bundle install`
root@8b30fef753e7:/circle# bundle install
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Using rake 13.0.3
Using concurrent-ruby 1.1.7
Using i18n 1.8.6
Using minitest 5.14.2
Using tzinfo 2.0.4
Using zeitwerk 2.4.2
Using activesupport 6.1.0
Using builder 3.2.4
Using erubi 1.10.0
Using mini_portile2 2.4.0
Using nokogiri 1.10.10
Using rails-dom-testing 2.0.3
Using crass 1.0.6
Using loofah 2.8.0
Using rails-html-sanitizer 1.3.0
Using actionview 6.1.0
Using rack 2.2.3
Using rack-test 1.1.0
Using actionpack 6.1.0
Using nio4r 2.5.4
Using websocket-extensions 0.1.5
Using websocket-driver 0.7.3
Using actioncable 6.1.0
Using globalid 0.4.2
Using activejob 6.1.0
Using activemodel 6.1.0
Using activerecord 6.1.0
Using mimemagic 0.3.5
Using marcel 0.3.3
Using activestorage 6.1.0
Using mini_mime 1.0.2
Using mail 2.7.1
Using actionmailbox 6.1.0
Using actionmailer 6.1.0
Using actiontext 6.1.0
Using case_transform 0.2
Using jsonapi-renderer 0.2.2
Using active_model_serializers 0.10.12
Using public_suffix 4.0.6
Using addressable 2.7.0
Using encryptor 3.0.0
Using attr_encrypted 3.1.0
Using bcrypt 3.1.16
Using bindex 0.8.1
Using msgpack 1.3.3
Using bootsnap 1.5.1
Using brakeman 4.10.1
Using bundler 1.17.3
Using byebug 11.1.3
Using cancancan 3.2.1
Using regexp_parser 1.8.2
Using xpath 3.2.0
Using capybara 3.34.0
Using childprocess 3.0.0
Using orm_adapter 0.5.0
Using method_source 1.0.0
Using thor 1.0.1
Using railties 6.1.0
Using responders 3.0.1
Using warden 1.2.9
Using devise 4.7.3
Using rotp 2.1.2
Using devise-two-factor 3.0.0
Using doorkeeper 5.4.0
Using ffi 1.14.2
Using sprockets 4.0.2
Using sprockets-rails 3.2.2
Using graphiql-rails 1.7.0
Using graphql 1.12.0
Using jbuilder 2.10.1
Using launchy 2.5.0
Using letter_opener 1.7.0
Using rb-fsevent 0.10.4
Using rb-inotify 0.10.1
Using listen 3.4.0
Using pg 1.2.3
Using puma 5.1.1
Using rack-cors 1.1.1
Using rack-mini-profiler 2.3.0
Using rack-proxy 0.6.5
Using rails 6.1.0
Using redis 4.2.5
Using rubyzip 2.3.0
Using sassc 2.4.0
Using tilt 2.0.10
Using sassc-rails 2.1.2
Using sass-rails 6.0.0
Using selenium-webdriver 3.142.7
Using semantic_range 2.3.1
Using spring 2.1.1
Using turbolinks-source 5.2.0
Using turbolinks 5.2.1
Using web-console 4.1.0
Using webdrivers 4.4.2
Using webpacker 5.2.1
Bundle complete! 29 Gemfile dependencies, 95 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
root@8b30fef753e7:/circle# rails d graphql:install
Running via Spring preloader in process 310
      remove  app/graphql/types
      remove  app/graphql/types/.keep
      remove  app/graphql/circle_schema.rb
      remove  app/graphql/types/base_object.rb
      remove  app/graphql/types/base_argument.rb
      remove  app/graphql/types/base_field.rb
      remove  app/graphql/types/base_enum.rb
      remove  app/graphql/types/base_input_object.rb
      remove  app/graphql/types/base_interface.rb
      remove  app/graphql/types/base_scalar.rb
      remove  app/graphql/types/base_union.rb
      remove  app/graphql/types/query_type.rb
add_root_type  query
Traceback (most recent call last):
        53: from -e:1:in `<main>'
        52: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        51: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        50: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
        49: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
        48: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
        47: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
        46: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:180:in `serve'
        45: from /usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:26:in `fork'
        44: from /usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
        43: from /usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:8:in `fork'
        42: from /usr/local/bundle/gems/activesupport-6.1.0/lib/active_support/fork_tracker.rb:10:in `block in fork'
        41: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/application.rb:220:in `block in serve'
        40: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/command_wrapper.rb:38:in `call'
        39: from /usr/local/bundle/gems/spring-2.1.1/lib/spring/commands/rails.rb:6:in `call'
        38: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        37: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
        36: from /circle/bin/rails:5:in `<top (required)>'
        35: from /usr/local/bundle/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
        34: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
        33: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
        32: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
        31: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
        30: from /usr/local/bundle/gems/bootsnap-1.5.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
        29: from /usr/local/bundle/gems/railties-6.1.0/lib/rails/commands.rb:18:in `<top (required)>'
        28: from /usr/local/bundle/gems/railties-6.1.0/lib/rails/command.rb:50:in `invoke'
        27: from /usr/local/bundle/gems/railties-6.1.0/lib/rails/command/base.rb:69:in `perform'
        26: from /usr/local/bundle/gems/thor-1.0.1/lib/thor.rb:392:in `dispatch'
        25: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        24: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        23: from /usr/local/bundle/gems/railties-6.1.0/lib/rails/commands/destroy/destroy_command.rb:24:in `perform'
        22: from /usr/local/bundle/gems/railties-6.1.0/lib/rails/generators.rb:275:in `invoke'
        21: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/base.rb:485:in `start'
        20: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/group.rb:232:in `dispatch'
        19: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `invoke_all'
        18: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `map'
        17: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `each'
        16: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:134:in `block in invoke_all'
        15: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/invocation.rb:127:in `invoke_command'
        14: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/command.rb:27:in `run'
        13: from /usr/local/bundle/gems/graphql-1.12.0/lib/generators/graphql/install_generator.rb:107:in `create_folder_structure'
        12: from /usr/local/bundle/gems/graphql-1.12.0/lib/generators/graphql/core.rb:21:in `insert_root_type'
        11: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:197:in `in_root'
        10: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:187:in `inside'
         9: from /usr/local/lib/ruby/2.5.0/fileutils.rb:122:in `cd'
         8: from /usr/local/lib/ruby/2.5.0/fileutils.rb:122:in `chdir'
         7: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:187:in `block in inside'
         6: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:197:in `block in in_root'
         5: from /usr/local/bundle/gems/graphql-1.12.0/lib/generators/graphql/core.rb:22:in `block in insert_root_type'
         4: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:32:in `insert_into_file'
         3: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions.rb:91:in `action'
         2: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:83:in `revoke!'
         1: from /usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:110:in `replace!'
/usr/local/bundle/gems/thor-1.0.1/lib/thor/actions/inject_into_file.rb:110:in `read': No such file or directory @ rb_sysopen - /cir
cle/app/graphql/circle_schema.rb (Errno::ENOENT)
```

</p>

</details>

**Comment by rmosolgo** [comment]
Thanks for reporting this! I agree, it should uninstall cleanly.
