### ISSUE TITLE
Better error message when an object type is used as an argument type

### ISSUE THREAD

**Issue by rmosolgo** [rmosolgo/graphql-ruby#3381]
It should raise at configuration-type, instead of this cryptic error at runtime: 

```
E, [2021-03-10T11:19:57.931030 #28734] ERROR -- : undefined method `validate_input' for Types::CategoryType:Class
E, [2021-03-10T11:19:57.931362 #28734] ERROR -- : /Users/drew/.rvm/gems/ruby-2.4.9/gems/attr_encrypted-1.4.0/lib/attr_encrypted.rb:259:in `method_missing'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/non_null.rb:44:in `validate_input'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/input_object.rb:185:in `block in validate_non_null_input'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/input_object.rb:184:in `each'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/input_object.rb:184:in `map'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/input_object.rb:184:in `validate_non_null_input'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema/non_null.rb:44:in `validate_input'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/variables.rb:33:in `block in initialize'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/variables.rb:19:in `each'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/variables.rb:19:in `each_with_object'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/variables.rb:19:in `initialize'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query.rb:226:in `new'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query.rb:226:in `block in variables'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query.rb:396:in `with_prepared_ast'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query.rb:225:in `variables'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/validation_pipeline.rb:80:in `ensure_has_validated'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query/validation_pipeline.rb:35:in `valid?'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/query.rb:261:in `valid?'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/analysis/ast.rb:31:in `block (2 levels) in analyze_multiplex'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/analysis/ast.rb:30:in `map'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/analysis/ast.rb:30:in `block in analyze_multiplex'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/analysis/ast.rb:29:in `analyze_multiplex'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:195:in `block in instrument_and_analyze'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:175:in `instrument_and_analyze'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:61:in `block in run_queries'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `block in trace'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:80:in `call_tracers'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/tracing.rb:66:in `trace'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:59:in `run_queries'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/execution/multiplex.rb:49:in `run_all'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema.rb:1557:in `multiplex'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/graphql-1.10.3/lib/graphql/schema.rb:1528:in `execute'
/Users/drew/Development/Source/Finsync/finsync/app/controllers/graphql_controller.rb:19:in `execute'
/Users/drew/.rvm/gems/ruby-2.4.9/gems/actionpack-4.2.11.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
```

**Comment by rmosolgo** [comment]
Apparently this is done now: https://github.com/rmosolgo/graphql-ruby/blob/ffec3b0b4b25a687342e5e5596c219022e31b756/lib/graphql/schema/argument.rb#L326-L327
