### ISSUE TITLE
[PRO] Dashboard broken due to operation store stack level too deep error

### ISSUE THREAD

**Issue by aserafin** [rmosolgo/graphql-ruby#3435]
**Describe the bug**

After upgrading graphql-pro to the latest versions I'm no longer able to access the dashboard. Here's relevant stack trace:

```
...
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:40:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:53:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:40:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:53:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:40:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:53:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:40:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/operation_store.rb:53:in `operation_store'
graphql-pro (1.17.12) lib/graphql/pro/dashboard/operation_store_component.rb:7:in `enabled?'
graphql-pro (1.17.12) lib/graphql/pro/dashboard/application_component.rb:20:in `block in home'
```

**Comment by rmosolgo** [comment]
Derp! I noticed the same thing locally, but since nobody had reported it yet, I fixed it on my feature branch. I just released GraphQL-Pro v1.17.14 with a fix for this error. Please let me know if you run into it again after updating. Sorry for the trouble!
