### ISSUE TITLE
Query Level Directive Crashes During Static Validation With Input Type Argument

### ISSUE THREAD

**Issue by cocoahero** [rmosolgo/graphql-ruby#3483]
When a custom directive that is designed to be used at the `QUERY` level defines an argument that is an input object, the static validator crashes at runtime.

```undefined method `get_argument' for nil:NilClass (NoMethodError)```

<details>
 <summary>Stacktrace</summary>

```
94: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema.rb:1653:in `execute'
93: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema.rb:1682:in `multiplex'
92: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:50:in `run_all'
91: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:60:in `run_queries'
90: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
89: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
88: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
87: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
86: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
85: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
84: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
83: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
82: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
81: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
80: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
79: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
78: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:207:in `block in instrument_and_analyze'
77: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:34:in `analyze_multiplex'
76: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
75: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:35:in `block in analyze_multiplex'
74: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:35:in `map'
73: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:36:in `block (2 levels) in analyze_multiplex'
72: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query.rb:312:in `valid?'
71: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query/validation_pipeline.rb:35:in `valid?'
70: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query/validation_pipeline.rb:75:in `ensure_has_validated'
69: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:29:in `validate'
68: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
67: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:42:in `block in validate'
66: from /opt/rubies/2.7.2/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
65: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:55:in `block (2 levels) in validate'
64: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:68:in `visit'
63: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
62: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
61: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
60: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/no_definitions_are_present.rb:34:in `on_document'
59: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/operation_names_are_valid.rb:16:in `on_document'
58: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragment_names_are_unique.rb:17:in `on_document'
57: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragments_are_finite.rb:6:in `on_document'
56: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragments_are_used.rb:6:in `on_document'
55: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:26:in `on_document'
54: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:79:in `on_document'
53: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/definition_dependencies.rb:38:in `on_document'
52: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_document'
51: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
50: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
49: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
48: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
47: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
46: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
45: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:76:in `on_operation_definition'
44: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
43: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/operation_names_are_valid.rb:12:in `on_operation_definition'
42: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fields_will_merge.rb:24:in `on_operation_definition'
41: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:18:in `on_operation_definition'
40: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_names_are_unique.rb:20:in `on_operation_definition'
39: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:44:in `on_operation_definition'
38: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:13:in `on_operation_definition'
37: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/mutation_root_exists.rb:12:in `on_operation_definition'
36: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/subscription_root_exists.rb:12:in `on_operation_definition'
35: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/definition_dependencies.rb:47:in `on_operation_definition'
34: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
33: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
32: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
31: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
30: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
29: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
28: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
27: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:116:in `on_directive'
26: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/directives_are_defined.rb:18:in `on_directive'
25: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/directives_are_in_valid_locations.rb:9:in `on_directive'
24: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_arguments_are_present.rb:13:in `on_directive'
23: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/argument_names_are_unique.rb:14:in `on_directive'
22: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_directive'
21: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
20: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
19: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
18: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
17: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
16: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
15: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:138:in `on_argument'
14: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/arguments_are_defined.rb:9:in `on_argument'
13: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb:8:in `on_argument'
12: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:49:in `on_argument'
11: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_argument'
10: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
9: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
8: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
7: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
6: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
5: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
4: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:156:in `on_input_object'
3: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:7:in `on_input_object'
2: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:37:in `validate_input_object'
1: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:32:in `get_parent_type'
/Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema/warden.rb:109:in `get_argument': undefined method `get_argument' for Types::QueryType:Class (NoMethodError)
(Desktop/sandbox)[] > ./runme.rb
Traceback (most recent call last):
95: from ./runme.rb:46:in `<main>'
94: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema.rb:1653:in `execute'
93: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema.rb:1682:in `multiplex'
92: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:50:in `run_all'
91: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:60:in `run_queries'
90: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
89: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
88: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
87: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
86: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
85: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
84: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
83: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
82: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
81: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
80: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
79: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
78: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/execution/multiplex.rb:207:in `block in instrument_and_analyze'
77: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:34:in `analyze_multiplex'
76: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
75: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:35:in `block in analyze_multiplex'
74: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:35:in `map'
73: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/analysis/ast.rb:36:in `block (2 levels) in analyze_multiplex'
72: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query.rb:312:in `valid?'
71: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query/validation_pipeline.rb:35:in `valid?'
70: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/query/validation_pipeline.rb:75:in `ensure_has_validated'
69: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:29:in `validate'
68: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/tracing.rb:66:in `trace'
67: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:42:in `block in validate'
66: from /opt/rubies/2.7.2/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
65: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/validator.rb:55:in `block (2 levels) in validate'
64: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:68:in `visit'
63: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
62: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
61: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
60: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/no_definitions_are_present.rb:34:in `on_document'
59: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/operation_names_are_valid.rb:16:in `on_document'
58: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragment_names_are_unique.rb:17:in `on_document'
57: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragments_are_finite.rb:6:in `on_document'
56: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragments_are_used.rb:6:in `on_document'
55: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:26:in `on_document'
54: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:79:in `on_document'
53: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/definition_dependencies.rb:38:in `on_document'
52: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_document'
51: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
50: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
49: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
48: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
47: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
46: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
45: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:76:in `on_operation_definition'
44: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
43: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/operation_names_are_valid.rb:12:in `on_operation_definition'
42: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fields_will_merge.rb:24:in `on_operation_definition'
41: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:18:in `on_operation_definition'
40: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_names_are_unique.rb:20:in `on_operation_definition'
39: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:44:in `on_operation_definition'
38: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:13:in `on_operation_definition'
37: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/mutation_root_exists.rb:12:in `on_operation_definition'
36: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/subscription_root_exists.rb:12:in `on_operation_definition'
35: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/definition_dependencies.rb:47:in `on_operation_definition'
34: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
33: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
32: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
31: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
30: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
29: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
28: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
27: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:115:in `on_directive'
26: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/directives_are_defined.rb:18:in `on_directive'
25: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/directives_are_in_valid_locations.rb:9:in `on_directive'
24: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_arguments_are_present.rb:13:in `on_directive'
23: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/argument_names_are_unique.rb:14:in `on_directive'
22: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_directive'
21: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
20: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
19: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
18: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
17: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
16: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
15: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:137:in `on_argument'
14: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/arguments_are_defined.rb:9:in `on_argument'
13: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb:8:in `on_argument'
12: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:49:in `on_argument'
11: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:123:in `on_argument'
10: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
9: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:101:in `each'
8: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
7: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
6: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `visit_node'
5: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/language/visitor.rb:79:in `public_send'
4: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/base_visitor.rb:155:in `on_input_object'
3: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:7:in `on_input_object'
2: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:34:in `validate_input_object'
1: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb:29:in `get_parent_type'
/Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.9/lib/graphql/schema/warden.rb:109:in `get_argument': undefined method `get_argument' for nil:NilClass (NoMethodError)
```
</details>

**Versions**

- graphql (1.12.9)

**GraphQL schema**

```ruby
class QueryType < GraphQL::Schema::Object
  field :posts, [String], '', null: false

  def posts
    return ["Hello", "World"]
  end
end

class CoordinateInput < GraphQL::Schema::InputObject
  argument :latitude, Float, "", required: true
  argument :longitude, Float, "", required: true
end

class MyDirective < GraphQL::Schema::Directive
  description "A nice runtime customization"
  locations QUERY

  argument(:location, CoordinateInput, "", required: true)

  def self.resolve(obj, args, context)

  end
end

class MySchema < GraphQL::Schema
  query QueryType
  directive MyDirective
end
```

**GraphQL query**

```graphql
query MyQuery @myDirective(location: { latitude: 37.8, longitude: -87.2 }) {
  posts
}
```

**Steps to reproduce**

1. Add a custom directive to your schema which takes an input object as argument. Mark its possible locations as `QUERY` only.
2. Execute a query where that directive is added

cc @eapache @swalkinshaw

**Comment by eapache** [comment]
At a glance, it seems like `context.argument_definition` is either returning `nil` or the wrong node when it's called in `get_parent_type`. I am somewhat confused by the implementation/comment of `argument_definition` given at https://github.com/rmosolgo/graphql-ruby/blob/bace1e4027900fc8779a5c2fd393ff6456046cea/lib/graphql/static_validation/base_visitor.rb#L179-L184

As I follow the visitor in my head (haven't actually run this) I would think that there would only be one argument definition in the list so far, and that's the one we want? Maybe this should be split into `argument_definition` and `parent_argument_definition` like the type_definition accessor was? @rmosolgo

**Comment by rmosolgo** [comment]
Ah, yeah, for today's episode of "how did it ever work"...

**Comment by rmosolgo** [comment]
I think you're right that the method names are off, but the behavioral problem looks a little different to me. It seems like the code was entirely unprepared for directives with input object arguments. That code checked for a parent argument definition, and if it didn't find one, it assumed that the argument owner was the last-visited field definition. For directives, that was false (and in this case, the last-visited field definition was `nil`). 

So, I added a check for the last-visited directive definition. Since fields can't be inside directives, that will be `nil` anytime that the code _should_ find a field definition. 

Let me know what you think of the linked patch :+1:
