### ISSUE TITLE
GraphQL::ParseError when query ends with a single backtrace character

### ISSUE THREAD

**Issue by mtoygar** [rmosolgo/graphql-ruby#3497]
### Description

graphql parser raises `GraphQL::ParseError` when query ends with a single backtrace(`\`). 

related to https://github.com/rmosolgo/graphql-ruby/issues/2506 (an earlier fix for multiple backtrace characters.)

**Versions**

`graphql` version: 1.12.10
`rails` (or other framework): -
other applicable versions (`graphql-batch`, etc) -

### Steps to reproduce

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql'
end

require 'graphql'

query = <<~GRAPHQL
  {
    productVariants(query: "text\\") {
      edges {
        node {
          displayName
          id
          image {
            transformedSrc(maxWidth: 75, maxHeight: 75)
          }
          inventoryQuantity
          price
          sku
          product {
            id
            onlineStoreUrl
            title
            totalVariants
          }
        }
      }
    }
  }
GRAPHQL

GraphQL.parse(query)
```

### Error Backtrace

<details>
<summary>Click to view exception backtrace</summary>

```
raceback (most recent call last):
	9: from graphl_parse_error.rb:35:in `<main>'
	8: from /Users/murattoygar/.rvm/gems/ruby-2.7.0/gems/graphql-1.12.10/lib/graphql.rb:35:in `parse'
	7: from /Users/murattoygar/.rvm/gems/ruby-2.7.0/gems/graphql-1.12.10/lib/graphql.rb:47:in `parse_with_racc'
	6: from parser.y:469:in `parse'
	5: from parser.y:455:in `parse_document'
	4: from /Users/murattoygar/.rvm/gems/ruby-2.7.0/gems/graphql-1.12.10/lib/graphql/tracing.rb:91:in `trace'
	3: from parser.y:459:in `block in parse_document'
	2: from (eval):3:in `do_parse'
	1: from (eval):3:in `_racc_do_parse_c'
parser.y:527:in `on_error': Parse error on "\\"" (error) at [2, 26] (GraphQL::ParseError)
```

</details>

**Comment by mtoygar** [comment]
yeap it does. Thank you!
