### ISSUE TITLE
GraphQL::Execution::Execute::Skip for v1.12.11 and greater

### ISSUE THREAD

**Issue by EugeneGrigorenko** [rmosolgo/graphql-ruby#3511]
**Describe the bug**

Subscriptions seem to be broken after  v1.12.11 update. Were working fine up to v1.12.10.
Here is the query: 
```
GraphqlChannel#execute({
"query"=>"subscription Updates($recordId: ID!) {  
   recordUpdates(recordId: $recordId) {
       updates {
          tasks {
              id
              value
        }
        subjectId
        action
    }  
}}

```

Here is the error response I'm getting
```
Could not execute command from (
{"command"=>"message", "identifier"=>"{\"channel\":\"GraphqlChannel\",\"channelId\":\"179cc7fb3b0\"}", 
"data"=>"{\"query\":\"subscription Updates($recordId: ID!) {\\n  recordUpdates(recordId: $recordId) {\\n    updates {\\n      tasks {\\n        id\\n     value\\n        __typename\\n      }\\n      subjectId\\n     action\\n      __typename\\n    }\\n    __typename\\n  }\\n}\\n\\n}\\n  __typename\\n}\\n\",\"variables\":{\"recordId\":\"Z2lkOi8vcmFwdG9yL0lzc3VlLzQ1NzA1\"},\"operationName\":\"Updates\",\"action\":\"execute\"}"}) 

[GraphQL::Execution::Execute::Skip - GraphQL::Execution::Execute::Skip]: 

/Users/eugenegrigorenko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.11/lib/graphql/execution/lazy.rb:52:in `value' | 
/Users/eugenegrigorenko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.11/lib/graphql/schema.rb:129:in `public_send' | 
/Users/eugenegrigorenko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.11/lib/graphql/schema.rb:129:in `sync_lazy' |
/Users/eugenegrigorenko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.11/lib/graphql/schema.rb:113:in `block in after_lazy' | 
/Users/eugenegrigorenko/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-1.12.11/lib/graphql/execution/lazy.rb:41:in `value'

**Versions**

`graphql` version: 1.12.11
`rails` (or other framework): 6.0.3.7
other applicable versions (`graphql-batch`, etc)

**Comment by rmosolgo** [comment]
Oh my! Thanks for the report. 

I thought I could make a little performance optimization by making the magic `SKIP` value an error object _here_:

https://github.com/rmosolgo/graphql-ruby/pull/3494/files#diff-f3c0e6c48a2ce8c0e051b7b9501532cc809b58201f85205296f8362f59d3430aR9

But evidently it breaks for subscription fields that use promises 😖 I must not have a test for that case. 

I'll add a test, fix it, cut a new release, and follow up here soon!

**Comment by rmosolgo** [comment]
I've opened a PR which I _think_ addresses this, but it's a little hard to tell _exactly_ where the `skip` was coming from. Could you try #3514 locally to confirm the fix? 

```ruby 
# gemfile 
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "fix-lazy-skip"
```

(If you're not able to confirm it, I'm happy to release it soon, then you can try a version from Rubygems. Just let me know.)

**Comment by EugeneGrigorenko** [comment]
Thanks for taking care of this. Seems to be working correctly for me 🎉
