### ISSUE TITLE
Default value of a Ruby `Date` or `DateTime` not being serialized to a `GraphQL::Types::ISO8601Date`

### ISSUE THREAD

**Issue by TomasBarry** [rmosolgo/graphql-ruby#3520]
**Describe the bug**

Default values for field arguments that are Ruby `Date` objects no longer get serialized to a `GraphQL::Types::ISO8601Date`. At version `1.9.15` they were whereas at version `1.12.12` they no longer are.

**Versions**

`graphql` version: `1.12.12`
`rails` (or other framework): `Rails 6.0.3.7`

**GraphQL schema**

```ruby
module Types
  class QueryType < Types::BaseObject
    field(
      :five_dates,
      [GraphQL::Types::ISO8601Date],
      null: false
    ) do
      argument(
        :start_date,
        GraphQL::Types::ISO8601Date,
        required: false,
        default_value: Date.today
      )
    end

    def five_dates(start_date:)
      (start_date..(start_date + 5.days))
    end
  end
end

class ApplicationSchema < GraphQL::Schema
  query(Types::QueryType)
  # …
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  fiveDates
}
```

```json
{
  "error": {
    "message": "undefined method `+' for nil:NilClass",
    "backtrace": [...]
  }
}
```

```graphql
query {
  fiveDates(startDate: "2021-01-01")
}
```

```json
{
  "data": {
    "fiveDates": [
      "2021-01-01",
      "2021-01-02",
      "2021-01-03",
      "2021-01-04",
      "2021-01-05",
      "2021-01-06"
    ]
  }
}
```

**Steps to reproduce**

Run the query on the schema above.

**Expected behavior**

`start_date` in the `five_dates` resolver should not be `nil` but it is. I have verified that this had worked in previous versions (specifically `1.9.15`).

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
"app/graphql/types/query_type.rb:17:in `five_dates'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:714:in `public_send'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:714:in `block in public_send_field'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:757:in `block in with_extensions'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:787:in `block (2 levels) in run_extensions_before_resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:790:in `run_extensions_before_resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:787:in `block in run_extensions_before_resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field_extension.rb:50:in `resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:780:in `run_extensions_before_resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:756:in `with_extensions'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:696:in `public_send_field'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:609:in `block in resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema.rb:116:in `after_lazy'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/field.rb:607:in `resolve'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:415:in `block (4 levels) in evaluate_selection_with_args'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:81:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/platform_tracing.rb:55:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/batch-loader-2.0.1/lib/batch_loader/graphql.rb:18:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:67:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:414:in `block (3 levels) in evaluate_selection_with_args'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/query.rb:362:in `block in with_error_handling'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/errors.rb:107:in `with_error_handling'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/query.rb:361:in `with_error_handling'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:413:in `block (2 levels) in evaluate_selection_with_args'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:679:in `resolve_with_directives'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:410:in `block in evaluate_selection_with_args'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:763:in `after_lazy'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:346:in `evaluate_selection_with_args'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:338:in `block in evaluate_selection'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/member/has_arguments.rb:132:in `block (2 levels) in coerce_arguments'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/member/has_arguments.rb:111:in `block in coerce_arguments'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/member/has_arguments.rb:110:in `each'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema/member/has_arguments.rb:110:in `coerce_arguments'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/arguments_cache.rb:50:in `dataload_for'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:337:in `evaluate_selection'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:268:in `block (2 levels) in evaluate_selections'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:267:in `block in evaluate_selections'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:266:in `each'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:266:in `evaluate_selections'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:141:in `block (4 levels) in run_eager'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:679:in `resolve_with_directives'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:140:in `block (3 levels) in run_eager'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:138:in `block (2 levels) in run_eager'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:100:in `tap_or_each'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:129:in `block in run_eager'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:679:in `resolve_with_directives'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter/runtime.rb:120:in `run_eager'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:81:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/scout_tracing.rb:37:in `block in platform_trace'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/scout_tracing.rb:36:in `platform_trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/batch-loader-2.0.1/lib/batch_loader/graphql.rb:21:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:67:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter.rb:72:in `evaluate'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/interpreter.rb:48:in `begin_query'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:85:in `begin_query'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:103:in `each'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:103:in `each_with_index'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:81:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/scout_tracing.rb:37:in `block in platform_trace'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:34:in `instrument'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/tracer.rb:44:in `instrument'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/scout_tracing.rb:36:in `platform_trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `block in call_tracers'",
"gems/ruby-2.6.1/gems/batch-loader-2.0.1/lib/batch_loader/graphql.rb:21:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:83:in `call_tracers'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/tracing.rb:67:in `trace'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:60:in `run_queries'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/execution/multiplex.rb:50:in `run_all'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1680:in `multiplex'",
"gems/ruby-2.6.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1651:in `execute'",
"app/controllers/graphql_controller.rb:18:in `execute'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'",
"gems/ruby-2.6.1/gems/react-rails-2.4.4/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'",
"gems/ruby-2.6.1/gems/sentry-raven-2.13.0/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `instance_exec'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'",
"gems/ruby-2.6.1/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'",
"gems/ruby-2.6.1/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'",
"gems/ruby-2.6.1/gems/bullet-6.1.3/lib/bullet/rack.rb:15:in `call'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/instant/middleware.rb:53:in `call'",
"gems/ruby-2.6.1/gems/scout_apm-4.0.4/lib/scout_apm/middleware.rb:17:in `call'",
"gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'",
"gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'",
"gems/ruby-2.6.1/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'",
"gems/ruby-2.6.1/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:567:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'",
"gems/ruby-2.6.1/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:87:in `protected_app_call'",
"gems/ruby-2.6.1/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:82:in `better_errors_call'",
"gems/ruby-2.6.1/gems/better_errors-2.9.1/lib/better_errors/middleware.rb:60:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'",
"gems/ruby-2.6.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'",
"gems/ruby-2.6.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `block in call'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80:in `block in tagged'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:28:in `tagged'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80:in `tagged'",
"gems/ruby-2.6.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'",
"gems/ruby-2.6.1/gems/request_store-1.5.0/lib/request_store/middleware.rb:19:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'",
"gems/ruby-2.6.1/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'",
"gems/ruby-2.6.1/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'",
"gems/ruby-2.6.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'",
"gems/ruby-2.6.1/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in `call'",
"gems/ruby-2.6.1/gems/hirefire-resource-0.9.0/lib/hirefire/middleware.rb:38:in `call'",
"gems/ruby-2.6.1/gems/sentry-raven-2.13.0/lib/raven/integrations/rack.rb:51:in `call'",
"gems/ruby-2.6.1/gems/webpacker-5.2.1/lib/webpacker/dev_server_proxy.rb:25:in `perform_request'",
"gems/ruby-2.6.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'",
"gems/ruby-2.6.1/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/configuration.rb:249:in `call'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/request.rb:76:in `block in handle_request'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/thread_pool.rb:338:in `with_force_shutdown'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/request.rb:75:in `handle_request'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/server.rb:437:in `process_client'",
"gems/ruby-2.6.1/gems/puma-5.3.1/lib/puma/thread_pool.rb:145:in `block in spawn_thread'"
```

</details>

**Comment by TomasBarry** [comment]
If you point me to where this serialization occurs I am happy to open a PR.

**Comment by TomasBarry** [comment]
Looking a bit, I assume the culprit is [this line](https://github.com/rmosolgo/graphql-ruby/blob/0c0beb3cb9dfeb8b315c567d137c624ae97f8bda/lib/graphql/argument.rb#L38) or [this line](https://github.com/rmosolgo/graphql-ruby/blob/0c0beb3cb9dfeb8b315c567d137c624ae97f8bda/lib/graphql/argument.rb#L126) (the former being what I would be more confident in). However, `Date.today == Object.new` returns `false so unless the `new_default_value` parameter is being set to `nil` somewhere further up the chain? I'll continue to pick at it.

**Comment by TomasBarry** [comment]
I have not yet tested this for certain but could it perhaps be [this line](https://github.com/rmosolgo/graphql-ruby/blob/a6487a0554624a235cb72f88478379270f6b7d43/lib/graphql/types/iso_8601_date.rb#L30) that upon an error returns `nil` when running `coerce_input`?
