### ISSUE TITLE
undefined method `keyword_arguments' when directive argument raises error

### ISSUE THREAD

**Issue by cocoahero** [rmosolgo/graphql-ruby#3522]
#### Description

When a directive's argument raises a `GraphQL::ExecutionError` from within the `prepare` callback, the runtime eventually crashes with:
```
undefined method `keyword_arguments' for #<GraphQL::ExecutionError: invalid argument> (NoMethodError)
```

#### Versions

`graphql` version: 1.12.10

#### GraphQL Schema

```ruby
class MyDirective < GraphQL::Schema::Directive
  locations GraphQL::Schema::Directive::QUERY

  argument :input, String, required: true, prepare: ->(input, ctx) {
    raise GraphQL::ExecutionError, "invalid argument"
  }
end

class QueryType < GraphQL::Schema::Object
  field :hello, String, null: false

  def hello
    "Hello World!"
  end
end

class Schema < GraphQL::Schema
  query QueryType

  directive MyDirective
end
```

#### Steps to Reproduce

```ruby
result = Schema.execute(<<~GQL)
query @myDirective(input: "hi") {
  hello
}
GQL

puts result.to_h
```

**Expected behavior**

As documented, the raised error should halt execution and be reported in the results' errors key.

**Actual behavior**

The GraphQL runtime crashes with a `NoMethodError`.

<details>
<summary>Exception Backtrace</summary>

```
32: from example.rb:26:in `<main>'
31: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/schema.rb:1653:in `execute'
30: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/schema.rb:1682:in `multiplex'
29: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:50:in `run_all'
28: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:60:in `run_queries'
27: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/tracing.rb:66:in `trace'
26: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
25: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
24: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
23: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
22: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
21: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
20: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
19: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
18: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
17: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
16: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
15: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
14: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
13: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
12: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
11: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `each'
10: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
9: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
8: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
7: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:85:in `begin_query'
6: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:49:in `begin_query'
5: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:76:in `evaluate'
4: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/tracing.rb:66:in `trace'
3: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:77:in `block in evaluate'
2: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:60:in `run_eager'
1: from /Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:443:in `resolve_with_directives'
/Users/jbaker/.gem/ruby/2.7.2/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:455:in `run_directive': undefined method `keyword_arguments' for #<GraphQL::ExecutionError: invalid argument> (NoMethodError)
```

</details>

**Comment by cocoahero** [comment]
I should note that when testing this same schema against `v1.12.12`, the exception is swallowed and passed to `MyDirective.resolve` as the argument's value instead of halting execution.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree the case should be handled better -- I think the error should be picked up by the runtime, added to the top-level "errors" key, and then the part of the query tagged by the directive should be skipped.
