### ISSUE TITLE
Subscription with argument of type [CustomTypeHere!]! fails

### ISSUE THREAD

**Issue by HavinLeung** [rmosolgo/graphql-ruby#3525]
**Describe the bug**

I have a subscription class which takes in an argument `input`, of type `[CustomTypeHere!]!`.
When I subscribe, the server spits out a `NoMethodError - undefined method 'arguments'` error

**Versions**

`graphql`: 1.12.12
`rails`: 6.1.3.2

**GraphQL schema**

```ruby
module Types
  class CustomTypeHere < Types::BaseInputObject
    description "Foo"

    argument :foo, GraphQL::Types::ID, required: false
    argument :bar, String, required: false
    argument :baz, Int, required: true

    validates required: { one_of: [:foo, :bar] }
  end
end

module Subscriptions
  class MySubscription < BaseSubscription
    argument :input, [Types::CustomTypeHere], required: true

    field :some_return, String, null: true
    field :errors, [Types::UserErrorType], null: false

    def authorized?(**args)
      false # it never gets this far
    end

    def subscribe(**args)
      {} # it never gets this far
    end
  end
end

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
subscription a {
  agencyProfileAdd(input: [{
    bar: "0",
    baz: 0
  }]) {
    someReturn
    errors {
      message
      path
    }
  }
}
```

**Steps to reproduce**

Run the subscription, check the error backtrace output in `rails s`

**Expected behavior**

Expect to at least hit the `#authorized?` method

**Actual behavior**

Never gets that far, some argument resolution logic seems to go wrong.

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
GraphqlChannel is transmitting the subscription confirmation
GraphqlChannel#execute({"query"=>"subscription a {\n  mySubscription(input: [{\n    baz: 0,\n    bar: \"0\"\n  }]) {\n    someReturn\n    errors {\n      message\n      path\n    }\n  }\n}\n", "variables"=>{}, "operationName"=>"a"})
Could not execute command from ({"command"=>"message", "identifier"=>"{\"channel\":\"GraphqlChannel\",\"channelId\":\"17a021e5170\"}", "data"=>"{\"query\":\"subscription a {\\n  mySubscription(input: [{\\n    baz: 0,\\n    bar: \\\"0\\\"\\n  }]) {\\n    someReturn\\n    errors {\\n      message\\n      path\\n    }\\n  }\\n}\\n\",\"variables\":{},\"operationName\":\"a\",\"action\":\"execute\"}"}) [NoMethodError - undefined method `arguments' for #<GraphQL::Schema::NonNull @of_type=#<GraphQL::Schema::List:0x00007fa03782a878 @of_type=#<GraphQL::Schema::NonNull @of_type=Types::CustomTypeHere>, @to_non_null_type=#<GraphQL::Schema::NonNull @of_type=#<GraphQL::Schema::List:0x00007fa03782a878 ...>>>>]: /Users/havinleung/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphql-1.12.12/lib/graphql/subscriptions/event.rb:102:in `get_arg_definition' | /Users/havinleung/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphql-1.12.12/lib/graphql/subscriptions/event.rb:79:in `block in stringify_args' | /Users/havinleung/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphql-1.12.12/lib/graphql/subscriptions/event.rb:76:in `each' | /Users/havinleung/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphql-1.12.12/lib/graphql/subscriptions/event.rb:76:in `stringify_args' | /Users/havinleung/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0/gems/graphql-1.12.12/lib/graphql/subscriptions/event.rb:95:in `stringify_args'
```

</details>

**Additional context**

I'm using ActionCable for subscriptions if that's relevant.
I've tried changing the arguments to `[String!]!` and it works perfectly, so it doesn't seem to be an issue with scalars.

**Comment by TheWongGuy** [comment]
Been doing some testing. This seems to affect all arguments to subscriptions that come in the type of a list.

Specifically in `events.rb` line 104.

```
def get_arg_definition(arg_owner, arg_name)
    arg_owner.arguments[arg_name] || arg_owner.arguments.each_value.find { |v| v.keyword.to_s == arg_name }
end
```

at some point `arg_owner` becomes the type `GraphQL::Schema::NonNull` which does not have the method `arguments`

**Comment by TheWongGuy** [comment]
Turns out `arg_owner.arguments` returns `BaseArguments` that are missing the @arguments method. So nested arguments are not passed down
