### ISSUE TITLE
Directive with overridden scalar argument causes DuplicateTypeNamesError when building definition

### ISSUE THREAD

**Issue by alex4787** [rmosolgo/graphql-ruby#3529]
When using `GraphQL::Schema.from_definition` to build a schema from SDL, and the schema file contains a directive with an argument of a custom scalar type that overrides a built-in GraphQL type (in this case `ID`), a `DuplicateTypeNamesError` is raised.

**Versions**

`graphql` version: 1.12.12 (and any 1.12.x version - no exception is raised for versions 1.11.x)

**GraphQL schema**

`schema.graphql`:

```graphql
schema {
  query: QueryRoot
}

directive @myDirective(id: ID) on MUTATION | QUERY

scalar ID

type QueryRoot {}
```

**Steps to reproduce**

Call `GraphQL::Schema.from_definition("schema.graphql")` (where `schema.graphql` is defined above)

**Expected behavior**

A runable schema should be built.

**Actual behavior**

Instead, an `DuplicateTypeNamesError` is raised.

<details>
<summary>Click to view exception backtrace</summary>

```
Traceback (most recent call last):
        21: from index.rb:5:in `<main>'
        20: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:781:in `from_definition'
        19: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:19:in `from_definition_path'
        18: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:23:in `from_document'
        17: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:106:in `build'
        16: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:106:in `new'
        15: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:106:in `initialize'
        14: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/build_from_definition.rb:129:in `block in build'
        13: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1576:in `directives'
        12: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1576:in `each'
        11: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1576:in `block in directives'
        10: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1586:in `directive'
         9: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1718:in `add_type_and_traverse'
         8: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema.rb:1718:in `new'
         7: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:17:in `initialize'
         6: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:44:in `add_type_and_traverse'
         5: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:44:in `each'
         4: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:44:in `block in add_type_and_traverse'
         3: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:164:in `add_type'
         2: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:164:in `each'
         1: from /Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:167:in `block in add_type'
/Users/alexchan/.gem/ruby/2.7.1/gems/graphql-1.12.12/lib/graphql/schema/addition.rb:153:in `add_type': Multiple definitions for `ID`. Previously found #<Class:0x00007fc69c994660> (Class), then found GraphQL::Types::ID (Class) at myDirective.id (GraphQL::Schema::DuplicateTypeNamesError)
```
</details>

**Comment by rmosolgo** [comment]
Thanks for the detailed bug report! Here's where directives are created from the parsed document: 

https://github.com/rmosolgo/graphql-ruby/blob/b06c54ecfce5b5611d919c81fbb709aee4f48334/lib/graphql/schema/build_from_definition.rb#L46-L63

It has a special type resolver, but it assumes that built-in scalars are used. Evidently, that's not always true 😅 ! 

It seems like `BUILT_IN_SCALARS` should _not_ be used as the default lookup hash passed to `build_resolve_type(...)` (instead, maybe an empty hash should be used?), and instead, `BUILT_IN_SCALARS` should be used as a fallback when the `.find { ... }` call returns `nil`. 

I'll try to take a look soon, but if anyone wants to take a shot at this in the meantime, I'd be happy to review a PR!
