### ISSUE TITLE
`add_directives_from': undefined method `directives' for Operations::Mutation:Class (NoMethodError)

### ISSUE THREAD

**Issue by gastonmorixe** [rmosolgo/graphql-ruby#3545]
**Describe the bug**

This error happens after making the base mutation to inherit from `GraphQL::Schema::RelayClassicMutation` instead of our own `::Types::Base::Object`

```
lib/graphql/schema/addition.rb:37:in `add_directives_from': undefined method `directives' for Operations::Mutation:Class (NoMethodError)
```

**Versions**

`graphql` version: 1.12.13
`rails`: 6.0.3.7
`ruby`: ruby 2.7.3p183

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
module Types
  module Base
    class Mutation < GraphQL::Schema::RelayClassicMutation
      argument_class ::Types::Base::Argument
      field_class ::Types::Base::Field
      input_object_class ::Types::Base::InputObject
      object_class ::Types::Base::Object
    end
  end
end
```

Note: We have PRO version too

```
Traceback (most recent call last):
	111: from bin/rails:6:in `<main>'
	110: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	109: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
	108: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
	107: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	106: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	105: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	104: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	103: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	102: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands.rb:18:in `<main>'
	101: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/command.rb:46:in `invoke'
	100: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/command/base.rb:69:in `perform'
	 99: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
	 98: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
	 97: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
	 96: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/server/server_command.rb:138:in `perform'
	 95: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/server/server_command.rb:138:in `tap'
	 94: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/server/server_command.rb:147:in `block in perform'
	 93: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/server/server_command.rb:37:in `start'
	 92: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/commands/server/server_command.rb:77:in `log_to_stdout'
	 91: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:422:in `wrapped_app'
	 90: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:249:in `app'
	 89: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/server.rb:349:in `build_app_and_options_from_config'
	 88: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:66:in `parse_file'
	 87: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:105:in `load_file'
	 86: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `new_from_string'
	 85: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/rack-2.2.3/lib/rack/builder.rb:116:in `eval'
	 84: from config.ru:5:in `block in <main>'
	 83: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `require'
	 82: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
	 81: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:324:in `block in require'
	 80: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/zeitwerk-2.4.2/lib/zeitwerk/kernel.rb:34:in `require'
	 79: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	 78: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	 77: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	 76: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	 75: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	 74: from /Users/gastonmorixe/Desktop/RR/code/server/config/environment.rb:15:in `<main>'
	 73: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application.rb:363:in `initialize!'
	 72: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:60:in `run_initializers'
	 71: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:205:in `tsort_each'
	 70: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:226:in `tsort_each'
	 69: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each_strongly_connected_component'
	 68: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `call'
	 67: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:347:in `each'
	 66: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:349:in `block in each_strongly_connected_component'
	 65: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:431:in `each_strongly_connected_component_from'
	 64: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:350:in `block (2 levels) in each_strongly_connected_component'
	 63: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/2.7.0/tsort.rb:228:in `block in tsort_each'
	 62: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:61:in `block in run_initializers'
	 61: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:32:in `run'
	 60: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/initializable.rb:32:in `instance_exec'
	 59: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application/finisher.rb:129:in `block in <module:Finisher>'
	 58: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:51:in `run_load_hooks'
	 57: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:51:in `each'
	 56: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:52:in `block in run_load_hooks'
	 55: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:66:in `execute_hook'
	 54: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:61:in `with_execution_control'
	 53: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/lazy_load_hooks.rb:68:in `block in execute_hook'
	 52: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/devise-jwt-0.5.9/lib/devise/jwt/railtie.rb:13:in `block (2 levels) in <class:Railtie>'
	 51: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application.rb:169:in `reload_routes!'
	 50: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application/routes_reloader.rb:20:in `reload!'
	 49: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application/routes_reloader.rb:40:in `load_paths'
	 48: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application/routes_reloader.rb:40:in `each'
	 47: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/railties-6.0.3.7/lib/rails/application/routes_reloader.rb:40:in `block in load_paths'
	 46: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `load'
	 45: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:291:in `load_dependency'
	 44: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:318:in `block in load'
	 43: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 42: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 41: from /Users/gastonmorixe/Desktop/RR/code/server/config/routes.rb:5:in `<main>'
	 40: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:408:in `draw'
	 39: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:426:in `eval_block'
	 38: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:426:in `instance_exec'
	 37: from /Users/gastonmorixe/Desktop/RR/code/server/config/routes.rb:824:in `block in <main>'
	 36: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/mapper.rb:1016:in `constraints'
	 35: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/mapper.rb:887:in `scope'
	 34: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/mapper.rb:1016:in `block in constraints'
	 33: from /Users/gastonmorixe/Desktop/RR/code/server/config/routes.rb:825:in `block (2 levels) in <main>'
	 32: from /Users/gastonmorixe/Desktop/RR/code/server/config/routes.rb:722:in `app_no_auth_routes'
	 31: from /Users/gastonmorixe/Desktop/RR/code/server/config/routes.rb:718:in `block in app_no_auth_routes'
	 30: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:214:in `const_missing'
	 29: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:60:in `load_missing_constant'
	 28: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	 27: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:61:in `block in load_missing_constant'
	 26: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:544:in `load_missing_constant'
	 25: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:48:in `require_or_load'
	 24: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:17:in `allow_bootsnap_retry'
	 23: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/active_support.rb:49:in `block in require_or_load'
	 22: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:389:in `require_or_load'
	 21: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:40:in `load_interlock'
	 20: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies/interlock.rb:13:in `loading'
	 19: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/concurrency/share_lock.rb:151:in `exclusive'
	 18: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies/interlock.rb:14:in `block in loading'
	 17: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:40:in `block in load_interlock'
	 16: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:406:in `block in require_or_load'
	 15: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:509:in `load_file'
	 14: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:701:in `new_constants_in'
	 13: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/activesupport-6.0.3.7/lib/active_support/dependencies.rb:510:in `block in load_file'
	 12: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 11: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/bootsnap-1.4.9/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:59:in `load'
	 10: from /Users/gastonmorixe/Desktop/RR/code/server/app/graphql/rocket_referrals_schema.rb:1:in `<main>'
	  9: from /Users/gastonmorixe/Desktop/RR/code/server/app/graphql/rocket_referrals_schema.rb:10:in `<class:RocketReferralsSchema>'
	  8: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema.rb:1053:in `mutation'
	  7: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema.rb:1718:in `add_type_and_traverse'
	  6: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema.rb:1718:in `new'
	  5: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:17:in `initialize'
	  4: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:44:in `add_type_and_traverse'
	  3: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:44:in `each'
	  2: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:44:in `block in add_type_and_traverse'
	  1: from /Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:174:in `add_type'
/Users/gastonmorixe/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0/gems/graphql-1.12.13/lib/graphql/schema/addition.rb:37:in `add_directives_from': undefined method `directives' for Operations::Mutation:Class (NoMethodError)
```

**Comment by gastonmorixe** [comment]
My bad, I confused Mutation Type operation with Mutation Base.
