### ISSUE TITLE
Backtrace seems broken in 1.12.13

### ISSUE THREAD

**Issue by sayduck-daniel** [rmosolgo/graphql-ruby#3550]
It seems there is a bug with this file https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/backtrace/tracer.rb

I wrote this simple code for you to reproduce this bug.

Anything I'm missing here?

```ruby
class Query < GraphQL::Schema::Object
  field :name, String, null: false
  def name
    'foo'
  end
end

class Test1Schema < GraphQL::Schema
  query Query
end

Test1Schema.multiplex([
  { query: 'query { name }' },
  { query: 'query { name }' }
])
```

I get the expected result:

```console
 [#<GraphQL::Query::Result @query=... @to_h={"data"=>{"name"=>"foo"}}>, #<GraphQL::Query::Result @query=... @to_h={"data"=>{"name"=>"foo"}}>]
```

When I add Backtrace:
```ruby
class Test2Schema < GraphQL::Schema
  use GraphQL::Backtrace
  query Query
end

Test2Schema.multiplex(batched_queries[:_json].map { |query| query.merge(context: context) })
```

I get this error:

```console
Traceback (most recent call last):
        1: from (irb):26
GraphQL::Backtrace::TracedError (Unhandled error during GraphQL execution:)

  undefined method `first' for nil:NilClass
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/backtrace/tracer.rb:18:in `trace'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/tracing.rb:83:in `call_tracers'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/tracing.rb:67:in `trace'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/interpreter.rb:93:in `sync_lazies'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/interpreter.rb:54:in `finish_multiplex'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/multiplex.rb:111:in `block in run_as_multiplex'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/multiplex.rb:110:in `run_as_multiplex'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
    /bundle/ruby/2.7.0/gems/graphql-1.12.13/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
    ... and 55 more lines

Use #cause to access the original exception (including #cause.backtrace).

GraphQL Backtrace:
Loc  | Field      | Object | Arguments | Result
1:9  | Query.name | nil    | {}        | #<NoMethodError: undefined method `first' for nil:NilClass>
1:1  | query      | nil    | {}        | {name: "foo"}
```

This send me to https://github.com/rmosolgo/graphql-ruby/blob/a41ac2252dc71c1b481fcf75e7a76834f5161ca9/lib/graphql/backtrace/tracer.rb#L18

But I'm not sure what to do here.

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I'm not sure what it is, but I'll take a look soon.

**Comment by sayduck-daniel** [comment]
@rmosolgo did you have a chance to look at it? If you run the sniper code, it will be self explanatory what is happening.

**Comment by rmosolgo** [comment]
Finally got a chance to take a look, sorry about the delay!

**Comment by sayduck-daniel** [comment]
Thanks! Will test on the next release.
