### ISSUE TITLE
Creating a custom Connection: protected method `new' called for Types::ProductConnection:Class

### ISSUE THREAD

**Issue by tiimgreen** [rmosolgo/graphql-ruby#3555]
I want to create a custom connection to fetch data - I have the following:

```ruby
module Types
  class QueryType < Types::BaseObject
    field :product_variants, Types::ProductVariantType.connection_type, null: false do
      argument :product_id, ID, required: true
    end

    def product_variants(product_id:)
      product = Product.find(product_id)
      Types::ProductVariantConnection.new(product.variants)
    end
  end
end
```

```ruby
module Types
  class ProductVariantType < Types::BaseObject
    ...
  end
end
```

```ruby
module Types
  class ProductVariantConnection < Types::BaseConnection
    edge_type(Types::ProductVariantEdge)

    def nodes; ... end

    def cursor_for(item); ... end

    # etc
  end
end
```

```ruby
module Types
  class ProductVariantEdge < Types::BaseEdge
    node_type(Types::ProductVariantType)
  end
end
```

**Versions**

`graphql` version: 1.12.10
`rails` (or other framework): 6.0.3.7
other applicable versions (`graphql-batch`, etc): graphql-client (0.16.0)

**GraphQL query**

e.g.:

```graphql
productVariants(productId: 1, first: 10) {
  edges {
    cursor
    node {
      id
    }
  }
}
```

**Expected behavior**

To allow me to use my custom connection

**Actual behavior**

The following error:

```
protected method `new' called for Types::ProductVariantConnection:Class
```

<details>
<summary>Click to view exception backtrace</summary>

```
┃ protected method `new' called for Types::ProductVariantConnection:Class
┃ /Users/tim/code/test_app/app/graphql/types/query_type.rb:30:in `product_variants'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:714:in `public_send'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:714:in `block in public_send_field'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:757:in `block in with_extensions'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:787:in `block (2 levels) in run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:787:in `block (2 levels) in run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:790:in `run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:787:in `block in run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field/connection_extension.rb:21:in `resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:780:in `run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:787:in `block in run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field_extension.rb:50:in `resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:780:in `run_extensions_before_resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:756:in `with_extensions'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:696:in `public_send_field'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:609:in `block in resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema.rb:115:in `after_lazy'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/field.rb:607:in `resolve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:281:in `block (4 levels) in evaluate_selection_with_args'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/tracing.rb:66:in `trace'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:280:in `block (3 levels) in evaluate_selection_with_args'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/query.rb:362:in `block in with_error_handling'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/errors.rb:107:in `with_error_handling'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/query.rb:361:in `with_error_handling'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:279:in `block (2 levels) in evaluate_selection_with_args'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:442:in `resolve_with_directives'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:276:in `block in evaluate_selection_with_args'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:526:in `after_lazy'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:217:in `evaluate_selection_with_args'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:209:in `block in evaluate_selection'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/member/has_arguments.rb:132:in `block (2 levels) in coerce_arguments'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/member/has_arguments.rb:111:in `block in coerce_arguments'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/member/has_arguments.rb:110:in `each'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema/member/has_arguments.rb:110:in `coerce_arguments'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/arguments_cache.rb:49:in `dataload_for'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:208:in `evaluate_selection'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:145:in `block (2 levels) in evaluate_selections'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:144:in `block in evaluate_selections'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:143:in `each'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:143:in `evaluate_selections'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:64:in `block (2 levels) in run_eager'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:63:in `block in run_eager'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:442:in `resolve_with_directives'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter/runtime.rb:60:in `run_eager'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:77:in `block in evaluate'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/tracing.rb:66:in `trace'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:76:in `evaluate'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/interpreter.rb:49:in `begin_query'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:85:in `begin_query'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/dataloader/null_dataloader.rb:16:in `append_job'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `each'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/tracing.rb:66:in `trace'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:60:in `run_queries'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/execution/multiplex.rb:50:in `run_all'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema.rb:1682:in `multiplex'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/graphql-1.12.10/lib/graphql/schema.rb:1653:in `execute'
┃ /Users/tim/code/test_app/app/controllers/graphql_controller.rb:15:in `execute'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:195:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/rendering.rb:30:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:42:in `block in process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:112:in `block in run_callbacks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/shopify_app-18.0.1/lib/shopify_app/controller_concerns/login_protection.rb:33:in `activate_shopify_session'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/react-rails-2.6.1/lib/react/rails/controller_lifecycle.rb:31:in `use_react_component_helper'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:121:in `block in run_callbacks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:139:in `run_callbacks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/abstract_controller/callbacks.rb:41:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/rescue.rb:22:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:33:in `block in process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `block in instrument'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/notifications.rb:180:in `instrument'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/instrumentation.rb:32:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal/params_wrapper.rb:245:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.7/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/abstract_controller/base.rb:136:in `process'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionview-6.0.3.7/lib/action_view/rendering.rb:39:in `process'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:190:in `dispatch'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_controller/metal.rb:254:in `dispatch'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:33:in `serve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:49:in `block in serve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `each'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/journey/router.rb:32:in `serve'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/routing/route_set.rb:834:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:202:in `call!'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/omniauth-2.0.4/lib/omniauth/strategy.rb:169:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/omniauth-2.0.4/lib/omniauth/builder.rb:45:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/tempfile_reaper.rb:15:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/etag.rb:27:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/conditional_get.rb:40:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/head.rb:12:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/http/content_security_policy.rb:18:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:266:in `context'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/session/abstract/id.rb:260:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/cookies.rb:648:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activerecord-6.0.3.7/lib/active_record/migration.rb:567:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/callbacks.rb:101:in `run_callbacks'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/callbacks.rb:26:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/debug_exceptions.rb:32:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/web-console-4.1.0/lib/web_console/middleware.rb:132:in `call_app'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/web-console-4.1.0/lib/web_console/middleware.rb:19:in `block in call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `catch'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/web-console-4.1.0/lib/web_console/middleware.rb:17:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:37:in `call_app'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `block in call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80:in `block in tagged'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:28:in `tagged'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/tagged_logging.rb:80:in `tagged'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.7/lib/rails/rack/logger.rb:26:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/sprockets-rails-3.2.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/request_id.rb:27:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/method_override.rb:24:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/shopify_app-18.0.1/lib/shopify_app/middleware/jwt_middleware.rb:23:in `call_next'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/shopify_app-18.0.1/lib/shopify_app/middleware/jwt_middleware.rb:17:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/shopify_app-18.0.1/lib/shopify_app/middleware/same_site_cookie_middleware.rb:11:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/runtime.rb:22:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/activesupport-6.0.3.7/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/executor.rb:14:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/static.rb:126:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-2.2.3/lib/rack/sendfile.rb:110:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/actionpack-6.0.3.7/lib/action_dispatch/middleware/host_authorization.rb:82:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/webpacker-4.3.0/lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/rack-proxy-0.6.5/lib/rack/proxy.rb:57:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/railties-6.0.3.7/lib/rails/engine.rb:527:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/puma-4.3.8/lib/puma/configuration.rb:228:in `call'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/puma-4.3.8/lib/puma/server.rb:718:in `handle_request'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/puma-4.3.8/lib/puma/server.rb:472:in `process_client'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/puma-4.3.8/lib/puma/server.rb:328:in `block in run'
┃ /Users/tim/.rvm/gems/ruby-2.7.1/gems/puma-4.3.8/lib/puma/thread_pool.rb:134:in `block in spawn_thread'
```

</details>

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. 

The issue here is, there are really _two_ classes required for a custom connection: 

1. A connection _type_ which describes the GraphQL interface for the connection. It declares fields like `nodes`, `edges`, and perhaps `totalCount`. This class inherits from `Types::BaseConnection` like your `ProductVariantConnection` above. ([doc](https://graphql-ruby.org/pagination/custom_connections#connection-type))
2. A connection _wrapper_ which implements pagination methods according to the underlying backend. This should extend `GraphQL::Pagination::Connection` (or one of its subclasses, [doc](https://graphql-ruby.org/pagination/custom_connections#connection-wrapper)). This class should implement methods like `nodes`, `has_next_page`, `has_previous_page`, and `cursor_for(item)`. 


The connection _type_ is initialized by graphql-ruby _only_ -- that's why you're getting the error described above. Instead, you should define a connection _wrapper_ class and initialize _that_ in your resolver. (The connection _type_ will be used by GraphQL-Ruby during execution, like any other GraphQL object type.) 

I hope that helps! If you try implementing a connection wrapper and run into trouble, please let me know.

**Comment by tiimgreen** [comment]
Amazing, thank you. This works now.
