### ISSUE TITLE
Mongoid 7.3.1 - Relay Connection Nil

### ISSUE THREAD

**Issue by caseyprovost** [rmosolgo/graphql-ruby#3587]
**Describe the bug**

* Upgraded Mongoid from 7.2.1 to 7.3.1
* Observe all `Mongoid::Association::Referenced::HasMany::Targets::Enumerable` causes an exception, as that module has been removed.
* Switch the relay call

```ruby
### old 
GraphQL::Relay::BaseConnection.register_connection_implementation(
  Mongoid::Association::Referenced::HasMany::Targets::Enumerable,
  GraphQL::Relay::MongoRelationConnection
)

GraphQL::Relay::BaseConnection.register_connection_implementation(
  Mongoid::Association::Referenced::HasMany::Enumerable,
  GraphQL::Relay::MongoRelationConnection
)
```
* Observe new exception (missing wrapper class)

```
Caused by NoMethodError: undefined method `new' for nil:NilClass
from /bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/relay/range_add.rb:41:in `initialize'
```

```ruby
# Mutation code

# frozen_string_literal: true

module Legacy
  module Mutations
    module LegacyReport
      module Entry
        class CreateMutation < BaseMutation
          graphql_name 'CreateReportEntry'
          description 'Creates a new entry in a report'

          field :report, Legacy::Types::ReportType, null: true
          field :report_entries_connection, Legacy::Types::ReportEntryType.connection_type, null: true
          field :new_entry_edge, Legacy::Types::ReportEntryType.edge_type, null: true

          argument :id, ID, as: :report, loads: Legacy::Types::ReportType, pundit_role: :update, required: true
          argument :position, Int, required: true
          argument :item_type, String, required: false
          argument :page_break, Boolean, required: false

          def resolve(arguments)
            report = arguments.delete(:report)

            input = Reports::Entries::CreateInput.new(arguments.to_h)
            result = Reports::Entries::CreateInteractor.call(report: report, input: input)

            if result.success?
              range_add = GraphQL::Relay::RangeAdd.new(
                parent: report,
                collection: report.report_entries,
                item: result.entry,
                context: context
              )

              {
                report: report,
                report_entries_connection: range_add.connection,
                new_entry_edge: range_add.edge,
                errors: []
              }
            else
              {
                report: nil,
                report_entries_connection: nil,
                new_entry_edge: nil,
                errors: user_errors_from_errors(result.errors)
              }
            end
          end
        end
      end
    end
  end
end
```

**Versions**

`graphql` graphql-pro (1.18.2)
`rails` (or other framework): Rails 6.1.4
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

```ruby
# frozen_string_literal: true

class Report
  include Mongoid::Document
  include Mongoid::Timestamps

  searchkick(
    callbacks: :queue,
    highlight: [:title, :subtitle],
    word_start: [:title, :subtitle],
    searchable: [:title, :subtitle]
  )

  has_many :report_entries, dependent: :destroy
  embeds_one :report_settings, autobuild: true
  embeds_one :cover_page_settings, class_name: 'ReportCoverPageSetting', autobuild: true
  belongs_to :featured_entry, class_name: 'ReportEntry', foreign_key: 'featured_id', optional: true

  field :creator_id, type: Integer
  field :project_id, type: Integer
  field :company_id, type: Integer
  field :title, type: String
  field :subtitle, type: String

  validates :creator_id, :company_id, presence: true
  validates :title, length: { maximum: 100 }
  validates :subtitle, length: { maximum: 500 }

  index({ company_id: 1, updated_at: -1 })
  index({ company_id: 1, title: 'text', subtitle: 'text' }, { background: true })
  index({ project_id: 1 })
  index({ creator_id: 1 })

  def search_data
    {
      id: id.to_s,
      company_id: company_id,
      creator_id: creator_id,
      project_id: project_id,
      title: title,
      subtitle: subtitle,
      updated_at: updated_at
    }
  end

  def creator_type
    'User'
  end

  def creator
    User.find_by(id: creator_id)
  end

  def as_json(options = nil)
    json = super
    json['id'] = id.to_s
    json['_id'] = id.to_s
    json['featured_id'] = featured_id&.to_s
    json
  end

  def node_id
    Legacy::CompanyCamSchema.id_from_object(self, nil, nil)
  end
end

# frozen_string_literal: true

module Legacy
  module Types
    class ReportEntryType < BaseObject
      graphql_name 'ReportEntry'
      description 'An entry in a report'
      implements GraphQL::Types::Relay::Node

      global_id_field :id

      field :featured, Boolean, null: true
      field :position, Int, null: true
      field :item, Legacy::Types::ReportEntryItemType, null: true
      field :page_break, Boolean, null: true
      field :notes, String, null: true

      def item
        return nil unless has_loadable_item?(object)
        Loaders::RecordLoader.for(object.item_type).load(object.item_id)
      end

    private

      def has_loadable_item?(object)
        object.item_type.present? && object.item_type == 'Image'
      end

    end
  end
end

# frozen_string_literal: true

module Legacy
  class CompanyCamSchema < GraphQL::Schema
    use GraphQL::Batch
    use GraphQL::Tracing::ScoutTracing
    use GraphQL::Pro::PusherSubscriptions, redis: Redis.new(url: Rails.application.config.legacy_graphql_subscription_redis_url)

    tracer Tracers::DatabaseConnectionTracer.new

    mutation Legacy::Types::MutationType
    query Legacy::Types::QueryType
    subscription Legacy::Types::SubscriptionType
    cursor_encoder Legacy::UrlSafeEncoder

    default_max_page_size 100

    instrument :query, Legacy::Instrumentations::RestrictMutationsToPayingCustomers

    connections.add(ActiveRecord::Relation, GraphQL::Pro::PostgresStableRelationConnection)
    connections.add(AssetFeedQueryResult, Connections::AssetFeedConnection)
    connections.add(SearchFlip::Criteria, Connections::SearchFlipCriteriaConnection)
    connections.add(SearchFlip::RecentProjectCriteria, Connections::SearchFlipRecentProjectCriteriaConnection)
    connections.add(GraphQL::Searchkick::LazySearch, GraphQL::Searchkick::ResultConnection)

    def self.scope_for_company(company)
      company&.id
    end

    def self.resolve_type(type, obj, ctx)
      case obj
      when JobNimbus, TeamUp, Zapier
        "Types::Integrations::#{obj.class}Type".constantize
      when Image
        Legacy::Types::PhotoType
      when Location
        Legacy::Types::ProjectType
      else
        super(type, obj, ctx)
      end
    rescue GraphQL::RequiredImplementationMissingError => error
      "Legacy::Types::#{obj.class}Type".constantize
    end

    def self.decode_id(id)
      Legacy::UrlSafeEncoder.decode(id)
    end

    def self.object_from_id(id, query_ctx)
      begin
        node = GlobalID::Locator.locate(decode_id(id))
      rescue ArgumentError
      end

      raise ActiveRecord::RecordNotFound unless node
      node
    end

    def self.id_from_object(object, type_definition = nil, query_ctx = nil)
      Legacy::UrlSafeEncoder.encode(object.to_global_id.to_s)
    end

    def self.model_id_from_node_id(node_id)
      GlobalID.parse(decode_id(node_id)).model_id
    end

    def self.database_id_from_id(node_id)
      Integer(model_id_from_node_id(node_id))
    end

    def self.unauthorized_object(error)
      # change when https://github.com/rmosolgo/graphql-ruby/issues/2627 is addressed
      handler = rescues[error.class]
      if handler
        handler.call(error)
      else
        raise error
      end
    end

    rescue_from ActiveRecord::RecordNotFound do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new('Record not found', extensions: { code: :not_found })
    end

    rescue_from ActiveRecord::RecordInvalid do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new(err.record.errors.full_messages.join(', '), extensions: { code: :invalid })
    end

    rescue_from Mongoid::Errors::Validations do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new(err.document.errors.full_messages.join(', '), extensions: { messages: err.document.errors.messages, code: :invalid })
    end

    rescue_from ActiveRecord::RecordNotUnique do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new(err.message, extensions: { code: :not_unique })
    end

    rescue_from Pundit::NotAuthorizedError do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new('You are not authorized to perform this action', extensions: { code: :unauthorized })
    end

    rescue_from GraphQL::UnauthorizedError do |err, obj, args, ctx, field|
      object = err.object
      object_id = object.respond_to?(:to_global_id) ? object.to_global_id.to_s : object.to_s
      Rails.logger.info({ message: err.message, object: object_id }.to_json)
      raise GraphQL::ExecutionError.new('You are not authorized to perform this action', extensions: { code: :unauthorized })
    end

    rescue_from CompanyCam::NotAuthorizedError do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new(err.message, extensions: { code: :unauthorized })
    end

    rescue_from CompanyCam::UnauthenticatedError do |err, obj, args, ctx, field|
      raise GraphQL::ExecutionError.new(err.message, extensions: { code: :unauthenticated })
    end

    rescue_from StandardError do |err, obj, args, ctx, field|
      if Rails.application.config.log_full_backtrace
        Rails.logger.error(err.class)
        Rails.logger.error(err.message)
        Rails.logger.error(err.backtrace.join("\n"))
      end
      Honeybadger.notify(err)
      raise GraphQL::ExecutionError.new(err.message, extensions: { code: :unknown })
    end
  end
end

# Prime cache by loading schema
Legacy::CompanyCamSchema.graphql_definition

```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation legacyReportEntryCreate($input: CreateReportEntryInput!){
          legacyReportEntryCreate(input: $input){
            report {
              id
            }
            newEntryEdge {
              node {
                id
                position
                pageBreak
              }
            }
            errors {
              message
            }
          }
        }
```

**Steps to reproduce**

Taking existing working Mongoid implementation with Relay. Upgrade Mongoid to 7.3.1 from 7.2.1, observe failure

**Expected behavior**

Passing a mongoid relation as a collection to `GraphQL::Relay::RangeAdd` should work.

**Actual behavior**

Exception

Caused by NoMethodError: undefined method `new' for nil:NilClass
from /bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/relay/range_add.rb:41:in `initialize

```
=> ["/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/relay/range_add.rb:41:in `initialize'",
 "/app/app/graphql/legacy/mutations/legacy_report/entry/create_mutation.rb:27:in `new'",
 "/app/app/graphql/legacy/mutations/legacy_report/entry/create_mutation.rb:27:in `resolve'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/resolver.rb:108:in `public_send'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/resolver.rb:108:in `block (3 levels) in resolve_with_support'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema.rb:116:in `after_lazy'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/resolver.rb:96:in `block (2 levels) in resolve_with_support'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema.rb:116:in `after_lazy'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/resolver.rb:87:in `block in resolve_with_support'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema.rb:116:in `after_lazy'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/resolver.rb:76:in `resolve_with_support'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/relay_classic_mutation.rb:64:in `resolve_with_support'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:714:in `public_send'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:714:in `block in public_send_field'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:750:in `with_extensions'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:696:in `public_send_field'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:609:in `block in resolve'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema.rb:116:in `after_lazy'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/schema/field.rb:607:in `resolve'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:495:in `block (4 levels) in evaluate_selection_with_args'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:81:in `call_tracers'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:83:in `block in call_tracers'",
 "/app/app/graphql/tracers/database_connection_tracer.rb:19:in `trace'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:83:in `call_tracers'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:83:in `block in call_tracers'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing/platform_tracing.rb:52:in `block in trace'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing/scout_tracing.rb:37:in `block in platform_trace'",
 "/bundle/ruby/2.6.0/gems/scout_apm-2.6.7/lib/scout_apm/tracer.rb:34:in `instrument'",
 "/bundle/ruby/2.6.0/gems/scout_apm-2.6.7/lib/scout_apm/tracer.rb:44:in `instrument'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing/scout_tracing.rb:36:in `platform_trace'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing/platform_tracing.rb:51:in `trace'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:83:in `call_tracers'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/tracing.rb:67:in `trace'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:494:in `block (3 levels) in evaluate_selection_with_args'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/query.rb:362:in `block in with_error_handling'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/errors.rb:107:in `with_error_handling'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/query.rb:361:in `with_error_handling'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:493:in `block (2 levels) in evaluate_selection_with_args'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:779:in `resolve_with_directives'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:490:in `block in evaluate_selection_with_args'",
 "/bundle/ruby/2.6.0/gems/graphql-1.12.14/lib/graphql/execution/interpreter/runtime.rb:878:in `after_lazy'",
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
i! It looks like it's failing to find a connection wrapper for the list of items given to `RangeAdd.new`: 

https://github.com/rmosolgo/graphql-ruby/blob/efd0711298bde27c7ff23cb6c70f675da564affc/lib/graphql/relay/range_add.rb#L39-L41

What does `report.report_entries.class` return? That class, or a superclass, should be setup with:

```ruby
GraphQL::Relay::BaseConnection.register_connection_implementation(
  <class here>,
  GraphQL::Relay::MongoRelationConnection
)
```

Let me know what you find and we can keep looking if that doesn't fix it!
