### ISSUE TITLE
Using `context` as a parameter in mutation breaks resolution

### ISSUE THREAD

**Issue by tmtrademarked** [rmosolgo/graphql-ruby#3611]
When providing the name `context` as a field for an input object to a mutation, it appears that some wire gets crossed in the schema resolution and produces an error. (`market` is the particular value of the `context` field in this particular example).

```
[afff0309-f076-4821-aa90-98b03d606c38] [::1]   
[afff0309-f076-4821-aa90-98b03d606c38] [::1] NoMethodError (undefined method `schema' for :market:Symbol):
[afff0309-f076-4821-aa90-98b03d606c38] [::1]   
[afff0309-f076-4821-aa90-98b03d606c38] [::1] app/controllers/graphql_controller.rb:31:in `execute'
[afff0309-f076-4821-aa90-98b03d606c38] [::1] lib/middleware/version_endpoint.rb:16:in `call'
[afff0309-f076-4821-aa90-98b03d606c38] [::1] lib/middleware/force_admin.rb:15:in `call'
[afff0309-f076-4821-aa90-98b03d606c38] [::1] lib/middleware/force_www.rb:13:in `call'
```

**Versions**

`graphql` version: 1.12.16
`rails` (or other framework): 6.0.3.7
other applicable versions (`graphql-batch`, etc): graphql-pro 1.18.3

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?
** We are using the interpreter because we have it enabled by default.
** We use two custom analyzers, the GraphQL Pro operation store, and the DataDog tracer

```ruby
class CreateCartInput < Types::BaseInputObject
  description 'Input object for creating a cart.'

  argument :context, Types::Enums::CartContext, required: true do
    description 'The context of cart to create.'
  end
end

class CartContext < Types::BaseEnum
  description 'The context in which a cart was created.'

  GIFT_CARD = :gift_card
  MARKET = :market
  SUBSCRIPTION_FOOD = :subscription_food
  SUBSCRIPTION_WINE = :subscription_wine

  value 'GIFT_CARD', value: GIFT_CARD do
    description 'Cart used for gift cards only.'
  end
  value 'MARKET', value: MARKET do
    description 'Cart used for marketplace orders.'
  end
  value 'SUBSCRIPTION_FOOD', value: SUBSCRIPTION_FOOD do
    description 'Cart belonging to a food subscription.'
  end
  value 'SUBSCRIPTION_WINE', value: SUBSCRIPTION_WINE do
    description 'Cart belonging to a wine subscription.'
  end
end

module Mutations
  class CreateCart < BaseMutation
    description 'Create a cart given the specified options. Note that for now, '\
                'this only works for Agora-backed carts.'

    argument :input, Types::Inputs::CreateCartInput, required: true

    field :cart, Types::Models::Cart, null: true do
      description 'The resulting cart after creation.'
    end

    def resolve(*)
      mutator.apply_mutation
    end
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation ScratchPad {
  createCart(input: {
    context: MARKET
  }) {
    cart {
      id
    }
    clientErrors {
      message
    }
  }
}
```

**Expected behavior**

Mutation is expected to run without errors.

**Actual behavior**

Query resolution raised an error trying to execute a method on the `context` variable. It appears to be mistaking the input field for the `context` of the evaluation somewhere in the stack. If I change the parameter on the input object from `context` to `cartContext`, the mutation runs correctly.

```
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] Started POST "/graphql" for ::1 at 2021-09-08 11:23:29 -0400
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] Processing by GraphqlController#execute as JSON
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1]   Parameters: {"query"=>"mutation ScratchPad {\n  createCart(input: {\n    context: MARKET,\n    idempotencyToken: \"fake_uuid\"\n  }) {\n    cart {\n      id\n    }\n    clientErrors {\n      message\n    }\n  }\n}", "variables"=>{}, "operationName"=>"ScratchPad", "graphql"=>{"query"=>"mutation ScratchPad {\n  createCart(input: {\n    context: MARKET,\n    idempotencyToken: \"fake_uuid\"\n  }) {\n    cart {\n      id\n    }\n    clientErrors {\n      message\n    }\n  }\n}", "variables"=>{}, "operationName"=>"ScratchPad"}}
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1]   User Load (3.7ms)  SELECT "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 2411031], ["LIMIT", 1]]
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1]   ↳ app/helpers/api/devise_helper.rb:84:in `current_api_user'
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] [Analyzers::DepthMonitor] Query ScratchPad has depth 3
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] [Analyzers::ComplexityMonitor] Query ScratchPad has complexity 5
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] Completed 500 Internal Server Error in 581ms (ActiveRecord: 202.5ms | Allocations: 41117)


[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1]   
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] NoMethodError (undefined method `schema' for :market:Symbol):
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1]   
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] app/controllers/graphql_controller.rb:31:in `execute'
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] lib/middleware/version_endpoint.rb:16:in `call'
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] lib/middleware/force_admin.rb:15:in `call'
[5c7b3ce6-acc1-47d5-b845-5ebb4785a3e9] [::1] lib/middleware/force_www.rb:13:in `call'
::1 - - [08/Sep/2021:11:23:29 EDT] "POST /graphql HTTP/1.1" 500 20660
```

**Comment by rmosolgo** [comment]
D'oh! Thanks for the detailed report. We have warnings for _fields_ called `context`, but I forgot about arguments. 

For now, I think you could use `as: :cart_context` with your argument: 

```ruby 
  argument :context, Types::Enums::CartContext, required: true, as: :cart_context do
    description 'The context of cart to create.'
  end
```

Then, reference it as `cart[:cart_context]` inside your mutation. That will prevent GraphQL-Ruby's generated method from conflicting with the normal `.context` method. 

I think it could be made to work with `cart[:context]`, it just can't build the `cart.context` helper method because of the conflict. I'll take a look and follow up here soon!
