### ISSUE TITLE
NoMethodError Exception: undefined method `map' for "":String

### ISSUE THREAD

**Issue by abatko** [rmosolgo/graphql-ruby#3618]
I'm getting `NoMethodError Exception: undefined method 'map' for "":String` after upgrading `graphql` to `1.12.16` from `1.12.8`.

Before the upgrade I was able to do the following in `bundle exec rails console`:

```
gch = GraphQL::Client::HTTP.new("https://www.wonderschool.com/graphql")
schema = GraphQL::Client.load_schema(gch)
```

...now I cannot. I can get around this by preceding [lib/graphql/schema/list.rb#L40](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/list.rb#L40) with the following line:
```
return nil if value.empty?
```
... i.e.
```
      def coerce_result(value, ctx)
        return nil if value.empty?
        value.map { |i| i.nil? ? nil : of_type.coerce_result(i, ctx) }
      end
```

I don't know if this is a problem with `graphql` or `https://www.wonderschool.com/graphql`. Please let me know how to proceed.

Not sure whether [this change](https://github.com/rmosolgo/graphql-ruby/commit/03c36db352b2e349ac5183f8342786a53087172b#diff-a189f501e454aa6a71e57bc49ea340c842a02cce563dd659463e7278d3282ea9L34) is relevant - mentioning it just in case.

**Versions**

`graphql` version: `1.12.16` (upgraded from `1.12.8`)
`rails`: `5.2.6` (upgraded from `5.2.5`)
`graphql-client`: `0.17.0` (upgraded from `0.16.0`)

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. Could you please share the full backtrace that comes with the error message? That will help me see what the code is doing when it encounters that error.

**Comment by abatko** [comment]
Thank you. Here are 30 lines from the backtrace:
```
30: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:61:in `block in run_initializers'
29: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `run'
28: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/initializable.rb:32:in `instance_exec'
27: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:619:in `block in <class:Engine>'
26: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:619:in `each'
25: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:620:in `block (2 levels) in <class:Engine>'
24: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:662:in `load_config_initializer'
23: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/notifications.rb:170:in `instrument'
22: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/railties-5.2.6/lib/rails/engine.rb:663:in `block in load_config_initializer'
21: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `load'
20: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:257:in `load_dependency'
19: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/activesupport-5.2.6/lib/active_support/dependencies.rb:285:in `block in load'
18: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
17: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/bootsnap-1.8.1/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:60:in `load'
16: from /Users/aba/Projects/care/care/config/initializers/wonderschool_api_config.rb:4:in `<main>'
15: from /Users/aba/Projects/care/care/config/initializers/wonderschool_api_config.rb:19:in `<module:WonderschoolAPIConfig>'
14: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-client-0.17.0/lib/graphql/client.rb:61:in `load_schema'
13: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-client-0.17.0/lib/graphql/client.rb:64:in `load_schema'
12: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-client-0.17.0/lib/graphql/client.rb:56:in `load_schema'
11: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema.rb:769:in `from_introspection'
10: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/loader.rb:35:in `load'
 9: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/loader.rb:35:in `new'
 8: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/loader.rb:35:in `initialize'
 7: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/loader.rb:36:in `block in load'
 6: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema.rb:1394:in `orphan_types'
 5: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema.rb:1737:in `add_type_and_traverse'
 4: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema.rb:1737:in `each'
 3: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema.rb:1738:in `block in add_type_and_traverse'
 2: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/argument.rb:301:in `validate_default_value'
 1: from /Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/member/validates_input.rb:28:in `coerce_isolated_result'
/Users/aba/.rbenv/versions/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.16/lib/graphql/schema/list.rb:46:in `coerce_result': undefined method `map' for "":String (NoMethodError)
```

**Comment by abatko** [comment]
I just downgraded back to `1.12.8`, and then upgraded through each patch and found that the exception is raised at `1.12.11`, so, [here's the change between `1.12.10` and `1.12.11`](https://github.com/rmosolgo/graphql-ruby/compare/v1.12.10...v1.12.11), in case that may help you. Please also let me know if there's anything I can do to help. It would be nice to know where to insert a `puts`, for example, to determine what in the schema is causing the problem.

**Comment by rmosolgo** [comment]
Ahhh thanks for looking into it. I think there are two issues: 

- 1.12.11 _started_ validating default values in schema definitions. (Previously they weren't validated until the first query was executed and used the default value) 
- Something in the schema you're using doesn't pass validation. I'm not sure if it's a problem with the schema or a problem with GraphQL-Ruby.

Judging by the error and the backtrace, it looks like there might be some input argument that accepts _list_ values, but the default value is configured to be an empty string. 

Actually, I was able to point GraphiQL at your schema, and I found this in the introspection result: 

```
            {
              "defaultValue": "\"\"",
              "name": "uploadcareIds",
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "NON_NULL",
                  "name": null,
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "String"
                  }
                }
              }
            }
```

That field expects a _list_ of strings, but the default value is an empty string. In fact, GraphQL _will_ accept the value of `""` at runtime (it will automatically wrap it as `[""]`), so maybe it should be accepted by this validator, too. 

If you update the schema definition so that the default value for that field is `[""]` (A list containing an empty string) instead of `""` (an empty string), does this error go away?

**Comment by abatko** [comment]
Wow, yes, that worked!...
```
            {
              "defaultValue": [""],
              "name": "uploadcareIds",
              "type": {
                "kind": "LIST",
                "name": null,
                "ofType": {
                  "kind": "NON_NULL",
                  "name": null,
                  "ofType": {
                    "kind": "SCALAR",
                    "name": "String"
                  }
                }
              }
            }
```

**Comment by rmosolgo** [comment]
Thanks for confirming! Sorry about the hangup. I think your previous configuration _should_ have been valid, since `""` was accepted at runtime. Let's keep this issue open to track the bug, and I'll try to address it soon!

**Comment by abatko** [comment]
> Let's keep this issue open to track the bug, and I'll try to address it soon!

Sounds good, and thank you so much!!

> I was able to point GraphiQL at your schema

Cool. I wish I knew how - I could have done it for you to save your time. Might you know of a writeup about how to do this introspection using GraphiQL? (I looked in the [wiki](https://github.com/rmosolgo/graphql-ruby/wiki).)

> so maybe it should be accepted by this validator, too.

Perhaps it should accept it and also issue a warning? It would be convenient if the warning was able to mention `uploadcareIds` and that there's a problem with `defaultValue`. Just a thought. I have no idea whether the validation process can be that sophisticated.
