### ISSUE TITLE
Dataloader doesn't batch when InputObjects are used for field arguments

### ISSUE THREAD

**Issue by demsullivan** [rmosolgo/graphql-ruby#3629]
**Describe the bug**

Dataloader doesn't batch fetch data when InputObjects are used for field arguments. Instead, it fetches each request immediately rather than batching.

**Versions**

`graphql` version: 2.12.16
`rails` (or other framework): N/A
other applicable versions (`graphql-batch`, etc)

**GraphQL schema, query & steps to reproduce**

```
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "activerecord", "6.0.3.4"
  gem "database_cleaner-active_record"
  gem "graphql", "1.12.16"
  gem "pg"
  gem "byebug"
end

require "graphql"
require "active_record"
require "database_cleaner/active_record"
require "logger"

DatabaseCleaner.strategy = :truncation
ActiveRecord::Base.logger = Logger.new(STDOUT)

ActiveRecord::Base.establish_connection(
  adapter: "postgresql",
  database: "graphql_batching_bug",
  host: "postgres",
  username: "rails",
  password: "rails"
)

ActiveRecord::Schema.define do
  self.verbose = false

  create_table :listings, force: :cascade do |t|
    t.integer :list_price
    t.datetime :listed_at
    t.integer :neighbourhood_id
    t.timestamps
  end

  create_table :neighbourhoods, force: :cascade do |t|
    t.timestamps
  end
end

class Listing < ActiveRecord::Base
  belongs_to :neighbourhood
end

class Neighbourhood < ActiveRecord::Base
  has_many :listings
end

class ConnectionType < GraphQL::Types::Relay::BaseConnection
  field :total_count, Int, null: false

  def total_count
    object.items.count
  end
end

class RangeInputObject < GraphQL::Schema::InputObject
  argument :min, Int, required: false
  argument :max, Int, required: false

  def prepare
    {}.tap do |result|
      result[:gte] = min if min.present?
      result[:lte] = max if max.present?
    end
  end
end

class DateRangeInputObject < GraphQL::Schema::InputObject
  argument :from, GraphQL::Types::ISO8601Date, required: false
  argument :to, GraphQL::Types::ISO8601Date, required: false

  def prepare
    {}.tap do |result|
      result[:gte] = from.to_s if from.present?
      result[:lte] = to.to_s if to.present?
    end
  end
end

class ListingType < GraphQL::Schema::Object
  connection_type_class ConnectionType

  field :id, ID, null: false
  field :list_price, Int, null: false
  field :listed_at, GraphQL::Types::ISO8601Date, null: false
end

class NeighbourhoodType < GraphQL::Schema::Object
  connection_type_class ConnectionType

  field :id, ID, null: false
  field :listings, ListingType.connection_type, null: false do |f|
    f.argument :list_price, RangeInputObject, required: false
    f.argument :listed_at, DateRangeInputObject, required: false
  end

  field :batched_listings, ListingType.connection_type, null: false do |f|
    f.argument :max_list_price, Int, required: false
    f.argument :min_listed_at, GraphQL::Types::ISO8601Date, required: false
  end

  def listings(list_price: nil, listed_at: nil)
    dataloader.with(RecordSource, Listing).load({
                                                  neighbourhood_id: object.id,
                                                  list_price: list_price,
                                                  listed_at: listed_at
                                                })
  end

  def batched_listings(max_list_price: nil, min_listed_at: nil)
    dataloader.with(RecordSource, Listing).load({
                                                  neighbourhood_id: object.id,
                                                  list_price: { lte: max_list_price },
                                                  listed_at: { gte: min_listed_at }
                                                })
  end
end

class Query < GraphQL::Schema::Object
  field :neighbourhoods, NeighbourhoodType.connection_type, null: false do |f|
    f.argument :ids, [ID], required: false
  end

  def neighbourhoods(ids: nil)
    ids.nil? ? Neighbourhood.all : Neighbourhood.where(id: ids).to_a
  end
end

class RecordSource < GraphQL::Dataloader::Source
  def initialize(model)
    @model = model
  end

  def fetch(queries)
    puts "fetching in dataloader source with #{queries.count} queries"
    queries.map do |query|
      q = []
      args = []

      %i(list_price listed_at).each do |field|
        if query[field].present?
          if query[field][:lte].present?
            q << "#{field} <= ?"
            args << query[field][:lte]
          end

          if query[field][:gte].present?
            q << "#{field} >= ?"
            args << query[field][:gte]
          end
        end
      end

      @model.where(neighbourhood_id: query[:neighbourhood_id]).where(q.join(" "), args).to_a
    end
  end
end

class Schema < GraphQL::Schema
  use GraphQL::Dataloader

  query Query
end

4.times do
  neighbourhood = Neighbourhood.create!

  4.times do |x|
    Listing.create!(neighbourhood: neighbourhood, list_price: x*1000, listed_at: x % 2 == 0 ? "2021-09-01" : "2021-09-15")
  end
end

# THIS DOES NOT WORK
result = Schema.execute(<<-GRAPHQL, variables: { hoodIds: [2, 4], minListPrice: 2000, minListedAt: "2021-09-10" })
query($hoodIds: [ID!], $maxListPrice: Int, $minListedAt: ISO8601Date)
{
  neighbourhoods (ids: $hoodIds) {
    nodes {
      id
      affordable: listings(listPrice: { max: $maxListPrice }) { totalCount }
      recent: listings(listedAt: { from: $minListedAt }) { totalCount }
    }
  }
}
GRAPHQL

# THIS WORKS
# result = Schema.execute(<<-GRAPHQL, variables: { hoodIds: [2, 4], minListPrice: 2000, minListedAt: "2021-09-10" })
# query($hoodIds: [ID!], $maxListPrice: Int, $minListedAt: ISO8601Date)
# {
#   neighbourhoods (ids: $hoodIds) {
#     nodes {
#       id
#       affordable: batchedListings(maxListPrice: $maxListPrice) { totalCount }
#       recent: batchedListings(minListedAt: $minListedAt) { totalCount }
#     }
#   }
# }
# GRAPHQL

puts result.to_h

DatabaseCleaner.clean
```

**Expected behavior**

In the console output, I should see dataloader fetching all four queries in a batch:

```
fetching in dataloader source with 4 queries
D, [2021-09-30T16:57:21.190024 #269] DEBUG -- :   Listing Load (0.3ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1  [["neighbourhood_id", 2]]
D, [2021-09-30T16:57:21.190809 #269] DEBUG -- :   Listing Load (0.3ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1 AND (listed_at >= '2021-09-10')  [["neighbourhood_id", 2]]
D, [2021-09-30T16:57:21.191285 #269] DEBUG -- :   Listing Load (0.2ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1  [["neighbourhood_id", 4]]
D, [2021-09-30T16:57:21.191791 #269] DEBUG -- :   Listing Load (0.2ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1 AND (listed_at >= '2021-09-10')  [["neighbourhood_id", 4]]
```

**Actual behavior**

In the console output, I see dataloader fetching each query separately:

```
fetching in dataloader source with 1 queries
D, [2021-09-30T16:55:39.751627 #9] DEBUG -- :   Listing Load (0.3ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1 AND (listed_at >= '2021-09-10')  [["neighbourhood_id", 4]]
fetching in dataloader source with 1 queries
D, [2021-09-30T16:55:39.752514 #9] DEBUG -- :   Listing Load (0.2ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1  [["neighbourhood_id", 4]]
fetching in dataloader source with 1 queries
D, [2021-09-30T16:55:39.753238 #9] DEBUG -- :   Listing Load (0.2ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1 AND (listed_at >= '2021-09-10')  [["neighbourhood_id", 2]]
fetching in dataloader source with 1 queries
D, [2021-09-30T16:55:39.753896 #9] DEBUG -- :   Listing Load (0.2ms)  SELECT "listings".* FROM "listings" WHERE "listings"."neighbourhood_id" = $1  [["neighbourhood_id", 2]]
```
**Additional context**

I understand this example probably doesn't make a lot of sense - it's very contrived because the RecordSource is actually executing multiple queries _anyway_ so batching doesn't make sense here.

My _actual_ use case is using Elasticsearch in the backend, which has a multi-search operation that allows us to batch queries like this, so in my use case it does make sense. Despite being contrived, this example still illustrates the issue where Dataloader fails to batch if a field has input objects as arguments.

**Comment by rmosolgo** [comment]
Wow, thank you for the detailed writeup and replication script. I was able to replicate the failure locally, and I agree, it should batch the same way for both those queries. 

At first, I thought `def prepare` might have something to do with it (just because I've made bugs there in the past), but I found that refactoring away `def prepare` made no difference -- it still batched wrong. 

I've been looking through the runtime code for what could be triggering the dataloader "run" before everything is ready, but I'm coming up short. _Directive_ code uses `@query.arguments_for(...)` which causes that, but that's irrelevant here: we've got no directives, and it works fine for plain arguments. I'll keep looking!

**Comment by rmosolgo** [comment]
Oh, I got a little bit of a clue, the problem is here: 

```
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/member/has_arguments.rb:143:in `coerce_arguments'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/input_object.rb:210:in `coerce_input'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/argument.rb:260:in `block in coerce_into_values'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/errors.rb:107:in `with_error_handling'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/argument.rb:259:in `coerce_into_values'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/member/has_arguments.rb:113:in `block (2 levels) in coerce_arguments'
```

Which brings us here:

https://github.com/rmosolgo/graphql-ruby/blob/ffec3b0b4b25a687342e5e5596c219022e31b756/lib/graphql/schema/member/has_arguments.rb#L138-L144

The given `block` needs to be passed along here (sometimes?) as a continuation: https://github.com/rmosolgo/graphql-ruby/blob/ffec3b0b4b25a687342e5e5596c219022e31b756/lib/graphql/schema/member/has_arguments.rb#L113

This will take some time to sort out ... thanks again for the great report!
