### ISSUE TITLE
[PRO] Dashboard broken due to operation store stack level too deep error

### ISSUE THREAD

**Issue by laurenhedberg** [rmosolgo/graphql-ruby#3653]
**Describe the bug**

This issue was previously reported here: https://giters.com/rmosolgo/graphql-ruby/issues/3435

I'm still experiencing it in graphql-pro 1.19.0

```
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:40:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/operation_store.rb:53:in `operation_store'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/operation_store_component.rb:7:in `enabled?'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/application_component.rb:22:in `block in home'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/application_component.rb:22:in `each'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/application_component.rb:22:in `find'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/application_component.rb:22:in `home'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/component.rb:31:in `public_send'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/component.rb:31:in `call_view'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/dispatcher.rb:71:in `render_view'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard/dispatcher.rb:29:in `dispatch'
  graphql-pro (1.19.0) lib/graphql/pro/dashboard.rb:66:in `call'
```

**Versions**

`graphql` version:   graphql-pro (1.19.0)
`rails` (or other framework): Rails 5.2.6
other applicable versions (`graphql-batch`, etc)

**Comment by rmosolgo** [comment]
Ok, thanks for the details on that. Could you update your `graphql-pro` to 1.19.1? That _should_ fix it -- let me know what you find!
