### ISSUE TITLE
Loading list of arguments authorizes the Array with pundit policy, rather than each object

### ISSUE THREAD

**Issue by jeffgran** [rmosolgo/graphql-ruby#3685]
**Describe the bug**

I am trying to do the following:

- using graphql-pro
- using the pundit integration
- using `loads:` keyword to load arguments, in this case a list/array of objects
- authorize each object individually based on its attributes in a pundit policy

Demonstration of my issue is here: https://github.com/jeffgran/graphql-ruby-arguments-pundit

I added a test showing the error.

**Versions**

`graphql`: [1.12.17](https://github.com/jeffgran/graphql-ruby-arguments-pundit/blob/master/Gemfile.lock#L86)
`rails`: [6.0.4.1](https://github.com/jeffgran/graphql-ruby-arguments-pundit/blob/master/Gemfile.lock#L123)
`graphql-pro`: [1.18.3](https://github.com/jeffgran/graphql-ruby-arguments-pundit/blob/master/Gemfile.lock#L87)

**GraphQL schema**

https://github.com/jeffgran/graphql-ruby-arguments-pundit/blob/master/app/graphql/graphql_test_schema.rb

**GraphQL query**

```graphql
      mutation test($something_ids: [ID!]){
        mutation_result: test(input: {somethingIds: $something_ids}) {
          success
        }
      }
```

**Steps to reproduce**

```bash
git clone git@github.com:jeffgran/graphql-ruby-arguments-pundit.git
cd graphql-ruby-arguments-pundit
bundle install
bin/rails test -b
```

**Expected behavior**

I expect each loaded object to be authorized individually. 

**Actual behavior**

Instead, the Pundit policy is sent and Array of objects, resulting in an error because Pundit policies expect to authorize a single `record` object at a time.

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
$ bin/rails test -b
Run options: -b --seed 45117

# Running:

E

Error:
GraphqlMutationTest#test_top_level:
NoMethodError: undefined method `can_be_accessed_by_user?' for #<Array:0x00007ffa0a94c788>
    /Users/jeffgran/dev/graphql-ruby-arguments-pundit/app/policies/something_policy.rb:6:in `read?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-pro-1.18.3/lib/graphql/pro/pundit_integration.rb:378:in `public_send'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-pro-1.18.3/lib/graphql/pro/pundit_integration.rb:378:in `authorized_by_policy?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-pro-1.18.3/lib/graphql/pro/pundit_integration.rb:139:in `authorized_as_type?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/argument.rb:131:in `authorized?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-pro-1.18.3/lib/graphql/pro/pundit_integration.rb:119:in `authorized?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:152:in `block in authorized?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:149:in `each_value'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:149:in `authorized?'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:92:in `block (2 levels) in resolve_with_support'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema.rb:116:in `after_lazy'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:87:in `block in resolve_with_support'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema.rb:116:in `after_lazy'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/resolver.rb:76:in `resolve_with_support'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/relay_classic_mutation.rb:64:in `resolve_with_support'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:714:in `public_send'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:714:in `block in public_send_field'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:750:in `with_extensions'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:696:in `public_send_field'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:609:in `block in resolve'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema.rb:116:in `after_lazy'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/field.rb:607:in `resolve'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:508:in `block (4 levels) in evaluate_selection_with_args'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:507:in `block (3 levels) in evaluate_selection_with_args'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/query.rb:366:in `block in with_error_handling'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/errors.rb:107:in `with_error_handling'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/query.rb:365:in `with_error_handling'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:506:in `block (2 levels) in evaluate_selection_with_args'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:503:in `block in evaluate_selection_with_args'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:887:in `after_lazy'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:437:in `evaluate_selection_with_args'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:429:in `block in evaluate_selection'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/member/has_arguments.rb:132:in `block (2 levels) in coerce_arguments'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/member/has_arguments.rb:111:in `block in coerce_arguments'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/member/has_arguments.rb:110:in `each'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema/member/has_arguments.rb:110:in `coerce_arguments'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/arguments_cache.rb:50:in `dataload_for'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:230:in `block (4 levels) in run_eager'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:229:in `block (3 levels) in run_eager'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:227:in `block (2 levels) in run_eager'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:218:in `block in run_eager'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter/runtime.rb:209:in `run_eager'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:72:in `evaluate'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/interpreter.rb:48:in `begin_query'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:85:in `begin_query'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:103:in `each'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/tracing.rb:66:in `trace'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:60:in `run_queries'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/execution/multiplex.rb:50:in `run_all'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema.rb:1688:in `multiplex'
    /Users/jeffgran/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/graphql-1.12.17/lib/graphql/schema.rb:1659:in `execute'
    /Users/jeffgran/dev/graphql-ruby-arguments-pundit/test/integration/graphql_mutation_test.rb:13:in `block in <class:GraphqlMutationTest>'


rails test test/integration/graphql_mutation_test.rb:4



Finished in 1.118174s, 0.8943 runs/s, 0.0000 assertions/s.
1 runs, 0 assertions, 0 failures, 1 errors, 0 skips
```

</details>

**Additional context**

I'm not trying to cause trouble, I swear :) Just trying to use this pundit integration to it's fullest, and running into a few issues here.

The stack trace shows `graphql-pro-1.18.3/lib/graphql/pro/pundit_integration.rb:378:in 'public_send'` which I think is the issue. I think it should look like the code here, where it detects if the type is a list type and if so it authorizes each in a loop: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/argument.rb#L143-L148

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report and replication code. 

I think the bug here is that authorization happens during the default `def load...` hook, and when that hook is overridden, authorization is not called 😖 . It definitely shouldn't work that way -- I'll work up a fix in a minute. 

Besides that, a few things to get this example working properly:

1. To work around the bug described above, use `Schema.object_from_id` instead of `def load_somethings:`

    ```diff 
    diff --git a/app/graphql/graphql_test_schema.rb b/app/graphql/graphql_test_schema.rb
    index 2beba13..11d30f4 100644
    --- a/app/graphql/graphql_test_schema.rb
    +++ b/app/graphql/graphql_test_schema.rb
    @@ -3,6 +3,7 @@ class GraphqlTestSchema < GraphQL::Schema
       query(Types::QueryType)
    
       def self.object_from_id(node_id, ctx)
    -    raise "this should not be called in this case as we are attempting to add a custom load method for the argument"
    +    Something.new
    +    # raise "this should not be called in this case as we are attempting to add a custom load method for the argument"
       end
     end
     ```
     
     ```diff 
     diff --git a/app/graphql/mutations/test.rb b/app/graphql/mutations/test.rb
    index c8c388e..32ccfb8 100644
    --- a/app/graphql/mutations/test.rb
    +++ b/app/graphql/mutations/test.rb
    @@ -12,16 +12,16 @@ module Mutations
         field :success, Boolean, null: false
    
    -    def load_somethings(ids)
    -      ids.map{ |_| Something.new }
    -    end
    +    # def load_somethings(ids)
    +    #   ids.map{ |_| Something.new }
    +    # end
    ```
    
    (I realize this isn't how you want it to work -- but just sharing to show how this thing is _supposed_ to work!)

1. Add a `Types::SomethingType`, which will be used for `loads:` below: 

    ```diff
    diff --git a/app/graphql/types/something_type.rb b/app/graphql/types/something_type.rb
    new file mode 100644
    index 0000000..3ae4ec9
    --- /dev/null
    +++ b/app/graphql/types/something_type.rb
    @@ -0,0 +1,4 @@
    +class Types::SomethingType < Types::BaseObject
    +  pundit_policy_class SomethingPolicy
    +  pundit_role :read
    +end
    ```
    
    (`loads:` expects a GraphQL type, not an application class. I expect it would have blown up at _that_ point if it wasn't blowing up during authorization.) 
    
    Include `pundit_...` setup for `Types::SomethingType`, because GraphQL-Ruby will use that for each loaded `Something` for `argument :something_ids`
    
1. Also, add a field so that `Types::SomethingType` is attached to the schema in some way: 

    ```diff
    diff --git a/app/graphql/types/query_type.rb b/app/graphql/types/query_type.rb
    index 46fa7de..1e5d562 100644
    --- a/app/graphql/types/query_type.rb
    +++ b/app/graphql/types/query_type.rb
    @@ -9,5 +9,7 @@ module Types
         def test_field
           "Hello World!"
         end
    +
    +    field :something, Types::SomethingType, null: true
       end
     end
    ```
    
    (If the type isn't attached to the schema somehow, GraphQL-Ruby will assume that it was hidden due to "visibility", and therefore shouldn't be returned to the client.) 
    
1. Remove authorization configuration from `argument :something_ids`, since they will be validated as `Types::SomethingType`. Also, update `loads:` to use the new GraphQL type instead of the application's Ruby class: 

    ```diff
    diff --git a/app/graphql/mutations/test.rb b/app/graphql/mutations/test.rb
    index c8c388e..8bd0ed2 100644
    --- a/app/graphql/mutations/test.rb
    +++ b/app/graphql/mutations/test.rb
    @@ -4,10 +4,8 @@ module Mutations
         pundit_role :allow
    
         argument :something_ids, [ID],
    -      loads: [Something],
    -      required: false,
    -      pundit_policy_class: SomethingPolicy,
    -      pundit_role: :read
    +      loads: [Types::SomethingType],
    +      required: false
    
         field :success, Boolean, null: false
    ```
    
    We can remove `pundit_policy_class` and `pundit_role` there because GraphQL-Ruby will use the configs from `Types::SomethingType` after loading them. 
    
1. Add default auth configuration to `Types::BaseArgument` since `argument :something_ids` doesn't have them anymore: 
    
    ```diff
    diff --git a/app/graphql/types/base_argument.rb b/app/graphql/types/base_argument.rb
    index 241abf7..706fb4a 100644
    --- a/app/graphql/types/base_argument.rb
    +++ b/app/graphql/types/base_argument.rb
    @@ -1,5 +1,7 @@
     module Types
       class BaseArgument < GraphQL::Schema::Argument
         include GraphQL::Pro::PunditIntegration::ArgumentIntegration
    +    pundit_policy_class ApplicationPolicy
    +    pundit_role :allow
       end
     end
     ````
     
     This is just to satisfy the Pundit integration which requires that all integrated arguments have _some_ configured value.
     


After all that, the tests work as expected:

```
~/code/graphql-ruby-arguments-pundit $ bin/rails test -b
Run options: -b --seed 38762

# Running:

#<GraphQL::Query::Result @query=... @to_h={"data"=>{"mutation_result"=>{"success"=>true}}}>
.
```

(And with a little `puts`ing, I can see that `SomethingPolicy` is being engaged as expected, too.) 

I hope that background helps, and I'll get that `def load_...` issue fixed up, too!

**Comment by jeffgran** [comment]
Hey @rmosolgo , thanks for this explanation! This all makes sense. To give you a little context on why this workaround doesn't work for me: it's because in our production app, for historical reasons (meaning, I know this isn't how it's meant to work but it's what we've got), we have quite a few places where the client is sending raw numerical IDs or UUIDs for an object, rather than a GraphQL complete, unique ID that has both the type and the id. Because of that, it becomes impossible to load the object with `MySchema.object_from_id(id)` because the `id` is just a number -- we lost the context of which type of object it is. That's why we have had to resort to using the `def loads_...` override. 

Another option that occurs to me though, is that we could pass some extra context to `object_from_id` so it could do its job. For example, if we specify the `loads: Something` for that argument, it could pass that `loads:` somehow as an extra opt/param to `object_from_id` so it would have all the information needed to load the object.

**Comment by rmosolgo** [comment]
Yep, totally makes sense why you'd want to use that local method for it. 

Personally, I don't think passing type information to `object_from_id` is the best solution. The original use for that method is the `node` field, for example: 

```graphql
{ 
  node(id: "abcd-efgh-1234") { ... }
}
```

In that case, there is _no_ type information at all. For now, I think using the local `def load_...` override is the way to go (and for sure, that's _why_ it exists!).
