### ISSUE TITLE
[GraphQL-Enterprise] Unconfigured caching error on Mutation with ObjectCache

### ISSUE THREAD

**Issue by davelooi** [rmosolgo/graphql-ruby#3709]
**Describe the bug**

ObjectCache Tracer raises unconfigured error on Mutation.

"UpdateNamePayload isn't configured for caching yet. `include GraphQL::Enterprise::ObjectCache::ObjectIntegration` and set `cacheable(true|false)` in #<Class:0x0000559ae4c8d5f0> (or a superclass) to configure it."

**Versions**

`graphql` version:

```
    graphql (1.12.19)
    graphql-client (0.17.0)
      activesupport (>= 3.0)
      graphql (~> 1.10)
    graphql-enterprise (1.0.1)
      graphql (>= 1.12.0)
      graphql-pro (>= 1.19.0)
    graphql-pro (1.20.1)
      graphql (>= 1.7.5)
```

`rails` (or other framework):

```
    rails (6.1.4.1)
      actioncable (= 6.1.4.1)
      actionmailbox (= 6.1.4.1)
      actionmailer (= 6.1.4.1)
      actionpack (= 6.1.4.1)
      actiontext (= 6.1.4.1)
      actionview (= 6.1.4.1)
      activejob (= 6.1.4.1)
      activemodel (= 6.1.4.1)
      activerecord (= 6.1.4.1)
      activestorage (= 6.1.4.1)
      activesupport (= 6.1.4.1)
      bundler (>= 1.15.0)
      railties (= 6.1.4.1)
      sprockets-rails (>= 2.0.0)
```

**GraphQL schema**

```ruby
module Mutations
  class UpdateName < BaseMutation
    null true
    argument :name, String, required: true
    field :data, Types::Objects::UserType, null: true

    def resolve(name:)
      context[:current_user].update!(first_name: name)

      {
        data: context[:current_user]
      }
    end
  end
end
```

**GraphQL query**

```graphql
mutation {
  updateName(input: {name:"Batman"}) {
    data {
      firstName
    }
  }
}
```

**Steps to reproduce**

Setup ObjectCache and execute the mutation.

`use GraphQL::Enterprise::ObjectCache, redis: REDIS_CLIENT, cache_introspection: true`

**Expected behavior**

```json
{
  "data": {
    "updateName": {
      "data": {
        "firstName": "Batman"
      }
    }
  }
}
```

**Actual behavior**

ObjectCache complains that caching isn't configured.

<details>
<summary>Click to view exception backtrace</summary>

```
{
  "error": {
    "message": "UpdateNamePayload isn't configured for caching yet. `include GraphQL::Enterprise::ObjectCache::ObjectIntegration` and set `cacheable(true|false)` in #<Class:0x0000559ae4c8d5f0> (or a superclass) to configure it.",
    "backtrace": [
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-enterprise-1.0.1/lib/graphql/enterprise/object_cache.rb:489:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:67:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/object.rb:53:in `authorized_new'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:930:in `authorized_new'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:702:in `continue_field'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:517:in `block (3 levels) in evaluate_selection_with_args'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:887:in `after_lazy'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:514:in `block (2 levels) in evaluate_selection_with_args'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:503:in `block in evaluate_selection_with_args'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:887:in `after_lazy'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:437:in `evaluate_selection_with_args'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:429:in `block in evaluate_selection'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/member/has_arguments.rb:162:in `block (3 levels) in coerce_arguments'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/member/has_arguments.rb:143:in `block (2 levels) in coerce_arguments'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/member/has_arguments.rb:142:in `each'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/member/has_arguments.rb:142:in `block in coerce_arguments'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema/member/has_arguments.rb:171:in `coerce_arguments'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/arguments_cache.rb:50:in `dataload_for'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:356:in `each'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:230:in `block (4 levels) in run_eager'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:229:in `block (3 levels) in run_eager'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:227:in `block (2 levels) in run_eager'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:189:in `tap_or_each'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:218:in `block in run_eager'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:788:in `resolve_with_directives'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter/runtime.rb:209:in `run_eager'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:81:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `block in call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/data_dog_tracing.rb:37:in `block in platform_trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/ddtrace-0.53.0/lib/ddtrace/tracer.rb:283:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/data_dog_tracing.rb:18:in `platform_trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `block in call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-enterprise-1.0.1/lib/graphql/enterprise/object_cache.rb:548:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:67:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter.rb:72:in `evaluate'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/interpreter.rb:48:in `begin_query'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:85:in `begin_query'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:103:in `each'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:103:in `each_with_index'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:208:in `block in instrument_and_analyze'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:187:in `instrument_and_analyze'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:81:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `block in call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/platform_tracing.rb:26:in `block in trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/data_dog_tracing.rb:37:in `block in platform_trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/ddtrace-0.53.0/lib/ddtrace/tracer.rb:283:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/data_dog_tracing.rb:18:in `platform_trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing/platform_tracing.rb:25:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `block in call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-enterprise-1.0.1/lib/graphql/enterprise/object_cache.rb:527:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:83:in `call_tracers'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/tracing.rb:67:in `trace'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:60:in `run_queries'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/execution/multiplex.rb:50:in `run_all'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema.rb:1701:in `multiplex'",
      "/home/looi/.asdf/installs/ruby/2.7.4/lib/ruby/gems/2.7.0/gems/graphql-1.12.19/lib/graphql/schema.rb:1672:in `execute'",
```

</details>

**Comment by rmosolgo** [comment]
Thanks for the detailed report, and sorry for the trouble!

Have you configured an `object_class ...` for your `BaseMutation` (example: https://graphql-ruby.org/mutations/mutation_classes#example-mutation-class)? I would _expect_ the cache to use the caching configuration inherited from that `object_class ...`. 

Another way to confirm would be to inspect the inheritance chain for `UpdateNamePayload`: 

```ruby 
MySchema.get_type("UpdateNamePayload").ancestors 
# [ ... ] 
```

What does that print out for you? Does one of the classes in that list have a cache configuration?

**Comment by davelooi** [comment]
Hey @rmosolgo

Inspecting the chain of inheritance helped.
```
[#<Class:0x000055b16066c1e8>,
 GraphQL::Schema::Object,
 GraphQL::Schema::Member,
 GraphQL::Schema::Member::GraphQLTypeNames,
 ActiveSupport::ForkTracker::CoreExtPrivate,
 ActiveSupport::ForkTracker::CoreExt,
 ActiveSupport::ToJsonWithActiveSupportEncoder,
 Object,
 PP::ObjectMixin,
 ActiveSupport::Dependencies::Loadable,
 ActiveSupport::Tryable,
 JSON::Ext::Generator::GeneratorMethods::Object,
 Kernel,
 BasicObject]
```

Turn out, I didn't have `object_class Types::BaseObject` configured in my `BaseMutation` class.

My project added graphql quite some time ago, and I guess our setup is a bit out of date.

Thanks for your help.
