### ISSUE TITLE
Raising exception in argument prepare proc causes undefined method `argument_values'

### ISSUE THREAD

**Issue by digitalmoksha** [rmosolgo/graphql-ruby#3789]
**Describe the bug**

We use a `prepare` proc for an argument:

```ruby
      argument :tag_names,
               [GraphQL::Types::String],
               required: true,
               description: "Container repository tag(s) to delete. Total number can't be greater than #{LIMIT}",
               prepare: ->(tag_names, _) do
                 raise Gitlab::Graphql::Errors::ArgumentError, TOO_MANY_TAGS_ERROR_MESSAGE if tag_names.size > LIMIT

                 tag_names
               end
```

if we raise an error, `Gitlab::Graphql::Errors::ArgumentError`, which inherits from `GraphQL::ExecutionError`, then we end up with a 

```ruby
NoMethodError: undefined method `argument_values' for #<Gitlab::Graphql::Errors::ArgumentError:0x00007fccf9474eb0>
```

which happens at https://github.com/rmosolgo/graphql-ruby/blob/c967b876e779cbb91727ce29d4d376dd4025cb48/lib/graphql/analysis/ast/field_usage.rb#L19.

The value that gets returned from `visitor.query.arguments_for(node, visitor.field_definition)` is the bubbled up exception, `#<Gitlab::Graphql::Errors::ArgumentError: Number of tags is greater than 20>`, which of course doesn't have an `argument_values` method.

**Versions**

`graphql` version: `1.12.21`
`rails` (or other framework): `6.1.4.1`
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok).
Are you using [interpreter](https://graphql-ruby.org/queries/interpreter.html)? Any custom instrumentation, etc?

Using interpreter and running `GraphQL::Analysis::AST::QueryComplexity`, `GraphQL::Analysis::AST::QueryDepth`, and `GraphQL::Analysis::AST::FieldUsage` analyzers

**Steps to reproduce**

Steps to reproduce the behavior

**Expected behavior**

Expected the exception we raised would be bubbled up into the `error` field as usual.

**Actual behavior**

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
NoMethodError (undefined method `argument_values' for #<Gitlab::Graphql::Errors::ArgumentError:0x00007f919eb142e8>):
  lib/gitlab/graphql/tracers/timer_tracer.rb:20:in `trace'
  lib/gitlab/graphql/generic_tracing.rb:48:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:38:in `platform_trace'
  lib/gitlab/graphql/tracers/logger_tracer.rb:14:in `trace'
  lib/gitlab/graphql/tracers/metrics_tracer.rb:13:in `trace'
  lib/gitlab/graphql/tracers/application_context_tracer.rb:23:in `trace'
  lib/gitlab/graphql/query_analyzers/ast/logger_analyzer.rb:30:in `result'
  lib/gitlab/graphql/tracers/timer_tracer.rb:20:in `trace'
  lib/gitlab/graphql/generic_tracing.rb:48:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:38:in `platform_trace'
  lib/gitlab/graphql/tracers/logger_tracer.rb:14:in `trace'
  lib/gitlab/graphql/tracers/metrics_tracer.rb:13:in `trace'
  lib/gitlab/graphql/tracers/application_context_tracer.rb:23:in `trace'
  lib/gitlab/graphql/tracers/timer_tracer.rb:20:in `trace'
  lib/gitlab/graphql/generic_tracing.rb:48:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:38:in `platform_trace'
  lib/gitlab/graphql/tracers/logger_tracer.rb:14:in `trace'
  lib/gitlab/graphql/tracers/metrics_tracer.rb:13:in `trace'
  lib/gitlab/graphql/tracers/application_context_tracer.rb:23:in `trace'
  lib/gitlab/graphql/tracers/timer_tracer.rb:20:in `trace'
  lib/gitlab/graphql/generic_tracing.rb:48:in `with_labkit_tracing'
  lib/gitlab/graphql/generic_tracing.rb:38:in `platform_trace'
  lib/gitlab/graphql/tracers/logger_tracer.rb:14:in `trace'
  lib/gitlab/graphql/tracers/metrics_tracer.rb:13:in `trace'
  lib/gitlab/graphql/tracers/application_context_tracer.rb:23:in `trace'
  app/graphql/gitlab_schema.rb:54:in `multiplex'
  app/controllers/graphql_controller.rb:141:in `execute_query'
  app/controllers/graphql_controller.rb:48:in `execute'
  lib/gitlab/auth/current_user_mode.rb:42:in `bypass_session!'
  app/controllers/concerns/sessionless_authentication.rb:35:in `sessionless_bypass_admin_mode!'
  ee/lib/gitlab/ip_address_state.rb:10:in `with'
  ee/app/controllers/ee/application_controller.rb:44:in `set_current_ip_address'
  app/controllers/application_controller.rb:491:in `set_current_admin'
  lib/gitlab/i18n.rb:105:in `with_locale'
  lib/gitlab/i18n.rb:111:in `with_user_locale'
  app/controllers/application_controller.rb:475:in `set_locale'
  app/controllers/application_controller.rb:469:in `set_current_context'
  lib/gitlab/middleware/speedscope.rb:13:in `call'
  lib/gitlab/request_profiler/middleware.rb:17:in `call'
  lib/gitlab/query_limiting/middleware.rb:17:in `block in call'
  lib/gitlab/query_limiting/transaction.rb:40:in `run'
  lib/gitlab/query_limiting/middleware.rb:16:in `call'
  lib/gitlab/jira/middleware.rb:19:in `call'
  lib/gitlab/middleware/go.rb:20:in `call'
  lib/gitlab/etag_caching/middleware.rb:21:in `call'
  lib/gitlab/middleware/query_analyzer.rb:11:in `block in call'
  lib/gitlab/database/query_analyzer.rb:37:in `within'
  lib/gitlab/middleware/query_analyzer.rb:11:in `call'
  lib/gitlab/middleware/multipart.rb:173:in `call'
  lib/gitlab/middleware/read_only/controller.rb:50:in `call'
  lib/gitlab/middleware/read_only.rb:18:in `call'
  lib/gitlab/middleware/same_site_cookies.rb:27:in `call'
  lib/gitlab/middleware/handle_malformed_strings.rb:21:in `call'
  lib/gitlab/middleware/basic_health_check.rb:25:in `call'
  lib/gitlab/middleware/handle_ip_spoof_attack_error.rb:25:in `call'
  lib/gitlab/middleware/request_context.rb:21:in `call'
  config/initializers/fix_local_cache_middleware.rb:11:in `call'
  lib/gitlab/middleware/compressed_json.rb:26:in `call'
  lib/gitlab/middleware/static.rb:11:in `call'
  lib/gitlab/testing/clear_process_memory_cache_middleware.rb:13:in `call'
  lib/gitlab/testing/request_inspector_middleware.rb:35:in `call'
  lib/gitlab/testing/robots_blocker_middleware.rb:30:in `call'
  lib/gitlab/testing/request_blocker_middleware.rb:47:in `call'
  lib/gitlab/middleware/rack_multipart_tempfile_factory.rb:19:in `call'
  lib/gitlab/middleware/sidekiq_web_static.rb:20:in `call'
  lib/gitlab/metrics/requests_rack_middleware.rb:75:in `call'
  spec/support/helpers/graphql_helpers.rb:428:in `post_graphql'
  spec/support/helpers/graphql_helpers.rb:449:in `post_graphql_mutation'
  spec/requests/api/graphql/mutations/container_repository/destroy_tags_spec.rb:62:in `block (3 levels) in <top (required)>'
  spec/requests/api/graphql/mutations/container_repository/destroy_tags_spec.rb:92:in `block (5 levels) in <top (required)>'
  spec/requests/api/graphql/mutations/container_repository/destroy_tags_spec.rb:92:in `block (4 levels) in <top (required)>'
  spec/spec_helper.rb:412:in `block (3 levels) in <top (required)>'
  spec/support/sidekiq_middleware.rb:9:in `with_sidekiq_server_middleware'
  spec/spec_helper.rb:403:in `block (2 levels) in <top (required)>'
  spec/spec_helper.rb:399:in `block (3 levels) in <top (required)>'
  lib/gitlab/application_context.rb:31:in `with_raw_context'
  spec/spec_helper.rb:399:in `block (2 levels) in <top (required)>'
  spec/support/database/prevent_cross_joins.rb:106:in `block (3 levels) in <main>'
  spec/support/database/prevent_cross_joins.rb:60:in `with_cross_joins_prevented'
  spec/support/database/prevent_cross_joins.rb:106:in `block (2 levels) in <main>'
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I agree it should work the way you expect. I'll take a look soon. When the fix is ready, I'll backport it to 1.12.x, too, since I see you're on 1.12.21 :+1:

**Comment by digitalmoksha** [comment]
Ah, thank you! Yes, we still need 1.12.x at the moment.

**Comment by rmosolgo** [comment]
🚢 'd in 1.12.23! Please let me know if you have any more trouble. (Also fixed on master.)

**Comment by digitalmoksha** [comment]
@rmosolgo awesome, working like a charm - thank you!!
