### ISSUE TITLE
[1.13.x] Invariant: unexpected field owner: nil

### ISSUE THREAD

**Issue by cocoahero** [rmosolgo/graphql-ruby#3845]
**Describe the bug**

When attempting to analyze a query where a field's `visible?` returns false, it crashes with an `Invariant: unexpected field owner` error within `Schema#get_field`.

**Versions**

`graphql, "1.13.5"` (1db571aa7bd2)

**Demo Script**

```ruby
#! /usr/bin/env ruby

require 'bundler/setup'
require 'graphql'

class BaseField < GraphQL::Schema::Field
  def initialize(*args, visible: true, **kwargs, &block)
    @visible = visible
    super(*args, **kwargs, &block)
  end

  def visible?(context)
    return @visible 
  end
end

class BaseObject < GraphQL::Schema::Object
  field_class BaseField
end

class Article < BaseObject
  field :title, String, null: false
end

class Query < BaseObject
  field :article, String, null: true, visible: false do |f|
    f.argument(:id, Integer, required: true)
  end

  def article(id:)
    { title: "hello world" }
  end
end

class Schema < GraphQL::Schema
  query Query
end

gql = <<~GQL
{
  article(id: 1) {
    title
  }
}
GQL

query = GraphQL::Query.new(Schema, gql)

GraphQL::Analysis::AST.analyze_query(query, [GraphQL::Analysis::AST::Analyzer])
```
**Backtrace**
```
/Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/schema.rb:1250:in `get_field': Invariant: unexpected field owner for "title": nil (NilClass) (ArgumentError)

This is probably a bug in GraphQL-Ruby, please report this error on GitHub: https://github.com/rmosolgo/graphql-ruby/issues/new?template=bug_report.md
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:103:in `on_field'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `public_send'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `visit_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:101:in `each'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:174:in `on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:123:in `on_field'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:117:in `on_field'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `public_send'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `visit_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:101:in `each'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:174:in `on_abstract_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:74:in `on_operation_definition'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `public_send'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:79:in `visit_node'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/language/visitor.rb:68:in `visit'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast/visitor.rb:41:in `visit'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast.rb:73:in `block in analyze_query'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/tracing.rb:66:in `trace'
	from /Users/jbaker/.gem/ruby/3.1.0/gems/graphql-1.13.5/lib/graphql/analysis/ast.rb:61:in `analyze_query'
	from ./demo.rb:49:in `<main>'
```

**Comment by rmosolgo** [comment]
Hmm, I think the underlying issue here is that analysis requires valid queries. The query in this example would normal fail with validation errors: 

```ruby
pp query.validation_errors.map(&:to_h)
# [{"message"=>"Field 'article' doesn't exist on type 'Query'",
#   "locations"=>[{"line"=>2, "column"=>3}],
#   "path"=>["query", "article"],
#   "extensions"=>
#    {"code"=>"undefinedField", "typeName"=>"Query", "fieldName"=>"article"}}]
```

But maybe `AST::Analysis` should be made to check `query.valid?` before starting.

**Comment by cocoahero** [comment]
We discovered this issue in our unit tests where we were actually testing to make sure our visibility condition worked, i.e looking for that validation error to be raised. Unfortunately these tests go end to end which means all the analyzers installed run first and crash.

**Comment by cocoahero** [comment]
> But maybe AST::Analysis should be made to check query.valid? before starting.

Would that mean the analyzer would not be run if the query isn't valid? My concern would be that work done in analyzers for metrics, etc would not get performed anymore.

I guess I'm more curious about what changed here. Prior to 1.13 these queries would also have been "invalid" by your definition since the field would not be visible, but the analyzers were still able to run. Perhaps it is because before it didn't need to worry about visibility at that step in the process since the name could only be defined once?

**Comment by rmosolgo** [comment]
>  before it didn't need to worry about visibility at that step

Yes! That's right, sorry I didn't clarify it before. A lot of the work for adding multiple-schema-members-per-name was updating code paths which assumed a one-to-one relationship between names and _things_. I assume that somewhere here was one of them, something like: previously, it looked up `type.fields[field_name]`, which didn't account for `context`. So it's been migrated to use `schema.get_field(type, field_name)` which raises this error sometime.

In any case, I see it _used_ to work, even for queries that failed static validation -- and I think I can make it still work in _some_ sense for that!
