### ISSUE TITLE
Error when calling `to_schema` on a schema which implements an interface on BaseConnection

### ISSUE THREAD

**Issue by dgalarza** [rmosolgo/graphql-ruby#3850]
**Describe the bug**

When attempting to implement an interface within a `BaseConnection`, building a schema definition fails with the error:

```
NoMethodError: undefined method `visible?' for nil:NilClass
```

**Versions**

`graphql version: 1.13.x`

**GraphQL schema**

```ruby
module Types
  class BaseConnection < GraphQL::Types::Relay::BaseConnection
    implements Types::PageableConnection
  end
end


module Types
  module PageableConnection
    include Types::BaseInterface

    field(
      :page_info,
      Types::PageInfoType,
      null: false,
      description: "Information to aid in pagination."
    )

    field :total_count, Integer, null: false
  end
end
```

Note: Even if the `PageableConnection` is an empty module, attempting to call `implements` with the interface continues to fail. Without calling `implements Types::PageableConnection` the schema generates just fine.

<details>
<summary>Click to view exception backtrace</summary>

```
NoMethodError: undefined method `visible?' for nil:NilClass
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/types/relay/connection_behaviors.rb:86:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema.rb:1553:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:32:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:32:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:12:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:94:in `block in initialize'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:329:in `block in read_through'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:325:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:226:in `block in visible_type?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:329:in `block in read_through'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:227:in `visible_type?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/type_membership.rb:29:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema.rb:1553:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:32:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:32:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/filter.rb:12:in `call'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:94:in `block in initialize'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:329:in `block in read_through'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:325:in `visible?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:231:in `visible_type_membership?'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/member/has_interfaces.rb:73:in `block in interfaces'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/member/has_interfaces.rb:67:in `each'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/member/has_interfaces.rb:67:in `interfaces'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/member/has_interfaces.rb:82:in `interfaces'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:193:in `block in interfaces'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:329:in `block in read_through'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:194:in `interfaces'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:386:in `reachable_type_set'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/warden.rb:126:in `reachable_types'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/language/document_from_schema_definition.rb:259:in `build_definition_nodes'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/language/document_from_schema_definition.rb:42:in `document'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/printer.rb:51:in `initialize'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/printer.rb:79:in `new'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema/printer.rb:79:in `print_schema'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/schema.rb:886:in `to_definition'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/rake_task.rb:98:in `public_send'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/rake_task.rb:98:in `write_outfile'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/graphql-1.13.5/lib/graphql/rake_task.rb:128:in `block (3 levels) in define_task'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `block in execute'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `each'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:273:in `execute'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/sentry-ruby-core-4.9.1/lib/sentry/rake.rb:24:in `execute'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:214:in `block in invoke_with_call_chain'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `synchronize'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:194:in `invoke_with_call_chain'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/task.rb:183:in `invoke'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:160:in `invoke_task'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block (2 levels) in top_level'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `each'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:116:in `block in top_level'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:125:in `run_with_threads'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:110:in `top_level'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:83:in `block in run'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:186:in `standard_exception_handling'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/lib/rake/application.rb:80:in `run'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/rake-12.3.3/exe/rake:27:in `<top (required)>'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/bin/rake:23:in `load'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/bin/rake:23:in `<top (required)>'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `load'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:58:in `kernel_load'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli/exec.rb:23:in `run'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:478:in `exec'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:31:in `dispatch'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/cli.rb:25:in `start'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/exe/bundle:49:in `block in <top (required)>'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/lib/ruby/gems/3.0.0/gems/bundler-2.2.31/exe/bundle:37:in `<top (required)>'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/bin/bundle:23:in `load'
/Users/dgalarza/.asdf/installs/ruby/3.0.2/bin/bundle:23:in `<main>'
```

</details>

**Comment by rmosolgo** [comment]
Thanks for the report! Weird how that happened, I'll take a look soon.
