### ISSUE TITLE
Missing validation for __type on non-root object

### ISSUE THREAD

**Issue by dylanahsmith** [rmosolgo/graphql-ruby#387]
`__schema` and `__type` are only accessible from on the root of a query operation, but this isn't caught during validation, leading to an unhandled exception (e.g. NoMethodError) from doing a query like `{ test { __type } }`

Here is a script that reproduces the exception

```ruby
require 'graphql'

TestType = GraphQL::ObjectType.define do
  name "Test"

  field :unused, types.String
end

QueryType = GraphQL::ObjectType.define do
  name "Query"

  field :test, TestType do
    resolve -> (obj, args, ctx) {
      {}
    }
  end
end

Schema = GraphQL::Schema.define do
  query QueryType
end

Schema.execute('{ test { __type } }')
```

which results in the following exception output

```
/Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:151:in `arguments_for': undefined method `arguments' for nil:NilClass (NoMethodError)
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:15:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `block in resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/value_resolution.rb:44:in `resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:51:in `get_finished_value'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:21:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:16:in `block in resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/operation_resolution.rb:6:in `resolve'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution.rb:20:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:33:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:15:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:254:in `get_result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:238:in `call'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:96:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/schema.rb:145:in `execute'
	from tmp/test.rb:23:in `<main>'
```

This is a low priority issue.  Just something that came up from some developer playing around with GraphQL.

**Comment by cjoudrey** [comment]
I think this has to do with: https://github.com/rmosolgo/graphql-ruby/blob/6a1afd35038c57885b6cb50cdca3b489d36da5ab/lib/graphql/static_validation/rules/fields_are_defined_on_type.rb#L9.

There might be other issues like this wherever `skip_field?` is used.
