### ISSUE TITLE
Connection type combined with validated argument and max complexity causes NoMethodError

### ISSUE THREAD

**Issue by ludo** [rmosolgo/graphql-ruby#3900]
**Describe the bug**

A validation error of an argument that occurs when querying a `connection_type` field while also passing `max_complexity` to `Schema.execute` causes a `NoMethodError`.

**Versions**

`graphql` version: 1.13.8
`rails` (or other framework): tested on 6.1 and 7.0
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Types
  class ItemType < Types::BaseObject
    field :title, String
  end
end

module Types
  class QueryType < Types::BaseObject
    field :items, Types::ItemType.connection_type, null: false do
      argument :bar, String do
        validates format: { with: /^\d{5}$/ } # Arbitrary validation, triggered with any validation as far as I can tell
      end
    end
    def items
      []
    end
  end
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  items(first: 3) {
    nodes {
      title
    }
  }
}
```

Response is an exception.

**Steps to reproduce**

I set up an example Rails app with a test that demonstrates the error here: https://github.com/ludo/graphql-validation-complexity. See README. Basically:

1. Set up a new app
2. Create an `items` query using the code mentioned in the GraphQL schema section above. It must use a `connection_type` and have an argument with a validation.
3. Perform `Schema.execute(query, max_complexity: 100)` and see error.

Passing max_complexity is important because the exception happens in the complexity calculation code.

**Expected behavior**

The validation error is returned.

**Actual behavior**

What specifically went wrong?

```
NoMethodError:
       undefined method `[]' for #<GraphQL::Schema::Validator::ValidationFailedError:0x000000011d389c80>
```

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
NoMethodError:
       undefined method `[]' for #<GraphQL::Schema::Validator::ValidationFailedError:0x000000011d389c80>
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/schema/field.rb:431:in `calculate_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:57:in `own_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:217:in `block in merged_max_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:193:in `each'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:193:in `merged_max_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:153:in `block in merged_max_complexity_for_scopes'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:140:in `each'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:140:in `merged_max_complexity_for_scopes'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:99:in `block in max_possible_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:96:in `each'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:96:in `reduce'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/query_complexity.rb:96:in `max_possible_complexity'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast/max_query_complexity.rb:12:in `result'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:78:in `map'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:78:in `block in analyze_query'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:61:in `analyze_query'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:37:in `block (2 levels) in analyze_multiplex'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:35:in `map'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:35:in `block in analyze_multiplex'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/analysis/ast.rb:34:in `analyze_multiplex'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/multiplex.rb:210:in `block in instrument_and_analyze'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/multiplex.rb:190:in `instrument_and_analyze'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/multiplex.rb:60:in `run_queries'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/execution/multiplex.rb:50:in `run_all'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/schema.rb:1767:in `multiplex'
     # /Users/ludovandenboom/.rvm/gems/ruby-2.7.2/gems/graphql-1.13.8/lib/graphql/schema.rb:1738:in `execute'
     # ./spec/schema_spec.rb:27:in `block (2 levels) in <top (required)>
```

</details>

**Comment by rmosolgo** [comment]
Thanks for all the details on this. It looks like the complexity validator isn't properly handling validation errors!
