### ISSUE TITLE
Received `type` in `id_from_object` changed in 2.0.0

### ISSUE THREAD

**Issue by ojab** [rmosolgo/graphql-ruby#3911]
**Describe the bug**

With type defined as 
```ruby
module Types
  class CalendarAuth
  end
end
```
in graphql-1.13.0 we have
```
From: *_schema.rb:29 *Schema.id_from_object:

    27: def self.id_from_object(object, type, _ctx)
    28:   binding.pry
 => 29:   Services::Id.encode_id(object.id, type.name)
    30: end

[1] pry(*Schema)> type
=> CalendarAuth
```
and in graphql-2.0.0 it's
```
[1] pry(*Schema)> type
=> Types::CalendarAuthType
```
and `type.name` changed from `CalendarAuth` to `Types::CalendarAuthType`.
Not sure if it's expected behavior change, looks like migration path could be `type.name` -> `type.graphql_name`, but I dunno [yet] if it will break something. 

**Versions**

`graphql` version: 1.13.0/2.0.0
`rails` (or other framework):6.1.4.4

**GraphQL schema**

Will craft a reproducer if needed.

**Comment by ojab** [comment]
```
[5] pry(TopSchedulerSchema)> puts caller.grep(%r{gems/graphql}).map { |l| l.delete_prefix('/home/ojab/.rbenv/versions/3.1.0/lib/ruby/gems/3.1.0/gems/') }
graphql-1.13.8/lib/graphql/relay/global_id_resolve.rb:14:in `call'
graphql-1.13.8/lib/graphql/schema/member/has_fields.rb:109:in `block in global_id_field'
graphql-1.13.8/lib/graphql/schema/field.rb:825:in `public_send'
graphql-1.13.8/lib/graphql/schema/field.rb:825:in `block in public_send_field'
graphql-1.13.8/lib/graphql/schema/field.rb:908:in `with_extensions'
graphql-1.13.8/lib/graphql/schema/field.rb:800:in `public_send_field'
graphql-1.13.8/lib/graphql/schema/field.rb:714:in `block in resolve'
graphql-1.13.8/lib/graphql/schema.rb:118:in `after_lazy'
graphql-1.13.8/lib/graphql/schema/field.rb:712:in `resolve'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:511:in `block (4 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:510:in `block (3 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/query.rb:366:in `block in with_error_handling'
graphql-1.13.8/lib/graphql/execution/errors.rb:107:in `with_error_handling'
graphql-1.13.8/lib/graphql/query.rb:365:in `with_error_handling'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:509:in `block (2 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:739:in `block (3 levels) in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:738:in `block (2 levels) in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:729:in `block in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:715:in `continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:805:in `block (2 levels) in resolve_list_item'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:802:in `block in resolve_list_item'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:800:in `resolve_list_item'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:775:in `block (2 levels) in continue_field'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:774:in `block in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:766:in `each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:766:in `continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:520:in `block (3 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:517:in `block (2 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:739:in `block (3 levels) in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:738:in `block (2 levels) in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:729:in `block in continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:715:in `continue_field'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:520:in `block (3 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:517:in `block (2 levels) in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
graphql-1.13.8/lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'
graphql-1.13.8/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
graphql-1.13.8/lib/graphql/execution/interpreter.rb:72:in `evaluate'
graphql-1.13.8/lib/graphql/execution/interpreter.rb:48:in `begin_query'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:85:in `begin_query'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
graphql-1.13.8/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:103:in `each'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:103:in `each_with_index'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:211:in `block in instrument_and_analyze'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
graphql-1.13.8/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:190:in `instrument_and_analyze'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
graphql-1.13.8/lib/graphql/tracing.rb:66:in `trace'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:60:in `run_queries'
graphql-1.13.8/lib/graphql/execution/multiplex.rb:50:in `run_all'
graphql-1.13.8/lib/graphql/schema.rb:1767:in `multiplex'
graphql-1.13.8/lib/graphql/schema.rb:1738:in `execute'
```

**Comment by rmosolgo** [comment]
Thanks again for reporting this -- I'm going to release 1.13.10 with the new behavior (no legacy `ObjectType` instances, classes instead) and a callout in the changelog.
