### ISSUE TITLE
Argument error in Ruby 3 – wrong number of arguments (given 2, expected 1)

### ISSUE THREAD

**Issue by marckohlbrugge** [rmosolgo/graphql-ruby#3927]
**I'm upgrading to Ruby 3.0 and receive the following ArgumentError error for all my graphql mutation specs:**

```
ArgumentError:
        wrong number of arguments (given 2, expected 1)
```

I'm pretty sure it has something to do with the way Ruby 3.0 handles the separation of positional and keyword arguments.

Unfortunately the stacktrace just shows how rspec executed the code, rather than the source of the issue:

```
  30) viewer .resolve returns current_user
      Failure/Error: post "/graphql", { params: { query: query }, headers: { authorization: user.api_token } }

      ArgumentError:
        wrong number of arguments (given 2, expected 1)
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/testing/integration.rb:21:in `post'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/actionpack-6.1.4.6/lib/action_dispatch/testing/integration.rb:372:in `post'
      # ./spec/graphql/queries/viewer_spec.rb:11:in `block (3 levels) in <module:Queries>'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `instance_exec'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:263:in `block in run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `block in with_around_and_singleton_context_hooks'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `block in with_around_example_hooks'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `block in run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:626:in `block in run_around_example_hooks_for'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-rails-5.1.0/lib/rspec/rails/adapters.rb:75:in `block (2 levels) in <module:MinitestLifecycleAdapter>'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:457:in `instance_exec'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:390:in `execute_with'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:628:in `block (2 levels) in run_around_example_hooks_for'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:352:in `call'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:629:in `run_around_example_hooks_for'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/hooks.rb:486:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:468:in `with_around_example_hooks'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:511:in `with_around_and_singleton_context_hooks'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example.rb:259:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:646:in `block in run_examples'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `map'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:642:in `run_examples'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:607:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `block in run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `map'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/example_group.rb:608:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (3 levels) in run_specs'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `map'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:121:in `block (2 levels) in run_specs'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/configuration.rb:2068:in `with_suite_hooks'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:116:in `block in run_specs'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/reporter.rb:74:in `report'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:115:in `run_specs'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:89:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:71:in `run'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/lib/rspec/core/runner.rb:45:in `invoke'
      # /Users/marc/.asdf/installs/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/rspec-core-3.11.0/exe/rspec:4:in `<top (required)>'
      # bin/rspec:29:in `load'
      # bin/rspec:29:in `<main>'
```

**Versions**

`graphql 2.0.0`
`rails 6.1.4.6`

**Addtional info**
I get this error for all mutations. Regular read-only queries execute without issue.

**Relevant code**

```ruby
# frozen_string_literal: true

module Mutations
  class CompleteTodo < BaseMutation
    argument :id, ID, required: true
    argument :attachments, [Types::AttachmentInputType, { null: true }], required: false
    argument :broadcast, Boolean, "Whether to broadcast the todo to chat. Only accessible to white-listed apps", required: false

    type Types::TodoType

    def resolve(id:, attachments: nil, broadcast: true)
      todo = context[:current_user].todos.find id

      mark_as_done = ::MarkTodoAsDone.new todo

      if attachments
        attachments_attributes = attachments.collect do |a|
          {
            file: {
              id: File.basename(a[:key]),
              storage: "cache",
              metadata: {
                filename: a[:filename],
                size: a[:size]
              }
            }.to_json
          }
        end

        mark_as_done.todo.assign_attributes attachments_attributes: attachments_attributes
      end

      mark_as_done.save!
      mark_as_done.broadcast if broadcast?(broadcast)

      todo
    end

    def broadcast?(broadcast)
      return false if context[:current_oauth_application_id] != Todo::MENUBAR_OAUTH_APPLICATION_ID

      broadcast
    end
  end
end

class Types::TodoType < Types::BaseObject
  description "A pending or completed todo. (Might be renamed to todo or task later on)"

  field :id, ID, null: false
  field :body, String, "Description of the todo", null: false
  field :created_at, GraphQL::Types::ISO8601DateTime, "When the todo was created", null: false, camelize: false
  field :updated_at, GraphQL::Types::ISO8601DateTime, "When the todo was last updated", null: false, camelize: false
  field :completed_at, GraphQL::Types::ISO8601DateTime, "When the todo was completed", null: true, camelize: false
  field :attachments, [Types::AttachmentType], "Image or videos", null: true
  field :product, Types::ProductType, "The product this todo is for", null: true
  field :user, Types::UserType, "Who added the todo", null: false

  delegate :product, to: :object
  delegate :user, to: :object
end

class WipSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)
end
```

**Comment by rmosolgo** [comment]
I'm guessing that the fix was: 


```diff
- post "/graphql", { params: { query: query }, headers: { authorization: user.api_token } }
+ post "/graphql", params: { query: query }, headers: { authorization: user.api_token } 
```

(Making `params:` and `headers:` true keyword arguments instead of passing a hash with those two keys)

**Comment by andrezimpel** [comment]
@rmosolgo thanks man. I just solved it a few min ago. I was using `def resolve(organization:)` instead of `def resolve(organization:, **args)`.  🤦🏽‍♂️
