### ISSUE TITLE
hash_key attribute doesn't work if field is called "method"

### ISSUE THREAD

**Issue by adamcohen2** [rmosolgo/graphql-ruby#3944]
**Describe the bug**

It's not possible to use the `hash_key` keyword if the field name is `method`, for example, the following will produce an error:

```ruby
field :method, String, null: true, hash_key: :another_method
```

Error when executing a query:

```json
{
  "errors": [
    {
      "message": "wrong number of arguments (given 0, expected 1)",
      "backtrace": [
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:692:in `method'"
      ]
    }
  ]
}
```

**Versions**

`graphql` version: `1.11.6`
`rails` (or other framework): `7.0.2`
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Example code has been taken from [graphql-ruby Tutorial](https://www.howtographql.com/graphql-ruby/0-introduction/)

**app/models/link.rb**

```ruby
class Link < ApplicationRecord
  def another_method
    "other method"
  end
end
```

**app/graphql/types/link_type.rb**

```ruby
module Types
  class LinkType < Types::BaseObject
    field :id, ID, null: false
    field :url, String, null: false
    field :description, String, null: false
    field :testing, String, null: false

    field :method, String, null: true, hash_key: :another_method
  end
end
```

**GraphQL query**

```graphql
{
  allLinks {
    method
  }
}
```

```json
{
  "errors": [
    {
      "message": "wrong number of arguments (given 0, expected 1)",
      "backtrace": [
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:692:in `method'"
      ]
    }
  ]
}
```

**Steps to reproduce**

Define a field with the following signature:

```ruby
module Types
  class LinkType < Types::BaseObject
    field :method, String, null: true, hash_key: :another_method
  end
end
```

Implement `another_method` inside the source class:

```ruby
class Link < ApplicationRecord
  def another_method
    "other method"
  end
end
```

Execute a query:

```graphql
{
  allLinks {
    method
  }
}
```

Error is returned:

```json
{
  "errors": [
    {
      "message": "wrong number of arguments (given 0, expected 1)",
      "backtrace": [
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:692:in `method'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:692:in `public_send'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:692:in `block in public_send_field'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:726:in `with_extensions'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:672:in `public_send_field'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/graphql-1.11.6/lib/graphql/schema/field.rb:585:in `block in resolve'",
        "<snip>",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/puma-5.6.2/lib/puma/server.rb:441:in `process_client'",
        "/Users/myname/.rvm/gems/ruby-2.7.5/gems/puma-5.6.2/lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
      ]
    }
  ],
  "data": {}
}
```

If we use `resolver_method` instead:

```ruby
module Types
  class LinkType < Types::BaseObject
    field :method, String, null: true, resolver_method: :resolve_method

    def resolve_method
      object.another_method
    end
  end
end
```

The query works as expected and returns the following:

```json
{
  "data": {
    "allLinks": [
      {
        "method": "other method"
      },
      {
        "method": "other method"
      }
    ]
  }
}
```

**Expected behavior**

It should be possible to use the `hash_key` with a field named `method` _or_ the documentation should be updated to explain that this usage is not supported, and that `resolver_method` must be used instead

**Actual behavior**

Error `wrong number of arguments (given 0, expected 1)` is returned

**Comment by rmosolgo** [comment]
Agreed it should work the way you describe -- thanks for the detailed bug report! I'll take a look soon.

**Comment by joelzwarrington** [comment]
> Agreed it should work the way you describe -- thanks for the detailed bug report! I'll take a look soon.

@rmosolgo would you mind if I had a look, I was recently in `field.rb` so shouldn't be too hard to have a look and see what's going on

**Comment by rmosolgo** [comment]
:+1: that'd be great, @joelzwarrington -- just ping me if I can help out at all!
