### ISSUE TITLE
Using an Enum array type in arguments results in an error.

### ISSUE THREAD

**Issue by chanks** [rmosolgo/graphql-ruby#397]
Was just getting around to upgrading the gem on an app (it was at 0.19.2 for a while), and when I tried to bump it up to 0.19.4 I started getting this error. I also tried bumping the version all the way up to the newest release, 1.2.2, but I still get the same error, as you can see below.

I have a "Skillables" enum, which contains a list of item types that can have skills, and there's a connection which takes an argument that is an array of the skillables enum, declared like `argument :skillable_types, types[SkillablesEnum]`.

The exact error is:

```
NoMethodError: undefined method `of_type' for Skillables:GraphQL::EnumType

/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `block in wrap_value'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `map'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `wrap_value'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `block in wrap_value'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `map'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:65:in `wrap_value'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:14:in `block in initialize'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:11:in `each'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/arguments.rb:11:in `inject'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/literal_input.rb:39:in `from_arguments'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query.rb:153:in `arguments_for'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/field_resolution.rb:15:in `initialize'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `new'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `block in resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/value_resolution.rb:44:in `resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/value_resolution.rb:58:in `resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/field_resolution.rb:51:in `get_finished_value'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/field_resolution.rb:21:in `result'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:16:in `block in resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution/operation_resolution.rb:6:in `resolve'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/serial_execution.rb:20:in `execute'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/executor.rb:33:in `execute'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query/executor.rb:15:in `result'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query.rb:258:in `get_result'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query.rb:242:in `call'
/home/chris/.rvm/gems/ruby-2.3.0/gems/graphql-1.2.2/lib/graphql/query.rb:100:in `result'
```

**Comment by xuorig** [comment]
Mind sharing your query ?

It seems like you're passing an `array` as a value but your type is an EnumType. 😮

**Comment by chanks** [comment]
I am indeed passing arrays as values. This is part of a spec that queries the connection with different types of arguments, it looks like:

```
          no_skills: skills(skillable_types: [], first: 50) {
            count, edges { cursor, node { __typename, id } }
          }
          link_skills: skills(skillable_types: [LINK], first: 50) {
            count, edges { cursor, node { __typename, id } }
          }
          other_skills: skills(skillable_types: [USER, LINK], first: 50) {
            count, edges { cursor, node { __typename, id } }
          }
```

All three clauses fail when I try them individually - if I omit them all, the query works.

**Comment by rmosolgo** [comment]
Thanks for reporting this and sharing so many details. One more if you don't mind, could you share the field definition for `skills` shown above, except the resolve function?

**Comment by chanks** [comment]
Nothing special:

```ruby
  connection :skills do
    type -> { SkillConnection }
    description "Related skills."
    argument :skillable_types, types[SkillablesEnum]

    resolve -> (skill, args, ctx) do
      # ...
    end
  end
```

**Comment by xuorig** [comment]
Mind sharing `SkillablesEnum` too 😹  ? @chanks

**Comment by chanks** [comment]
Ha, alright. It just points to arrays of some ruby classes.

```ruby
SkillablesEnum = GraphQL::EnumType.define do
  name "Skillables"
  description "Types of skillable objects."

  value 'LINK', value: [PublicLink, CompanyLink].freeze
  value 'COURSE', value: [PublicCourse, CompanyCourse].freeze
  value 'USER', value: [User].freeze
end
```

**Comment by xuorig** [comment]
Something fishy here

![screenshot 2016-11-14 16 03 14](https://cloud.githubusercontent.com/assets/1919498/20282702/df1a6cf6-aa83-11e6-8eca-f9d9e7c22f37.png)

**Comment by rmosolgo** [comment]
Wow, enum values that are arrays. Fair game, for sure, but it's the first I've seen of it!

That code where the error happened is new, and it (wrongly) assumes that incoming array values have list types. 

As a workaround, you could use a wrapper object to avoid using arrays as `value:`. 

Otherwise I'll take a look and get a fix soon! Thanks again for the details, that's tremendously helpful :D

**Comment by chanks** [comment]
Ha, thanks! It worked fine up through version 0.19.2 so I just didn't think much of it :smile:

**Comment by rmosolgo** [comment]
Btw good call @xuorig on the enum type. Thanks, I didn't see that one coming!

**Comment by rmosolgo** [comment]
Just pushed 1.2.3 which _should_ fix this, please let me know if this problem shows up again!

**Comment by chanks** [comment]
That seemed to do it, thanks!
