### ISSUE TITLE
`NoMethodError` when calling `#fields` on  a type that implements an interface that implements an interface

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#3980]
**Describe the bug**

When calling `#fields` on  a type that implements an interface that implements an interface, I'm getting a `NoMethodError`.

**Versions**

`graphql` version: 2.0.2

**GraphQL schema**

See script below.

**GraphQL query**

N/A (an exception occurs without a query being run).

**Steps to reproduce**

Put this in `graphql_issue.rb`:

``` ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.0.2'
end

require 'graphql'

schema_string = <<~EOS
  type Query {
    entities: [Entity!]!
    #{"namedEntities: [NamedEntity!]!" if ENV["INCLUDE_NAMED_ENTITIES_FIELD"]}
    person: Person
  }

  type Person implements NamedEntity {
    id: ID!
    name: String
    nationality: String
  }

  type Product implements NamedEntity {
    id: ID!
    name: String
    amount: Int
  }

  interface NamedEntity implements Entity {
    id: ID!
    name: String
  }

  type Payment implements Entity {
    id: ID!
    amount: Int
  }

  interface Entity {
    id: ID!
  }
EOS

puts GraphQL::Schema.from_definition(schema_string).types.fetch("Payment").fields.keys.join(", ")
puts GraphQL::Schema.from_definition(schema_string).types.fetch("Person").fields.keys.join(", ")
```

Run it:

```
$ ruby graphql_issue.rb
id, amount
Traceback (most recent call last):
        6: from graphql_issue.rb:45:in `<main>'
        5: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:23:in `fields'
        4: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:23:in `each'
        3: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:25:in `block in fields'
        2: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:137:in `visible_interface_implementation?'
        1: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:137:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:138:in `block in visible_interface_implementation?': undefined method `abstract_type' for #<LateBoundType @name=Entity> (NoMethodError)
```

Notice that `#fields` call worked on the type that implements an interface. But on the type that implements an interface that implements an interface, it raises the exception.

Weirdly, the problem goes away if you define an extra field on `Query`. You can see this if you run this script with `INCLUDE_NAMED_ENTITIES_FIELD` set:

```
$ INCLUDE_NAMED_ENTITIES_FIELD=1 ruby graphql_issue.rb
id, amount
id, name, nationality
```

**Expected behavior**

`#fields` should return the fields and not raise an exception.

**Actual behavior**

An exception was raised.

<details>
<summary>Click to view exception backtrace</summary>

```
Traceback (most recent call last):
        6: from graphql_issue.rb:45:in `<main>'
        5: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:23:in `fields'
        4: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:23:in `each'
        3: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:25:in `block in fields'
        2: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:137:in `visible_interface_implementation?'
        1: from /Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:137:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.2/lib/graphql/schema/member/has_fields.rb:138:in `block in 
```

</details>

**Comment by joelzwarrington** [comment]
I had a look at the issue believe it to be the cause of an unwrapped LateBoundType in a few places:
- `visible?(member, ctx)` in `GraphQL::Schema`
- `abstract_type` in `GraphQL::Schema::HasFields`
- and likely others

I think there can be checks to get the type if a `LateBoundType` is encountered, but likely there's a better place than repeating the unwrapping in every location to check for visibility and membership?

Oddly enough, defining the schema you provided using classes, works just fine. So there's something happening when interpreting the SDL and `.from_definition` method which causes the `LateBoundType`.

```ruby
require 'bundler/inline'

gemfile do
  source 'https://rubygems.org'
  gem 'graphql', '2.0.2'
end

require 'graphql'

module Entity
  include GraphQL::Schema::Interface

  orphan_types Payment

  field :id, ID, null: false
end

module NamedEntity
  include GraphQL::Schema::Interface
  implements Entity

  orphan_types Product

  field :name, String, null: true
end

class Product < GraphQL::Schema::Object
  implements NamedEntity

  field :amount, Int, null: true
end

class Payment < GraphQL::Schema::Object
  implements Entity

  field :amount, Int, null: true
end

class Person < GraphQL::Schema::Object
  implements NamedEntity

  field :nationality, String, null: true
end

class Query < GraphQL::Schema::Object
  field :entities, [Entity], null: false
  field :named_entities, [NamedEntity], null: false
  field :person, Person, null: true
end

class Schema < GraphQL::Schema
  query Query
end

schema_definition = Schema.to_definition
schema_from_definition = Schema.from_definition(schema_definition)
schema_from_definition.types['Payment'].fields
schema_from_definition.types['Person'].fields
```
