### ISSUE TITLE
Intermittent 'failed to implement [field]' errors after boot

### ISSUE THREAD

**Issue by wjordan** [rmosolgo/graphql-ruby#3993]
**Describe the bug**

My team has been experiencing an intermittent `Failed to implement App.status` error when resolving a specific GraphQL field in our production Rails app, where the `status` method is present on an STI subclass being loaded (though not on the base class).

Error:
```
RuntimeError:             Failed to implement App.status, tried:

            - `Types::AppType#status`, which did not exist
            - `FirecrackerApp#status`, which did not exist
            - Looking up hash key `:status` or `"status"` on `#<FirecrackerApp:0x000056035c705200>`, but it wasn't a Hash

            To implement this field, define one of the methods above (and check for typos)
```

<details>
<summary>backtrace</summary>

```
  from graphql (1.13.9) lib/graphql/schema/field.rb:848:in `block in public_send_field'
  from graphql (1.13.9) lib/graphql/schema/field.rb:911:in `with_extensions'
  from graphql (1.13.9) lib/graphql/schema/field.rb:803:in `public_send_field'
  from graphql (1.13.9) lib/graphql/schema/field.rb:717:in `block in resolve'
  from graphql (1.13.9) lib/graphql/schema.rb:118:in `after_lazy'
  from graphql (1.13.9) lib/graphql/schema/field.rb:715:in `resolve'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:511:in `block (4 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/tracing.rb:81:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `block in call_tracers'
  from graphql (1.13.9) lib/graphql/schema/timeout.rb:86:in `trace'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:67:in `trace'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:510:in `block (3 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/query.rb:366:in `block in with_error_handling'
  from graphql (1.13.9) lib/graphql/execution/errors.rb:107:in `with_error_handling'
  from graphql (1.13.9) lib/graphql/query.rb:365:in `with_error_handling'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:509:in `block (2 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:739:in `block (3 levels) in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:738:in `block (2 levels) in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:729:in `block in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:715:in `continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:805:in `block (2 levels) in resolve_list_item'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:802:in `block in resolve_list_item'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:800:in `resolve_list_item'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:775:in `block (2 levels) in continue_field'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:774:in `block in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:766:in `each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:766:in `continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:520:in `block (3 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:517:in `block (2 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:739:in `block (3 levels) in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:738:in `block (2 levels) in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:729:in `block in continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:715:in `continue_field'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:520:in `block (3 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:517:in `block (2 levels) in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:432:in `block in evaluate_selection'
  from graphql (1.13.9) lib/graphql/schema/member/has_arguments.rb:204:in `block (3 levels) in coerce_arguments'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/schema/member/has_arguments.rb:185:in `block (2 levels) in coerce_arguments'
  from graphql (1.13.9) lib/graphql/schema/member/has_arguments.rb:184:in `each'
  from graphql (1.13.9) lib/graphql/schema/member/has_arguments.rb:184:in `block in coerce_arguments'
  from graphql (1.13.9) lib/graphql/schema/member/has_arguments.rb:213:in `coerce_arguments'
  from graphql (1.13.9) lib/graphql/execution/interpreter/arguments_cache.rb:52:in `dataload_for'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:431:in `evaluate_selection'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'
  from graphql (1.13.9) lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'
  from graphql (1.13.9) lib/graphql/execution/interpreter.rb:73:in `block in evaluate'
  from graphql (1.13.9) lib/graphql/tracing.rb:81:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `block in call_tracers'
  from graphql (1.13.9) lib/graphql/schema/timeout.rb:89:in `trace'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:67:in `trace'
  from graphql (1.13.9) lib/graphql/execution/interpreter.rb:72:in `evaluate'
  from graphql (1.13.9) lib/graphql/execution/interpreter.rb:48:in `begin_query'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:85:in `begin_query'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'
  from graphql (1.13.9) lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:103:in `each'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:103:in `each_with_index'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:211:in `block in instrument_and_analyze'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
  from graphql (1.13.9) lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:190:in `instrument_and_analyze'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:62:in `block in run_queries'
  from graphql (1.13.9) lib/graphql/tracing.rb:81:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `block in call_tracers'
  from graphql (1.13.9) lib/graphql/schema/timeout.rb:65:in `trace'
  from graphql (1.13.9) lib/graphql/tracing.rb:83:in `call_tracers'
  from graphql (1.13.9) lib/graphql/tracing.rb:67:in `trace'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:60:in `run_queries'
  from graphql (1.13.9) lib/graphql/execution/multiplex.rb:50:in `run_all'
  from graphql (1.13.9) lib/graphql/schema.rb:1767:in `multiplex'
  from graphql (1.13.9) lib/graphql/schema.rb:1738:in `execute'
  from app/controllers/graphql_controller.rb:16:in `execute'
[...]
```

</details>

**Steps to reproduce**

When a server is affected, it raises the exception as soon as it boots and continues raising the exception on every similar query until restarted.

We have only seen this issue occur several times in production immediately following deploys, and haven't been able to reproduce it otherwise. Heavy query-load during boot might be a possible factor.

**Versions**

`graphql` version: 1.13.9
`rails` (or other framework): 6.1.4.6
other applicable versions: `graphql-pro` 1.21.3

**GraphQL schema**

<details>
<summary>schema code (truncated/extracted from a much larger Rails app)</summary>

```ruby
class FlySchema < GraphQL::Schema
  # ...
  query(Queries)

  def self.object_from_id(id, query_ctx)
    GraphNode.find_by_graph_id(id)
  end

  def self.resolve_type(type, obj, ctx)
    case obj
    when ::App then Types::AppType
    # ...
    end
  end
end

class Queries < Types::BaseObject
  include GraphQL::Types::Relay::HasNodesField

  field :apps, Types::AppType.connection_type, null: false do
    description "List apps"
  end

  def apps
    current_user.apps.where(type: 'FirecrackerApp')
  end
end

class Types::AppType < Types::BaseObject
  include PrimaryKey
  implements GraphQL::Types::Relay::Node
  field :id, ID, null: false, description: "Unique application ID"
  field :status, String, null: false, description: "Application status"

  def id
    object.name
  end
end

class Types::BaseObject < GraphQL::Schema::Object
  def current_user
    context[:current_user]
  end
end

class User < ApplicationRecord
  has_many :apps
end

class App < ApplicationRecord
end

class FirecrackerApp < App
  def status
    # ...
  end
end

class ApplicationRecord < ActiveRecord::Base
  include GraphNode
end

module GraphNode
  extend ActiveSupport::Concern

  def graph_id
    Fly.graph_id.encode(self.class.polymorphic_name, self.id)
  end

  def self.find_by_graph_id(id)
    class_name, item_id = Fly.graph_id.decode(id)
    Object.const_get(class_name).find_by(id: item_id)
  end
end
```
</details>

**GraphQL query**

```graphql
query{
  apps(first: 200) {
    nodes { id status }
  }
}
```

**Additional context**

- My best guess is some kind of race condition triggered by classes loading in a certain bad order, or something getting cached in GraphQL internals incorrectly, but could use help investigating this theory or adding extra debug info to help track down a root cause.

- To rule out any kind of autoloading issue, I confirmed `config.autoloader = :zeitwerk` and `config.eager_load = true` settings in the `production` environment. If I try manually unloading the `FirecrackerApp` class (e.g., `Object.send(:remove_const, :FirecrackerApp)`) the query produces a different error (`ActiveRecord::SubclassNotFound`).

**Comment by rmosolgo** [comment]
Woah, how strange! Yeah, it seems like it must be somehow related to loading, but I sure can't think of _how_...

> cached in GraphQL internals 

I can't think of any caching that would involve this. The code that raises that error is here: 

https://github.com/rmosolgo/graphql-ruby/blob/044e85bb729e68f19b371ee70a5e39a8e4644833/lib/graphql/schema/field.rb#L814-L857

It doesn't cache anything about how a field should be resolved, though -- it checks every object, every time the field is resolved. 

By the looks of it, GraphQL _should_ find `FirecrackerApp#status`, which is defined with `def status` in that class. By why wouldn't it find it with `respond_to?`!?  How could there be a constant, `FirecrackerApp`, _without_ it reaching that method definition!? 🤔 

Rails Autoloading docs _do_ have some caveats about STI ([doc](https://guides.rubyonrails.org/v6.1/autoloading_and_reloading_constants.html#single-table-inheritance)), but they say everything should Just Work :tm: in production, given the configuration which you confirmed above. So that doesn't seem to go anywhere. 


I'm afraid I don't have any other clues... If it was me, I'd try adding some `require_dependency "firecracker_app"`s to see if they make the problem go away -- say, to `app/graphql/types/app.rb` and/or `app/models/app.rb`. I can't think of _why_ that would make a difference, but then again, I'm totally stumped! Can you think of anything else I could investigate on the GraphQL side?

**Comment by rmosolgo** [comment]
Did you find any further clues on this?

**Comment by wjordan** [comment]
One thread we're investigating is that we noticed there is a custom graphql-ruby parser cache (#3156) that gets enabled wherever Bootsnap is enabled, so we're going to disable Bootsnap (disabling the parser cache as well) and see if this stops the error.

**Comment by jphenow** [comment]
Update: we've basically confirmed it is unrelated to the Bootsnap piece since it just occurred again.

**Comment by rmosolgo** [comment]
Sorry, I really don't have any more insight on this one 😖  If you find any more debug-related info, or if you get to the bottom of it, please let me know here or in a new issue!
