### ISSUE TITLE
Building Generic Form Builder

### ISSUE THREAD

**Issue by fameoflight** [rmosolgo/graphql-ruby#4062]
Not a bug, but just wondering what I might be doing wrong here.  I am trying to build a strongly type checked form builder 

Form Input Class 

```ruby
module Types
  module Form
    class FormInputType < Types::Base::BaseObject
      field :name, String, null: false
      field :label, String, null: false
      field :kind, Types::Form::FormInputKind, null: false
    end
  end
end
```

And my input kind class 

```ruby
module Types
  module Form
    class FormInputKind < Types::Base::BaseUnion
      possible_types GraphQL::Types::Int, GraphQL::Types::Float, GraphQL::Types::ISO8601Date,
                     GraphQL::Types::ISO8601DateTime

      def self.resolve_type(object, _context)
        case object['kind']
        when :integer
          GraphQL::Types::Int
        when :number
          GraphQL::Types::Int
        when :decimal
          GraphQL::Types::Float
        when :boolean
          GraphQL::Types::Boolean
        when :date
          GraphQL::Types::ISO8601Date
        when :datetime
          GraphQL::Types::ISO8601DateTime
        end
      end
    end
  end
end
```

Introspection query give me schema, but relay complier fails 

```json
        {
          "kind": "OBJECT",
          "name": "FormInput",
          "description": null,
          "interfaces": [

          ],
          "possibleTypes": null,
          "fields": [
            {
              "name": "kind",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "UNION",
                  "name": "FormInputKind",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null,
              "args": [

              ]
            },
            {
              "name": "label",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null,
              "args": [

              ]
            },
            {
              "name": "name",
              "description": null,
              "type": {
                "kind": "NON_NULL",
                "name": null,
                "ofType": {
                  "kind": "SCALAR",
                  "name": "String",
                  "ofType": null
                }
              },
              "isDeprecated": false,
              "deprecationReason": null,
              "args": [

              ]
            }
          ],
          "inputFields": null,
          "enumValues": null
        },
        {
          "kind": "UNION",
          "name": "FormInputKind",
          "description": null,
          "interfaces": null,
          "possibleTypes": [
            {
              "kind": "SCALAR",
              "name": "ISO8601DateTime",
              "ofType": null
            },
            {
              "kind": "SCALAR",
              "name": "Int",
              "ofType": null
            }
          ],
          "fields": null,
          "inputFields": null,
          "enumValues": null
        },
```

Here is the error I am getting from relay compiler. I am just looking for hint where should I begin to debug this. 

```
yarn run v1.22.18
$ yarn run relay-compiler --src ./src  --watch
$ /Users/hemantv/workspace/stable/stable-webapp/node_modules/.bin/relay-compiler --src ./src --watch
Error: Expected ISO8601DateTime to be a GraphQL Object type.
    at assertObjectType (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/definition.js:127:11)
    at getObjectType (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/utilities/buildClientSchema.js:126:45)
    at Array.map (<anonymous>)
    at types (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/utilities/buildClientSchema.js:221:49)
    at resolveThunk (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/definition.js:480:40)
    at defineTypes (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/definition.js:944:15)
    at GraphQLUnionType.getTypes (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/definition.js:900:26)
    at collectReferencedTypes (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/schema.js:356:59)
    at new GraphQLSchema (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/type/schema.js:148:9)
    at buildClientSchema (/Users/hemantv/workspace/stable/stable-webapp/node_modules/graphql/utilities/buildClientSchema.js:73:10)
```

Additionally it would be great help if you can point to how to go about converting the input I get from frontend to make sure it meet the above format.

**Comment by fameoflight** [comment]
Ok solved this by converting InputKind to enum 

```ruby
module Types
  module Form
    class FormInputKind < Types::Base::BaseEnum
      value 'int'
      value 'string'

    end
  end
end
```
