### ISSUE TITLE
NoMethodError: undefined method `map' for nil:NilClass

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-ruby#408]
Not sure if this is a problem with `graphql` or with `graphql-batch`, but since the last line in the stack trace I figured this would be a good place to start.

I'm getting this stack trace:

```
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/arguments.rb:65:in `wrap_value'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/arguments.rb:14:in `block in initialize'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/arguments.rb:11:in `each'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/arguments.rb:11:in `inject'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/arguments.rb:11:in `initialize'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/literal_input.rb:39:in `new'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/literal_input.rb:39:in `from_arguments'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query.rb:153:in `arguments_for'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/field_resolution.rb:15:in `initialize'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `new'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:11:in `block in resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/value_resolution.rb:44:in `resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/field_resolution.rb:51:in `get_finished_value'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-batch-0.2.5/lib/graphql/batch/execution_strategy.rb:61:in `get_finished_value'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/field_resolution.rb:21:in `result'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:16:in `block in resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `each'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/selection_resolution.rb:10:in `resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution/operation_resolution.rb:6:in `resolve'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/serial_execution.rb:20:in `execute'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-batch-0.2.5/lib/graphql/batch/execution_strategy.rb:6:in `execute'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/executor.rb:33:in `execute'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query/executor.rb:15:in `result'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query.rb:258:in `get_result'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query.rb:242:in `call'
/Users/keithpitt/.gem/ruby/2.3.1/gems/graphql-1.2.4/lib/graphql/query.rb:100:in `result'
/Users/keithpitt/Development/buildkite/app/models/api/graph/query.rb:21:in `block in execute'
```

My query looks like this:

```graphql
      query TestQuery($templates: [APIAccessTokenTemplates!], $organizations: [ID!]) {
        viewer {
          apiAccessTokens(
            first: 10,
            template: $templates,
            organizations: $organizations
          ) {
            edges {
              node {
                description
                uuid
                token
              }
            }
          }
        }
      }
```

And I'm supplying variables to both `templates` and `organizations`:

```
    {
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ],
      organizations: [ "acme-inc" ]
    }
```

Let me know if there's any other data you need!

**Comment by keithpitt** [comment]
Ah correction on my last bug report. It _does not_ error if you supply both variables.

It seems to only bug out when I leave the other as null. So if I supply just:

```
{
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ]
}
```

It breaks. But If I change it to:

```
    {
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ],
      organizations: [ "acme-inc" ]
    }
```

Then it's fine. I also noticed that:

```
    {
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ],
      organizations: [ nil ]
    }
```

Will also cause it to to throw an error.

**Comment by rmosolgo** [comment]
Interesting! It sounds like there's a variable value validation step missing (or perhaps it's there, but not working correctly). I think this is _supposed_ to handle this case:

https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/query/variables.rb#L39

Thanks for the details, I'll take a look soon!!

**Comment by keithpitt** [comment]
Awesome, thanks!

**Comment by rmosolgo** [comment]
I was able to reproduce the third case you mentioned [in a spec](#410), but in one case, my result was different.

When I specified a nullable list of non-null values (`$ids: [ID!]`) and provided a list with a null value (`"ids" => [ nil ]`), I got a "nice" error from GraphQL: `Variable ids of type [ID!] was provided invalid value`. 

Could you confirm that you get a Ruby error in that case? I found a bug which _think_ is the culprit (#410) but I want to make sure I'm not missing something!

**Comment by keithpitt** [comment]
Ah yes, my apologies. You're right! If I pass:

```
    {
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ],
      organizations: [ nil ]
    }
```

I get:

```
       +{"errors"=>
       +  [{"message"=>
       +     "Variable organizations of type [ID!] was provided invalid value",
       +    "locations"=>[{"line"=>1, "column"=>57}],
       +    "value"=>[nil],
       +    "problems"=>
       +     [{"path"=>[0], "explanation"=>"Expected value to not be null"}]}]}
```

**Comment by keithpitt** [comment]
But if I pass `nil` (no array):

```
    {
      templates: [ "API_ACCESS_TOKEN_TEMPLATE_ELASTIC_CI_AWS" ],
      organizations: nil
    }
```

It _does_ raise an exception.

**Comment by rmosolgo** [comment]
Cool, thanks for checking on that! I think #410 will do the job. I'll try to get a patch version out this afternoon.

**Comment by keithpitt** [comment]
Awesome, thanks for checking it out! <3
