### ISSUE TITLE
stack level too deep after 1.13.0 (not present on 1.12.24)

### ISSUE THREAD

**Issue by TSMMark** [rmosolgo/graphql-ruby#4093]
The error exists on latest as well. v2.0.9

**Describe the bug**

It seems like when fields recursively reference each other, it has a problem.

```
Exception (SystemStackError): stack level too deep
stack level too deep
/root/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/set.rb:119:in `each_entry'
/root/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/set.rb:119:in `do_with_enum'
/root/.asdf/installs/ruby/3.0.0/lib/ruby/3.0.0/set.rb:442:in `merge'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:44:in `add_directives_from'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:186:in `block in add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `each'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:185:in `block in add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `each'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `add_type'
# ... ETC ...
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:185:in `block in add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `each'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:185:in `block in add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `each'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:180:in `add_type'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:50:in `block in add_type_and_traverse'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:50:in `each'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:50:in `add_type_and_traverse'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema/addition.rb:17:in `initialize'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema.rb:1782:in `new'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema.rb:1782:in `add_type_and_traverse'
/vydia/bundle/ruby/3.0.0/gems/graphql-1.13.0/lib/graphql/schema.rb:1084:in `query'
/vydia/graphql/v1/schemas/schema.rb:14:in `<class:Schema>'
```

**Versions**

```
    graphql (1.13.0)
    graphql-batch (0.5.1)
```

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Objects
  class NetworkGroup < Objects::Base

    description "Parent network group for networks"

    field :id, ID, null: false
    field :aggregating_network_id, ID, null: false
    field :aggregating_network, "Objects::Network", description: "The main network thats deploying to others within the group", null: false
    def aggregating_network
      Loaders::Single.for(::Network).load(object.aggregating_network_id)
    end
    field :networks, "[Objects::Network]", description: "The Networks in the group", null: false
    def networks
      ::Network.available_to_user(context["current_user"]).where(network_group_id: object.id, archived: false).all
    end

    field :name, String, null: false

  end
end

module Objects
  class Network < Objects::Base

    description "One of a user's Release's broadcast's networks"

    field :id, ID, null: false
    field :name, String, null: false
    field :deployer_name, String, description: "Name of the deployer", null: false
    field :deploy_only_once, Boolean, description: "Network only allows one deploy", null: false
    field :image_url, String, description: "Image URL for this network", null: false
    def image_url
      object.image_path&.present? ? Vydia::Utils::S3.s3_presigned_url(object.image_path) : ""
    end
    field :is_social, Boolean, description: "If network is social network", null: false
    def is_social
      object.is_social?
    end
    field :service, String, description: "The values can either be distribute or monetize", null: true
    field :supported_policy_types, [String], description: "Supported Policy types are Permit, Monetize, Block", null: false, deprecation_reason: "WARNING: this field is not currently used in any application"
    field :supported_policy_types_for_current_user, [String], null: false
    def supported_policy_types_for_current_user
      object.supported_policy_types_for_user(context["current_user"])
    end

    field :network_group, "Objects::NetworkGroup", description: "The group the network belongs to", null: true
    def network_group
      Loaders::Single.for(::NetworkGroup).load(object.network_group_id)
    end

  end
end
```

**Steps to reproduce**

Teardown and recreate all objects and schema

**Expected behavior**

Use new objects and not stack too deep

**Actual behavior**

See backtrace above

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I wrote up a quick replication using cyclical references as in your example, but it worked fine for me: 

```ruby 
require "bundler/inline"

gemfile do
  gem "graphql", "2.0.9"
end


class TypeOne < GraphQL::Schema::Object
  field :type_two, "TypeTwo"
end

class TypeTwo < GraphQL::Schema::Object
  field :type_one, "TypeOne"
end

class Query < GraphQL::Schema::Object
  field :type_one, TypeOne
end

class Schema < GraphQL::Schema
  query(Query)
end


puts Schema.to_definition

# type Query {
#   typeOne: TypeOne
# }

# type TypeOne {
#   typeTwo: TypeTwo
# }

# type TypeTwo {
#   typeOne: TypeOne
# }
```

Interestingly, I see `add_directives_from` in the stack trace. Does it appear elsewhere in the excluded section? Do you have any custom directives in your schema? (I wonder if there's a _very long_ cyclical reference from directives that isn't handled well by GraphQL-Ruby.)

**Comment by TSMMark** [comment]
> Does it appear elsewhere in the excluded section? 

Nope I only removed lines that were identical to the lines before and after 

>  custom directives in your schema? 

Not that I could find. I really don't think so

On first boot there is no error, which is probably why you could not reproduce. That's what I meant by "Teardown and recreate all objects and schema", but re-reading it now that was not clear. Sorry!

To elaborate, we have a hot loading mechanism where we `remove_const` all the objects and schemas and everything else and then re define them. It has worked great until the `1.13.0` version. 

If I had to guess, I think there may be some cached reference to the old object(s) somewhere in the graphql-ruby gem code, starting with `1.13.0`.

**Comment by TSMMark** [comment]
It's kind of like this in essence, but this small snippet does not reproduce the stack too deep error. I'll continue trying to repro in a shareable snippet

```ruby
require "bundler/inline"

gemfile do
  gem "graphql", "1.13.0"
end

class TypeOne < GraphQL::Schema::Object
  field :type_two, "TypeTwo"
end

class TypeTwo < GraphQL::Schema::Object
  field :type_one, "TypeOne"
end

class Query < GraphQL::Schema::Object
  field :type_one, "TypeOne"
end

class Schema < GraphQL::Schema
  query Query
end

puts Schema.to_definition

Object.send(:remove_const, :TypeOne)
TypeOne rescue puts "TypeOne is not defined 👍"
Object.send(:remove_const, :TypeTwo)
TypeTwo rescue puts "TypeTwo is not defined 👍"
Object.send(:remove_const, :Query)
Query rescue puts "Query is not defined 👍"
Object.send(:remove_const, :Schema)
Schema rescue puts "Schema is not defined 👍"

class TypeOne < GraphQL::Schema::Object
  field :type_two, "TypeTwo"
end

class TypeTwo < GraphQL::Schema::Object
  field :type_one, "TypeOne"
end

class Query < GraphQL::Schema::Object
  field :type_one, "TypeOne"
end

class Schema < GraphQL::Schema
  query Query
end

puts Schema.to_definition
```

Output:

```
type Query {
  typeOne: TypeOne
}

type TypeOne {
  typeTwo: TypeTwo
}

type TypeTwo {
  typeOne: TypeOne
}
TypeOne is not defined 👍
TypeTwo is not defined 👍
Query is not defined 👍
Schema is not defined 👍
type Query {
  typeOne: TypeOne
}

type TypeOne {
  typeTwo: TypeTwo
}

type TypeTwo {
  typeOne: TypeOne
}
```

**Comment by TSMMark** [comment]
I still can't get a small repro, but I tried digging thru the diff between version that worked and that didn't.

Looks like `add_type_and_traverse` was modified and the recursion issue is coming from in there:

https://github.com/rmosolgo/graphql-ruby/compare/95392ba27a52b695569a9c0947ebe02a68c916c3...ec0611acdadf39243ac680a0224550a09d0fc043#diff-ca02a7189be9dc9f1c0d328028ba139f8be8da82eca96bbfccd3c098b5ad03f7R1783-R1812

also `add_type`. Maybe this `# No need to re-visit` bit?

https://github.com/rmosolgo/graphql-ruby/compare/95392ba27a52b695569a9c0947ebe02a68c916c3...ec0611acdadf39243ac680a0224550a09d0fc043#diff-757c851acc813feb446c8c6c03e673384c603aa53cb39c6e302ce12a20df3730R156-R157

I'm really not very familiar with the inner workings of this gem. Maybe you have a guess as to what changed that could be a hint where to look / how to craft a small repro

**Comment by TSMMark** [comment]
After some debugging, I discovered that `prev_type` contained an array of many instances of the graphql object type class here: https://github.com/rmosolgo/graphql-ruby/compare/95392ba27a52b695569a9c0947ebe02a68c916c3...ec0611acdadf39243ac680a0224550a09d0fc043 

lib/graphql/schema/addition.rb LOC 156-157

```ruby
        if (prev_type = get_local_type(type.graphql_name)) && prev_type == type
          # No need to re-visit
```

I changed the condition to check if `prev_type` is an array and check if the array already includes the `type`

```
if (prev_type = get_local_type(type.graphql_name)) && (prev_type == type || (prev_type.is_a?(Array) && prev_type.include?(type)))
```

That avoided the infinite loop and seemed to work perfectly. I ran some basic queries and they seem to work still.

Any idea of the implications of making a change like this? And would you accept a PR to make this change? I can submit one if so.

Thanks!
