### ISSUE TITLE
[PRO] Bad handling of invalid cursor with relay connection edges request

### ISSUE THREAD

**Issue by such** [rmosolgo/graphql-ruby#4148]
**Describe the bug**

A simple graphql request on a Relay connection `edges` throws if the `after` cursor is invalid.

It works fine when the request is on the connection `nodes`.

**Versions**

`graphql` version: 2.0.12
`graphql-pro` version: 1.22.2
`rails` (or other framework): 7.0.2.4

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class Schema < GraphQL::Schema
  connections.add(ActiveRecord::Relation, GraphQL::Pro::PostgresStableRelationConnection)

  default_max_page_size 50

  class Card < GraphQL::Schema::Object
    implements GraphQL::Types::Relay::Node

    global_id_field :id
  end

  class Query < GraphQL::Schema::Object
    field :cards, Card.connection_type, null: true

    def cards
      ::Card.all
    end
  end

  query(Query)
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
{
    cards(after: "test") {
      pageInfo {
        endCursor
      }
      edges {
        node {
          id
        }
      }
    }
  }
```

**Steps to reproduce**

https://gist.github.com/such/1ae00ba56d160c39120539e11500e18c

**Expected behavior**

A clear error

**Actual behavior**

An exception

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
/Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/pagination/connection.rb:157:in `edges': undefined method `map' for nil:NilClass (NoMethodError)

        @edges ||= nodes.map { |n| @edge_class.new(n, self) }
                        ^^^^
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:707:in `public_send'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:707:in `block (2 levels) in resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:817:in `block in with_extensions'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:853:in `block (2 levels) in run_extensions_before_resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:856:in `run_extensions_before_resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:853:in `block in run_extensions_before_resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field_extension.rb:137:in `resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:840:in `run_extensions_before_resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:812:in `with_extensions'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:657:in `block in resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema.rb:1031:in `after_lazy'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/field.rb:655:in `resolve'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:502:in `block (3 levels) in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/tracing.rb:65:in `trace'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:501:in `block (2 levels) in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:830:in `call_method_on_directives'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:498:in `block in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:929:in `after_lazy'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:436:in `evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:425:in `evaluate_selection'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:739:in `block (3 levels) in continue_field'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:830:in `call_method_on_directives'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:738:in `block (2 levels) in continue_field'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:729:in `block in continue_field'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:929:in `after_lazy'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:715:in `continue_field'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:516:in `block (3 levels) in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:929:in `after_lazy'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:513:in `block (2 levels) in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:830:in `call_method_on_directives'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:498:in `block in evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:929:in `after_lazy'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:436:in `evaluate_selection_with_args'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:429:in `block in evaluate_selection'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/member/has_arguments.rb:246:in `block (3 levels) in coerce_arguments'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/member/has_arguments.rb:227:in `block (2 levels) in coerce_arguments'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/member/has_arguments.rb:226:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/member/has_arguments.rb:226:in `block in coerce_arguments'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema/member/has_arguments.rb:255:in `coerce_arguments'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/arguments_cache.rb:52:in `dataload_for'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:428:in `evaluate_selection'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:830:in `call_method_on_directives'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:830:in `call_method_on_directives'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter.rb:51:in `block in evaluate'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/tracing.rb:65:in `trace'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter.rb:50:in `evaluate'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/interpreter.rb:26:in `begin_query'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:118:in `begin_query'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:81:in `block (4 levels) in run_all'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:81:in `block (3 levels) in run_all'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:80:in `each'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:80:in `each_with_index'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:80:in `block (2 levels) in run_all'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:67:in `block in run_all'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/tracing.rb:65:in `trace'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/execution/multiplex.rb:66:in `run_all'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema.rb:993:in `multiplex'
	from /Users/adrien/.rvm/gems/ruby-3.1.1@sorare/gems/graphql-2.0.12/lib/graphql/schema.rb:969:in `execute'
	from cursor.rb:49:in `<main>
```

</details>

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I just released 1.22.3 with a fix. (Apparently `pageInfo` and `nodes` worked fine in this case... but not `edges`!)
