### ISSUE TITLE
Resolvers do inherit context anymore in GraphQL 2.0.13

### ISSUE THREAD

**Issue by ldlgds2** [rmosolgo/graphql-ruby#4165]
**Describe the bug**

Several resolvers defined call in QueryType do not seem to inherit context anymore.

**Versions**

`graphql` version: 2.0.13
`rails` (or other framework): 6.1.6.1

**GraphQL schema**

```ruby
module Types
  class QueryType < Types::BaseObject
...
    field :gather_things,
          resolver: Resolvers::GatherThings,
          null: true do
      argument :scope, String, required: false
      argument :scope_id, ID, required: false
...
end

module Resolvers
  class Base < GraphQL::Schema::Resolver
    def current_user_id
      @current_user_id ||= context[:current_user].id
    end
  end
end

module Resolvers
  class GatherThings < Resolvers::Base
...
    def things_resolver(scope, scope_id)
      if scope.nil?
        Thing.from_user(current_user_id)
...
      end
    end
...
end```

**Steps to reproduce**

Call the query `gather_things`

**Expected behavior**

Return things or empty array.

**Actual behavior**

Context is not found and hence no `current_user_id`

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
undefined method 'id' for nil:NilClass
/Users/ldlgds/Documents/MyApplication/Code/api/app/graphql/resolvers/base.rb:6:in 'current_user_id'
/Users/ldlgds/Documents/MyApplication/Code/api/app/graphql/resolvers/gather_things.rb:18:in 'assets_resolver'
/Users/ldlgds/Documents/MyApplication/Code/api/app/graphql/resolvers/gather_things.rb:9:in 'resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/resolver.rb:105:in 'public_send'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/resolver.rb:105:in 'block (3 levels) in resolve_with_support'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:1031:in 'after_lazy'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/resolver.rb:93:in 'block (2 levels) in resolve_with_support'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:1031:in 'after_lazy'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/resolver.rb:84:in 'block in resolve_with_support'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:1031:in 'after_lazy'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/resolver.rb:73:in 'resolve_with_support'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:686:in 'public_send'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:686:in 'block (2 levels) in resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:818:in 'block in with_extensions'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:854:in 'block (2 levels) in run_extensions_before_resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:857:in 'run_extensions_before_resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:854:in 'block in run_extensions_before_resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field_extension.rb:137:in 'resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:841:in 'run_extensions_before_resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:813:in 'with_extensions'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:657:in 'block in resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:1031:in 'after_lazy'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/field.rb:655:in 'resolve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:501:in 'block (3 levels) in evaluate_selection_with_args'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/tracing.rb:65:in 'trace'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:500:in 'block (2 levels) in evaluate_selection_with_args'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:828:in 'call_method_on_directives'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:497:in 'block in evaluate_selection_with_args'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:927:in 'after_lazy'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:435:in 'evaluate_selection_with_args'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:428:in 'block in evaluate_selection'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/member/has_arguments.rb:246:in 'block (3 levels) in coerce_arguments'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/dataloader/null_dataloader.rb:19:in 'append_job'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/member/has_arguments.rb:227:in 'block (2 levels) in coerce_arguments'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/member/has_arguments.rb:226:in 'each'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/member/has_arguments.rb:226:in 'block in coerce_arguments'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema/member/has_arguments.rb:255:in 'coerce_arguments'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/arguments_cache.rb:52:in 'dataload_for'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:427:in 'evaluate_selection'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:358:in 'block (2 levels) in evaluate_selections'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/dataloader/null_dataloader.rb:19:in 'append_job'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:357:in 'block in evaluate_selections'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:356:in 'each'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:356:in 'evaluate_selections'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:231:in 'block (4 levels) in run_eager'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:828:in 'call_method_on_directives'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:230:in 'block (3 levels) in run_eager'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/dataloader/null_dataloader.rb:19:in 'append_job'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:228:in 'block (2 levels) in run_eager'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:190:in 'tap_or_each'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:219:in 'block in run_eager'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:828:in 'call_method_on_directives'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter/runtime.rb:210:in 'run_eager'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter.rb:51:in 'block in evaluate'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/tracing.rb:65:in 'trace'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter.rb:50:in 'evaluate'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/interpreter.rb:26:in 'begin_query'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:118:in 'begin_query'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:81:in 'block (4 levels) in run_all'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/dataloader/null_dataloader.rb:19:in 'append_job'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:81:in 'block (3 levels) in run_all'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:80:in 'each'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:80:in 'each_with_index'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:80:in 'block (2 levels) in run_all'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:29:in 'block (2 levels) in apply_instrumenters'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:46:in 'block (2 levels) in each_query_call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:41:in 'each_query_call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:45:in 'block in each_query_call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:72:in 'call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:44:in 'each_query_call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:27:in 'block in apply_instrumenters'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:72:in 'call_hooks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/instrumentation.rb:26:in 'apply_instrumenters'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:67:in 'block in run_all'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/tracing.rb:65:in 'trace'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/execution/multiplex.rb:66:in 'run_all'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:993:in 'multiplex'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/graphql-2.0.13/lib/graphql/schema.rb:969:in 'execute'
/Users/ldlgds/Documents/Circle Share/Code/api/app/controllers/graphql_controller.rb:14:in 'execute'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/basic_implicit_render.rb:6:in 'send_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:228:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/rendering.rb:30:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:42:in 'block in process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:106:in 'run_callbacks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/abstract_controller/callbacks.rb:41:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/rescue.rb:22:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:34:in 'block in process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in 'block in instrument'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications/instrumenter.rb:24:in 'instrument'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/notifications.rb:203:in 'instrument'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/instrumentation.rb:33:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal/params_wrapper.rb:249:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/railties/controller_runtime.rb:27:in 'process_action'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/abstract_controller/base.rb:165:in 'process'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:190:in 'dispatch'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_controller/metal.rb:254:in 'dispatch'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:50:in 'dispatch'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:33:in 'serve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:50:in 'block in serve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in 'each'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/journey/router.rb:32:in 'serve'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/routing/route_set.rb:842:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:202:in 'call!'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:169:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:202:in 'call!'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/omniauth-2.1.0/lib/omniauth/strategy.rb:169:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/omniauth-2.1.0/lib/omniauth/builder.rb:44:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/bullet-7.0.3/lib/bullet/rack.rb:15:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/http_accept_language-2.1.1/lib/http_accept_language/middleware.rb:14:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-jwt_auth-0.6.0/lib/warden/jwt_auth/middleware/token_dispatcher.rb:20:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-jwt_auth-0.6.0/lib/warden/jwt_auth/middleware/revocation_manager.rb:21:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/builder.rb:244:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-jwt_auth-0.6.0/lib/warden/jwt_auth/middleware.rb:22:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in 'context'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/cookies.rb:689:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-1.2.9/lib/warden/manager.rb:36:in 'block in call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-1.2.9/lib/warden/manager.rb:34:in 'catch'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/warden-1.2.9/lib/warden/manager.rb:34:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/etag.rb:27:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/head.rb:12:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activerecord-6.1.6.1/lib/active_record/migration.rb:601:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:27:in 'block in call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/callbacks.rb:98:in 'run_callbacks'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/callbacks.rb:26:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/actionable_exceptions.rb:18:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/debug_exceptions.rb:29:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/show_exceptions.rb:33:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:37:in 'call_app'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:26:in 'block in call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in 'block in tagged'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:37:in 'tagged'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/activesupport-6.1.6.1/lib/active_support/tagged_logging.rb:99:in 'tagged'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/railties-6.1.6.1/lib/rails/rack/logger.rb:26:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/remote_ip.rb:81:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/request_id.rb:26:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/runtime.rb:22:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/executor.rb:14:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/static.rb:24:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/actionpack-6.1.6.1/lib/action_dispatch/middleware/host_authorization.rb:148:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/rack-cors-1.1.1/lib/rack/cors.rb:100:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/railties-6.1.6.1/lib/rails/engine.rb:539:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/configuration.rb:252:in 'call'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/request.rb:77:in 'block in handle_request'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/thread_pool.rb:340:in 'with_force_shutdown'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/request.rb:76:in 'handle_request'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/server.rb:441:in 'process_client'
/Users/ldlgds/.rvm/gems/ruby-3.0.4/gems/puma-5.6.4/lib/puma/thread_pool.rb:147:in 'block in spawn_thread'
Completed 500 Internal Server Error in 95ms (Views: 0.9ms | ActiveRecord: 9.7ms | Allocations: 49154)```
</details>

**Comment by ldlgds2** [comment]
Rolling back to 2.0.12 is a temporary fix.

**Comment by ldlgds2** [comment]
I later found out that something was nullifying my session upstream. This was due to the use of JWTs for session management and mixing them with cookies for OmniAuth. I have to work out on a solution for using both depending on the intended use.
