### ISSUE TITLE
SyntaxError - unexpected local variable or method, expecting

### ISSUE THREAD

**Issue by bake0937** [rmosolgo/graphql-ruby#4168]
**Describe the bug**

If a Query is executed with incorrect syntax and raises a StandardError, an exception is now raised instead of a response.

**Versions**

`graphql` version: `2.0.12`

`rails` (or other framework): `7.0.3.1`

`ruby` version: `3.1.2`

**GraphQL schema**

Sample resolver:

```ruby
class UsersResolver <  GraphQL::Schema::Resolver
  class UserType < Types::BaseObject
    field :data, [Types::UserType], null: false
    field :paging, Types::PagingType, null: false
  end

  type UsersType, null: false

  argument :page, Int, required: false
  argument :limit, Int, required: false

  def resolve(**_args)
    users = User.all
    {
      data: users
    }
  end
end
```

sample `app/graphql/project_schema.rb`
```ruby
class ProjectSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  ・・・

  rescue_from(StandardError) do |_err, _obj, _args, _ctx, _field|
    raise GraphQL::ExecutionError.new("An unexpected error occurred", extensions: { code: 'INTERNAL ERROR' })
  end
end
```

**Steps to reproduce**

Make a syntax error as follows．

```diff
class UsersResolver <  GraphQL::Schema::Resolver
  class UserType < Types::BaseObject
    field :data, [Types::UserType], null: false
    field :paging, Types::PagingType, null: false
  end

  type UsersType, null: false

  argument :page, Int, required: false
  argument :limit, Int, required: false

  def resolve(**_args)
--    users = User.all
++    users = User.all(
    {
      data: users
    }
  end
end
```

Execute the query
```graphql
query {
  users(
    page: null
    limit: null
  ) {
    data {
      id
    }
  }
}
```

**Expected behavior**

```json
{
  "data": null,
  "errors": [
    {
      "message": "An unexpected error occurred",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

**Actual behavior**

Not the expected response, exception `"exception": "#<SyntaxError: /app/app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'\n..."` is displayed

<details>
<summary>Click to view exception backtrace</summary>

```json
{
  "status": 500,
  "error": "Internal Server Error",
  "exception": "#<SyntaxError: /app/app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'\n      users = users.where(enabled: args[...\n      ^~~~~\n>",
  "traces": {
    "Application Trace": [
      {
        "exception_object_id": 18440,
        "id": 0,
        "trace": "app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'"
      },
      {
        "exception_object_id": 18440,
        "id": 3,
        "trace": "app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'"
      },
      {
        "exception_object_id": 18440,
        "id": 8,
        "trace": "app/graphql/types/query_type.rb:13:in `<class:QueryType>'"
      },
      {
        "exception_object_id": 18440,
        "id": 9,
        "trace": "app/graphql/types/query_type.rb:3:in `<module:Types>'"
      },
      {
        "exception_object_id": 18440,
        "id": 10,
        "trace": "app/graphql/types/query_type.rb:1:in `<top (required)>'"
      },
      {
        "exception_object_id": 18440,
        "id": 13,
        "trace": "app/graphql/project_schema.rb:3:in `<class:ProjectSchema>'"
      },
      {
        "exception_object_id": 18440,
        "id": 14,
        "trace": "app/graphql/project_schema.rb:1:in `<top (required)>'"
      },
      {
        "exception_object_id": 18440,
        "id": 17,
        "trace": "app/controllers/graphql_controller.rb:16:in `execute'"
      }
    ],
    "Framework Trace": [
      {
        "exception_object_id": 18440,
        "id": 1,
        "trace": "      users = users.where(enabled: args[..."
      },
      {
        "exception_object_id": 18440,
        "id": 2,
        "trace": "      ^~~~~"
      },
      {
        "exception_object_id": 18440,
        "id": 4,
        "trace": "      users = users.where(enabled: args[..."
      },
      {
        "exception_object_id": 18440,
        "id": 5,
        "trace": "      ^~~~~"
      },
      {
        "exception_object_id": 18440,
        "id": 6,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 7,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 11,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 12,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 15,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 16,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 18,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 19,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/base.rb:215:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 20,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/rendering.rb:53:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 21,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 22,
        "trace": "activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'"
      },
      {
        "exception_object_id": 18440,
        "id": 23,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:233:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 24,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 25,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 26,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `block in instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 27,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 28,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 29,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 30,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 31,
        "trace": "activerecord (7.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 32,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/base.rb:151:in `process'"
      },
      {
        "exception_object_id": 18440,
        "id": 33,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal.rb:188:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 34,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal.rb:251:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 35,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 36,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 37,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 38,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'"
      },
      {
        "exception_object_id": 18440,
        "id": 39,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 40,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:852:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 41,
        "trace": "bullet (7.0.3) lib/bullet/rack.rb:15:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 42,
        "trace": "rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'"
      },
      {
        "exception_object_id": 18440,
        "id": 43,
        "trace": "rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 44,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/cookies.rb:697:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 45,
        "trace": "rack (2.2.4) lib/rack/etag.rb:27:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 46,
        "trace": "rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 47,
        "trace": "rack (2.2.4) lib/rack/head.rb:12:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 48,
        "trace": "activerecord (7.0.3.1) lib/active_record/migration.rb:603:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 49,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
      },
      {
        "exception_object_id": 18440,
        "id": 50,
        "trace": "activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'"
      },
      {
        "exception_object_id": 18440,
        "id": 51,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 52,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 53,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 54,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 55,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 56,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:40:in `call_app'"
      },
      {
        "exception_object_id": 18440,
        "id": 57,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `block in call'"
      },
      {
        "exception_object_id": 18440,
        "id": 58,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `block in tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 59,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:38:in `tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 60,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 61,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 62,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 63,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 64,
        "trace": "rack (2.2.4) lib/rack/runtime.rb:22:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 65,
        "trace": "activesupport (7.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 66,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/server_timing.rb:20:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 67,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 68,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/static.rb:23:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 69,
        "trace": "rack (2.2.4) lib/rack/sendfile.rb:110:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 70,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 71,
        "trace": "railties (7.0.3.1) lib/rails/engine.rb:530:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 72,
        "trace": "puma (5.6.4) lib/puma/configuration.rb:252:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 73,
        "trace": "puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'"
      },
      {
        "exception_object_id": 18440,
        "id": 74,
        "trace": "puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'"
      },
      {
        "exception_object_id": 18440,
        "id": 75,
        "trace": "puma (5.6.4) lib/puma/request.rb:76:in `handle_request'"
      },
      {
        "exception_object_id": 18440,
        "id": 76,
        "trace": "puma (5.6.4) lib/puma/server.rb:441:in `process_client'"
      },
      {
        "exception_object_id": 18440,
        "id": 77,
        "trace": "puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
      }
    ],
    "Full Trace": [
      {
        "exception_object_id": 18440,
        "id": 0,
        "trace": "app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'"
      },
      {
        "exception_object_id": 18440,
        "id": 1,
        "trace": "      users = users.where(enabled: args[..."
      },
      {
        "exception_object_id": 18440,
        "id": 2,
        "trace": "      ^~~~~"
      },
      {
        "exception_object_id": 18440,
        "id": 3,
        "trace": "app/graphql/resolvers/users_resolver.rb:18: syntax error, unexpected local variable or method, expecting ')'"
      },
      {
        "exception_object_id": 18440,
        "id": 4,
        "trace": "      users = users.where(enabled: args[..."
      },
      {
        "exception_object_id": 18440,
        "id": 5,
        "trace": "      ^~~~~"
      },
      {
        "exception_object_id": 18440,
        "id": 6,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 7,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 8,
        "trace": "app/graphql/types/query_type.rb:13:in `<class:QueryType>'"
      },
      {
        "exception_object_id": 18440,
        "id": 9,
        "trace": "app/graphql/types/query_type.rb:3:in `<module:Types>'"
      },
      {
        "exception_object_id": 18440,
        "id": 10,
        "trace": "app/graphql/types/query_type.rb:1:in `<top (required)>'"
      },
      {
        "exception_object_id": 18440,
        "id": 11,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 12,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 13,
        "trace": "app/graphql/project_schema.rb:3:in `<class:ProjectSchema>'"
      },
      {
        "exception_object_id": 18440,
        "id": 14,
        "trace": "app/graphql/project_schema.rb:1:in `<top (required)>'"
      },
      {
        "exception_object_id": 18440,
        "id": 15,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 16,
        "trace": "zeitwerk (2.6.0) lib/zeitwerk/kernel.rb:27:in `require'"
      },
      {
        "exception_object_id": 18440,
        "id": 17,
        "trace": "app/controllers/graphql_controller.rb:16:in `execute'"
      },
      {
        "exception_object_id": 18440,
        "id": 18,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 19,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/base.rb:215:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 20,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/rendering.rb:53:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 21,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:234:in `block in process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 22,
        "trace": "activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'"
      },
      {
        "exception_object_id": 18440,
        "id": 23,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/callbacks.rb:233:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 24,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/rescue.rb:22:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 25,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 26,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `block in instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 27,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications/instrumenter.rb:24:in `instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 28,
        "trace": "activesupport (7.0.3.1) lib/active_support/notifications.rb:206:in `instrument'"
      },
      {
        "exception_object_id": 18440,
        "id": 29,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/instrumentation.rb:66:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 30,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 31,
        "trace": "activerecord (7.0.3.1) lib/active_record/railties/controller_runtime.rb:27:in `process_action'"
      },
      {
        "exception_object_id": 18440,
        "id": 32,
        "trace": "actionpack (7.0.3.1) lib/abstract_controller/base.rb:151:in `process'"
      },
      {
        "exception_object_id": 18440,
        "id": 33,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal.rb:188:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 34,
        "trace": "actionpack (7.0.3.1) lib/action_controller/metal.rb:251:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 35,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'"
      },
      {
        "exception_object_id": 18440,
        "id": 36,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:32:in `serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 37,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 38,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `each'"
      },
      {
        "exception_object_id": 18440,
        "id": 39,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/journey/router.rb:32:in `serve'"
      },
      {
        "exception_object_id": 18440,
        "id": 40,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/routing/route_set.rb:852:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 41,
        "trace": "bullet (7.0.3) lib/bullet/rack.rb:15:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 42,
        "trace": "rack (2.2.4) lib/rack/session/abstract/id.rb:266:in `context'"
      },
      {
        "exception_object_id": 18440,
        "id": 43,
        "trace": "rack (2.2.4) lib/rack/session/abstract/id.rb:260:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 44,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/cookies.rb:697:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 45,
        "trace": "rack (2.2.4) lib/rack/etag.rb:27:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 46,
        "trace": "rack (2.2.4) lib/rack/conditional_get.rb:40:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 47,
        "trace": "rack (2.2.4) lib/rack/head.rb:12:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 48,
        "trace": "activerecord (7.0.3.1) lib/active_record/migration.rb:603:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 49,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'"
      },
      {
        "exception_object_id": 18440,
        "id": 50,
        "trace": "activesupport (7.0.3.1) lib/active_support/callbacks.rb:99:in `run_callbacks'"
      },
      {
        "exception_object_id": 18440,
        "id": 51,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 52,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 53,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 54,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 55,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 56,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:40:in `call_app'"
      },
      {
        "exception_object_id": 18440,
        "id": 57,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `block in call'"
      },
      {
        "exception_object_id": 18440,
        "id": 58,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `block in tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 59,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:38:in `tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 60,
        "trace": "activesupport (7.0.3.1) lib/active_support/tagged_logging.rb:114:in `tagged'"
      },
      {
        "exception_object_id": 18440,
        "id": 61,
        "trace": "railties (7.0.3.1) lib/rails/rack/logger.rb:25:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 62,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 63,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 64,
        "trace": "rack (2.2.4) lib/rack/runtime.rb:22:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 65,
        "trace": "activesupport (7.0.3.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 66,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/server_timing.rb:20:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 67,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/executor.rb:14:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 68,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/static.rb:23:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 69,
        "trace": "rack (2.2.4) lib/rack/sendfile.rb:110:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 70,
        "trace": "actionpack (7.0.3.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 71,
        "trace": "railties (7.0.3.1) lib/rails/engine.rb:530:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 72,
        "trace": "puma (5.6.4) lib/puma/configuration.rb:252:in `call'"
      },
      {
        "exception_object_id": 18440,
        "id": 73,
        "trace": "puma (5.6.4) lib/puma/request.rb:77:in `block in handle_request'"
      },
      {
        "exception_object_id": 18440,
        "id": 74,
        "trace": "puma (5.6.4) lib/puma/thread_pool.rb:340:in `with_force_shutdown'"
      },
      {
        "exception_object_id": 18440,
        "id": 75,
        "trace": "puma (5.6.4) lib/puma/request.rb:76:in `handle_request'"
      },
      {
        "exception_object_id": 18440,
        "id": 76,
        "trace": "puma (5.6.4) lib/puma/server.rb:441:in `process_client'"
      },
      {
        "exception_object_id": 18440,
        "id": 77,
        "trace": "puma (5.6.4) lib/puma/thread_pool.rb:147:in `block in spawn_thread'"
      }
    ]
  }
}
```

</details>

**Additional context**

I want the response to return what I set in rescue_from, not what Rails error returns as is.

I added a method(hogehoge) that did not exist and the response was as expected.

<details>
<summary>Click to view expected response</summary>

```diff
class UsersResolver <  GraphQL::Schema::Resolver
  class UserType < Types::BaseObject
    field :data, [Types::UserType], null: false
    field :paging, Types::PagingType, null: false
  end

  type UsersType, null: false

  argument :page, Int, required: false
  argument :limit, Int, required: false

  def resolve(**_args)
--    users = User.all
++    users = User.all.hogehoge
    {
      data: users
    }
  end
end
```

```json
{
  "data": null,
  "errors": [
    {
      "message": "An unexpected error occurred",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "users"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR"
      }
    }
  ]
}
```

</details>

It will probably be similar to https://github.com/rmosolgo/graphql-ruby/issues/4074.
Please comment if you have a fix or solution for this issue.

**Comment by rmosolgo** [comment]
As far as I know, GraphQL-Ruby can't rescue syntax errors, because they happen _before_ GraphQL starts running. In the backtrace, I see that Rails is loading files with zeitwerk (`...require...`) -- so it hasn't even loaded the constants that will be used for running the query. 

On the other hand, NoMethodErrors like the one you described happen _during_ execution: the query starts, and when it reaches `.hogehoge`, Ruby can't find a definition for that method so it 💥 s. In that case, GraphQL-Ruby has already started, so it can rescue that error. 

So, I don't think there's anything else `rescue_from` can do here!
