### ISSUE TITLE
selects? on Union type error on 2.0.14

### ISSUE THREAD

**Issue by joeosburn** [rmosolgo/graphql-ruby#4192]
Using the new graphql 2.0.14, when I run code like this:

```
lookahead.selection(:nodes) if lookahead.selects?(:nodes)
```

in a resolver returning a Union type, I get the following error:

```
      Failure/Error: lookahead.selection(:nodes) if lookahead.selects?(:nodes)

      NoMethodError:
        undefined method `fields' for Types::MyUnion:Class

                type.fields(context)
                    ^^^^^^^

      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/schema.rb:480:in `get_fields'
      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:171:in `block in fields'
      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:331:in `block in read_through'
      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:172:in `fields'
      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/execution/lookahead.rb:98:in `selection'
      # ruby-3.1.2/gems/graphql-2.0.14/lib/graphql/execution/lookahead.rb:80:in `selects?'
```

Perhaps related to this PR? https://github.com/rmosolgo/graphql-ruby/pull/4189

Thanks.

**Comment by rmosolgo** [comment]
Oops, I bet so! Thanks for the detailed report. I'll get a fix together soon and follow up here.
