### ISSUE TITLE
.selects? raises NoMethodError on GraphQL::Types::Boolean

### ISSUE THREAD

**Issue by frostevent** [rmosolgo/graphql-ruby#4215]
**Describe the bug**

Commit https://github.com/rmosolgo/graphql-ruby/commit/651cc07f33b272e611dbccaac47175643a68de59 broke the `.selects?` method on a `GraphQL::Types::Boolean`.

**Versions**

`graphql` version: [v2.0.14](https://github.com/rmosolgo/graphql-ruby/tree/v2.0.14)
`rails` version: [7.0.3.1](https://github.com/rails/rails/tree/v7.0.3.1)
`graphql-batch` version: [0.5.1](https://github.com/Shopify/graphql-batch/tree/v0.5.1)

**GraphQL schema**

```ruby
class MyQuery < GraphQL::Schema::Object
  description "query root"

  field :selecting_another_field, Boolean, null: false, extras: [:lookahead]

  def selecting_another_field(lookahead:)
    lookahead.selects?(:another_field)
  end
end

class MySchema < GraphQL::Schema
  query MyQuery
end
```

**GraphQL query**

```graphql
query {
  selectingAnotherField
}
```

**Steps to reproduce**
Call the provided query against the provided schema.

```
MySchema.execute(query)
```

**Expected behavior**
Returns the following JSON response:
```json
{
  "data": {
    "selectingAnotherField": false
  }
}
```

**Actual behavior**
Raises `NoMethodError`
```
NoMethodError: undefined method `fields' for GraphQL::Types::Boolean:Class
from /Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema.rb:480:in `get_fields'
```

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema.rb:480:in `get_fields'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:171:in `block in fields'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:331:in `block in read_through'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:172:in `fields'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/lookahead.rb:98:in `selection'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/lookahead.rb:80:in `selects?'
(pry):10:in `selecting_another_field'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:686:in `public_send'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:686:in `block (2 levels) in resolve'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:807:in `with_extensions'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:657:in `block in resolve'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema/field.rb:655:in `resolve'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:501:in `block (3 levels) in evaluate_selection_with_args'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:500:in `block (2 levels) in evaluate_selection_with_args'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:497:in `block in evaluate_selection_with_args'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:435:in `evaluate_selection_with_args'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:424:in `evaluate_selection'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:74:in `block (6 levels) in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:73:in `block (5 levels) in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:61:in `block (4 levels) in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `each'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `each_with_index'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `block (3 levels) in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:44:in `block in run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:37:in `run_all'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema.rb:995:in `multiplex'
/Users/jeremie/notarize/notarize-api/vendor/bundle/ruby/3.0.0/gems/graphql-2.0.14/lib/graphql/schema.rb:971:in `execute'
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by frostevent** [comment]
Thanks for the reply.

Yes, in my application I get the same result:
```
[4] pry(main)> GraphQL::Types::Boolean.kind.fields?
=> false
```

I see the check statement was added in https://github.com/rmosolgo/graphql-ruby/commit/ecd98b9f3ee894e50107b991a3e783fedc7e3d04 which occurred after the release of [v2.0.14](https://github.com/rmosolgo/graphql-ruby/tree/v2.0.14).

I'll try again with my application pointing to the latest commit and see if I can reproduce. I'll close if fixed. 

Thanks for the help 👍

**Comment by frostevent** [comment]
Confirming that 2.0.15 fixed it, thanks 👍
