### ISSUE TITLE
Custom introspection TypeType class: Found two visible definitions for `__Field`

### ISSUE THREAD

**Issue by 23tux** [rmosolgo/graphql-ruby#4225]
**Describe the bug**

I have a custom introspection module, that adds a related field to a type. It is used for an auto generated editor that needs more meta information about a GraphQL type. When I try to use `GraphQL::Introspection::FieldType` inside a custom introspection module as the type of a field, I get an error. 

**Versions**

`graphql` version: 2.0.14
`rails`: 6.0.5.1
`graphql-batch`: 0.5.1
`graphql-schema_comparator`: 1.1.2

**GraphQL schema**

```
class Queries < GraphQL::Schema::Object
  field :my_field, String, null: false

  def my_field
    "my_field"
  end
end

module MyIntrospection
  class TypeType < GraphQL::Introspection::TypeType
    field :related_field, GraphQL::Introspection::FieldType, null: true

    def related_field
      Queries.fields[:my_field]
    end
  end
end

class Schema < GraphQL::Schema
  query Queries
  introspection MyIntrospection
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
    query {
      __schema {
        types {
          name
          relatedField { name }
        }
      }
    }
```

**Steps to reproduce**

Call the GraphQL query with

```
Schema.execute(query).to_h
```

**Expected behavior**

I would expect to get every information under `relatedField` that I would get when using `types { fields { name } }` in an introspection query.

**Actual behavior**

I get an error when executing the query:

```
Found two visible definitions for `__Field`: GraphQL::Introspection::FieldType, #<Class:0x000055dadb5798e0> (GraphQL::Schema::DuplicateNamesError)
```

<details>
<summary>Click to view exception backtrace</summary>

```
Traceback (most recent call last):
        92: from -e:1:in `<main>'
        91: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        90: from /usr/local/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:72:in `require'
        89: from /usr/src/app/bin/rails:12:in `<main>'
        88: from /usr/local/bundle/gems/zeitwerk-2.6.1/lib/zeitwerk/kernel.rb:35:in `require'
        87: from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        86: from /usr/local/bundle/gems/bootsnap-1.13.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:32:in `require'
        85: from /usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands.rb:18:in `<main>'
        84: from /usr/local/bundle/gems/railties-6.0.5.1/lib/rails/command.rb:46:in `invoke'
        83: from /usr/local/bundle/gems/railties-6.0.5.1/lib/rails/command/base.rb:69:in `perform'
        82: from /usr/local/bundle/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
        81: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
        80: from /usr/local/bundle/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
        79: from /usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/runner/runner_command.rb:42:in `perform'
        78: from /usr/local/bundle/gems/railties-6.0.5.1/lib/rails/commands/runner/runner_command.rb:42:in `load'
        77: from foo.rb:24:in `<main>'
        76: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema.rb:971:in `execute'
        75: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema.rb:995:in `multiplex'
        74: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:37:in `run_all'
        73: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
        72: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:44:in `block in run_all'
        71: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
        70: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'
        69: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'
        68: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
        67: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'
        66: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'
        65: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'
        64: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `block (3 levels) in run_all'
        63: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `each_with_index'
        62: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:60:in `each'
        61: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:61:in `block (4 levels) in run_all'
        60: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        59: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:73:in `block (5 levels) in run_all'
        58: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
        57: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter.rb:74:in `block (6 levels) in run_all'
        56: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'
        55: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
        54: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'
        53: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
        52: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'
        51: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        50: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'
        49: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
        48: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'
        47: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
        46: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
        45: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
        44: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        43: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
        42: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:424:in `evaluate_selection'
        41: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:435:in `evaluate_selection_with_args'
        40: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
        39: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:497:in `block in evaluate_selection_with_args'
        38: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
        37: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:512:in `block (2 levels) in evaluate_selection_with_args'
        36: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
        35: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:515:in `block (3 levels) in evaluate_selection_with_args'
        34: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:714:in `continue_field'
        33: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
        32: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:728:in `block in continue_field'
        31: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'
        30: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:737:in `block (2 levels) in continue_field'
        29: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
        28: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:738:in `block (3 levels) in continue_field'
        27: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `evaluate_selections'
        26: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:356:in `each'
        25: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:357:in `block in evaluate_selections'
        24: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        23: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:358:in `block (2 levels) in evaluate_selections'
        22: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:424:in `evaluate_selection'
        21: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:435:in `evaluate_selection_with_args'
        20: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:927:in `after_lazy'
        19: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:497:in `block in evaluate_selection_with_args'
        18: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:828:in `call_method_on_directives'
        17: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:500:in `block (2 levels) in evaluate_selection_with_args'
        16: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/tracing.rb:65:in `trace'
        15: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/execution/interpreter/runtime.rb:501:in `block (3 levels) in evaluate_selection_with_args'
        14: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:655:in `resolve'
        13: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema.rb:1033:in `after_lazy'
        12: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:657:in `block in resolve'
        11: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:813:in `with_extensions'
        10: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:841:in `run_extensions_before_resolve'
         9: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field_extension.rb:137:in `resolve'
         8: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:854:in `block in run_extensions_before_resolve'
         7: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:857:in `run_extensions_before_resolve'
         6: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:854:in `block (2 levels) in run_extensions_before_resolve'
         5: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:818:in `block in with_extensions'
         4: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:688:in `block (2 levels) in resolve'
         3: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/field.rb:688:in `public_send'
         2: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/introspection/schema_type.rb:23:in `types'
         1: from /usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:128:in `reachable_types'
/usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:367:in `reachable_type_set': Found two visible definitions for `__Field`: GraphQL::Introspection::FieldType, #<Class:0x000055dadb5798e0> (GraphQL::Schema::DuplicateNamesError)
```

</details>

**Additional context**
A wild guess would be this: Calling `GraphQL::Introspection::FieldType` in my custom introspection module defines a custom GraphQL type with the name `__Field`. But as I provide a custom introspection module, there is another implementation generated that also uses `__Field` as it's name, and this one is used in this class `#<Class:0x000055dadb5798e0>`.

This kinda sounds like a chicken-and-egg problem: I can't use the generated `__Field` during it's generation... But I'm not sure if that makes any sense.

**Comment by rmosolgo** [comment]
Sorry for the trouble and thanks for the detailed report! I think you're exactly right about what's going wrong. When GraphQL-Ruby encounters a custom introspection module, it populates that module with subclasses of the built-in introspection classes: 

https://github.com/rmosolgo/graphql-ruby/blob/d799eb3e455cf6a0038e78e1f2ac24fe2c5fc90c/lib/graphql/schema/introspection_system.rb#L17-L26

https://github.com/rmosolgo/graphql-ruby/blob/d799eb3e455cf6a0038e78e1f2ac24fe2c5fc90c/lib/graphql/schema/introspection_system.rb#L104-L110

But obviously, that gets messed up in this case :S 

I think you could work around it by making a custom `FieldType` class, then referencing that one: 

```diff
  module MyIntrospection
+   class FieldType < GraphQL::Introspection::FieldType
+   end 
+
    class TypeType < GraphQL::Introspection::TypeType
-     field :related_field, GraphQL::Introspection::FieldType, null: true
+     field :related_field, FieldType, null: true
  
      def related_field
        Queries.fields[:my_field]
      end
    end
  end
```

That way, the new field would use the new, custom `FieldType` instead of the old built-in one. Want to give that a try?

**Comment by 23tux** [comment]
@rmosolgo Thanks for the feedback!

Unfortunately, this didn't work, I still get the same error. I also tried to rename the custom `FieldType` class to `FieldTestType` in hope that it generates a different name, but no:

```
/usr/local/bundle/gems/graphql-2.0.14/lib/graphql/schema/warden.rb:367:in `reachable_type_set': Found two visible definitions for `__Field`: Introspection::FieldTestType, #<Class:0x000055af14df1ad8> (GraphQL::Schema::DuplicateNamesError)
```

Do you have any other idea? Is there any way to access the used `GraphQL::Introspection::FieldType` in my introspection module? Or is it not available yet, because we're during the init phase of the schema? 

Or would using an orphan type help in any way? Or maybe it is possible to add the `field :related_field` AFTER the schema is initialized? But I'm just bouncing ideas here.

**Comment by 23tux** [comment]
@rmosolgo I played around a little bit, and it seems like this is working:

```
# frozen_string_literal: true

class Queries < GraphQL::Schema::Object
  field :my_field, String, null: false do
    argument :blub, String, required: false
  end

  def my_field
    "my_field"
  end
end

module Introspection
  class TypeType < GraphQL::Introspection::TypeType
  end
end

class Schema < GraphQL::Schema
  query Queries
  introspection Introspection
end

Introspection::TypeType.field(:related_field, Schema.introspection_system.types.fetch("__Field"), null: true)
Introspection::TypeType.define_method(:related_field) do
  Queries.fields["myField"]
end
```

It feels pretty hacky though: Adding the `:related_field` field *AFTER* the custom introspection module is installed and the schema is loaded. Could this cause any issues with the internal caching of the GraphQL gem? Would you recommend doing it this way?

**Comment by rmosolgo** [comment]
I think that should be OK -- if the `.field(...)` call was adding a new type to the schema, it might not work, but since it's reusing an already-added type from the schema, it should work fine. To be sure it's getting the same type that's used by the schema, you could also do it this way: 

```ruby
...field(..., Schema.get_type("__Field")
```

Although, under the hood, `Schema.get_type` will end up doing the same kind of lookup that you suggest above. So I think either way will work!
