### ISSUE TITLE
Support for multiple Schemas

### ISSUE THREAD

**Issue by caseyprovost** [rmosolgo/graphql-ruby#4273]
**Describe the bug**

I have 2 APIs that I want to serve from the same Rails app. I've built 2 separate schemas and removed most sharing of base fields so that `Types::BaseObject` becomes `Types::B2b::BaseObject` in the second API. The problem is that I cannot seem to get around the problem of multiple definitions of Types. Example error below:

```json
{"errors":[{"message":"Found two visible definitions for `Collection`: Types::B2b::CollectionType, Types::CollectionType","backtrace":
```

I am not sure if this is a bug, a limitation of the library, or user error. But hopefully, the description above helps.

**Versions**

* graphql (2.0.15)
* graphql-batch (0.5.1)
* Rails 7.0.4

`graphql` version:
`rails` (or other framework):
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
module Types
  module B2b
    class CollectionType < BaseObject
      field :id, ID, null: false
    end
  end
end

module Types
  class CollectionType < Types::BaseObject
    field :id, ID, null: false
  end
end

module Types
  module B2b
    class QueryType < BaseObject
      include GraphQL::Types::Relay::HasNodeField
      include GraphQL::Types::Relay::HasNodesField

      field :viewer, Types::B2b::ViewerType, null: true
      field :collections, Types::B2b::CollectionType.connection_type, null: false
      field :collection, Types::B2b::CollectionType do
        argument :id, ID, required: true
      end
    end
  end
end

module Types
  class QueryType < Types::BaseObject
    include GraphQL::Types::Relay::HasNodeField
    include GraphQL::Types::Relay::HasNodesField

    field :viewer, Types::ViewerType, null: true
    field :collections, Types::CollectionType.connection_type, null: true
    field :collection, Types::CollectionType, null: true do
      description "get an individual collection"
      argument :id, ID, required: true
    end
  end
end

class ApiSchema < GraphQL::Schema
  include SchemaHelper

  mutation(Types::MutationType)
  query(Types::QueryType)
  use GraphQL::Batch
  use GraphQL::Dataloader
end

class B2bSchema < GraphQL::Schema
  include SchemaHelper

  mutation(Types::B2b::MutationType)
  query(Types::B2b::QueryType)
  use GraphQL::Batch
  use GraphQL::Dataloader
end
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query {
  {
  collections {
    totalCount

    edges {
      node {
        id
      }  
    }
  }
}
}
```

```json
{"errors":[{"message":"Found two visible definitions for `Collection`: Types::B2b::CollectionType, Types::CollectionType","backtrace":["/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/warden.rb:367:in `reachable_type_set'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/warden.rb:128:in `reachable_types'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/introspection/schema_type.rb:23:in `types'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:688:in `public_send'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:688:in `block (2 levels) in resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:818:in `block in with_extensions'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:854:in `block (2 levels) in run_extensions_before_resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:857:in `run_extensions_before_resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:854:in `block in run_extensions_before_resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field_extension.rb:137:in `resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:841:in `run_extensions_before_resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:813:in `with_extensions'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:657:in `block in resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema.rb:1043:in `after_lazy'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema/field.rb:655:in `resolve'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:511:in `block (3 levels) in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/tracing.rb:65:in `trace'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:510:in `block (2 levels) in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:434:in `evaluate_selection'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:368:in `block (2 levels) in evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `each'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:752:in `block (3 levels) in continue_field'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:751:in `block (2 levels) in continue_field'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:200:in `tap_or_each'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:742:in `block in continue_field'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:728:in `continue_field'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:525:in `block (3 levels) in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:522:in `block (2 levels) in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:942:in `after_lazy'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:434:in `evaluate_selection'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:368:in `block (2 levels) in evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `each'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:366:in `evaluate_selections'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:241:in `block (4 levels) in run_eager'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:240:in `block (3 levels) in run_eager'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:238:in `block (2 levels) in run_eager'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:200:in `tap_or_each'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:229:in `block in run_eager'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:842:in `call_method_on_directives'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter/runtime.rb:220:in `run_eager'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:74:in `block (6 levels) in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/tracing.rb:65:in `trace'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:73:in `block (5 levels) in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:61:in `block (4 levels) in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `each'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `each_with_index'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:60:in `block (3 levels) in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:193:in `call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:193:in `call_hooks'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:44:in `block in run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/tracing.rb:65:in `trace'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/execution/interpreter.rb:37:in `run_all'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema.rb:1005:in `multiplex'","/bundle/ruby/3.1.0/gems/graphql-2.0.15/lib/graphql/schema.rb:981:in `execute'","/app/app/controllers/b2b/graphql_controller.rb:16:in `execute'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:215:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/rendering.rb:53:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:234:in `block in process_action'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:118:in `block in run_callbacks'","/bundle/ruby/3.1.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'","/bundle/ruby/3.1.0/gems/audited-5.0.2/lib/audited/sweeper.rb:16:in `around'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'","/bundle/ruby/3.1.0/gems/actiontext-7.0.4/lib/action_text/rendering.rb:20:in `with_renderer'","/bundle/ruby/3.1.0/gems/actiontext-7.0.4/lib/action_text/engine.rb:69:in `block (4 levels) in \u003cclass:Engine\u003e'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `instance_exec'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:127:in `block in run_callbacks'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:138:in `run_callbacks'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/callbacks.rb:233:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/rescue.rb:22:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `block in instrument'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications/instrumenter.rb:24:in `instrument'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/notifications.rb:206:in `instrument'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/instrumentation.rb:66:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'","/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/railties/controller_runtime.rb:27:in `process_action'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/abstract_controller/base.rb:151:in `process'","/bundle/ruby/3.1.0/gems/actionview-7.0.4/lib/action_view/rendering.rb:39:in `process'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:188:in `dispatch'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_controller/metal.rb:251:in `dispatch'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:32:in `serve'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:50:in `block in serve'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `each'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/journey/router.rb:32:in `serve'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/routing/route_set.rb:852:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'","/bundle/ruby/3.1.0/gems/bullet-7.0.3/lib/bullet/rack.rb:15:in `call'","/bundle/ruby/3.1.0/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb:77:in `memoized_call'","/bundle/ruby/3.1.0/gems/flipper-0.23.1/lib/flipper/middleware/memoizer.rb:42:in `call'","/bundle/ruby/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:36:in `block in call'","/bundle/ruby/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `catch'","/bundle/ruby/3.1.0/gems/warden-1.2.9/lib/warden/manager.rb:34:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/tempfile_reaper.rb:15:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/etag.rb:27:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/conditional_get.rb:40:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/head.rb:12:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/http/permissions_policy.rb:38:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/http/content_security_policy.rb:36:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:266:in `context'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/session/abstract/id.rb:260:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/cookies.rb:696:in `call'","/bundle/ruby/3.1.0/gems/activerecord-7.0.4/lib/active_record/migration.rb:603:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/callbacks.rb:99:in `run_callbacks'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/callbacks.rb:26:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'","/bundle/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:132:in `call_app'","/bundle/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:19:in `block in call'","/bundle/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `catch'","/bundle/ruby/3.1.0/gems/web-console-4.2.0/lib/web_console/middleware.rb:17:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'","/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:40:in `call_app'","/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:25:in `block in call'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `block in tagged'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:37:in `tagged'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/tagged_logging.rb:99:in `tagged'","/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/rack/logger.rb:25:in `call'","/bundle/ruby/3.1.0/gems/sprockets-rails-3.4.2/lib/sprockets/rails/quiet_assets.rb:13:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'","/bundle/ruby/3.1.0/gems/request_store-1.5.1/lib/request_store/middleware.rb:19:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/request_id.rb:26:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/method_override.rb:24:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/runtime.rb:22:in `call'","/bundle/ruby/3.1.0/gems/activesupport-7.0.4/lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/server_timing.rb:60:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/executor.rb:14:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/static.rb:23:in `call'","/bundle/ruby/3.1.0/gems/rack-2.2.4/lib/rack/sendfile.rb:110:in `call'","/bundle/ruby/3.1.0/gems/actionpack-7.0.4/lib/action_dispatch/middleware/host_authorization.rb:131:in `call'","/bundle/ruby/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/error_notifier.rb:33:in `block in call'","/bundle/ruby/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/agent.rb:433:in `with_rack_env'","/bundle/ruby/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/error_notifier.rb:30:in `call'","/bundle/ruby/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/user_feedback.rb:31:in `call'","/bundle/ruby/3.1.0/gems/honeybadger-5.0.2/lib/honeybadger/rack/user_informer.rb:21:in `call'","/bundle/ruby/3.1.0/gems/rack-mini-profiler-3.0.0/lib/mini_profiler/profiler.rb:393:in `call'","/bundle/ruby/3.1.0/gems/railties-7.0.4/lib/rails/engine.rb:530:in `call'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/configuration.rb:268:in `call'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:89:in `block in handle_request'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:343:in `with_force_shutdown'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/request.rb:88:in `handle_request'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:430:in `process_client'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/server.rb:233:in `block in run'","/bundle/ruby/3.1.0/gems/puma-6.0.0/lib/puma/thread_pool.rb:150:in `block in spawn_thread'"]}],"data":{}}
```

**Steps to reproduce**

2 Schemas, try to use GraphiQL to load one of them.

**Expected behavior**

No duplicate types

**Actual behavior**

Duplicate types detected causing a 500 error

**Additional context**

Let me know if you need more information!

**Comment by caseyprovost** [comment]
Found the issue, it was user-error. Sorry for the noise!
