### ISSUE TITLE
`coerce_input` sometimes weirdly receives `GraphQL::Language` nodes

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#4307]
**Describe the bug**

I've found that while `coerce_input` _usually_ receives field arguments in their natural ruby form, occasionally it receives field arguments as `GraphQL::Language::Nodes::...` types.  This is unexpected (and it's hard to write a `coerce_input` to handle this case).

It seems to only happen when the argument is provided inline in the query (if you pass the argument as a query variable, it doesn't happen).  And while resolving a single query, it appears that `coerce_input` is called twice, and the scalar value doesn't agree in this case (once it's what I expect, and once it's in the `GraphQL::Language::Nodes::...` form).

On a side note, I found it a little surprising that every argument goes through `coerce_input` twice.  There's a potential optimization here where the coerced input is re-used instead of re-coercing the same input.

**Versions**

`graphql` version: 2.0.16 (also observable in 2.0.15, haven't tried on prior versions)
`rails` (or other framework): N/A
other applicable versions (`graphql-batch`, etc): N/A

**GraphQL schema**

See the inline script below for the SDL.

**GraphQL query**

See the inline script below for the query.

**Steps to reproduce**

put this into `graphql_ruby_bug.rb`:

``` ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", "2.0.16"
end

require "graphql"

SCHEMA_STRING = <<~EOS
  scalar JsonValue

  type Query {
    echoJsonValue(arg: JsonValue): JsonValue
  }
EOS

class Application
  def initialize
    @schema = GraphQL::Schema.from_definition(SCHEMA_STRING, default_resolve: self)
  end

  def execute_query(query_string, **vars)
    puts "=" * 80
    puts "Executing query:"
    puts query_string
    puts

    @schema.execute(query_string, variables: vars)
  end

  def call(parent_type, field, object, args, context)
    args.fetch(:arg)
  end

  def coerce_input(type, value, ctx)
    ::JSON.generate(value).tap do |encoded|
      puts "coerced #{value.inspect} into #{encoded.inspect}"

      if ENV["SHOW_STACKTRACE"] && encoded.include?("#<GraphQL::Language::Nodes::NullValue")
        puts caller.join("\n")
      end
    end
  end

  def coerce_result(type, value, ctx)
    ::JSON.parse(value)
  end
end

app = Application.new

app.execute_query(<<~EOS, arg: [3, "abc", nil, 7])
  query WithArg($arg: JsonValue) {
    echoJsonValue(arg: $arg)
  }
EOS

app.execute_query(<<~EOS)
  query {
    echoJsonValue(arg: [3, "abc", null, 7])
  }
EOS
```

Run the script to reproduce.

**Expected behavior**

I expect to see this output:

```
================================================================================
Executing query:
query WithArg($arg: JsonValue) {
  echoJsonValue(arg: $arg)
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
================================================================================
Executing query:
query {
  echoJsonValue(arg: [3, "abc", null, 7])
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
```

**Actual behavior**

I get this output:

```
================================================================================
Executing query:
query WithArg($arg: JsonValue) {
  echoJsonValue(arg: $arg)
}

coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
================================================================================
Executing query:
query {
  echoJsonValue(arg: [3, "abc", null, 7])
}

coerced [3, "abc", #<GraphQL::Language::Nodes::NullValue:0x0000000162af6d20 @line=2, @col=33, @filename=nil, @name="null">, 7] into "[3,\"abc\",\"#<GraphQL::Language::Nodes::NullValue:0x0000000162af6d20>\",7]"
coerced [3, "abc", nil, 7] into "[3,\"abc\",null,7]"
```

Notice the 3rd "coerced..." line--it shows that we got a `GraphQL::Language::Nodes::NullValue` object in our array, which feels like a bug.  (At the very least, it's undocumented behavior.) It's also surprising that `coerce_input` gets different values if the arg comes in via a query variable vs being inline--I wouldn't expect that.

If you re-run the script with `SHOW_STACKTRACE=1` you can see the callstack for this case:

<details>
<summary>Click to view stacktrace</summary>

```
tmp/graphql_ruby_bug.rb:37:in `tap'
tmp/graphql_ruby_bug.rb:37:in `coerce_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/build_from_definition.rb:305:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/build_from_definition.rb:305:in `block in build_scalar_type_coerce_method'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/scalar.rb:45:in `validate_non_null_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema/member/validates_input.rb:15:in `validate_input'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:45:in `block in recursively_validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:73:in `maybe_raise_if_invalid'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:44:in `recursively_validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:15:in `block in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:14:in `catch'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/literal_validator.rb:14:in `validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validation_context.rb:41:in `validate_literal'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb:19:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/arguments_are_defined.rb:9:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:120:in `on_argument'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/argument_names_are_unique.rb:9:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/required_arguments_are_present.rb:7:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:12:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_will_merge.rb:31:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_are_defined_on_type.rb:25:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:89:in `on_field'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/definition_dependencies.rb:47:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/subscription_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/query_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/mutation_root_exists.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:13:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:44:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variable_names_are_unique.rb:20:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb:18:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fields_will_merge.rb:26:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/operation_names_are_valid.rb:12:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/unique_directives_per_location.rb:27:in `block (2 levels) in <module:UniqueDirectivesPerLocation>'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/base_visitor.rb:59:in `on_operation_definition'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `each'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:101:in `on_abstract_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:123:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/definition_dependencies.rb:38:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/variables_are_used_and_defined.rb:79:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb:26:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragments_are_used.rb:6:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragments_are_finite.rb:6:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/fragment_names_are_unique.rb:17:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/operation_names_are_valid.rb:16:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/rules/no_definitions_are_present.rb:34:in `on_document'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `public_send'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:79:in `visit_node'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:174:in `on_node_with_modifications'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/language/visitor.rb:68:in `visit'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:44:in `block (3 levels) in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:43:in `catch'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:43:in `block (2 levels) in validate'
/Users/myron/.rvm/rubies/ruby-2.7.5/lib/ruby/2.7.0/timeout.rb:78:in `timeout'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:42:in `block in validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/static_validation/validator.rb:30:in `validate'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query/validation_pipeline.rb:71:in `ensure_has_validated'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query/validation_pipeline.rb:33:in `valid?'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/query.rb:295:in `valid?'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:26:in `block (2 levels) in analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:25:in `map'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:25:in `block in analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/analysis/ast.rb:24:in `analyze_multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:53:in `block (3 levels) in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:167:in `block (2 levels) in each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:162:in `each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:166:in `block in each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:165:in `each_query_call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:45:in `block (2 levels) in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:193:in `call_hooks'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:44:in `block in run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/tracing.rb:65:in `trace'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/execution/interpreter.rb:37:in `run_all'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema.rb:1018:in `multiplex'
/Users/myron/.rvm/gems/ruby-2.7.5/gems/graphql-2.0.16/lib/graphql/schema.rb:994:in `execute'
tmp/graphql_ruby_bug.rb:29:in `execute_query'
tmp/graphql_ruby_bug.rb:59:in `<main>'
```

</details>

**Comment by rmosolgo** [comment]
Woah! Thanks for the detailed writeup and replication. I totally agree with your diagnosis. Yeah, GraphQL-Ruby has called `coerce_input` twice for a long time, once during validation and once during runtime, if I remember correctly 😓 . 

I'll take a look at the bug first, and consider the double-coerce call after that.
