### ISSUE TITLE
Dataloader and Connections: Couldn't find a connection wrapper

### ISSUE THREAD

**Issue by dominicfollett** [rmosolgo/graphql-ruby#4357]
**Describe the bug**

Hello and thank you for this awesome library. Caveat: I am new to graphql.
I realize that I might be doing something wrong. I thought that I could use Dataloader along with the Connection pattern. My active record models have the following relationship: Contract --< ContractSignatures (one to many). When querying Contracts I want to use Dataloader to prevent multiple queries to the DB for the ContractSignatures. 
I created a Source, and used Dataloader in the resolve method for the `signatures` field on my ContractType. However when testing this out I get the following error:

```
Couldn't find a connection wrapper for ContractSignature during Contract.signatures (#<ContractSignature ... >)
```

**Versions**

`graphql` version: 2.0.17
`rails` (or other framework): Rails 6.0.4
`graphiql-rails`: 1.7.0
`apollo-federation`: 3.3.1

**GraphQL schema**
```ruby
class MySchema < GraphQL::Schema
  include ApolloFederation::Schema
  extend Utils::HashHelpers

  query(Types::QueryType)
  mutation(Mutations::MutationType)

  use GraphQL::Dataloader

  def self.id_from_object(object, type_definition, _query_ctx)
    GraphQL::Schema::UniqueWithinType.encode(type_definition.graphql_name, object.id)
  end

  def self.object_from_id(id, _query_ctx)
    type_name, item_id = GraphQL::Schema::UniqueWithinType.decode(id)
    Object.const_get(type_name).find(item_id)
  end

  ...
end
```

**ContractType**
```ruby
module Types
  module Internal
    class ContractType < BaseObject
      ...
        field :signatures, ContractSignatureType.connection_type, null: false
      ...
        def signatures
          dataloader.with(
            ::Types::Internal::Sources::ContractSignatures,
            ::ContractSignature
          ).load(object.id)
        end
  end
end
```

**Source**
```ruby
...
   # I could probably simplify this, but I've just started using sources
    module Sources
      class ContractSignatures < GraphQL::Dataloader::Source
        def initialize(model_class)
          @model_class = model_class
        end

        def fetch(id)
          @model_class.where(contract_service_contract_id: id)
        end

      end
    end
...
```

**ContractSignatureType**
```ruby
module Types
  module Internal
    class ContractSignatureType < BaseObject
      field :id, ID, null: false
      ...
      field :contract, Internal::ContractType, null: false
      ...
    end
  end
end
```

**BaseObject**
```ruby
module Types
  class BaseObject < GraphQL::Schema::Object
    include ApolloFederation::Object

    field_class BaseField
    connection_type_class BaseConnection
  end
end
```

**BaseConnection**
```ruby
module Types
  # Extentions to the custom connection.
  class BaseConnection < GraphQL::Types::Relay::BaseConnection
    field :total_count, Integer, null: false

    def total_count
      object.items.count
    end
  end
end
```
**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
query Contract($contractId: ID!) {
  contract(id: $contractId) {
    id
    signatures {
      totalCount
      nodes {
        id
      }
    }
  }
}
```

```json
{
  "data": {
    "contract": {
      "id": "7896",
      "signatures": {
        "totalCount": 2,
        "nodes": [
          {
            "id": "34298"
          },
          {
            "id": "44871"
          }
        ]
      }
    }
  }
}
```

**Steps to reproduce**

Hopefully the above is clear enough for reproduction. 
1. Define a field, and call `connection_type` on the field's Type
2. Create a Source that returns an ActiveRecord relation
3. In your field resolver, use Dataloader to load the object

**Expected behavior**

That the Connection would handle ActiveRecord relations returned by the Source.

**Actual behavior**

It appears that a Connection wrapper is missing.

Place full backtrace here (if a Ruby exception is involved): Please see below

<details>
<summary>Click to view exception backtrace</summary>

```
Couldn't find a connection wrapper for ContractSignature during Contract.signatures (#<ContractSignature _obfuscated_>)
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/pagination/connections.rb:82:in `wrap'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field/connection_extension.rb:59:in `block in after_resolve'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema.rb:1040:in `after_lazy'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field/connection_extension.rb:29:in `after_resolve'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:826:in `block (2 levels) in with_extensions'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:823:in `each'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:823:in `block in with_extensions'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema.rb:1040:in `after_lazy'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:821:in `with_extensions'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:653:in `block in resolve'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema.rb:1040:in `after_lazy'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/field.rb:651:in `resolve'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:511:in `block (3 levels) in evaluate_selection_with_args'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/tracing.rb:65:in `trace'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:510:in `block (2 levels) in evaluate_selection_with_args'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:852:in `call_method_on_directives'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:507:in `block in evaluate_selection_with_args'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:952:in `after_lazy'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:445:in `evaluate_selection_with_args'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/execution/interpreter/runtime.rb:439:in `block in evaluate_selection'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/schema/member/has_arguments.rb:288:in `block (3 levels) in coerce_arguments'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/dataloader.rb:181:in `block in run'
/usr/local/bundle/gems/graphql-2.0.17/lib/graphql/dataloader.rb:306:in `block in spawn_fiber'
```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by dominicfollett** [comment]
I checked the types returned by my Source and:

```
<ContractSignature::ActiveRecord_Relation:0x0000ffff8e322358>
```
which is what I get from `ContractSignature.where(contract_id: id)` and is what causes the 'connection wrapper' error.

**However**
```
<ActiveRecord::Relation [#<ContractSignature _obfuscated_ >, ...]>
```

which is what I get from `ContractSignature.all` works (albeit it returns everything). I thought that 'Connection' worked with ActiveRecord out the box... does this mean I may need to register my model with graphql-ruby somehow?

**Comment by dominicfollett** [comment]
Hey there, apologies for creating this Github issue. The fundamental problem was my misunderstanding of how Dataloader works. I realized that I needed to group the results by the key I was querying on, I adjusted my `fetch` method to the following:

```
        def fetch(ids)
          result = @model_class.where(contract_id: ids).group_by(&:contract_id)

          ids.each do |id|
            result[id] = result[id] || []
          end

          result.values
        end
```

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it, thanks for sharing what you found!
