### ISSUE TITLE
`Cannot create Binding object for non-Ruby caller` when rendering Dashboard

### ISSUE THREAD

**Issue by jdeff** [rmosolgo/graphql-ruby#4381]
**Describe the bug**

It appears that the Dashboard is broken in Ruby 3.2. I get the following error when trying to render:

```
RuntimeError: Cannot create Binding object for non-Ruby caller
```

**Versions**

`graphql` version: 2.0.16
`graphql-pro` version: 1.23.6
`rails` (or other framework): 7.0.4.1

**Steps to reproduce**

- Install and use Ruby 3.2
- Follow the steps in https://graphql-ruby.org/pro/dashboard.html#installation to set up the dashboard
- Open the dashboard in a browser

<details>
<summary>Click to view exception backtrace</summary>

```
[/Users/jdeff/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `binding'](http://localhost:4000/graphql/dashboard2/topics#)
[/Users/jdeff/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `bind_call'](http://localhost:4000/graphql/dashboard2/topics#)
[/Users/jdeff/.asdf/installs/ruby/3.2.0/lib/ruby/3.2.0/delegate.rb:89:in `method_missing'](http://localhost:4000/graphql/dashboard2/topics#)
[graphql-pro (1.23.6) lib/graphql/pro/dashboard/context.rb:25:in `to_binding'](http://localhost:4000/graphql/dashboard2/topics#)
[graphql-pro (1.23.6) lib/graphql/pro/dashboard/template.rb:24:in `render'](http://localhost:4000/graphql/dashboard2/topics#)
[graphql-pro (1.23.6) lib/graphql/pro/dashboard/dispatcher.rb:103:in `render_view'](http://localhost:4000/graphql/dashboard2/topics#)
[graphql-pro (1.23.6) lib/graphql/pro/dashboard/dispatcher.rb:29:in `dispatch'](http://localhost:4000/graphql/dashboard2/topics#)
[graphql-pro (1.23.6) lib/graphql/pro/dashboard.rb:56:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/journey/router.rb:50:in `block in serve'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/journey/router.rb:32:in `each'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/journey/router.rb:32:in `serve'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/routing/route_set.rb:852:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[bullet (7.0.7) lib/bullet/rack.rb:17:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[scout_apm (5.3.3) lib/scout_apm/instant/middleware.rb:55:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[scout_apm (5.3.3) lib/scout_apm/middleware.rb:20:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/session/abstract/id.rb:266:in `context'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/session/abstract/id.rb:260:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/cookies.rb:704:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/etag.rb:27:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/conditional_get.rb:27:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/head.rb:12:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[activerecord (7.0.4.1) lib/active_record/migration.rb:603:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'](http://localhost:4000/graphql/dashboard2/topics#)
[activesupport (7.0.4.1) lib/active_support/callbacks.rb:99:in `run_callbacks'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-rails (5.7.0) lib/sentry/rails/rescued_exception_interceptor.rb:12:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry/rack/capture_exceptions.rb:28:in `block (2 levels) in call'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry/hub.rb:220:in `with_session_tracking'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry-ruby.rb:375:in `with_session_tracking'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry/rack/capture_exceptions.rb:19:in `block in call'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry/hub.rb:59:in `with_scope'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry-ruby.rb:355:in `with_scope'](http://localhost:4000/graphql/dashboard2/topics#)
[sentry-ruby (5.7.0) lib/sentry/rack/capture_exceptions.rb:18:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[railties (7.0.4.1) lib/rails/rack/logger.rb:40:in `call_app'](http://localhost:4000/graphql/dashboard2/topics#)
[railties (7.0.4.1) lib/rails/rack/logger.rb:25:in `block in call'](http://localhost:4000/graphql/dashboard2/topics#)
[activesupport (7.0.4.1) lib/active_support/tagged_logging.rb:99:in `block in tagged'](http://localhost:4000/graphql/dashboard2/topics#)
[activesupport (7.0.4.1) lib/active_support/tagged_logging.rb:37:in `tagged'](http://localhost:4000/graphql/dashboard2/topics#)
[activesupport (7.0.4.1) lib/active_support/tagged_logging.rb:99:in `tagged'](http://localhost:4000/graphql/dashboard2/topics#)
[railties (7.0.4.1) lib/rails/rack/logger.rb:25:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/request_id.rb:26:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/runtime.rb:22:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[activesupport (7.0.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/server_timing.rb:61:in `block in call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/server_timing.rb:26:in `collect_events'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/server_timing.rb:60:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/static.rb:23:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack (2.2.6.2) lib/rack/sendfile.rb:110:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[actionpack (7.0.4.1) lib/action_dispatch/middleware/host_authorization.rb:137:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[rack-cors (1.1.1) lib/rack/cors.rb:100:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[railties (7.0.4.1) lib/rails/engine.rb:530:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/configuration.rb:268:in `call'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/request.rb:93:in `block in handle_request'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/thread_pool.rb:340:in `with_force_shutdown'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/request.rb:92:in `handle_request'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/server.rb:429:in `process_client'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/server.rb:232:in `block in run'](http://localhost:4000/graphql/dashboard2/topics#)
[puma (6.0.2) lib/puma/thread_pool.rb:147:in `block in spawn_thread'](http://localhost:4000/graphql/dashboard2/topics#)
```
</details>

**Additional context**

It looks like this behavior may be caused by changes in Ruby 3.2: https://rubyreferences.github.io/rubychanges/3.2.html#kernelbinding-raises-if-accessed-not-from-ruby

**Comment by jdeff** [comment]
I don't know what the implications are, but I was able to get the page to at least render by changing the `to_binding` method in `lib/graphql/pro/dashboard/context.rb` to:

```
        def to_binding
          instance_eval { Kernel.binding }
        end
```

**Comment by rohanmendon** [comment]
its fixed in graphql-pro (1.24.0)

**Comment by rmosolgo** [comment]
Hey @jdeff, sorry for the trouble. Yes, I expect this to be fixed in graphql-pro  v1.23.9, could you try updating to that version and let me know if it solves the problem for you?

**Comment by rmosolgo** [comment]
Please let me know if you encounter this error again after updating to that new version!

**Comment by jdeff** [comment]
Sorry for the delay here. Yes, upgrading solved the problem. Thanks!
