### ISSUE TITLE
AppsignalTracing error with version 2.0.21

### ISSUE THREAD

**Issue by daniel-gato** [rmosolgo/graphql-ruby#4444]
`GraphQL::Tracing::AppsignalTracing` not working with field extensions:

```console
1) Types::UserType test
     Failure/Error: @result = SayduckSchema.execute(query, context:, variables:).deep_symbolize_keys
     
     NoMethodError:
       undefined method `graphql_name' for nil:NilClass
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/appsignal_trace.rb:65:in `platform_field_key'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/platform_trace.rb:8:in `block in initialize'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/platform_trace.rb:41:in `execute_field'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/timeout.rb:84:in `execute_field'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:555:in `block in evaluate_selection_with_resolved_keyword_args'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:904:in `call_method_on_directives'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:552:in `evaluate_selection_with_resolved_keyword_args'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:528:in `block in evaluate_selection_with_args'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:1002:in `after_lazy'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:477:in `evaluate_selection_with_args'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:471:in `block in evaluate_selection'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:288:in `block (3 levels) in coerce_arguments'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:269:in `block (2 levels) in coerce_arguments'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:268:in `each'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:268:in `block in coerce_arguments'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/member/has_arguments.rb:297:in `coerce_arguments'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/arguments_cache.rb:52:in `dataload_for'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:470:in `evaluate_selection'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:395:in `block (2 levels) in evaluate_selections'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:394:in `block in evaluate_selections'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:393:in `each'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:393:in `evaluate_selections'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:291:in `block (4 levels) in run_eager'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:904:in `call_method_on_directives'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:290:in `block (3 levels) in run_eager'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:285:in `block (2 levels) in run_eager'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:246:in `tap_or_each'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:276:in `block in run_eager'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:904:in `call_method_on_directives'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter/runtime.rb:267:in `run_eager'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:75:in `block (6 levels) in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/trace.rb:43:in `execute_query'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/appsignal_trace.rb:34:in `block in execute_query'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/appsignal-3.4.1/lib/appsignal/helpers/instrumentation.rb:543:in `instrument'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/appsignal_trace.rb:33:in `execute_query'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:74:in `block (5 levels) in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:62:in `block (4 levels) in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:61:in `each'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:61:in `each_with_index'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:61:in `block (3 levels) in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:172:in `block (2 levels) in each_query_call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:167:in `each_query_call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:171:in `block in each_query_call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:198:in `call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:170:in `each_query_call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:198:in `call_hooks'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:45:in `block in run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/appsignal_trace.rb:30:in `block in execute_multiplex'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/appsignal-3.4.1/lib/appsignal/helpers/instrumentation.rb:543:in `instrument'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/tracing/appsignal_trace.rb:29:in `execute_multiplex'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema/timeout.rb:68:in `execute_multiplex'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/execution/interpreter.rb:37:in `run_all'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema.rb:1069:in `multiplex'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/graphql-2.0.21/lib/graphql/schema.rb:1045:in `execute'
     # ./spec/support/graphql_manager.rb:23:in `execute'
     # ./spec/graphql/types/user_type_spec.rb:56:in `block (2 levels) in <top (required)>'
     # /Users/daniel/.rvm/gems/ruby-3.2.1/gems/webmock-3.18.1/lib/webmock/rspec.rb:37:in `block (2 levels) in <top (required)>'
```

error is here:

```
      def platform_field_key(field)
        "#{field.owner.graphql_name}.#{field.graphql_name}.graphql"
      end
```

field.owner is empty.

**Comment by rmosolgo** [comment]
Thanks for reporting this and sorry for the trouble! I wonder when field owner is empty 👀  I'll take a look soon and report back here.

**Comment by rmosolgo** [comment]
👋  I took a try at replicating this issue locally but I couldn't come up with a field whose owner was `nil`. Do you know anything about the particular field involved in this issue, or would you mind debugging it a bit? For example, how was this field defined, and how is it attached to the schema? Also, you mention that extensions has something to do with it -- what makes you say so? thanks!

**Comment by ColemanDuck** [comment]
Hi there! I'm a team member of Daniel's and will provide a bit more context here. 😄 

So essentially we have this query (among others, but just an example) that is failing: 

```ruby
let(:query) do
  <<-GRAPHQL
  query ($id: ID!) {
    node(id: $id) {
      ... on User {
        customer { id }
        customers { nodes { id } }
        name firstname lastname email token  areLatestTosAccepted platformTutorialCompletedAt
        mailingMonthlyAnalyticsReportSubscribed
      }
    }
  }
  GRAPHQL
end 
```
And so I went and checked out what was failing (as Daniel described):

```ruby
def platform_field_key(field)
   ap field.graphql_name # => "node"
   ap field.owner # => nil
   "#{field.owner.graphql_name}.#{field.graphql_name}.graphql"
end
```

With owner being `nil` as expected, so to show you a bit how it works together, here is the `NodeFieldExtension` where owner is becoming `nil`.

```ruby
module FieldExtensions
  class NodeFieldExtension < BaseFieldExtension
    def apply
      field.argument :id,
                     GraphQL::Types::ID,
                     required: true
    end

    def resolve(arguments:, context:, **)
      context.schema.object_from_id(arguments[:id], context)
    end
  end
end # => NodeFieldExtension
```

Which is used in our `query_type.rb` like so: 

```ruby
field :node,
          GraphQL::Types::Relay::Node,
          null: true,
          relay_nodes_field: true,
          owner: nil,
          extensions: [FieldExtensions::NodeFieldExtension] # => extension used here.
```

And our `query_type.rb` is then implemented in the schema: 

```ruby
class SayduckSchema < GraphQL::Schema
  # ...

  use GraphQL::Subscriptions::ActionCableSubscriptions
  use GraphQL::Tracing::AppsignalTracing # FIXME: https://github.com/rmosolgo/graphql-ruby/issues/4444
  use GraphQL::Batch
  use GraphqlTimeout, max_seconds: ENV.fetch('GRAPHQL_TIMEOUT', 20).to_i

  query Types::QueryType
  mutation Types::MutationType
  subscription Types::GraphqlSubscriptionType

  # ...
```

Also for some additional context, this issue popped up after a maintenance day where we migrated to Ruby 3 from 2.7 as well as updated a few different gems etc. If any of this is unclear, not exactly what you're looking for, or if you need more context, I'll be glad to help!

**Comment by rmosolgo** [comment]
How about removing `owner: nil` from your `field :node ...` configuration? I think that's why `field.owner` is nil in this case, it's overriding the default: 

https://github.com/rmosolgo/graphql-ruby/blob/7939e1439620026f960d9e2e930c7be75715e081/lib/graphql/schema/member/has_fields.rb#L12

Would that work for you?

**Comment by rmosolgo** [comment]
It's used throughout the gem to determine, for a given field, which type the field was defined on.  (Arguments, Enum values, and Directives have "owners" too.)
