### ISSUE TITLE
Only generation of JSON objects or arrays allowed

### ISSUE THREAD

**Issue by nickpoorman** [rmosolgo/graphql-ruby#446]
I just upgraded from 1.2.6 to the master HEAD (51711829b4bdd2d85ca206189bb9615c7f61ab35) and now I'm getting this error when I refresh GraphiQL (using https://github.com/rmosolgo/graphiql-rails):

*Note: I printed out the `arg` that seems to be causing the error and it's: `true`.*

```
[INFO ] Completed 200 OK in 54ms (Views: 48.9ms | ActiveRecord: 0.6ms) (pid:79364)(dyno:0)
 [INFO ] Started POST "/graphql" for ::1 at 2016-12-08 09:11:54 -0500 (pid:79364)(dyno:0)
 [INFO ] Processing by WoofGraphql::GraphqlController#create as */* (pid:79364)(dyno:0)
 [INFO ] Parameters: {"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n", "graphql"=>{"query"=>"\n  query IntrospectionQuery {\n    __schema {\n      queryType { name }\n      mutationType { name }\n      subscriptionType { name }\n      types {\n        ...FullType\n      }\n      directives {\n        name\n        description\n        locations\n        args {\n          ...InputValue\n        }\n      }\n    }\n  }\n\n  fragment FullType on __Type {\n    kind\n    name\n    description\n    fields(includeDeprecated: true) {\n      name\n      description\n      args {\n        ...InputValue\n      }\n      type {\n        ...TypeRef\n      }\n      isDeprecated\n      deprecationReason\n    }\n    inputFields {\n      ...InputValue\n    }\n    interfaces {\n      ...TypeRef\n    }\n    enumValues(includeDeprecated: true) {\n      name\n      description\n      isDeprecated\n      deprecationReason\n    }\n    possibleTypes {\n      ...TypeRef\n    }\n  }\n\n  fragment InputValue on __InputValue {\n    name\n    description\n    type { ...TypeRef }\n    defaultValue\n  }\n\n  fragment TypeRef on __Type {\n    kind\n    name\n    ofType {\n      kind\n      name\n      ofType {\n        kind\n        name\n        ofType {\n          kind\n          name\n          ofType {\n            kind\n            name\n            ofType {\n              kind\n              name\n              ofType {\n                kind\n                name\n                ofType {\n                  kind\n                  name\n                }\n              }\n            }\n          }\n        }\n      }\n    }\n  }\n"}} (pid:79364)(dyno:0)
 [DEBUG] User Load (0.8ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = $1 ORDER BY "users"."id" ASC LIMIT $2  [["id", 3], ["LIMIT", 1]] (pid:79364)(dyno:0)
arg: true
 [ERROR] only generation of JSON objects or arrays allowed (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json_pure-2.0.2/lib/json/common.rb:224:in `generate' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json_pure-2.0.2/lib/json/common.rb:224:in `generate' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/json_pure-2.0.2/lib/json/common.rb:394:in `dump' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:96:in `print_arg' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:108:in `block in reduce_list' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:107:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:107:in `reduce' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:107:in `reduce_list' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:78:in `block in initialize' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:78:in `map' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:78:in `initialize' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:26:in `new' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:26:in `block in find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:35:in `block in find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:35:in `block in find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:25:in `find_conflicts' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:17:in `block (2 levels) in validate' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:15:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/rules/fields_will_merge.rb:15:in `block in validate' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:65:in `block in apply_hooks' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:65:in `each' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:65:in `reduce' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:65:in `apply_hooks' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:60:in `end_visit' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:49:in `visit_node' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/language/visitor.rb:39:in `visit' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/static_validation/validator.rb:34:in `validate' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/query.rb:229:in `document_valid?' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/query.rb:197:in `valid?' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/query.rb:110:in `result' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/bundler/gems/graphql-ruby-51711829b4bd/lib/graphql/schema.rb:155:in `execute' (pid:79364)(dyno:0)
 [ERROR] /Users/nick/Library/Mobile Documents/com~apple~CloudDocs/programming/projects/woof/lib/engines/woof_graphql/app/controllers/woof_graphql/graphql_controller.rb:11:in `create' (pid:79364)(dyno:0)
```

**Comment by rmosolgo** [comment]
Ah shucks, forgot an explicit `quirks_mode: true` in https://github.com/rmosolgo/graphql-ruby/pull/437/files#diff-78f1111c25780f58baa075bc8b689d36R80. It's default in Ruby's built-in JSON but not in some other JSON implementations! 

Maybe it's time to implement `GraphQL::JSON` as a pass-through which always includes that option, I've seen this bug a few times now 😖

**Comment by nickpoorman** [comment]
Yeah enabling `quirks_mode` seems to have solved it:

```
def print_arg(arg)
          case arg
          when GraphQL::Language::Nodes::VariableIdentifier
            "$#{arg.name}"
          when GraphQL::Language::Nodes::Enum
            "#{arg.name}"
          else
            JSON.generate(arg, { quirks_mode: true })
          end
        end
```

**Comment by jaimeohm** [comment]
Thank you! Setting quirks_mode to true solved my issue on Travis-CI with getting JSON.pretty_generate(...) to work without an error. Not related to this project, but thank you for leaving detailed notes here during your debugging.
