### ISSUE TITLE
Using multiple monitoring tools in GraphQL::Schema stopped working

### ISSUE THREAD

**Issue by mmarcinkowski** [rmosolgo/graphql-ruby#4542]
**Describe the bug**

I'm trying to upgrade the graphql gem in my Rails application from version 2.0.16 to version 2.0.24. However, after the upgrade, I encountered an unexpected issue where the registration of multiple monitoring tools is no longer functioning as expected. Specifically, the capability to send traces to Appsignal and Datadog, which was previously working seamlessly, has ceased to operate.

I have reviewed the release notes, but I have not found any specific information regarding changes or limitations related to multiple monitoring tools registration. Therefore, I believe this issue may be a result of an unintended regression.

**Versions**

`graphql` version: 2.0.24
`rails` version: 7.0.5.1

**GraphQL::Schema**
```ruby
module Graph
  class Schema < GraphQL::Schema
    query Graph::Types::QueryType
    mutation Graph::Types::MutationType
    
    use GraphQL::Tracing::DataDogTracing, service: "graphql"
    use GraphQL::Tracing::AppsignalTracing
  end
end
```

**Steps to reproduce**

```ruby
# spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# frozen_string_literal: true

require "spec_helper"

module Appsignal
  module_function

  def instrument(key, &block); yield; end
  def instrumented; []; end
end

describe "Multiple monitoring tools" do
  module MultipleMonitoringToolsTest
    class Thing < GraphQL::Schema::Object
      field :str, String

      def str; "blah"; end
    end

    class Named < GraphQL::Schema::Union
      possible_types Thing
      def self.resolve_type(obj, ctx)
        Thing
      end
    end

    class Query < GraphQL::Schema::Object
      include GraphQL::Types::Relay::HasNodeField

      field :int, Integer, null: false

      def int
        1
      end

      field :thing, Thing
      def thing; :thing; end

      field :named, Named, resolver_method: :thing
    end

    class TestSchema < GraphQL::Schema
      query(Query)
      trace_with(GraphQL::Tracing::DataDogTrace)
      trace_with(GraphQL::Tracing::AppsignalTrace)
    end
  end

  it "returns GraphQL::Query::Result instance" do
    query = "{ int thing { str } named { ... on Thing { str } } }"
    assert_instance_of GraphQL::Query::Result, MultipleMonitoringToolsTest::TestSchema.execute(query)
  end
end
```

**Expected behavior**

```sh
➜  graphql-ruby git:(master) ✗  bundle exec rake test TEST=spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# Running tests with run options --seed 28696:

.

Finished tests in 0.001812s, 551.8764 tests/s, 551.8764 assertions/s.


1 tests, 1 assertions, 0 failures, 0 errors, 0 skips
```

**Actual behavior**

Gem raises ArgumentError.

```sh
➜  graphql-ruby git:(master) ✗  bundle exec rake test TEST=spec/graphql/tracing/multiple_monitoring_tools_spec.rb

# Running tests with run options --seed 41865:

E

Finished tests in 0.001901s, 526.0389 tests/s, 0.0000 assertions/s.


Error:
Multiple traces#test_0001_returns GraphQL::Query::Result instance:
ArgumentError: wrong number of arguments (given 2, expected 1)
...
1 tests, 0 assertions, 0 failures, 1 errors, 0 skips
```

<details>
<summary>Click to view exception backtrace</summary>

```
ArgumentError: wrong number of arguments (given 2, expected 1)
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:46:in `platform_execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:46:in `execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:47:in `block in execute_field'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:48:in `block in platform_execute_field'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:47:in `platform_execute_field'
    /graphql-ruby/lib/graphql/tracing/platform_trace.rb:46:in `execute_field'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:541:in `block in evaluate_selection_with_resolved_keyword_args'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:538:in `evaluate_selection_with_resolved_keyword_args'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:449:in `evaluate_selection'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:380:in `block (2 levels) in evaluate_selections'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:379:in `block in evaluate_selections'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:378:in `each'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:378:in `evaluate_selections'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:284:in `block (4 levels) in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:283:in `block (3 levels) in run_eager'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:275:in `block (2 levels) in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:236:in `tap_or_each'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:266:in `block in run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:892:in `call_method_on_directives'
    /graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:257:in `run_eager'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:75:in `block (6 levels) in run_all'
    /graphql-ruby/lib/graphql/tracing/trace.rb:43:in `execute_query'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:47:in `block in execute_query'
    /graphql-ruby/spec/support/datadog.rb:52:in `trace'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:35:in `execute_query'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:34:in `block in execute_query'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:33:in `execute_query'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:74:in `block (5 levels) in run_all'
    /graphql-ruby/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:62:in `block (4 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `each'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `each_with_index'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:61:in `block (3 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:171:in `block (2 levels) in each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:166:in `each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:170:in `block in each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:197:in `call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:169:in `each_query_call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:197:in `call_hooks'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:45:in `block in run_all'
    /graphql-ruby/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:58:in `block in execute_multiplex'
    /graphql-ruby/spec/support/datadog.rb:52:in `trace'
    /graphql-ruby/lib/graphql/tracing/data_dog_trace.rb:35:in `execute_multiplex'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:30:in `block in execute_multiplex'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:8:in `instrument'
    /graphql-ruby/lib/graphql/tracing/appsignal_trace.rb:29:in `execute_multiplex'
    /graphql-ruby/lib/graphql/execution/interpreter.rb:37:in `run_all'
    /graphql-ruby/lib/graphql/schema.rb:1084:in `multiplex'
    /graphql-ruby/lib/graphql/schema.rb:1060:in `execute'
    /graphql-ruby/spec/graphql/tracing/multiple_monitoring_tools_spec.rb:51:in `block (2 levels) in <top (required)>'

```

</details>

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble and thanks for the detailed report. I worked up a fix in #4543, could you give it a try in your app and see if it works properly for you? You can bundle it like this: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "fix-multple-trace-platforms"
```

What happened was, I refactored tracing in order to make it much faster. It was _supposed_ to be a seamless replacement, but obviously I missed a spot here! 

The new implementation mixes trace modules into a single trace class, but this creates conflicts when different modules implement methods in different ways. That's what happened here: one trace module called `super`, which called the same method on a different trace module, but they actually implemented the same method slightly differently, creating this error.

**Comment by ilan-goody** [comment]
I'm also seeing this issue with Datadog and Scout and I can confirm that the PR fixes the problem. Any plans on releasing this update?

**Comment by mmarcinkowski** [comment]
Hello @rmosolgo! Thank you for the blazing fast response and the fix. I used the branch and wasn't able to reproduce the issue anymore. Do you know when we could expect a release? :)

**Comment by jonny-ras** [comment]
Hey! So I'm actually still seeing this behaviour, but only when I use lazy loaders to fetch information.

This is the error I'm catching (reproduced in our tests, but seeing it in a prod env as well)
```rb
[1] pry(CoreSchema)> err
=> #<ArgumentError: wrong number of arguments (given 1, expected 0; required keywords: query, field, ast_node, arguments, object)>
[2] pry(CoreSchema)> field
=> #<Types::BaseField Team.totalConversationsCount: Int!>
```

<details>
<summary>The backtrace from the error</summary>

```rb
[3] pry(CoreSchema)> err.backtrace # Abbreviated to only graphql traces
=> ["/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/platform_trace.rb:44:in `execute_field'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:110:in `execute_field_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/platform_trace.rb:61:in `execute_field_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter/runtime.rb:976:in `block in after_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/lazy.rb:30:in `value'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `each'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `block in resolve_each_depth'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:22:in `resolve_each_depth'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:99:in `block (5 levels) in run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:47:in `execute_query_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:47:in `block in execute_query_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing/tracer.rb:526:in `skip_trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing/tracer.rb:139:in `trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing.rb:18:in `trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:36:in `execute_query_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/appsignal_trace.rb:30:in `block in execute_query_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/appsignal-3.3.10/lib/appsignal/helpers/instrumentation.rb:528:in `instrument'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/appsignal_trace.rb:29:in `execute_query_lazy'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:98:in `block (4 levels) in run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:89:in `block (3 levels) in run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:171:in `block (2 levels) in each_query_call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:166:in `each_query_call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:170:in `block in each_query_call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:197:in `call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:169:in `each_query_call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:197:in `call_hooks'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:45:in `block in run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:61:in `block in execute_multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing/tracer.rb:526:in `skip_trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing/tracer.rb:139:in `trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/ddtrace-1.8.0/lib/datadog/tracing.rb:18:in `trace'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:36:in `execute_multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/appsignal_trace.rb:30:in `block in execute_multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/appsignal-3.3.10/lib/appsignal/helpers/instrumentation.rb:528:in `instrument'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/tracing/appsignal_trace.rb:29:in `execute_multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:37:in `run_all'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/schema.rb:1138:in `multiplex'",
 "/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/graphql-2.0.25/lib/graphql/schema.rb:1114:in `execute'",]
```
</details>

One of the loaders, as an example

```rb
# typed: ignore
module Loaders
  module Team
    class TotalConversationsCountLoader < GraphQL::Batch::Loader
      def initialize(account, app, app_user)
        @account = account
        @app = app
        @app_user = app_user
      end

      def perform(team_ids)
        teams = ::Team.fetch_multi(team_ids)
        counts = ::Teams::Service.count_total_conversations(@account, @app, @app_user, teams)
        teams.each_with_index { |team, idx| fulfill(teams[idx].id, counts[idx]) }
      end
    end
  end
end
```

The type where it fails
```rb
# typed: ignore
module Types
  module Teams
    class TeamType < Types::BaseObject
      field :id, Integer, null: false
      field :total_conversations_count, ::Integer, null: false
      
      def total_conversations_count
        ::Loaders::Team::TotalConversationsCountLoader.for(object.account, object.app, current_user).load(object.id)
      end
    end
  end
end
```

**Comment by rmosolgo** [comment]
Derp! Thanks for letting me know. I pushed 792c75db8 to #4579 to address that error (and a few like it...)
