### ISSUE TITLE
LocalJumpError: no block given (yield) (LocalJumpError)

### ISSUE THREAD

**Issue by iwaseasahi** [rmosolgo/graphql-ruby#4578]
**Describe the bug**

The following error occurred in a Rails application I am developing.

```rb
LocalJumpError: no block given (yield) (LocalJumpError)
  app/controllers/graphql/application_controller.rb:12:in `execute'
    result = schema.execute(query, variables:, context: graphql_context, operation_name:)
...
```

**Versions**

`graphql` version: `2.0.25`
`rails` (or other framework): `7.0.6`

**GraphQL schema**

```ruby
# frozen_string_literal: true

module Graphql
  class ApplicationController < ActionController::API
    def execute
      query = params[:query]

      result = schema.execute(query, variables:, context: graphql_context, operation_name:)
      @graphql_error = result['errors'].present?
      render json: result
    end

    private

    def schema
      raise NotImplementedError, "You must implement #{self.class}##{__method__}"
    end
  end
end
```

**Expected behavior**

This error does not occur with `graphql` version: `2.0.24`.

**Actual behavior**

It calls super here.
https://github.com/rmosolgo/graphql-ruby/blob/f39d5dbb1778a950bf84101e27ede8364c16bd63/lib/graphql/tracing/data_dog_trace.rb#L105

It seems to be an error because yeild cannot be executed because the block is not passed.
https://github.com/rmosolgo/graphql-ruby/blob/f39d5dbb1778a950bf84101e27ede8364c16bd63/lib/graphql/tracing/trace.rb#L50-L52

<details>
<summary>Click to view exception backtrace</summary>

```
{"#<Proc:0x00007f5e37df9958 /usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/contrib/rails/log_injection.rb:13>":null,"message":"[\"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:51:in `execute_field'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:105:in `execute_field'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:110:in `execute_field_lazy'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter/runtime.rb:976:in `block in after_lazy'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/lazy.rb:30:in `value'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `each'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `block in resolve_each_depth'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:22:in `resolve_each_depth'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:99:in `block (5 levels) in run_all'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:47:in `execute_query_lazy'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:47:in `block in execute_query_lazy'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/trace_operation.rb:199:in `block in measure'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/span_operation.rb:150:in `measure'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/trace_operation.rb:199:in `measure'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/tracer.rb:383:in `start_span'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/tracer.rb:159:in `block in trace'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/context.rb:45:in `activate!'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/tracer.rb:158:in `trace'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing.rb:18:in `trace'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:36:in `execute_query_lazy'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:98:in `block (4 levels) in run_all'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:89:in `block (3 levels) in run_all'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:171:in `block (2 levels) in each_query_call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:166:in `each_query_call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:170:in `block in each_query_call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:197:in `call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:169:in `each_query_call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:197:in `call_hooks'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/execution/interpreter.rb:45:in `block in run_all'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'\", \"/usr/local/bundle/gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:61:in `block in execute_multiplex'\", \"/usr/local/bundle/gems/ddtrace-1.13.0/lib/datadog/tracing/trace_operation.rb:199:in `block in measure'\",
```

</details>

**Comment by Stashchenko** [comment]
We've faced with the same error:
```shell 
LocalJumpError:
       no block given (yield)
     gems/graphql-2.0.25/lib/graphql/tracing/trace.rb:51:in `execute_field'
     gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:105:in `execute_field'
     gems/graphql-2.0.25/lib/graphql/tracing/data_dog_trace.rb:110:in `execute_field_lazy'
     gems/graphql-2.0.25/lib/graphql/execution/interpreter/runtime.rb:976:in `block in after_lazy'
     gems/graphql-2.0.25/lib/graphql/execution/lazy.rb:30:in `value'
     gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `each'
     gems/graphql-2.0.25/lib/graphql/execution/interpreter/resolve.rb:23:in `block in resolve_each_depth'
     gems/graphql-2.0.25/lib/graphql/dataloader.rb:181:in `block in run'
     gems/graphql-2.0.25/lib/graphql/dataloader.rb:306:in `block in spawn_fiber'

```

**Comment by rmosolgo** [comment]
Sorry for the trouble and thanks for the detailed report! I have a fix worked up in #4579 

Could you confirm it works for you? You can bundle it like this: 

```ruby
gem "graphql", github: "rmosolgo/graphql-ruby", ref: "fix-block-arg"
```

And if it looks good to you, I'll cut a new release with that patch!

**Comment by iwaseasahi** [comment]
@rmosolgo 
Thanks for your quick fix.
I had solved the problem by making sure it worked in my Rails application by version 2.0.26.

**Comment by Stashchenko** [comment]
> ```ruby
> gem "graphql", github: "rmosolgo/graphql-ruby", ref: "fix-block-arg"
> ```

I'm getting the error: `Revision fix-block-arg does not exist in the repository https://github.com/rmosolgo/graphql-ruby.git. Maybe you misspelled it?`

**Comment by rmosolgo** [comment]
Glad to hear it! Sorry about the trouble -- I deleted that branch once the fix was confirmed, then released the new version.
