### ISSUE TITLE
Argument name "null" seems to cause parse error

### ISSUE THREAD

**Issue by sj26** [rmosolgo/graphql-ruby#4584]
**Describe the bug**

I'm using graphql-client with the [Linear GraphQL API](https://developers.linear.app/docs/graphql). It has an input type:

```graphql
"""
Issue filtering options.
"""
input NullableIssueFilter {
  """
  Compound filters, all of which need to be matched by the issue.
  """
  and: [NullableIssueFilter!]

  # ...

  """
  Filter based on the existence of the relation.
  """
  null: Boolean

  # ...
}
```

But when I try to use it in a query:

```ruby
module Linear
  HTTP = GraphQL::Client::HTTP.new("https://api.linear.app/graphql") do
    def headers(context)
      { "Authorization" => "Bearer #{ENV.fetch("LINEAR_API_KEY")}" }
    end
  end

  Schema = GraphQL::Client.load_schema(HTTP)

  Client = GraphQL::Client.new(schema: Schema, execute: HTTP)

  IssueFragment = Linear::Client.parse(<<~GRAPHQL)
    fragment on Issue {
      id, title, description, url, priority
      state { id, name }
      assignee { id, name, email }
      attachments(filter: { url: { contains: "..." } }) {
        nodes { id, url }
      }
    }
  GRAPHQL

  IssuesQuery = Linear::Client.parse(<<~GRAPHQL)
    query($linearTeamId: ID!, $cursor: String, $limit: Int!) {
      issues(after: $cursor, first: $limit, filter: {
        team: { id: { eq: $linearTeamId } }
        labels: { name: { eq: "..." } }
        attachments: { url: { contains: "..." } }
        parent: { null: true }
      }) {
        nodes {
          ...Linear::IssueFragment
        }
        pageInfo {
          endCursor
          hasNextPage
        }
      }
    }
  GRAPHQL
end
```

It raises an error:

```backtrace
parser.y:543:in `on_error': Parse error on "null" (NULL) at [6, 15] (GraphQL::ParseError)
  from (eval):3:in `_racc_do_parse_c'
  from (eval):3:in `do_parse'
  from parser.y:474:in `block in parse_document'
  from /opt/homebrew/lib/ruby/gems/3.2.0/gems/graphql-2.0.26/lib/graphql/tracing/trace.rb:23:in `parse'
  from parser.y:470:in `parse_document'
  from parser.y:484:in `parse'
  from /opt/homebrew/lib/ruby/gems/3.2.0/gems/graphql-2.0.26/lib/graphql.rb:46:in `parse'
  from /opt/homebrew/lib/ruby/gems/3.2.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:186:in `parse'
  from ...
```

I don't think the spec precludes the name "null":

http://spec.graphql.org/June2018/#Name

and I can't figure out a way to quote an argument name in a query like this.

Am I holding it wrong, or is this a bug in the parser?

**Versions**

- graphql 2.0.26
- graphql-client 0.18.0
- ruby 3.2.2

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. I think you're right about how it should work. I'm working up a fix in #4586

**Comment by rmosolgo** [comment]
The only problem is ... I think we broke GraphQL-Client in #4577 😖 I'll take a look and see if I can fix it downstream.

**Comment by sj26** [comment]
😅
