### ISSUE TITLE
method `method_conflict_warning?' for GraphQL::Types::Relay::HasNodeField:Module after upgrading

### ISSUE THREAD

**Issue by davidwparker** [rmosolgo/graphql-ruby#4612]
**Describe the bug**

Trying to upgrade from 1.12.18 to 2.1.0 and getting this error:
`<NoMethodError: undefined method `method_conflict_warning?' for GraphQL::Types::Relay::HasNodeField:Module>`

Changed 
```ruby
    # Used by Relay to lookup objects by UUID
    add_field(GraphQL::Types::Relay::NodeField)

    # Fetches a list of objects given a list of IDs
    add_field(GraphQL::Types::Relay::NodesField)
```

to
```ruby
    # Used by Relay to lookup objects by UUID
    add_field(GraphQL::Types::Relay::HasNodeField)

    # Fetches a list of objects given a list of IDs
    add_field(GraphQL::Types::Relay::HasNodesField)
```
Per instructions here
https://github.com/rmosolgo/graphql-ruby/blob/v2.1.0/CHANGELOG.md#deprecations-4

**Versions**

`graphql` version:
`rails` (or other framework):
other applicable versions (`graphql-batch`, etc)
```
    graphql (2.1.0)
    graphql-batch (0.5.3)
      graphql (>= 1.12.18, < 3)
      promise.rb (~> 0.7.2)
    graphql-pagination (2.0.0.rc)
      graphql (~> 2.0)
```

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
require "graphql/batch"

class ApplicationSchema < GraphQL::Schema
  mutation(Types::MutationType)
  query(Types::QueryType)

  use GraphQL::Subscriptions::ActionCableSubscriptions

  use GraphQL::Batch

  use GraphQL::Backtrace

  subscription Types::SubscriptionType
end
```

**Steps to reproduce**

NA

**Expected behavior**

Replacing per changelog works

**Actual behavior**

Error

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
NoMethodError (undefined method `method_conflict_warning?' for GraphQL::Types::Relay::HasNodeField:Module):

app/graphql/types/base_object.rb:8:in `<class:BaseObject>'
app/graphql/types/base_object.rb:4:in `<module:Types>'
app/graphql/types/base_object.rb:3:in `<main>'
app/graphql/types/mutation_type.rb:4:in `<module:Types>'
app/graphql/types/mutation_type.rb:3:in `<main>'
app/graphql/secureframe_schema.rb:5:in `<class:SecureframeSchema>'
app/graphql/secureframe_schema.rb:4:in `<main>'
app/controllers/graphql_controller.rb:91:in `execute'
```

</details>

**Additional context**

NA

Is it too much of a jump to upgrade that much at once?
Sorry, if so, just say as much and close the ticket and I'll break down to smaller upgrades.
Thank you!

**Comment by rmosolgo** [comment]
Hi! Sorry for the trouble. I guess the changelog lacked some clarity; those new modules should be attached with `include`, for example: 

```ruby
    # Used by Relay to lookup objects by UUID
    include GraphQL::Types::Relay::HasNodeField

    # Fetches a list of objects given a list of IDs
    include GraphQL::Types::Relay::HasNodesField
```

Does that work for you?

**Comment by davidwparker** [comment]
@rmosolgo - yep, that works. Closing thank you!
