### ISSUE TITLE
cannot load such file -- racc/parser.rb on Ruby 3.3 when requiring gem

### ISSUE THREAD

**Issue by ivoanjo** [rmosolgo/graphql-ruby#4650]
**Describe the bug**

Hey! I work at Datadog on the [ddtrace](https://github.com/datadog/dd-trace-rb) gem, which provides tracing integration with graphql.

Today I've upgraded our CI to Ruby 3.3.0-preview2 and our integration tests with the graphql gem started failing, I suspect because the `racc` gem is now "bundled" in Ruby 3.3, and not a "default" gem ([as recorded in the 3.0.0-preview2 release notes](https://www.ruby-lang.org/en/news/2023/09/14/ruby-3-3-0-preview2-released/)).

**Versions**

`graphql` version: 2.1.0

**Steps to reproduce**

The following trivial script can reproduce the issue:

```ruby
require 'bundler/inline'

puts RUBY_DESCRIPTION

gemfile do
  source 'https://rubygems.org'

  gem 'graphql', '= 2.1.0'
end

require 'graphql'
```

and the output:

```
ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) [x86_64-linux]
ruby-3.3.0-preview2/lib/ruby/3.3.0+0/bundler/rubygems_integration.rb:273:in `require': cannot load such file -- racc/parser.rb (LoadError)
  from ruby-3.3.0-preview2/lib/ruby/3.3.0+0/bundler/rubygems_integration.rb:273:in `block (2 levels) in replace_require'
  from /home/ivo.anjo/.rvm/gems/ruby-3.3.0-preview2/gems/graphql-2.1.0/lib/graphql/language/parser.rb:7:in `<top (required)>'
  from ruby-3.3.0-preview2/lib/ruby/3.3.0+0/bundler/rubygems_integration.rb:273:in `require'
  from ruby-3.3.0-preview2/lib/ruby/3.3.0+0/bundler/rubygems_integration.rb:273:in `block (2 levels) in replace_require'
  from /home/ivo.anjo/.rvm/gems/ruby-3.3.0-preview2/gems/graphql-2.1.0/lib/graphql/language.rb:10:in `<top (required)>'
```

Modifying the script by doing this:

```ruby
require 'bundler/inline'

puts RUBY_DESCRIPTION

gemfile do
  source 'https://rubygems.org'

  gem 'graphql', '= 2.1.0'
  gem 'racc'
end

require 'graphql'
```

Makes it work, but now with a warning:

```
ruby 3.3.0preview2 (2023-09-14 master e50fcca9a7) [x86_64-linux]
ruby-3.3.0-preview2/gems/graphql-2.1.0/lib/graphql/schema/base_64_bp.rb:3: warning: base64 will be not part of the default gems since Ruby 3.4.0. Add base64 to your Gemfile. Also contact author of graphql-2.1.0 to add base64 into its gemspec.
```

**Expected behavior**

Gem should be loaded :)

**Actual behavior**

Gem was not loaded :)

**Additional context**

Thanks for your work on the graphql gem! I actually submitted a couple of PRs years ago and it's great to see it's still in great health ;)

**Comment by ivoanjo** [comment]
Awesome, thank you! :)
