### ISSUE TITLE
Regression in 2.1.0: `GraphQL::Query#sanitized_query_string` raises `TypeError`

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#4651]
**Describe the bug**

When using `GraphQL::Query#sanitized_query_string` on a query that contains an enum argument with a default, a `TypeError` is raised.

This appears to be a regression; I get the error on 2.1.0 but not on 2.0.27. (However, 2.0.27 also had a bug here, but it wasn't as impactful of a bug, and I had never noticed that bug before writing this reproduction script!)

**Versions**

`graphql` version: 2.1.0
`rails` (or other framework): N/A

**GraphQL schema**

```graphql
scalar DateTime

enum DateTimeGroupingGranularity {
  DAY
}

type Query {
  widgetAggregations: WidgetAggregationConnection
}

type WidgetAggregation {
  groupedBy: WidgetAggregationGroupedBy
}

type WidgetAggregationConnection {
  nodes: [WidgetAggregation!]!
}

type WidgetAggregationGroupedBy {
  createdAt(
    granularity: DateTimeGroupingGranularity!
  ): DateTime
}
```

**GraphQL query**

```graphql
query Widgets(
  $groupingGranularity: DateTimeGroupingGranularity = DAY
) {
  widgetAggregations {
    nodes {
      groupedBy {
        createdAt(granularity: $groupingGranularity)
      }
    }
  }
}
```

**Steps to reproduce**

Create a `test_sanitized_query_printing.rb` file with these contents:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"
  gem "graphql", ENV.fetch("GRAPHQL_GEM_VERSION", "2.1.0")
end

require "graphql"

query_string = <<~EOS
  query Widgets(
    $groupingGranularity: DateTimeGroupingGranularity = DAY
  ) {
    widgetAggregations {
      nodes {
        groupedBy {
          createdAt(granularity: $groupingGranularity)
        }
      }
    }
  }
EOS

schema_string = <<~EOS
  scalar DateTime

  enum DateTimeGroupingGranularity {
    DAY
  }

  type Query {
    widgetAggregations: WidgetAggregationConnection
  }

  type WidgetAggregation {
    groupedBy: WidgetAggregationGroupedBy
  }

  type WidgetAggregationConnection {
    nodes: [WidgetAggregation!]!
  }

  type WidgetAggregationGroupedBy {
    createdAt(
      granularity: DateTimeGroupingGranularity!
    ): DateTime
  }
EOS

schema = ::GraphQL::Schema.from_definition(schema_string)

query = ::GraphQL::Query.new(
  schema,
  query_string,
  variables: {},
  operation_name: "Widgets",
  context: {}
)

puts query.sanitized_query_string
```

Run the script to reproduce the bug.

**Expected behavior**

I expect the script to print output like:

```graphql
query Widgets {
  widgetAggregations {
    nodes {
      groupedBy {
        createdAt(granularity: DAY)
      }
    }
  }
}
```

**Actual behavior**

On 2.1.0, it raises an exception:

```
$ GRAPHQL_GEM_VERSION=2.1.0 ruby test_sanitized_query_printing.rb
/Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:22:in `append': no implicit conversion of GraphQL::Language::Nodes::Enum into String (TypeError)

            @out << other
                    ^^^^^
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:66:in `print_string'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:104:in `print_enum'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:404:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:109:in `print_variable_identifier'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:428:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:93:in `print_argument'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:118:in `block in print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:117:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:117:in `each_with_index'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:117:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:119:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:408:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:389:in `block in print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:124:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:119:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:408:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:389:in `block in print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:124:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:119:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:408:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:389:in `block in print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:124:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:119:in `print_field'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:408:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:389:in `block in print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:388:in `print_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:162:in `print_operation_definition'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:422:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:71:in `block in print_document'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:70:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:70:in `each_with_index'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:70:in `print_document'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:398:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:57:in `print_node'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/printer.rb:57:in `print'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/language/sanitized_printer.rb:33:in `sanitized_query_string'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/query.rb:279:in `block in sanitized_query_string'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/query.rb:452:in `with_prepared_ast'
        from /Users/myron/.rvm/gems/ruby-3.2.2/gems/graphql-2.1.0/lib/graphql/query.rb:278:in `sanitized_query_string'
        from test_sanitized_query_printing.rb:60:in `<main>'
```

On 2.0.27 it does not raise an exception:

```
$ GRAPHQL_GEM_VERSION=2.0.27 ruby test_sanitized_query_printing.rb
query Widgets {
  widgetAggregations {
    nodes {
      groupedBy {
        createdAt(granularity: #<GraphQL::Language::Nodes::Enum:0x0000000110490bb8>)
      }
    }
  }
}
```

Note, however, that it's not working correctly there, either--it's printing `#<GraphQL::Language::Nodes::Enum:0x0000000110490bb8>` in place of `DAY`.

When fixing this, it'd be nice to fix both problems (and not simply revert back to the buggy-but-not-an-exception behavior of 2.0.27).

**Comment by rmosolgo** [comment]
Thanks for the detailed report! I guess this one has been wrong for a _long_ time 😅  Its fixed in #4652 and I just released it in graphql-ruby 2.1.1. Let me know if you have any more trouble with it!
