### ISSUE TITLE
Possible error with directive parsing on GraphQL 2.2.0

### ISSUE THREAD

**Issue by brendo** [rmosolgo/graphql-ruby#4737]
Dependabot raised a bump PR to go from 2.1.7 to 2.2.0 in one of our projects. Our test suite is failing with this error that I _suspect_ is related to directives:

```
/tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:701:in `raise_parse_error': Expected LCURLY, actual: DIR_SIGN ("@") at [265356, 38] (/app/app/graph_clients/admin_api/schema.graphql) (GraphQL::ParseError)
--
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:690:in `expect_token'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:375:in `parse_field_definitions'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:281:in `definition'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:71:in `document'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:43:in `block in parse'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/tracing/trace.rb:24:in `parse'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:42:in `parse'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:16:in `parse'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/language/parser.rb:25:in `parse_file'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/schema/build_from_definition.rb:14:in `from_definition_path'
  | from /tmp/bundle/ruby/3.2.0/gems/graphql-2.2.0/lib/graphql/schema.rb:119:in `from_definition'
```

I'm assuming `[265356, 38]` means line 265356 of the schema, which I think is this section (the line number matches the newline after this bit):

```
  """
  The type of remote event that triggered this anomaly.
  """
  eventType: String @dynamicVisibility
```

The `@dynamicVisibility` directive is included at the top of the schema file and is defined as:

```
"""
Indicates the element's visibility in public schemas is contingent on client credentials.
"""
directive @dynamicVisibility on ARGUMENT_DEFINITION | ENUM | ENUM_VALUE | FIELD_DEFINITION | INPUT_FIELD_DEFINITION | INPUT_OBJECT | INTERFACE | OBJECT | SCALAR | UNION
```

Sorry bit new to this gem so not sure how to debug further, though I suspect it may be a corner case related to https://redirect.github.com/rmosolgo/graphql-ruby/issues/4718?

**Comment by rmosolgo** [comment]
Thanks for the detailed report and sorry for the trouble! I think you were exactly right about where it ran into trouble. I was able to replicate the bug and fix it in #4738. I'll merge it and release a new version in the morning :+1:

**Comment by brendo** [comment]
Thanks so much, and no worries at all!
