### ISSUE TITLE
Crash when scalar raises CoercionError on null

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4740]
**Describe the bug**

When a custom scalar raises a `GraphQL::CoercionError` for an explicit null value on an optional argument, nothing catches the exception or turns it into a response error.

**GraphQL schema**
```ruby
require "graphql"

class CustomScalar < GraphQL::Schema::Scalar
  class << self
    def coerce_input(input_value, _context)
      raise GraphQL::CoercionError, "Invalid value"
    end
  end
end

class QueryType < GraphQL::Schema::Object
  field :hello, String do
    argument :input, CustomScalar, required: false
  end

  def hello(input: nil)
    "hello world"
  end
end

class Schema < GraphQL::Schema
  query(QueryType)
end

result = Schema.execute('{ hello(input: null) }')
puts result.to_json
```

**Expected behavior**

I would expect the above script to print a graphql error response, something like
```
{"errors":[{"message":"Invalid value","locations":[{"line":1,"column":3}],"path":["query","hello","input"],"extensions":{"code":"argumentLiteralsIncompatible","typeName":"CoercionError"}}]}
```

If you pass any value *other* than null into the argument, that is what you get.

**Actual behavior**

The exception bubbles to the top and the program crashes.

<details>
<summary>Click to view exception backtrace</summary>

```
./sample.rb:6:in `coerce_input': Invalid value (GraphQL::CoercionError)
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/argument.rb:260:in `coerce_into_values'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:283:in `block (3 levels) in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:281:in `block (2 levels) in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:280:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:280:in `block in coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema/member/has_arguments.rb:309:in `coerce_arguments'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/arguments_cache.rb:49:in `dataload_for'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:271:in `evaluate_selection'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:214:in `block (2 levels) in evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:212:in `block in evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:211:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:211:in `evaluate_selections'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:121:in `block (4 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:709:in `call_method_on_directives'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:120:in `block (3 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:111:in `block (2 levels) in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:71:in `tap_or_each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:102:in `block in run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:709:in `call_method_on_directives'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter/runtime.rb:93:in `run_eager'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:75:in `block (6 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/tracing/trace.rb:43:in `execute_query'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:74:in `block (5 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:62:in `block (4 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `each'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `each_with_index'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:61:in `block (3 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:165:in `block (2 levels) in each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:160:in `each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:164:in `block in each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:191:in `call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:163:in `each_query_call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:46:in `block (2 levels) in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:191:in `call_hooks'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:45:in `block in run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/tracing/trace.rb:39:in `execute_multiplex'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/execution/interpreter.rb:37:in `run_all'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema.rb:1229:in `multiplex'
	from /Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.1.6/lib/graphql/schema.rb:1205:in `execute'
	from ./sample.rb:25:in `<main>'
```

</details>

**Comment by eapache-opslevel** [comment]
(Yes, the original code I boiled down to get this example is weird and broken for other reasons - it's not normal for a custom scalar to raise `CoercionError` on null if the argument is required. But maybe the library shouldn't even be trying to do coercion in that case? It's a null on an optional argument, that's just valid by default.)

**Comment by rmosolgo** [comment]
Ah, interesting. Thanks for the detailed report. I think the gem assumes that an error would surface here: 

https://github.com/rmosolgo/graphql-ruby/blob/fe9292bedbd5f5ff9616a82555ff78268a19f5e1/lib/graphql/schema/scalar.rb#L43-L50

But that looks like it doesn't handle `null`s -- they're assumed to be valid: 

https://github.com/rmosolgo/graphql-ruby/blob/fe9292bedbd5f5ff9616a82555ff78268a19f5e1/lib/graphql/schema/member/validates_input.rb#L11-L17

But then `null` _is_ passed to `coerce_input` later. Maybe that special handling for `.nil?` should be removed, so that validation runs the same as runtime coercion.
