### ISSUE TITLE
Schema parse on fragment: missing types on fragment definition

### ISSUE THREAD

**Issue by arinhouck** [rmosolgo/graphql-ruby#4773]
**Describe the bug**

When calling parse function on a fragment I am getting an error for Nilclas on `@types` in GraphQLClient `QueryTypename#add_typename` module. Entry point from graphql-ruby is the following (see full stack trace below):
```
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:97:in `on_fragment_definition_with_modifications'
```

**Versions**

graphql version: 2.2.4
rails (or other framework): 6.1.7
graphql-pro: 1.25.1

**GraphQL schema**

Schema class
```ruby
require 'graphql/schema'

module GemName
  module Commercetools
    Schema = GraphQL::Schema::BuildFromDefinition.from_definition_path(
      GraphQL::Schema,
      File.expand_path('../../../support/commercetools-api-reference/api-specs/graphql/schema.sdl', __dir__),
      default_resolve: nil
    )
  end
end
```

Code ran from spec
```ruby 
    TestClient = GraphQL::Client.new(schema: GemName::Commercetools::Schema)
     Selection = TestClient.parse <<~GQL
        fragment on Cart {
          __typename
        }
      GQL
```

sdl from commerce tools (its too long to include the full thing, let me know if I should upload the full idl somewhere to reference)
```graphql

"Versioned object have an ID and version and modification. Every update of this object changes it's version."
interface Versioned {
  id: String!
  version: Long!
  createdAt: DateTime!
  lastModifiedAt: DateTime!
  createdBy: Initiator
  lastModifiedBy: Initiator
}

interface ReferenceExpandable {
  id: String!
}

type Cart implements Versioned & ReferenceExpandable {
  customerId: String
  customer: Customer
  customerEmail: String
  anonymousId: String
  lineItems: [LineItem!]!
  totalLineItemQuantity: Long
  customLineItems: [CustomLineItem!]!
  totalPrice: Money!
  taxedPrice: TaxedPrice
  shippingAddress: Address
  billingAddress: Address
  inventoryMode: InventoryMode!
  taxMode: TaxMode!
  taxRoundingMode: RoundingMode!
  taxCalculationMode: TaxCalculationMode!
  customerGroup: CustomerGroup
  customerGroupRef: Reference
  country: Country
  shippingInfo: ShippingInfo
  discountCodes: [DiscountCodeInfo!]!
  refusedGifts: [CartDiscount!]!
  refusedGiftsRefs: [Reference!]!
  paymentInfo: PaymentInfo
  locale: Locale
  shippingRateInput: ShippingRateInput
  origin: CartOrigin!
  storeRef: KeyReference
  store: Store
  itemShippingAddresses: [Address!]!
  cartState: CartState!
  key: String
  custom: CustomFieldsType
  deleteDaysAfterLastModification: Int
  id: String!
  version: Long!
  createdAt: DateTime!
  lastModifiedAt: DateTime!
  createdBy: Initiator
  lastModifiedBy: Initiator
}
```

**Steps to reproduce**

1. Run a parse against a fragment and it's unable to detect types at graphql client level?

**Expected behavior**

No error on parse.

**Actual behavior**

<details>
<summary>Click to view exception backtrace</summary>

```
Failure/Error:
  Selection = TestClient.parse <<~GQL
    fragment on Cart {
      __typename
    }
  GQL

NoMethodError:
  undefined method `[]' for nil:NilClass

              type = @types[node]
                           ^^^^^^
# ./vendor/bundle/ruby/3.1.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:28:in `add_typename'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:56:in `on_fragment_definition'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:97:in `on_fragment_definition_with_modifications'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:123:in `public_send'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:123:in `block in on_document_children'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:121:in `each'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:121:in `on_document_children'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:86:in `on_document'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:97:in `on_document_with_modifications'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:[55](https://github.com/knowde/knowde_graphql/actions/runs/7467973186/job/20322525224#step:4:56):in `public_send'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-2.2.4/lib/graphql/language/visitor.rb:55:in `visit'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-client-0.18.0/lib/graphql/client/query_typename.rb:62:in `insert_typename_fields'
# ./vendor/bundle/ruby/3.1.0/gems/graphql-client-0.18.0/lib/graphql/client.rb:189:in `parse'
# ./spec/lib/gem_name/client/query_builder_spec.rb:6:in `<module:CustomerActiveCart>'
# ./spec/lib/gem_name/client/query_builder_spec.rb:5:in `<module:TestSupport>'
# ./spec/lib/gem_name/client/query_builder_spec.rb:4:in `<module:GemName>'
# ./spec/lib/gem_name/client/query_builder_spec.rb:3:in `<top (required)>'
```

</details>

**Additional context**

The bug was introduced when I went to upgrade from `2.0.14` to `2.2.4`.

**Comment by rmosolgo** [comment]
Unfortunately GraphQL-Client is in a bad way 😢  

Some changes in GraphQL-Ruby 2.1 caused graphql-client to break: https://github.com/github/graphql-client/issues/310

The fix is here: https://github.com/github/graphql-client/pull/314

But nobody at GitHub will review the patch or give me commit access, so we're stuck 😖  

The only way forward I see is for me to publish to RubyGems from my fork (I still have write permissions to RubyGems from when I worked at GitHub...), but that seems a bit shady.

**Comment by arinhouck** [comment]
I hear you. Sounds like that might be the preferred approach so everyone can upgrade smoothly and prevent new projects using graphql-ruby from getting stuck with similar problems when building latest version. Look forward to a resolution so we can take advantage of the new features provided!

**Comment by rmosolgo** [comment]
I got an email from one of the devs at GitHub saying they're trying to find some way to resolve the maintenance access issue. I'll wait till the middle of next week or so before taking drastic action ... but I don't think there's anything to do in GraphQL-Ruby now, so I'll close this issue.
