### ISSUE TITLE
"stack level too deep" error when installing `2.2.0`+

### ISSUE THREAD

**Issue by dmorgan-fa** [rmosolgo/graphql-ruby#4818]
## What
When first installing the gem on version `2.2.0`+, the following `stack level too deep` error occurs:

``` bash
$ gem install graphql -v2.2.0
Fetching graphql-2.2.0.gem
Successfully installed graphql-2.2.0
Parsing documentation for graphql-2.2.0
Installing ri documentation for graphql-2.2.0
/Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/any_method.rb:131:in `is_alias_for': stack level too deep (SystemStackError)
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:134:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0/gems/rdoc-6.6.2/lib/rdoc/method_attr.rb:135:in `documented?'
	 ... 10898 levels...
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:193:in `process_args'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/command_manager.rb:151:in `run'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:56:in `run'
	from /Users/<username>/.asdf/installs/ruby/3.2.2/bin/gem:12:in `<main>'
```

This **only** happens the first time when installing the 2.2.0+ version, so run `gem uninstall graphql` first to purge the local install.
It does not happen for v`2.1` (i.e. `gem install graphql -v2.1.11` is fine)

## Versions

- `graphql`: 2.2.0+
- M1 Mac, Sonoma 14.2.1
- `ruby`: 3.2.2, 3.3.0
- `asdf` to install `ruby` via `rbenv/ruby-build` (Also present when installed with `ruby-install`)

## Steps to reproduce

1. Remove any existing grapqhl gems: `gem uninstall graphql` & select all
1. Install any 2.2.0 version: `gem install graphql -v 2.2.0`

**Comment by rmosolgo** [comment]
Hey, thanks for reporting this! I had seen it too, but since, as you noted, it _worked_ if you ran it a second time, I ignored it 🙈  I was able to replicate the problem locally with `rdoc **/*.rb`, and confirm that #4819 will fix it.

**Comment by rmosolgo** [comment]
I also reported this bug to RDoc: https://github.com/ruby/rdoc/issues/1088

**Comment by dmorgan-fa** [comment]
Thanks for the speedy reply and fix @rmosolgo 🙏
