### ISSUE TITLE
`nil can't be coerced into Integer (TypeError)` when parsing invalid bare-name with hyphen

### ISSUE THREAD

**Issue by eapache-opslevel** [rmosolgo/graphql-ruby#4879]
**Describe the bug**

New lexer/parser raises when a (invalid) bare-name argument string includes a hyphen:

```
$ GraphQL.parse("{ field(argument:a-b) }")
/Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.2.12/lib/graphql/language/lexer.rb:82:in `rescue in token_value': (token_value failed: TypeError: nil can't be coerced into Integer) (GraphQL::Error)
/Users/eapache/.rvm/gems/ruby-3.2.2@opslevel/gems/graphql-2.2.12/lib/graphql/language/lexer.rb:80:in `-': nil can't be coerced into Integer (TypeError)

        @string.byteslice(@scanner.pos - @scanner.matched_size, @scanner.matched_size)
                                         ^^^^^^^^^^^^^^^^^^^^^
```

**Versions**

`graphql` version: 2.2.12

**Comment by rmosolgo** [comment]
fixed in 2.2.14, thanks for reporting this!
