### ISSUE TITLE
Version 1.13.22 uninitialized constant error

### ISSUE THREAD

**Issue by kaylareopelle** [rmosolgo/graphql-ruby#4900]
**Describe the bug**

As of yesterday, [when running tests using version 1.13.22 of the graphql gem](https://github.com/open-telemetry/opentelemetry-ruby-contrib/actions/runs/8541826613/job/23438326780#step:3:160), we get the following error:

```ruby
lib/graphql/compatibility/execution_specification/specification_schema.rb:6:in 
  `<module:SpecificationSchema>': uninitialized constant 
    GraphQL::Compatibility::ExecutionSpecification::SpecificationSchema::OpenStruct (NameError)

        BOGUS_NODE = OpenStruct.new({ bogus: true })
```

If I edit `specification_schema.rb` to `require "ostruct"`, the error goes away and all tests pass.

This error seems to raise when the gem is required in the test helper.

I have yet to find anything that changed between April 2 and April 3 that may have caused this.

**Versions**

`graphql` version: 1.13.22 (and possibly others in the 1.x series) 
Everything in 2.x is fine and the file doesn't seem to exist in the 2.x series.

**GraphQL schema**

N/A

**GraphQL query**

N/A

**Steps to reproduce**

I haven't been able to create a minimal reproduction yet.

**Expected behavior**

Version 1.13.22 can load without error. 

**Actual behavior**

What specifically went wrong?

<details>
<summary>Click to view exception backtrace</summary>

```
  /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification/specification_schema.rb:6:in `<module:SpecificationSchema>': uninitialized constant GraphQL::Compatibility::ExecutionSpecification::SpecificationSchema::OpenStruct (NameError)
  
          BOGUS_NODE = OpenStruct.new({ bogus: true })
                       ^^^^^^^^^^
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification/specification_schema.rb:5:in `<module:ExecutionSpecification>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification/specification_schema.rb:4:in `<module:Compatibility>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification/specification_schema.rb:3:in `<module:GraphQL>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification/specification_schema.rb:2:in `<top (required)>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility/execution_specification.rb:3:in `<top (required)>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql/compatibility.rb:2:in `<top (required)>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/graphql-1.13.22/lib/graphql.rb:135:in `<top (required)>'
  	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  	from <internal:/opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `each'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:55:in `block in require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `each'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler/runtime.rb:44:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/bundler-2.5.7/lib/bundler.rb:187:in `require'
  	from /home/runner/work/opentelemetry-ruby-contrib/opentelemetry-ruby-contrib/instrumentation/graphql/test/test_helper.rb:8:in `<top (required)>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /home/runner/work/opentelemetry-ruby-contrib/opentelemetry-ruby-contrib/instrumentation/graphql/test/instrumentation/graphql/instrumentation_test.rb:7:in `<top (required)>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rake-13.2.0/lib/rake/rake_test_loader.rb:21:in `block in <main>'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rake-13.2.0/lib/rake/rake_test_loader.rb:6:in `select'
  	from /opt/hostedtoolcache/Ruby/3.3.0/x64/lib/ruby/gems/3.3.0/gems/rake-13.2.0/lib/rake/rake_test_loader.rb:6:in `<main>'
  rake aborted!
  Command failed with status (1)
  /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `load'
  /opt/hostedtoolcache/Ruby/3.3.0/x64/bin/bundle:25:in `<main>'
  Tasks: TOP => test
  (See full trace by running task with --trace)
```

</details>

**Additional context**

N/A

**Comment by kaylareopelle** [comment]
Since this involves such an old version of the gem, what is your policy for making updates?

**Comment by kaylareopelle** [comment]
On further review, this probably isn't a GraphQL-specific error. I'm seeing [similar issues with OpenStruct on other libraries](https://github.com/newrelic/newrelic-ruby-agent/actions/runs/8552048243/job/23466798716#step:12:6876).

**Comment by composerinteralia** [comment]
My guess is that these libraries were relying on `rake` loading it, which changed in https://github.com/ruby/rake/commit/a27bb8e10786efa4776cc3ecfe12490e1ea106a7

**Comment by rmosolgo** [comment]
🚢  in 1.13.23 -- please let me know if you have any more trouble with it!

**Comment by kaylareopelle** [comment]
Thanks, @rmosolgo and @composerinteralia! The fix is working!

**Comment by jedschneider** [comment]
updating to 1.13.23 worked for me!
