### ISSUE TITLE
ArgumentError: wrong number of arguments (given 6, expected 7) GraphQL v2.3.0 c_parser v1.0.7

### ISSUE THREAD

**Issue by arielvalentin** [rmosolgo/graphql-ruby#4904]
**Describe the bug**

The OTel Instrumentation test suite is failing with what seems to be an incompatibility with GraphQL v2.3.0 and the c_parser v1.0.7:

```console
  1) Error:
OpenTelemetry::Instrumentation::GraphQL::Tracers::GraphQLTracer::#platform_trace::when platform_field is enabled#test_0001_traces execute_field:
ArgumentError: wrong number of arguments (given 6, expected 7)
 ```

**Versions**

GraphQL v2.3.0 
c_parser v1.0.7

**Steps to reproduce**

Check out the latest version of the opentelemetry-ruby-contrib repo. 

```console
$> bundle exec appraisal generate
$> bundle exec appraisal install
$> bundle exec appraisal rake test
```

**Expected behavior**

The test suite should pass!

**Actual behavior**

The tests fail with the exception backtrace below. 

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```console

1) Error:
OpenTelemetry::Instrumentation::GraphQL::Tracers::GraphQLTracer::#platform_trace::when platform_field is enabled#test_0001_traces execute_field:
ArgumentError: wrong number of arguments (given 6, expected 7)
   /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/language/nodes.rb:316:in `from_a'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:96:in `c_parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:96:in `block in result'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/trace.rb:24:in `parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:13:in `block in parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:60:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `block in call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:30:in `block in trace'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:33:in `block in platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:32:in `platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:29:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:46:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:13:in `parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:95:in `result'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-c_parser-1.0.7/lib/graphql/c_parser.rb:11:in `parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql.rb:46:in `parse'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/query.rb:398:in `prepare_ast'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/query.rb:458:in `with_prepared_ast'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/query.rb:316:in `validation_pipeline'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/query.rb:324:in `valid?'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/analysis/ast.rb:27:in `block (2 levels) in analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/analysis/ast.rb:26:in `map'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/analysis/ast.rb:26:in `block in analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/trace.rb:32:in `analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:21:in `block in analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:60:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `block in call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:30:in `block in trace'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:33:in `block in platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:32:in `platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:29:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:46:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:21:in `analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/analysis/ast.rb:25:in `analyze_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/execution/interpreter.rb:46:in `block in run_all'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/trace.rb:40:in `execute_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:29:in `block in execute_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:60:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `block in call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:30:in `block in trace'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:33:in `block in platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `block in in_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `block in with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/context.rb:87:in `with_value'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace.rb:70:in `with_span'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/opentelemetry-api-1.2.5/lib/opentelemetry/trace/tracer.rb:37:in `in_span'
    lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb:32:in `platform_trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/platform_tracing.rb:29:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:62:in `call_tracers'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing.rb:46:in `trace'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/tracing/legacy_trace.rb:29:in `execute_multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/execution/interpreter.rb:37:in `run_all'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/schema.rb:1312:in `multiplex'
    /Users/arielvalentin/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/graphql-2.3.0/lib/graphql/schema.rb:1288:in `execute'
    test/instrumentation/graphql/tracers/graphql_tracer_test.rb:132:in `block (4 levels) in <top (required)>'

```

</details>

**Additional context**

With these details, we can efficiently hunt down the bug!

**Comment by arielvalentin** [comment]
ok looks like this is fixed with v1.0.8 😄
