### ISSUE TITLE
Queries with multiline strings inputs are still failing even using the backported method

### ISSUE THREAD

**Issue by niltonvasques** [rmosolgo/graphql-ruby#4915]
**Describe the bug**

Multiline strings are still failing even using the backport method

**Versions**

`graphql` version: 2.3.0
`rails` (or other framework): 7.0.8
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
input RecordInput {
  active: Boolean
  createdAt: DateTime
  dynamicFields: Hash
  id: ID
  updatedAt: DateTime
}

type RecordType {
  active: Boolean
  createdAt: DateTime
  dynamicFields: Hash
  id: ID
  updatedAt: DateTime
}

createRecord(data: RecordInput): RecordType
```

**GraphQL query**

Example GraphQL query and response (if query execution is involved)

```graphql
mutation {
  createRecord(data: {
     dynamicFields: { string_test: "avenue 1st\n 2nd line"}
  })
 { id, dynamicFields }         
```

```json
{
    "data": {
        "createRecord": {
            "id": "661ce077eb3e2e5243bc22d2",
            "dynamicFields": {
                "string_test": "avenue 1st\n 2nd line"
            }
        }
    }
}
```

**Steps to reproduce**

@rmosolgo, even using this backport method `GraphQL::Language.escape_single_quoted_newlines` (https://github.com/rmosolgo/graphql-ruby/pull/4834), I'm still facing problems with newlines. See:

**Query string before backport**

```
"\n                mutation {\n                  createRecord(data: {\n                     dynamicFields: { string_test: \"avenue 1st\n 2nd line\"},\n                   })\n                  { id, dynamicFields }\n                }\n              "
```

**Query string after backport**

```
"\n                mutation {\n                  createRecord(data: {\n                     dynamicFields: { string_test: \"avenue 1st\\n 2nd line\"},\n                   })\n                  { id, dynamicFields }\n                }\n              "
```

**Expected behavior**

The multline string problem should not be a problem after using the `GraphQL::Language.escape_single_quoted_newlines` to fix the query.

**Actual behavior**

Schema complaining about block strings. `Expected string or block string, but it was malformed`

<details>
<summary>Click to view exception backtrace</summary>

```
     Failure/Error: query_name = ::GraphQL.parse(params[:query]).definitions[0].selections[0].name
      
     GraphQL::ParseError:
       Expected string or block string, but it was malformed
     Shared Example Group: "a dynamic graphql controller" called from ./spec/requests/record_spec.rb:4
     # /usr/share/rvm/gems/ruby-3.3.0@pocket/gems/graphql-2.3.0/lib/graphql/language/lexer.rb:147:in `raise_parse_error'
     # /usr/share/rvm/gems/ruby-3.3.0@pocket/gems/graphql-2.3.0/lib/graphql/language/lexer.rb:68:in `advance'
     # /usr/share/rvm/gems/ruby-3.3.0@pocket/gems/graphql-2.3.0/lib/graphql/language/parser.rb:56:in `advance_token'
     # /usr/share/rvm/gems/ruby-3.3.0@pocket/gems/graphql-2.3.0/lib/graphql/language/parser.rb:713:in `expect_token'
```

**My controller**

```
  def execute
    query = params[:query]
    escaped_query = GraphQL::Language.escape_single_quoted_newlines(query)
    if !query.equal?(escaped_query) # If the same string was returned, then nothing was escaped.
      query = escaped_query
    end
    variables = ensure_hash(params[:variables])
    operation_name = params[:operationName]
    context = get_context(params[:query])

    result = MySchema.execute(query, variables: variables,
                                            operation_name: operation_name,
                                            context: context)
```

</details>

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble and thanks for the detailed report. Based on your examples, I added some cases to the GraphQL-Ruby test suite, but they passed as expected: 1e662f4d4

In your application, could you share the terminal output of `puts bad_query_string.inspect`? That would help me make sure I'm using the same linebreaks and backslashes as are present in your example.

**Comment by niltonvasques** [comment]
Interesting!

Find the output here from the `bad query string`.

```
"\n                mutation {\n                  createRecord(data: {\n                     dynamicFields: { string_test: \"avenue 1st\n 2nd line\"},\n                   })\n                  { id, dynamicFields }\n                }\n              "
```

**Comment by rmosolgo** [comment]
Ok, thanks for sharing that... I created a test script based on that string. Could you please run it and share the output you get? 

```ruby 
require "bundler/inline"

gemfile do
  gem "graphql", "2.3.0"
end

str1 = "
                mutation {
                  createRecord(data: {
                     dynamicFields: { string_test: \"avenue 1st
 2nd line\"},
                   })
                  { id, dynamicFields }\
               }
              "
puts str1.inspect
# "\n                mutation {\n                  createRecord(data: {\n                     dynamicFields: { string_test: \"avenue 1st\n 2nd line\"},\n                   })\n                  { id, dynamicFields }               }\n              "

str2 = GraphQL::Language.escape_single_quoted_newlines(str1)
# This one is different: it has an extra backslash ("\\n" instead of "\n"), showing that the newline was escaped:
puts str2.inspect
# "\n                mutation {\n                  createRecord(data: {\n                     dynamicFields: { string_test: \"avenue 1st\\n 2nd line\"},\n                   })\n                  { id, dynamicFields }               }\n              "

begin
  GraphQL.parse(str1)
rescue GraphQL::ParseError => err
  pp [err.line, err.col, err.message]
  # [4, 52, "Expected string or block string, but it was malformed"]
end

pp GraphQL.parse(str2).class
# GraphQL::Language::Nodes::Document
```

**Comment by niltonvasques** [comment]
@rmosolgo I just found the problem, our application calls `GraphQL.parse` function directly to analyse query names, thus now we are also escaping from there! 

`::GraphQL.parse(query).definitions[0].selections[0].name`

Thanks a lot for help me to identify it.

**Comment by rmosolgo** [comment]
Glad you got to the bottom of it :+1:
