### ISSUE TITLE
Infinity not allowed in JSON raised when calling GraphQL::Query.new with inf values and using graphql pro operation store

### ISSUE THREAD

**Issue by alexus37** [rmosolgo/graphql-ruby#4922]
**Describe the bug**

Hi we are using the operation store from the graphQL pro gem in our schema. 
If a user submits a query with an infinity value the `GraphQL::Query.new` raises a `Infinity not allowed in JSON` exception.

```ruby
query = <<~'GRAPHQL'
    query {
      repository(owner: "owner", name: "name") {
        issue(number: 9999e999) {
          id
        }
      }
    }
    GRAPHQL
document = GraphQL.parse(query, tracer: tracer)
GraphQL::Query.new(
      schema,
      document: document,
      context: context,
      variables: variables,
      validate: validate,
    ) # raises
```

After looking at the call stack it seems that the `QueryExtension` defined in the `graphql/pro/operation_store.rb` is being prepend to graphQL query `GraphQL::Query.prepend(QueryExtension)`. This method calls the `populate_operation` which checks if the `query.query_string.nil?` which internally calls to JSON on the args which causes the error.

A simple fix would be to add a `query.valid?` check before calling the `query_string` method.

**Versions**

`graphql` version: 1.13.22
`graphql-pro` version: 1.27.0 

**Expected behavior**

The init should not throw even if the args have wrong values. This was the case for graphql-pro 1.23

**Actual behavior**

What specifically went wrong?

An error was raised.

Backtrace:

<details>
<summary>Click to view exception backtrace</summary>

<p>

```
Infinity not allowed in JSON
"/workspaces/vendor/ruby/5124f9ac7513eb590c37717337c430cb93caa151/lib/ruby/3.3.0/json/common.rb:305:in `generate'",
 "/workspaces/vendor/ruby/5124f9ac7513eb590c37717337c430cb93caa151/lib/ruby/3.3.0/json/common.rb:305:in `generate'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language.rb:32:in `serialize'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:355:in `print_node'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:38:in `print_argument'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:63:in `block in print_field'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:63:in `map'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:63:in `print_field'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:311:in `print_node'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:290:in `block in print_selections'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:289:in `each'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:289:in `print_selections'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:65:in `print_field'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:311:in `print_node'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:290:in `block in print_selections'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:289:in `each'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:289:in `print_selections'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:116:in `print_operation_definition'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:325:in `print_node'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:34:in `block in print_document'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:34:in `map'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:34:in `print_document'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:301:in `print_node'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/printer.rb:28:in `print'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/language/nodes.rb:78:in `to_query_string'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-1.13.22/lib/graphql/query.rb:153:in `query_string'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-pro-1.27.0/lib/graphql/pro/operation_store.rb:221:in `populate_operation'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-pro-1.27.0/lib/graphql/pro/operation_store.rb:312:in `check_operation_store'",
 "/workspaces/vendor/gems/3.3.0/ruby/3.3.0/gems/graphql-pro-1.27.0/lib/graphql/pro/operation_store.rb:307:in `initialize'",
 "/workspaces/lib/platform.rb:204:in `new'",
```

</p>
</details>

**Comment by rmosolgo** [comment]
Hey, thanks for the detailed report! I agree it should handle this cleanly. 

I opened https://github.com/rmosolgo/graphql-ruby/pull/4923 to rescue this error nicer on master. But that won't help 1.13.x. 

I also just released graphql-pro 1.27.1 which checks for `query.document` before calling `query.query_string`. That way, if it has an already-parsed AST, it won't try to recreate the query string. That should fix this bug, too! Please give that version a try and let me know if you have any trouble with it.
