### ISSUE TITLE
Regression: InputObjectType can't be specified with variables

### ISSUE THREAD

**Issue by dylanahsmith** [rmosolgo/graphql-ruby#50]
commit fa7a2dba9dae5db516c0d276c80d7d4af4d1c9a5 introduced a regression where coerce gets called on ObjectInputType which doesn't implement the method

Example:

```ruby
require 'graphql'
require 'json'

AddInput = GraphQL::InputObjectType.define do
  name "AddInput"
  input_field :a, types.Int
  input_field :b, types.Int
end

QueryRoot = GraphQL::ObjectType.define do
  name "Query"

  field :add, types.String do
    argument :input, AddInput
    resolve ->(obj, args, ctx) {
      input = args['input']
      "#{input['a'].inspect} + #{input['b'].inspect}"
    }
  end
end

Schema = GraphQL::Schema.new(query: QueryRoot)
query_string = <<GRAPHQL
query Q($input: AddInput) {
  add(input: $input)
}
GRAPHQL
variables = { "input" => { "a" => 1.2, "b" => 2.3 } }
result = Schema.execute(query_string, variables: variables, debug: true)
puts JSON.pretty_generate(result)
```

outputs

```
/Users/dylansmith/src/graphql-ruby/lib/graphql/base_type.rb:74:in `coerce_input!': undefined method `coerce_input' for AddInput:GraphQL::InputObjectType (NoMethodError)
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:28:in `reduce_value'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:8:in `block in initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:14:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:14:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:92:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:92:in `block in resolve_field'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/directive_chain.rb:30:in `call'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/directive_chain.rb:30:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:91:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:91:in `resolve_field'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:34:in `block in result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/operation_resolution.rb:17:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/base_execution.rb:16:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:50:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:27:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:43:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/schema.rb:41:in `execute'
	from tmp/example.rb:29:in `<main>'
```

previously it would output

```
{
  "data": {
    "add": "1.2 + 2.3"
  }
}
```

**Comment by rmosolgo** [comment]
Thanks for the test case, it passes on master! The values are correctly coerced to integers:

```ruby
puts JSON.pretty_generate(result)
# {
#   "data": {
#     "add": "1 + 2"
#   }
# }
```

Does it look good to you?

**Comment by dylanahsmith** [comment]
Looks good
