### ISSUE TITLE
Default values for variables are ignored

### ISSUE THREAD

**Issue by dylanahsmith** [rmosolgo/graphql-ruby#51]
Example:

```ruby
require 'graphql'
require 'json'

QueryRoot = GraphQL::ObjectType.define do
  name "Query"

  field :double, types.String do
    argument :x, types.Int
    resolve ->(obj, args, ctx) {
      "#{args['x'].inspect} ** 2"
    }
  end
end

Schema = GraphQL::Schema.new(query: QueryRoot)
query_string = <<GRAPHQL
query Q($x: Int = 3) {
  double(x: $x)
}
GRAPHQL
variables = {}
result = Schema.execute(query_string, variables: variables, debug: true)
puts JSON.pretty_generate(result)
```

outputs

```
/Users/dylansmith/src/graphql-ruby/lib/graphql/base_type.rb:77:in `coerce_input!': Couldn't coerce nil to Int (GraphQL::ExecutionError)
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:28:in `reduce_value'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:8:in `block in initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/arguments.rb:6:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:14:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/field_resolution.rb:14:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:92:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:92:in `block in resolve_field'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/directive_chain.rb:30:in `call'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/directive_chain.rb:30:in `initialize'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:91:in `new'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:91:in `resolve_field'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:34:in `block in result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `each'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `reduce'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/selection_resolution.rb:33:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/serial_execution/operation_resolution.rb:17:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/base_execution.rb:16:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:50:in `execute'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query/executor.rb:27:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/query.rb:43:in `result'
	from /Users/dylansmith/src/graphql-ruby/lib/graphql/schema.rb:41:in `execute'
	from tmp/example.rb:22:in `<main>'
```

because it tries to coerce `nil` when the variable isn't provided, instead of replacing it with the default value.

Before commit fa7a2dba9dae5db516c0d276c80d7d4af4d1c9a5, which added input coercion, it the output was

```
{
  "data": {
    "double": "nil ** 2"
  }
}
```

**Comment by rmosolgo** [comment]
Thanks for the test case, it passes on master! The default value is correctly exposed to the resolve function:

```ruby
puts JSON.pretty_generate(result)
# {
#   "data": {
#     "double": "3 ** 2"
#   }
# }
```

Does it look good to you?

**Comment by dylanahsmith** [comment]
Thanks
