### ISSUE TITLE
`GraphQL::Execution::Lookahead#arguments` can unexpectedly be a `GraphQL::ExecutionError`

### ISSUE THREAD

**Issue by myronmarston** [rmosolgo/graphql-ruby#5135]
**Describe the bug**

When using a `lookahead` to deal with a child selection, the `node.arguments` can sometimes be a `GraphQL::ExecutionError` instead of a hash as expected. Notably, [the docs](https://graphql-ruby.org/api-doc/2.3.19/GraphQL/Execution/Lookahead.html#arguments-instance_method) document it as being a hash.

**Versions**

`graphql` version: `2.3.19` but this also happens in git `HEAD` (I checked since I thought your fix in #5133 may have already fixed this).
`rails` (or other framework): N/A

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```graphql
type MyData {
  now(timeZone: String! = "UTC"): String!
}

type Query {
  myData: MyData
}
```

**GraphQL query**

```graphql
query Now($timeZone: String = null) {
  myData {
    now(timeZone: $timeZone)
  }
}
```

**Steps to reproduce**

Put this in a file:

```ruby
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  if ENV["GIT"]
    gem "graphql", git: "https://github.com/rmosolgo/graphql-ruby.git"
  else
    gem "graphql", "2.3.19"
  end

  gem "debug"
  gem "tzinfo"
end

require "debug"
require "graphql"
require "time"

SCHEMA_STRING = <<~EOS
  type MyData {
    now(timeZone: String! = "UTC"): String!
  }

  type Query {
    myData: MyData
  }
EOS

class Application
  def initialize
    @schema = ::GraphQL::Schema.from_definition(SCHEMA_STRING, default_resolve: self)
    @schema.types.fetch("Query").fields.fetch("myData").extras([:lookahead])
  end

  def call(parent_type, field, object, args, context)
    if field.graphql_name == "myData"
      now_node = args.fetch(:lookahead).selection(:now)
      time_zone = ::TZInfo::Timezone.get(now_node.arguments.fetch(:time_zone))

      {"now" => time_zone.to_local(::Time.now)}
    else
      object.fetch(field.graphql_name)
    end
  end

  def execute_query(description, query_string, variables: {})
    puts <<~EOS
      #{"-" * 80}
      #{description}

      Query:
      #{query_string}

      Variables:
      #{::JSON.generate(variables)}

    EOS

    query = ::GraphQL::Query.new(@schema, query_string, variables: variables)
    response = query.result

    puts <<~EOS
      Response:
      #{::JSON.pretty_generate(response.to_h)}
    EOS
  end
end

app = Application.new

app.execute_query("Operation variable has no default, no variables provided", <<~EOS)
  query Now($timeZone: String) {
    myData {
      now(timeZone: $timeZone)
    }
  }
EOS

app.execute_query("Operation variable has null default, variables provided", <<~EOS, variables: {"timeZone": "America/Los_Angeles"})
  query Now($timeZone: String = null) {
    myData {
      now(timeZone: $timeZone)
    }
  }
EOS

app.execute_query("Operation variable has null default, no variables provided", <<~EOS)
  query Now($timeZone: String = null) {
    myData {
      now(timeZone: $timeZone)
    }
  }
EOS
```

Run the script to reproduce the bug.  The first 2 queries succeed, but the 3rd query encounters the bug and gets a `NoMethodError`.

**Expected behavior**

As a basic invariant, I expect _any_ query to either succeed, or to be rejected as invalid up front. In no case do I expect a validation issue to manifest as a `GraphQL::ExecutionError` as the return value of `Lookahead#arguments`.

For this specific case, I expect the 3rd query to succeed just like the first.  I wouldn't expect the `= null` on the operation variable to have any impact.

**Actual behavior**

Here's the output I get when I run the script:

```
--------------------------------------------------------------------------------
Operation variable has no default, no variables provided

Query:
query Now($timeZone: String) {
  myData {
    now(timeZone: $timeZone)
  }
}


Variables:
{}

Response:
{
  "data": {
    "myData": {
      "now": "2024-10-31 00:16:33 +0000"
    }
  }
}
--------------------------------------------------------------------------------
Operation variable has null default, variables provided

Query:
query Now($timeZone: String = null) {
  myData {
    now(timeZone: $timeZone)
  }
}


Variables:
{"timeZone":"America/Los_Angeles"}

Response:
{
  "data": {
    "myData": {
      "now": "2024-10-30 17:16:33 -0700"
    }
  }
}
--------------------------------------------------------------------------------
Operation variable has null default, no variables provided

Query:
query Now($timeZone: String = null) {
  myData {
    now(timeZone: $timeZone)
  }
}


Variables:
{}

tmp/graphql_bug.rb:39:in `call': undefined method `fetch' for #<GraphQL::ExecutionError: `null` is not a valid input for `String!`, please provide a value for this argument.> (NoMethodError)

      time_zone = ::TZInfo::Timezone.get(now_node.arguments.fetch(:time_zone))
                                                           ^^^^^^
      [backtrace moved into the details below]
```

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/build_from_definition.rb:473:in `resolve_field_myData'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/field.rb:736:in `public_send'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/field.rb:736:in `block (2 levels) in resolve'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/field.rb:870:in `with_extensions'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/field.rb:707:in `block in resolve'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:751:in `minimal_after_lazy'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/query.rb:424:in `after_lazy'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/schema/field.rb:705:in `resolve'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:375:in `block (2 levels) in evaluate_selection_with_resolved_keyword_args'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/tracing/trace.rb:52:in `execute_field'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:374:in `block in evaluate_selection_with_resolved_keyword_args'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:363:in `evaluate_selection_with_resolved_keyword_args'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:341:in `block in evaluate_selection_with_args'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:810:in `after_lazy'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:288:in `evaluate_selection_with_args'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:277:in `evaluate_selection'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:228:in `block (3 levels) in evaluate_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:227:in `block (2 levels) in evaluate_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:209:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:209:in `block in evaluate_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:206:in `evaluate_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:96:in `block (3 levels) in run_eager'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:95:in `block (2 levels) in run_eager'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:116:in `each_gathered_selections'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:86:in `block in run_eager'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:696:in `call_method_on_directives'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter/runtime.rb:85:in `run_eager'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:71:in `block (4 levels) in run_all'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/tracing/trace.rb:44:in `execute_query'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:70:in `block (3 levels) in run_all'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/dataloader/null_dataloader.rb:19:in `append_job'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:58:in `block (2 levels) in run_all'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:54:in `each'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:54:in `each_with_index'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:54:in `block in run_all'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/tracing/trace.rb:40:in `execute_multiplex'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/execution/interpreter.rb:38:in `run_all'
        from /Users/myron/.rvm/gems/ruby-3.2.5/gems/graphql-2.3.19/lib/graphql/query.rb:253:in `result'
        from tmp/graphql_bug.rb:49:in `execute_query'
        from tmp/graphql_bug.rb:85:in `<main>'
```

</details>

**Additional context**

This is similar to #5127, which you kindly fixed after I reported. If possible, I'd love for v2.3.20 to include both fixes since both are impacting my users.

**Comment by rmosolgo** [comment]
Hey, sorry for the trouble and thanks for the detailed report. I agree this isn't the best way to handle this error. I think it would be better to terminate the query with an error instead of starting to execute it, but I wouldn't be surprised if this case isn't covered in GraphQL-Ruby's tests yet 😅 

Here's the part in the GraphQL Spec that addresses it: https://spec.graphql.org/draft/#sec-All-Variable-Usages-Are-Allowed.Allowing-Optional-Variables-When-Default-Values-Exist

Interestingly, the default value of `null` is _not_ addressed there, but a runtime value of `null` is addressed: 

> The value `null` could still be provided to such a variable at runtime. A non-null argument must raise a [field error](https://spec.graphql.org/draft/#field-error) if provided a `null` value.

Honestly, I think that queries like this should be rejected altogether (since the variable definition doesn't satisfy the type condition where it's used), but it may be too late to change that default behavior in the gem.

**Comment by myronmarston** [comment]
> Honestly, I think that queries like this should be rejected altogether (since the variable definition doesn't satisfy the type condition where it's used), but it may be too late to change that default behavior in the gem.

That was my initial expectation, too. However, upon further reflection, I've changed my mind. Here's my thought process:

* `= null` doesn't fundamentally change the type of the variable. In either case, the variable is nullable, and that doesn't directly align with the type of the input argument.
* As you noted, the GraphQL spec specifically allows a nullable variable for a non-null input argument when the input arg has a default value.
* There's a sense in which `= null` on a nullable variable doesn't do anything. It explicitly sets the default value to `null`, but the default value of a nullable variable is already `null`, so it doesn't feel like it should change anything.

**Comment by myronmarston** [comment]
Another possible angle to consider--is there a GraphQL server implementation that the GraphQL spec maintainers consider to be "canonically correct"? If so, can we see how it treats this case?

**Comment by rmosolgo** [comment]
The JS implementation is called the "reference implementation," so that would be a good comparison point.

**Comment by myronmarston** [comment]
Another data point here is how the GraphQL gem handles this when the resolver isn't using a lookahead.  If I change the implementation in my script like so:

```ruby
class Application
  def initialize
    @schema = ::GraphQL::Schema.from_definition(SCHEMA_STRING, default_resolve: self)
  end

  def call(parent_type, field, object, args, context)
    if field.graphql_name == "myData"
      {"now" => :resolve_on_next_call}
    elsif field.graphql_name == "now"
      time_zone = ::TZInfo::Timezone.get(args.fetch(:time_zone))
      time_zone.to_local(::Time.now)
    else
      raise "Unrecognized GraphQL field: #{field}"
    end
  end
  # ...
end
```

...and then run it, the output of the 3rd query is:

```
--------------------------------------------------------------------------------
Operation variable has null default, no variables provided

Query:
query Now($timeZone: String = null) {
  myData {
    now(timeZone: $timeZone)
  }
}


Variables:
{}

Response:
{
  "errors": [
    {
      "message": "`null` is not a valid input for `String!`, please provide a value for this argument.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "myData",
        "now"
      ]
    }
  ],
  "data": {
    "myData": null
  }
}
```

As I see it, the primary issue is that when the resolver uses a `lookahead` the validation error manifests as a return value from `arguments` rather than rejecting the query outright.  I think it's fine to resolve this issue by preserving the current non-lookahead behavior (i.e. reject this query), but just do so consistently for both lookahead and non-lookahead implementations.

Separately, if you decide to allow this query and want to change it to allow it (for both lookahead and non-lookahead resolvers), that's great too!
