### ISSUE TITLE
 missing keyword: :irep_node

### ISSUE THREAD

**Issue by dboots** [rmosolgo/graphql-ruby#5177]
**Describe the bug**

Migrating from 1.8.5 to 1.13.23. I have a feeling the syntax has changed, but I can't figure out where.

**Versions**

`graphql` version: 1.13.23
`rails` (or other framework): 7.0
other applicable versions (`graphql-batch`, etc) 
graphql-batch 0.5.0
ruby 3.04

**GraphQL schema**

Include relevant types and fields (in Ruby is best, in GraphQL IDL is ok). Any custom extensions, etc?

```ruby
class MySchema < GraphQL::Schema
  use GraphQL::Batch

  def self.execute(query_str = nil, **kwargs)
    super(query_str = nil, **kwargs)
  rescue Shared::MyCustomError => err
    { 'data' => nil,
      'errors' => [
        {
          'message' => err.msg
        },
        {
          'path' => err.path
        }
      ] }
  end

  query Shared::Types::QueryType
  mutation Shared::Types::MutationType

  max_depth 20
end
```

```ruby
class QueryType < ::Types::BaseObject
      field :ldap_containers,
            resolver: Directory::Resolvers::MyContainersResolver.with_config(cfg_options: { parent_obj_type: nil }),
            connection: true,
            extras: [:path, :irep_node]
end
```

```ruby


class MyResolver < ::Types::BaseResolver
      include DirQuery
      include RootQueryEnv
      include StringFormatters

      argument :input, Directory::Inputs::MyContainersInput,
               'Input object',
               default_value: { a: true, b: false },
               required: false
      type Directory::Connections::MyContainersConnection, null: true

      def self.with_config(options)
        Class.new(self) do
          options.each do |key, value|
            public_send(key, value)
          end
        end
      end

      def self.cfg_options(options = nil)
        if options
          @options = options
        else
          @options
        end
      end

      # here's the resolver for this query
      def resolve(input:, path:, irep_node:)
      end
end
```

```ruby

# frozen_string_literal: true

class MyGraphqlController < AuthedApplicationController
  def query
    query_string = params[:query]
    query_variables = params[:variables] || {}
    document, error_message = get_document(query_string)
    context = {
      session: session,
      current_user: current_user,
      base_current_user: base_current_user,
      request: request
    }

    if document
      result = MySchema.execute(
        query_string,
        document: document,
        variables: query_variables,
        context: context
      )

      render json: result
    else
      error_hash = { 'errors' => ['message' => error_message] }
      render json: error_hash
    end
  rescue => e
    # create unique error event ID:
    error_event_id = Base64.strict_encode64("#{Socket.gethostname}-#{Time.now}").to_s

    # create clean/safe error message without stack trace or details
    clean_err_msg = "Uncaught Exception: EventID = #{error_event_id}"

    # create full/detailed error message with full error and stack
    full_err_msg = ["#{clean_err_msg}: #{e}"] + e.backtrace # + caller[0..10]

    # log out the full errror with eventID, error, and trace
    Rails.logger.error full_err_msg

    # if Prod or Stage env, then only return safe error message to graphql
    # otherwise return full trace and details
    error_hash = if Rails.env.development? || Rails.env.local? || Rails.env.dev?
                   { 'errors' => ['message' => full_err_msg] }
                 else
                   { 'errors' => ['message' => clean_err_msg] }
                 end
    render json: error_hash
  end

  private

  def get_document(query_string)
    # create cache key for query document
    cache_key = Base64.encode64(query_string)

    # does cached document exist?
    if Rails.cache.exist?(cache_key)
      # of sp. then return it
      Rails.logger.debug 'Pulling Already Parsed query document from Rails cache'
      return Rails.cache.read(cache_key), true

    # else cached doc not found
    else

      # so try to parse the query
      begin
        result = GraphQL.parse(query_string)

      # if it failed, then capture the error and return it
      rescue StandardError => e
        error_message = "Graphql Document Parse Exception: #{e.message}"
        Rails.logger.error error_message
        return false, error_message
      end

      # Parse succeeded, so write document to cache and return it
      Rails.cache.write(cache_key, result)
      Rails.logger.debug 'Query String Successfully Parsed, and added to Rails cache'
      return result, true
    end
  end
end

```

**Steps to reproduce**

I believe it's just the query being executed via GraphqlController, failing at the resolver.

**Expected behavior**

A valid recordset from the Graphql query

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
["Uncaught Exception: EventID = ZG9uLWJvb3Rzcy1NYWNCb29rLVByby5sb2NhbC0yMDI0LTExLTI3IDEwOjUyOjI5IC0wNTAw: missing keyword: :irep_node", "/Users/folder/projects/project/api/app/graphql/directory/resolvers/my_containers_resolver.rb:37:in `resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/resolver.rb:107:in `public_send'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/resolver.rb:107:in `block (3 levels) in resolve_with_support'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:118:in `after_lazy'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/resolver.rb:95:in `block (2 levels) in resolve_with_support'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:118:in `after_lazy'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/resolver.rb:86:in `block in resolve_with_support'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:118:in `after_lazy'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/resolver.rb:75:in `resolve_with_support'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:841:in `public_send'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:841:in `block in public_send_field'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:939:in `block in with_extensions'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:975:in `block (2 levels) in run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:975:in `block (2 levels) in run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:978:in `run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:975:in `block in run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field/connection_extension.rb:21:in `resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:962:in `run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:975:in `block in run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field_extension.rb:137:in `resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:962:in `run_extensions_before_resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:934:in `with_extensions'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:818:in `public_send_field'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:732:in `block in resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:118:in `after_lazy'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/field.rb:730:in `resolve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:511:in `block (4 levels) in evaluate_selection_with_args'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/tracing.rb:66:in `trace'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:510:in `block (3 levels) in evaluate_selection_with_args'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/query.rb:366:in `block in with_error_handling'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/errors.rb:107:in `with_error_handling'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/query.rb:365:in `with_error_handling'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:509:in `block (2 levels) in evaluate_selection_with_args'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:506:in `block in evaluate_selection_with_args'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:915:in `after_lazy'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:440:in `evaluate_selection_with_args'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:433:in `block in evaluate_selection'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/member/has_arguments.rb:204:in `block (3 levels) in coerce_arguments'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/member/has_arguments.rb:185:in `block (2 levels) in coerce_arguments'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/member/has_arguments.rb:184:in `each'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/member/has_arguments.rb:184:in `block in coerce_arguments'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema/member/has_arguments.rb:213:in `coerce_arguments'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/arguments_cache.rb:52:in `dataload_for'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:432:in `evaluate_selection'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:359:in `block (2 levels) in evaluate_selections'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:358:in `block in evaluate_selections'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:357:in `each'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:357:in `evaluate_selections'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:231:in `block (4 levels) in run_eager'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:230:in `block (3 levels) in run_eager'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:228:in `block (2 levels) in run_eager'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:190:in `tap_or_each'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:219:in `block in run_eager'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:812:in `call_method_on_directives'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter/runtime.rb:210:in `run_eager'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter.rb:73:in `block in evaluate'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/tracing.rb:66:in `trace'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter.rb:72:in `evaluate'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/interpreter.rb:48:in `begin_query'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:85:in `begin_query'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:104:in `block (2 levels) in run_as_multiplex'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/dataloader/null_dataloader.rb:17:in `append_job'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:104:in `block in run_as_multiplex'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:103:in `each'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:103:in `each_with_index'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:103:in `run_as_multiplex'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:63:in `block (2 levels) in run_queries'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:211:in `block in instrument_and_analyze'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:29:in `block (2 levels) in apply_instrumenters'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:46:in `block (2 levels) in each_query_call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:41:in `each_query_call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:45:in `block in each_query_call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:44:in `each_query_call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:27:in `block in apply_instrumenters'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:72:in `call_hooks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/instrumentation.rb:26:in `apply_instrumenters'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:190:in `instrument_and_analyze'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:62:in `block in run_queries'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/tracing.rb:66:in `trace'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:60:in `run_queries'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/execution/multiplex.rb:50:in `run_all'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:1768:in `multiplex'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/graphql-1.13.23/lib/graphql/schema.rb:1739:in `execute'", "/Users/folder/projects/project/api/app/graphql/project_schema.rb:8:in `execute'", "/Users/folder/projects/project/api/app/controllers/project_graphql_controller.rb:19:in `query'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/abstract_controller/base.rb:215:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/rendering.rb:165:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/abstract_controller/callbacks.rb:234:in `block in process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/callbacks.rb:118:in `block in run_callbacks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/audited-5.7.0/lib/audited/sweeper.rb:16:in `around'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/callbacks.rb:127:in `block in run_callbacks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/audited-5.7.0/lib/audited/sweeper.rb:16:in `around'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/callbacks.rb:127:in `block in run_callbacks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/callbacks.rb:138:in `run_callbacks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/abstract_controller/callbacks.rb:233:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/rescue.rb:23:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/notifications.rb:206:in `block in instrument'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/notifications/instrumenter.rb:24:in `instrument'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/notifications.rb:206:in `instrument'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/instrumentation.rb:66:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal/params_wrapper.rb:259:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activerecord-7.0.8.6/lib/active_record/railties/controller_runtime.rb:27:in `process_action'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/abstract_controller/base.rb:151:in `process'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal.rb:188:in `dispatch'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_controller/metal.rb:251:in `dispatch'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/routing/route_set.rb:49:in `dispatch'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/routing/route_set.rb:32:in `serve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/journey/router.rb:50:in `block in serve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/journey/router.rb:32:in `each'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/journey/router.rb:32:in `serve'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/routing/route_set.rb:852:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/cookies.rb:704:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/tempfile_reaper.rb:15:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/etag.rb:27:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/conditional_get.rb:40:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/head.rb:12:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/http/permissions_policy.rb:38:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/http/content_security_policy.rb:36:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:266:in `context'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/session/abstract/id.rb:260:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/cookies.rb:704:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activerecord-7.0.8.6/lib/active_record/migration.rb:638:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/activesupport-7.0.8.6/lib/active_support/callbacks.rb:99:in `run_callbacks'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/callbacks.rb:26:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/actionable_exceptions.rb:17:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/show_exceptions.rb:29:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/railties-7.0.8.6/lib/rails/rack/logger.rb:40:in `call_app'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/railties-7.0.8.6/lib/rails/rack/logger.rb:27:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/remote_ip.rb:93:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/request_id.rb:26:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/method_override.rb:24:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/runtime.rb:22:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/executor.rb:14:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/static.rb:23:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-2.2.10/lib/rack/sendfile.rb:110:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/actionpack-7.0.8.6/lib/action_dispatch/middleware/host_authorization.rb:138:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/rack-cors-2.0.2/lib/rack/cors.rb:102:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/railties-7.0.8.6/lib/rails/engine.rb:530:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/puma-3.12.6/lib/puma/configuration.rb:227:in `call'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/puma-3.12.6/lib/puma/server.rb:706:in `handle_request'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/puma-3.12.6/lib/puma/server.rb:476:in `process_client'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/puma-3.12.6/lib/puma/server.rb:334:in `block in run'", "/Users/folder/.rvm/gems/ruby-3.0.4/gems/puma-3.12.6/lib/puma/thread_pool.rb:135:in `block in spawn_thread'"]
```

</details>

**Comment by rmosolgo** [comment]
Hi! Thanks for the detailed report. The problem stems from: 

- `extras: [..., :irep_node]`, which _used to_ add `irep_node: ...` to the resolver arguments, but evidently doesn't in 1.13.23 
- And, `resolve(..., irep_node:)` which expected that argument to be injected by GraphQL-Ruby, but it wasn't. 

The _easiest_ fix would be to remove `:irep_node` from the array of extras and remove `irep_node:` from the list of arguments in `def resolve(...)`. But, does the resolver _use_ `irep_node`? 

If it does, we can probably find another `extras: [...]` argument to use (either `:ast_node` or `:lookahead`). GraphQL-Ruby's underlying execution code changed such that there _are no_ `irep_node`s anymore! It might be possible to use the legacy runtime code in v1.13.23, but I'm not sure -- I'd have to check.  Please share some details about how `def resolve` uses the passed-in `irep_node` if you'd like help migrating that usage.

**Comment by dboots** [comment]
Thanks for the quick response! 

I was looking into the documentation at https://graphql-ruby.org/api-doc/1.8.5/GraphQL/Query/Context.html#irep_node-instance_method and looking into the `context` but based on your comment, that seems to be moot. 

``` ruby
def resolve(input:, path:, **kwargs)
        parent_obj_type = self.class.cfg_options[:parent_obj_type]
        # if this wasn't a root query then get the env from the root query:
        my_env = get_root_query_env(irep_node)

        # if the current user has read perms on this object/attr
        if parent_obj_type
          # if the current user has read perms on this object/attr
          return nil unless context[:current_user].attr_perms_on_dn('ldap',
                                                                    my_env,
                                                                    object,
                                                                    parent_obj_type)[path.last.chomp('_obj').to_sym][:read]
        end

        # set ldap search scope (either specified or default)
        my_base = if input[:filter_base]
                    input[:filter_base]
                  else
                    "Ldap::LDAP_#{my_env.upcase}_BASE".constantize
                  end

        # create string to hold custom queries from args
        my_query = +''

        # if individual attr filters were specified
        if input[:filter_attrs]
          # build AND ldap query from filter_attrs
          input[:filter_attrs].each do |key, value|
            next if key == :filter_join
            my_query << if Ldap::LDAP_GROUP_DN_ATTRS.include?(key)
                          "(#{key.to_s.camelcase(:lower)}=#{safe_search_format(value)})"
                        else
                          "(#{key.to_s.camelcase(:lower)}=*#{safe_search_format(value)}*)"
                        end
          end

          # was a join method specified?
          if input[:filter_attrs][:filter_join]
            # was filter_join AND?
            if input[:filter_attrs][:filter_join] == 'AND'
              # then wrap query in AND Join
              new_query = "(&#{my_query})"
              my_query = new_query

            # else was an OR joing specified?
            elsif input[:filter_attrs][:filter_join] == 'OR'
              # then wrap query in OR join
              new_query = "(|#{my_query})"
              my_query = new_query
            end
          end
        end

        # if a native ldap query/filter was given
        if input[:ldap_filter]
          # append ldap filter to existing query string
          my_query << input[:ldap_filter]
        end

        unique_batch_key = +''

        # error if they tried to do a top level recursive query with no filter
        if my_query.length.zero? && input[:filter_base].nil? && input[:scope] == 'sub'
          error_message = 'Recursive Scope specified, with no query or filter Base.  Either ' \
                          'change scope to  \'one\', or specify filter or filter_base'
          return GraphQL::ExecutionError.new(error_message)
        end

        # lets setup a cache key for this LDAP query
        my_cache_key = "ldap/#{my_env}/#{my_base.downcase}/#{input[:scope]}/" \
                       "#{my_query.downcase}/#{Base64.encode64(Ldap::LDAP_CONTAINER_READABLE_ATTRS.to_s)}"

        # if no_cache was specified, lets wipe out any items cached for this cache_key first
        if input[:no_cache]
          my_cache_key_part = "ldap/#{my_env}/#{my_base.downcase}/#{input[:scope]}/" \
                              "#{my_query.downcase}"
          Rails.cache.delete_matched(%r{#{my_cache_key_part}})
        end

        Rails.logger.debug 'LDAP_CONTAINERS_RESOLVER: Checking Rails Cache for key for ' \
                           "Containers Top Level Query: Scope: #{input[:scope]} Base: " \
                           "#{my_base} Query: #{my_query}"

        # get cached result or if not cached, do actual query
        if Rails.cache.exist?(my_cache_key)
          Rails.logger.debug 'LDAP_CONTAINERS_RESOLVER: Pulling ldap Container objects for ' \
                             "batchKey #{unique_batch_key} from Rails Cache (!)"
          Rails.cache.read(my_cache_key)
        else
          # Get groups from batch loader
          # get_top_level_query_from_batch(my_env, my_base, input, my_query, my_cache_key)
          sort_by_args(top_level_plural_query('ldap', my_env, my_base.downcase, input[:scope], my_query.downcase, 'containers'), input)
        end
      end
```

**Comment by dboots** [comment]
I was also barking up this tree of moving the env logic to context?

https://graphql-ruby.org/queries/executing_queries.html#scoped-context

In a parent resolver, possibly setting the env in question here, but I am still getting familiar with the codebase.

**Comment by rmosolgo** [comment]
I hope you found something that worked for you! If it gives you any more trouble as you work through it, please let me know here and I'd be happy to help debug.
