### ISSUE TITLE
Upgraded from 2.4.4 to 2.4.7 getting uninitialized constant GraphQL::Schema::Object

### ISSUE THREAD

**Issue by janosrusiczki** [rmosolgo/graphql-ruby#5188]
**Describe the bug**

As the title says, I upgraded my gem from 2.4.4 (which was working fine) to 2.4.7 (also tried with 2.4.6) and I'm getting the following error:

```
NameError: uninitialized constant GraphQL::Schema::Object (NameError)

@object_class || find_inherited_value(:object_class, GraphQL::Schema::Object)
                                                                    ^^^^^^^^
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/resolver/has_payload_type.rb:56:in `object_class'
```

This is on the build machine when running `bin/rails db:schema:load` but it's the same on the local environment too when running anything that would initialize Rails.

To me it seems to be something related to autoloading but I can't figure it out.

**Versions**

`graphql` version: 2.4.7 (and 2.4.6)
`rails` (or other framework): 7.2.2
other applicable versions (`graphql-batch`, etc)

**GraphQL schema**

Not relevant.

**GraphQL query**

Not relevant.

**Steps to reproduce**

Run `rails server` or `rails db:schema:load`.

**Expected behavior**

Rails starts up.

**Actual behavior**

What specifically went wrong?

Place full backtrace here (if a Ruby exception is involved):

<details>
<summary>Click to view exception backtrace</summary>

```
bin/rails aborted!
NameError: uninitialized constant GraphQL::Schema::Object (NameError)

            @object_class || find_inherited_value(:object_class, GraphQL::Schema::Object)
                                                                                ^^^^^^^^
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/resolver/has_payload_type.rb:56:in `object_class'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/resolver/has_payload_type.rb:92:in `generate_payload_type'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/mutation.rb:85:in `generate_payload_type'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/resolver/has_payload_type.rb:20:in `payload_type'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/resolver/has_payload_type.rb:63:in `field'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/relay_classic_mutation.rb:28:in `<class:RelayClassicMutation>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/relay_classic_mutation.rb:22:in `<class:Schema>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/relay_classic_mutation.rb:4:in `<module:GraphQL>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/relay_classic_mutation.rb:3:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema.rb:46:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/query/null_context.rb:15:in `<class:NullContext>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/query/null_context.rb:6:in `<class:Query>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/query/null_context.rb:4:in `<module:GraphQL>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/query/null_context.rb:3:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-2.4.7/lib/graphql/schema/object.rb:3:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-pagination-2.2.0/lib/graphql_pagination.rb:3:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/graphql-pagination-2.2.0/lib/graphql-pagination.rb:1:in `<main>'
<internal:/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
<internal:/opt/hostedtoolcache/Ruby/3.3.6/x64/lib/ruby/3.3.0/rubygems/core_ext/kernel_require.rb>:37:in `require'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/zeitwerk-2.7.1/lib/zeitwerk/core_ext/kernel.rb:34:in `require'
/home/runner/work/photonia/photonia/config/application.rb:9:in `<main>'
/home/runner/work/photonia/photonia/Rakefile:6:in `require_relative'
/home/runner/work/photonia/photonia/Rakefile:6:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:43:in `block in with_rake'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:41:in `with_rake'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands/rake/rake_command.rb:20:in `perform'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:156:in `invoke_rake'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:73:in `block in invoke'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:149:in `with_argv'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/command.rb:69:in `invoke'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/railties-7.2.2/lib/rails/commands.rb:18:in `<main>'
/home/runner/work/photonia/photonia/vendor/bundle/ruby/3.3.0/gems/bootsnap-1.18.4/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
bin/rails:4:in `<main>'
```

</details>

**Additional context**

N/A

**Comment by janosrusiczki** [comment]
Fixed https://github.com/RenoFi/graphql-pagination/pull/182

**Comment by rmosolgo** [comment]
Hey, thanks for the reporting this and sorry for the trouble. I'm glad you found a work-around but it seems like the old code in `graphql-pagination` _should_ work. I'm going to investigate how those `require` calls in GraphQL-Ruby can be improved, too.

**Comment by rmosolgo** [comment]
Well, I take it back -- I put some time into supporting a direct `require "graphql/schema/object"` call, but once I got the issue described here sorted out, another, trickier one popped up: 

```
/Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/object.rb:5:in `<class:Schema>': uninitialized constant GraphQL::Schema::Member (NameError)

    class Object < GraphQL::Schema::Member
                                  ^^^^^^^^
from /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/object.rb:4:in `<module:GraphQL>'
from /Users/rmosolgo/code/graphql-ruby/lib/graphql/schema/object.rb:3:in `<top (required)>'
from /Users/rmosolgo/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `require'
from /Users/rmosolgo/.rbenv/versions/3.3.0/lib/ruby/3.3.0/bundled_gems.rb:74:in `block (2 levels) in replace_require'
```

I could solve that by adding a `require "graphql/schema/member"`, but it opens a whole new can of worms -- every other "downstream" file would need to require those upstream ones, and I'm not ready to commit to supporting it. 

For future reference, the spec I added works like this: 

```diff 
+  it "can be loaded directly" do
+   stderr_and_stdout, status = Open3.capture2e("ruby -Ilib -e 'require \"graphql/schema/object\"'")
+   assert_equal "", stderr_and_stdout
+  end
```

And if we decided to support direct `require`s in the future, we could add new tests like that for any files we want to support.
