### ISSUE TITLE
Bug: Relay Mutations + Lazy Resolvers + Errors

### ISSUE THREAD

**Issue by stephencelis** [rmosolgo/graphql-ruby#527]
We noticed today that mutation types don't seem to play nicely with lazy resolvers and errors. _E.g._:

``` rb
resolve ->(_, inputs, ctx) {
  Promise.resolve({})
    .then { raise GraphQL::ExecutionError, 'oops' }
```

The resolved value is replaced with the error here:

https://github.com/rmosolgo/graphql-ruby/blob/a7f1bd8bbb04decdce47790b60c634c63480f765/lib/graphql/execution/lazy.rb#L36-L49

And we see the bug when a `GraphQL::Relay::Mutation::Result` is instantiated, particularly this line:

https://github.com/rmosolgo/graphql-ruby/blob/a7f1bd8bbb04decdce47790b60c634c63480f765/lib/graphql/relay/mutation.rb#L156

Because `result` is an error and not a hash, we get:

```
NoMethodError - undefined method `each' for #<GraphQL::ExecutionError: oops>:
  graphql (1.4.2) lib/graphql/relay/mutation.rb:152:in `initialize'
  graphql (1.4.2) lib/graphql/relay/mutation.rb:198:in `build_result'
  graphql (1.4.2) lib/graphql/relay/mutation.rb:187:in `block in call'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:54:in `block in then'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:40:in `value'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:54:in `block in then'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:40:in `value'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:54:in `block in then'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:40:in `value'
  graphql (1.4.2) lib/graphql/execution/lazy/resolve.rb:25:in `block in resolve_in_place'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:40:in `value'
  graphql (1.4.2) lib/graphql/execution/lazy/resolve.rb:58:in `deep_sync'
  graphql (1.4.2) lib/graphql/execution/lazy/resolve.rb:11:in `resolve'
  graphql (1.4.2) lib/graphql/execution/lazy.rb:18:in `resolve'
  graphql (1.4.2) lib/graphql/execution/execute.rb:41:in `block in resolve_selection'
  graphql (1.4.2) lib/graphql/internal_representation/selection.rb:41:in `block in each_selection'
  graphql (1.4.2) lib/graphql/internal_representation/selection.rb:38:in `each_selection'
  graphql (1.4.2) lib/graphql/execution/execute.rb:29:in `resolve_selection'
  graphql (1.4.2) lib/graphql/execution/execute.rb:9:in `execute'
  graphql (1.4.2) lib/graphql/query/executor.rb:37:in `execute'
  graphql (1.4.2) lib/graphql/query/executor.rb:18:in `result'
  graphql (1.4.2) lib/graphql/query.rb:115:in `result'
  graphql (1.4.2) lib/graphql/schema.rb:184:in `execute'
```

I'd expect the error to raise as it naturally does outside of laziness.

**Comment by rmosolgo** [comment]
😅

**Comment by rmosolgo** [comment]
That's more like it: #528

**Comment by stephencelis** [comment]
Thanks!
