### ISSUE TITLE
Trouble parsing queries with empty strings

### ISSUE THREAD

**Issue by chanks** [rmosolgo/graphql-ruby#62]
Looks like this was tackled back in #23, but querying using empty strings isn't completely working for me. When I try to query with:

```
mutation ClientMutation {
  company {
    update_user(id: "#{@user_1.id}", name: "Harriet", job_title: "") {
      id,
      name
    }
  }
}
```

I get:
```
NoMethodError: undefined method `parts' for #<Hash:0x0000000299b860>
    /home/chris/.rvm/gems/ruby-2.2.3/gems/graphql-0.10.1/lib/graphql/query.rb:47:in `initialize'
    /home/chris/.rvm/gems/ruby-2.2.3/gems/graphql-0.10.1/lib/graphql/schema.rb:40:in `new'
    /home/chris/.rvm/gems/ruby-2.2.3/gems/graphql-0.10.1/lib/graphql/schema.rb:40:in `execute'
```

It looks like while the parser usually returns a GraphQL::Language::Nodes::Document object, on the above query it actually returns a hash:
```
{:document_parts=>
  [{:operation_type=>"mutation"@6,
    :name=>"ClientMutation"@15,
    :variables=>[],
    :directives=>[],
    :selections=>
     [{:alias=>nil,
       :field_name=>"company"@40,
       :field_arguments=>[],
       :directives=>[],
       :selections=>
        {:optional_selections=>
          [{:alias=>nil,
            :field_name=>"update_user"@60,
            :field_arguments=>
             {:optional_field_arguments=>
               [#<GraphQL::Language::Nodes::Argument:0x00000001d551c8 @col=23, @line=3, @name="id", @value="1a0dde0c-8566-4edf-ba52-88a16620403a">,
                #<GraphQL::Language::Nodes::Argument:0x00000001c88740 @col=67, @line=3, @name="name", @value="Harriet">,
                {:field_argument_name=>"job_title"@133, :field_argument_value=>{:string=>[]}}]},
            :directives=>[],
            :selections=>
             [#<GraphQL::Language::Nodes::Field:0x000000016aa8f0 @alias=nil, @arguments=[], @col=13, @directives=[], @line=4, @name="id", @selections=[]>,
              #<GraphQL::Language::Nodes::Field:0x000000011f1750 @alias=nil, @arguments=[], @col=13, @directives=[], @line=5, @name="name", @selections=[]>]}]}}]}]}
```

I haven't dug deep enough to figure out why, though.

**Comment by rmosolgo** [comment]
Bummer!  Thanks for reporting this. 

It's the [`Transformer`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/transform.rb)'s job to turn those matches into to proper `Nodes` objects (that's the Parslet API). But somewhere along the way, one of those matches is failing, and it's causing all the subsequent matches to fail!

**Comment by rmosolgo** [comment]
I blame 

```
:field_argument_value=>{:string=>[]}
```

It should have been transformed here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/transform.rb#L107-L112

But somehow it's a `sequence`, not a `simple`

**Comment by chanks** [comment]
Hmm, that's interesting. I'll have some time to dig into this some
tomorrow, I'll see what I find then.

**Comment by rmosolgo** [comment]
I tried it out in the console and it seemed to parse ok: 

```ruby
GraphQL.parse(%|
mutation ClientMutation {
  company {
    update_user(id: "12", name: "Harriet", job_title: "") {
      id,
      name
    }
  }
}
|)
# => #<GraphQL::Language::Nodes::Document:0x007fae22040c18
```

Do you have access to the full query string that fails? Maybe the content of `@user_1.id` is something unusual, or maybe there are some invisible characters inside `job_title` ?

**Comment by chanks** [comment]
Here's a complete reproduction:
```ruby
require 'securerandom'
require 'graphql' #=> Bonus bug! NameError: uninitialized constant GraphQL::Schema::Printer::Set
require 'set'
require 'graphql'

GraphQL.parse(
<<-GRAPHQL
  query Query {
    users {
      id,
      email
    }
  }
GRAPHQL
)
#=> #<GraphQL::Language::Nodes::Document:0x00000001a8c108 @parts=...

GraphQL.parse(
<<-GRAPHQL
  query Query {
    users(id: "5c1bad6f-5e69-41f4-bfbb-37fa38ba20f8") {
      id,
      email
    }
  }
GRAPHQL
)
#=> #<GraphQL::Language::Nodes::Document:0x00000001b70da8 @parts=

GraphQL.parse(
<<-GRAPHQL
  query Query {
    users(id: "") {
      id,
      email
    }
  }
GRAPHQL
)
#=> {:document_parts=>[{:operation_type=>"query"@2, :name=>"Query"@8, :variables=>[], :directives=>[], :selections=>[{:alias=>nil, :field_name=>"users"@20, :field_arguments=>{:optional_field_arguments=>[{:field_argument_name=>"id"@26, :field_argument_value=>{:string=>[]}}]}, :directives=>[], :selections=>[#<GraphQL::Language::Nodes::Field:0x000000016b5278 @name="id", @alias=nil, @arguments=[], @directives=[], @selections=[], @line=3, @col=7>, #<GraphQL::Language::Nodes::Field:0x000000015ace80 @name="email", @alias=nil, @arguments=[], @directives=[], @selections=[], @line=4, @col=7>]}]}]}
```

**Comment by chanks** [comment]
Oh, are you using master? I'm on 0.10.1, it might have been fixed in this commit: https://github.com/rmosolgo/graphql-ruby/commit/d16325e06d4484eaa813abea8e3d9f7a0a551d44

**Comment by rmosolgo** [comment]
I was just checking the same thing, I'm an idiot :stuck_out_tongue_closed_eyes: 

![image](https://cloud.githubusercontent.com/assets/2231765/11077112/625517b4-87cc-11e5-9847-919b1fa0d7f9.png)

**Comment by rmosolgo** [comment]
just pushed 0.10.2, hopefully that'll do the trick!

**Comment by chanks** [comment]
Cool, thanks! It'd also be a good idea to `require 'set'` in
`GraphQL::Schema::Printer`, I ran into that in my reproduction. It probably
doesn't affect enough people to justify 0.10.3, though :)

**Comment by chanks** [comment]
Just upgraded and it works great, so I'm closing this, thanks again!
