### ISSUE TITLE
NoMethodError: undefined method `input_fields' for ID:GraphQL::ScalarType

### ISSUE THREAD

**Issue by keithpitt** [rmosolgo/graphql-ruby#636]
Here's another GraphQL query I stumbled across today with a `NoMethodError`:

```graphql
query Index_ViewerRelayQL($id_0: ID!) {
  node(id: {eq: $id_0}) {
    ... on Viewer {
      id
      changelogs(read: false) @include(if: true) {
        count
      }
    }
  }
}
```

You'll notice instead of `node(id: $id_0)`, there's this weird `{eq: $id_0}` value in there.

Returns:

```
NoMethodError: undefined method `input_fields' for ID:GraphQL::ScalarType
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/static_validation/rules/variable_usages_are_allowed.rb:22:in `block in validate'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:65:in `block in apply_hooks'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:65:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:65:in `reduce'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:65:in `apply_hooks'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:54:in `begin_visit'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:45:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `block in visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `each'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:47:in `visit_node'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/language/visitor.rb:39:in `visit'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/static_validation/validator.rb:34:in `validate'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/query/validation_pipeline.rb:74:in `ensure_has_validated'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/query/validation_pipeline.rb:33:in `valid?'
/Users/keithpitt/.gem/ruby/2.4.0/gems/graphql-1.5.4/lib/graphql/query.rb:118:in `result'
```

We turned on a public bug bounty program for our GraphQL endpoint and these hackers are finding all sorts of wonderful ways to blow things up :)

**Comment by rmosolgo** [comment]
😅 I watched (/am watching) mruby go through this ... we're gonna tighten up a lot of things! Thanks for contributing to graphql-ruby this way 😄 

I'll take a crack at this one soon!

**Comment by keithpitt** [comment]
No worries 👍
