### ISSUE TITLE
Uninitialized constant GraphQL::Relay::ConnectionField

### ISSUE THREAD

**Issue by octavonce** [rmosolgo/graphql-ruby#863]
```
ShiftsField = GraphQL::Field.define do
  name('shifts')
  argument :order, types.String, default_value: '-id'
  type(ShiftType.connection_type)

  description 'Returns shifts'

  resolve(ShiftResolver.new)
end

ViewerType = GraphQL::ObjectType.define do
  name 'Viewer'
  description 'Support unassociated root queries that fetches collections.'
  interfaces [ GraphQL::Relay::Node.interface ]

  global_id_field :id
end

ViewerType.fields['current_user'] = CurrentUserField
ViewerType.fields['shifts'] = GraphQL::Relay::ConnectionField.create(
  ShiftsField
)
```

When i run it it gives me this error:
```
NameError: uninitialized constant GraphQL::Relay::ConnectionField
/Users/bassculture/Projects/catergrid/catergrid-web/app/api/types/viewer_type.rb:12:in `<top (required)>'
/Users/bassculture/Projects/catergrid/catergrid-web/app/api/types/query_type.rb:9:in `block in <top (required)>'
/Users/bassculture/Projects/catergrid/catergrid-web/app/api/relay_schema.rb:1:in `<top (required)>'
/Users/bassculture/Projects/catergrid/catergrid-web/lib/tasks/relay.rake:9:in `block (3 levels) in <top (required)>'
/Users/bassculture/.rbenv/versions/2.4.0/bin/bundle:22:in `load'
/Users/bassculture/.rbenv/versions/2.4.0/bin/bundle:22:in `<main>'
```

What's going on?

**Comment by rmosolgo** [comment]
Sorry, I think that's not supported since a refactor of how connections work. Try this instead: 

```ruby 
ViewerType = GraphQL::ObjectType.define do
  # ... 
  connection :shifts, ShiftsField
end 
```

And remove this part: 

```ruby 
# remove this: 
ViewerType.fields['shifts'] = GraphQL::Relay::ConnectionField.create(
  ShiftsField
)
```

Does that work for you?

**Comment by octavonce** [comment]
Yes, thank you very much!

**Comment by kapilpipaliya** [comment]
Fix it in the documentation also:
http://graphql-ruby.org/relay/connections.html#creating-connection-fields-by-hand

**Comment by Willianvdv** [comment]
@kapilpipaliya if you have time, can you send in a pull request with the fix for the documentation/?
