### ISSUE TITLE
PG: OFFSET must not be negative

### ISSUE THREAD

**Issue by gauravtiwari** [rmosolgo/graphql-ruby#940]
Ref: #508 
Ref: #802

Seems like this error is back in 1.6.7, tested with 1.6.5 and same error. 

```bash
G::InvalidRowCountInResultOffsetClause - ERROR:  OFFSET must not be negative
: 
  rack-mini-profiler (0.10.1) lib/patches/db/pg.rb:93:in `async_exec'
  activerecord (5.0.3) lib/active_record/connection_adapters/postgresql_adapter.rb:598:in `block in exec_no_cache'
  activerecord (5.0.3) lib/active_record/connection_adapters/abstract_adapter.rb:590:in `block in log'
  activesupport (5.0.3) lib/active_support/notifications/instrumenter.rb:21:in `instrument'
```

**Comment by gauravtiwari** [comment]
Closing since this is fixed on master 👍

**Comment by rmosolgo** [comment]
oopsie, I'll release 1.6.8 soon with the fix!
